objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>Certification Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Earned_Date__c</fullName>
        <description>Earned date of Certification. Comes from first Examination Date</description>
        <label>Earned Date</label>
        <summarizedField>Academy_Certification_Examination__c.Date__c</summarizedField>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Academy_Certification_Examination__c.Academy_Certification2__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Certification_Student__r.Contact__r.FirstName + &apos; &apos;+ &apos; &apos;+  Certification_Student__r.Contact__r.LastName</formula>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CopadoCertificatePDFController.cls
/**
* This Apex class is responsible for rendering Pdf called from Invocable controller method from Process builder
* which will be fired when a Academy_Certification__c is created with status as VALID
* Created by dineshdk on 16/08/2018.
* Modified by David Pinett on 08/05/2019. To Hotfix Null Object DeReference 
*/
public without sharing class CopadoCertificatePDFController {
    public String htmlDisplay { get; set; }
    
    public CopadoCertificatePDFController() {
        String AcademyCertificateProgramId ='',certName= '',candName='',issuedDate='',certId='';
        if(APEXPages.currentPage().getParameters().get('download')!=null){
            if(APEXPages.currentPage().getParameters().get('CertificateId')!=null){
                AcademyCertificateProgramId = APEXPages.currentPage().getParameters().get('CertificateId');
                AcademyCertificateProgramId = AcademyCertificateProgramId.substring(9,AcademyCertificateProgramId.length()-9);
                User LoggedInUser = [SELECT Id, ContactId FROM User WHERE ID=: UserInfo.getUserId()];   
                List<Academy_Certification__c> Academy_Certification = new List<Academy_Certification__c >([SELECT Id,Earned_Date__c, Certification_Student__c,Certification_Student__r.contact__c, Student_Name__c, Status__c, Certification_Program__c,Certification_Program__r.Name,Certification_Id__c FROM Academy_Certification__c WHERE Certification_Student__r.Contact__c =: LoggedInUser.contactId  AND Certification_Program__c=:AcademyCertificateProgramId AND Status__c = 'Valid']);
                if(Academy_Certification.size()>0){
                    certName = Academy_Certification.get(0).Certification_Program__r.Name!=null?Academy_Certification.get(0).Certification_Program__r.Name:'';
                    candName = Academy_Certification.get(0).Student_Name__c!=null?Academy_Certification.get(0).Student_Name__c:'';
                    datetime tempDateTime = Academy_Certification.get(0).Earned_Date__c;
                    issuedDate = tempDateTime.day() + '-' + tempDateTime.month() + '-' + tempDateTime.year();
                    certId = Academy_Certification.get(0).Certification_Id__c!=null?Academy_Certification.get(0).Certification_Id__c:'';
                }
            }
        }
        else{
            certName = Apexpages.currentPage().getParameters().get('ProgramName');
            candName = Apexpages.currentPage().getParameters().get('StudentName');
            issuedDate = Apexpages.currentPage().getParameters().get('CertificateIssueDate');
            certId = Apexpages.currentPage().getParameters().get('CertificateId');
        }
        if(certName!='' || candName!='' || issuedDate!='' || certId!=''){
            EmailTemplate emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE Name = : System.Label.ET_Academy_CERT_PDF_BLOB LIMIT 1];
            String strHTML = emailTemplate.HtmlValue.replaceAll('(\\r|\\n)+', '');
            htmlDisplay = strHTML.replace('certName', certName).replace('candName', candName).replace('issuedDate', issuedDate).replace('certId', certId);
        }
    }
}