objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Examination</label>
        <referenceTo>Academy_Certification_Examination__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>Certification Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Earned_Date__c</fullName>
        <description>Earned date of Certification. Comes from first Examination Date</description>
        <label>Earned Date</label>
        <summarizedField>Academy_Certification_Examination__c.Date__c</summarizedField>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Academy_Certification_Examination__c.Academy_Certification2__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration Date of certification based on approved Examination date.</description>
        <formula>IF(ISBLANK(Certification_Examination__r.Date__c),TODAY()-1,
	(DATE(YEAR( DATEVALUE(Certification_Examination__r.Date__c)) + 1,
			MONTH(DATEVALUE(Certification_Examination__r.Date__c)), 
				DAY(DATEVALUE(Certification_Examination__r.Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Certification_Student__r.Contact__r.FirstName + &apos; &apos;+ &apos; &apos;+  Certification_Student__r.Contact__r.LastName</formula>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Examination__c.object
<CustomObject>
    <description>Exams records applied to student in order to support achieved certifications</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the certification program</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date when exam was or will be applied.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Examination Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Certification_Student__r.Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <label>Academy Certification Examination</label>
    <nameField>
        <displayFormat>ACE-{000000}</displayFormat>
        <label>Academy Certification Examination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JBCXM__SurveyParticipant__c.object
<CustomObject>
    <description>This is used to store survey participants</description>
    <fields>
        <fullName>JBCXM__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Participants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SuP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/downloadCertifiedLogoImage.cls
public class downloadCertifiedLogoImage {
    @AuraEnabled
    Public Static ResponseWrap checkUserIsCertified(){
        ResponseWrap response = new ResponseWrap();
        response.IsError = TRUE;
        response.result = new List<String>();
        MAP<Id,String> Certification_ProgramIdWithNameMap = new MAP<Id,String>();
        Set<Id> Certification_ProgramIds = new Set<Id>();
        List<User> LoggedInUser = [SELECT Id,email, ContactId FROM USER WHERE Id =: UserInfo.getUserId()];
        List<Academy_Certification__c> Academy_CertificationList = [SELECT Id, Certification_Student__r.Contact__c, Certification_Program__c,Certification_Program__r.Name FROM Academy_Certification__c WHERE Certification_Student__r.Contact__c =: LoggedInUser.get(0).ContactId AND Status__c = 'Valid'];
        if(Academy_CertificationList.size()>0){
            for(Academy_Certification__c AC : Academy_CertificationList){
                Certification_ProgramIds.add(AC.Certification_Program__c);
                Certification_ProgramIdWithNameMap.put(AC.Certification_Program__c,AC.Certification_Program__r.Name);
            }
            if(Certification_ProgramIds.size()>0){
                list<String> tempCertification_ProgramIds = new List<String>();
                List<ContentDocumentLink> ContentDocumentLinkList = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN:Certification_ProgramIds];
                if(ContentDocumentLinkList.size()>0){
                    response.IsError = FALSE;
                    for(ContentDocumentLink ContentDocumentLinkObj : ContentDocumentLinkList){
                        if(Certification_ProgramIdWithNameMap.containskey(ContentDocumentLinkObj.LinkedEntityId)){
                            tempCertification_ProgramIds.add(ContentDocumentLinkObj.LinkedEntityId);
                            response.result.add(Certification_ProgramIdWithNameMap.get(ContentDocumentLinkObj.LinkedEntityId)+'___'+ContentDocumentLinkObj.ContentDocumentId);
                        }
                    }
                    if(tempCertification_ProgramIds.size() != Certification_ProgramIds.size()){
                        for(String ids : Certification_ProgramIds){
                            if(!tempCertification_ProgramIds.contains(ids)){
                                response.result.add(Certification_ProgramIdWithNameMap.get(ids)+'___'+'No Preview');
                            }
                        }
                    }
                }
            }            
        }
        RETURN response;
    }
    
    @AuraEnabled
    Public Static CretificateDownloadResponse downloadCertificate(){
        CretificateDownloadResponse response = new CretificateDownloadResponse();
        response.IsError = TRUE;
        response.Academy_CertificationList = new List<Academy_Certification__c>();
        response.CertificateLogoList = new List<String>();
        MAP<Id,String> Certification_ProgramIdWithNameMap = new MAP<Id,String>();
        Set<Id> Certification_ProgramIds = new Set<Id>();
        List<User> LoggedInUser = [SELECT Id,email, ContactId FROM USER WHERE Id =:UserInfo.getUserId()];
        List<Academy_Certification__c> academyCertifications = [SELECT Id,Certification_Id__c,Certification_Examination__r.Date__c,Expiration_Date__c,Earned_Date__c,Certification_Program__r.Name, Certification_Student__c,Certification_Student__r.Contact__r.EMAIL, Status__c, Student_Name__c FROM Academy_Certification__c WHERE Certification_Student__r.Contact__c =: LoggedInUser.get(0).ContactId ORDER BY Expiration_Date__c];

        // Map containing Contact Id + Certification Program Id as a Key and Valid certificate as a value
        Map<String,Academy_Certification__c> contactCertificationProgramKeyWithValidCertificateMap = new Map<String,Academy_Certification__c>();
        // Map containing Contact Id + Certification Program Id as a Key and
        // Expired Certificate ( with no other valid Certificate for same Certificate Program ) as a value
        Map<String,Academy_Certification__c> contactCertificationProgramKeyWithExpiredCertificateMap = new Map<String,Academy_Certification__c>();
        for(Academy_Certification__c AC : academyCertifications){
            String mapKey = String.valueOf(AC.Certification_Student__r.Contact__c) + String.valueof(AC.Certification_Program__c);
            if(AC.Status__c == 'Valid') {
                contactCertificationProgramKeyWithValidCertificateMap.put(mapKey, AC);
            }
            else if(AC.Status__c == 'Expired' && !contactCertificationProgramKeyWithValidCertificateMap.containsKey(mapKey)) {
                contactCertificationProgramKeyWithExpiredCertificateMap.put(mapKey, AC);
            }
            if(contactCertificationProgramKeyWithValidCertificateMap.containsKey(mapKey) && contactCertificationProgramKeyWithExpiredCertificateMap.containsKey(mapKey)) {
                contactCertificationProgramKeyWithExpiredCertificateMap.remove(mapKey);
            }
        }
        response.Academy_CertificationList.addAll(contactCertificationProgramKeyWithValidCertificateMap.values());
        response.Academy_CertificationList.addAll(contactCertificationProgramKeyWithExpiredCertificateMap.values());

        if(response.Academy_CertificationList.size()>0){
            for(Academy_Certification__c AC : response.Academy_CertificationList){
                Certification_ProgramIds.add(AC.Certification_Program__c);
                Certification_ProgramIdWithNameMap.put(AC.Certification_Program__c,AC.Certification_Program__r.Name);
            }
            if(Certification_ProgramIds.size()>0){
                list<String> tempCertification_ProgramIds = new List<String>();
                List<ContentDocumentLink> ContentDocumentLinkList = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN:Certification_ProgramIds];
                if(ContentDocumentLinkList.size()>0){
                    response.IsError = FALSE;
                    for(ContentDocumentLink ContentDocumentLinkObj : ContentDocumentLinkList){
                        if(Certification_ProgramIdWithNameMap.containskey(ContentDocumentLinkObj.LinkedEntityId)){
                            tempCertification_ProgramIds.add(ContentDocumentLinkObj.LinkedEntityId);
                            response.CertificateLogoList.add(Certification_ProgramIdWithNameMap.get(ContentDocumentLinkObj.LinkedEntityId)+'___'+ContentDocumentLinkObj.ContentDocumentId);
                        }
                    }
                    if(tempCertification_ProgramIds.size() != Certification_ProgramIds.size()){
                        for(String ids : Certification_ProgramIds){
                            if(!tempCertification_ProgramIds.contains(ids)){
                                response.CertificateLogoList.add(Certification_ProgramIdWithNameMap.get(ids)+'___'+'No Preview');
                            }
                        }
                    }
                }
            }            
        }
        RETURN response;
    }
    
    public class ResponseWrap{
        @AuraEnabled Public boolean IsError;
        @AuraEnabled Public List<String> result;
    }
    public class CretificateDownloadResponse{
        @AuraEnabled Public boolean IsError;
        @AuraEnabled Public List<String> CertificateLogoList;
        @AuraEnabled Public List<Academy_Certification__c> Academy_CertificationList;
    }
}