objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration Date of certification based on approved Examination date.</description>
        <formula>IF(ISBLANK(Certification_Examination__r.Date__c),TODAY()-1,
	(DATE(YEAR( DATEVALUE(Certification_Examination__r.Date__c)) + 1,
			MONTH(DATEVALUE(Certification_Examination__r.Date__c)), 
				DAY(DATEVALUE(Certification_Examination__r.Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AcademyCertificateExpireBatch.cls
global class AcademyCertificateExpireBatch implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Name, Expiration_Date__c, Status__c FROM Academy_Certification__c WHERE Status__c = 'Valid' AND Expiration_Date__c<:System.today() ]);
    }
    
    global void execute(Database.BatchableContext BC, List<Academy_Certification__c> scope){
        if(scope.size()>0){
            List<Academy_Certification__c> scopeList = new List<Academy_Certification__c>();
            for(Academy_Certification__c Academy_Certification : scope){
                Academy_Certification.Status__c='Expired';
                scopeList.add(Academy_Certification);
            }
            if(scopeList.size()>0){
                UPDATE scopeList;  
            }
        }        
    }
    
    global void finish(Database.BatchableContext BC){
    }
}