objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Examination</label>
        <referenceTo>Academy_Certification_Examination__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Id__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>Certification Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Certification_Student__r.Contact__r.FirstName + &apos; &apos;+ &apos; &apos;+  Certification_Student__r.Contact__r.LastName</formula>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Examination__c.object
<CustomObject>
    <description>Exams records applied to student in order to support achieved certifications</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the certification program</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date when exam was or will be applied.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Certification_Student__r.Contact__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <label>Academy Certification Examination</label>
    <nameField>
        <displayFormat>ACE-{000000}</displayFormat>
        <label>Academy Certification Examination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JBCXM__SurveyParticipant__c.object
<CustomObject>
    <description>This is used to store survey participants</description>
    <fields>
        <fullName>JBCXM__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Participants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SuP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AcademyCertificationPDFMailer.cls
/**
 * This Apex class has Invocable method which will be fired through Process builder when a Academy_Certification__c is created
 * with status as VALID and will send an email with certification pdf attached to the related contact email.
 * Created by dineshdk on 16/08/2018.
 */

public without sharing class AcademyCertificationPDFMailer {

    @InvocableMethod
    public static void sendEmailMethood(List<Id> certIds) {
        String certificateName ;
        String candidateName ;
        String certificateId ;
        String candEmail;
        String issuedDate;
        String contactID;
        Messaging.SingleEmailMessage [] emails = new Messaging.SingleEmailMessage[]{
        };

        Map<Id, Academy_Certification_Student__c> academy_certification_studentMap = new Map<Id, Academy_Certification_Student__c>([SELECT Id, Name, Contact__r.EMAIL FROM Academy_Certification_Student__c WHERE Id IN (SELECT Certification_Student__c FROM Academy_Certification__c WHERE Id IN :certIds)]);
        Map<Id, Academy_Certification__c> academy_certificationMap = new Map<Id, Academy_Certification__c>([SELECT Id,Certification_Program__r.Name,Certification_Student__c, Certification_Examination__r.Date__c, Student_Name__c, Certification_Id__c FROM Academy_Certification__c WHERE Id IN :certIds]);
        OrgWideEmailAddress[] owa = [SELECT Id, DisplayName, Address FROM OrgWideEmailAddress WHERE Address = 'academy@copa.do' LIMIT 1];
        EmailTemplate templateId = [SELECT Id, HtmlValue FROM EmailTemplate WHERE Name = :System.Label.ET_Academy_CERT_PDF LIMIT 1];
        system.debug('academy_certification_studentMap...' + academy_certification_studentMap);

        for(ID cId : certIds) {
            if(academy_certificationMap.containsKey(cId)) {
                candidateName = academy_certificationMap.get(cId).Student_Name__c != null ? academy_certificationMap.get(cId).Student_Name__c : '' ;
                certificateName = academy_certificationMap.get(cId).Certification_Program__r.name != null ? academy_certificationMap.get(cId).Certification_Program__r.name : '';
                DateTime dT = academy_certificationMap.get(cId).Certification_Examination__r.Date__c ;
                issuedDate = dT.day() + '-' + dT.month() + '-' + dT.year();
                Id academy_certification_studentId = academy_certificationMap.get(cId).Certification_Student__c != null ? academy_certificationMap.get(cId).Certification_Student__c : '';
                certificateId = academy_certificationMap.get(cId).Certification_Id__c != null ? academy_certificationMap.get(cId).Certification_Id__c : '';
                if(academy_certification_studentMap.containsKey(academy_certification_studentId)) {
                    candEmail = academy_certification_studentMap.get(academy_certification_studentId).Contact__r.email != null ? academy_certification_studentMap.get(academy_certification_studentId).Contact__r.email : '';
                    contactID = academy_certification_studentMap.get(academy_certification_studentId).Contact__r.Id != null ? academy_certification_studentMap.get(academy_certification_studentId).Contact__r.Id : '';
                }
                //Visualforce that will contain the structure of the PDF.
                PageReference pagePdfContent =
                        new PageReference('/apex/CopadoCertificatePDFRenderer?ProgramName=' + certificateName + '&StudentName=' + candidateName + '&CertificateId=' + certificateId + '&CertificateIssueDate=' + issuedDate);
                //Obtain the page content as PDF blob in a variable.
                Blob b;
                if(!Test.isRunningTest()) b = pagePdfContent.getContentAsPDF();
// Create the email attachment
                Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                efa.setFileName('Copado Certified ' + certificateName + '.pdf');
                efa.setContentType('application/pdf');
                efa.setBody(b);
                List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTemplateID(templateId.Id);
                mail.setSaveAsActivity(true);
                String[] toAddresses = new String[]{
                        candEmail
                };
                mail.setToAddresses(toAddresses);
                if(owa.size() != 0)mail.setOrgWideEmailAddressId(owa[0].id);
                mail.setTargetObjectId(contactID);
                mail.setWhatId(cId);
                mail.setFileAttachments(new Messaging.EmailFileAttachment[]{
                        efa
                });
                emails.add(mail);
            }
        }
        Messaging.SendEmailResult[] er = Messaging.sendEmail(emails, false);
        system.debug('result ...' + er);

    }
}