objects/Academy_API_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>trusted_IP_Address__c</fullName>
        <label>trusted IP Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy API Settings</label>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Student Id to identify student from external platforms</description>
        <externalId>true</externalId>
        <label>Student Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JBCXM__SurveyParticipant__c.object
<CustomObject>
    <description>This is used to store survey participants</description>
    <fields>
        <fullName>JBCXM__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Participants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SuP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AcademyStudents.cls
@RestResource(urlMapping='/AcademyStudent')
global without sharing class AcademyStudents  {

    public class Error {
        public string errorMessage;
    }
    public static AcademyCertification.Error err = New AcademyCertification.Error();
    @HttpGet
    global static void show() {
        RestResponse res = new RestResponse();
        res = RestContext.response;

        if (([Select ID FROM Academy_API_Settings__c WHERE trusted_IP_Address__c = :RestContext.request.headers.get('Idtoken')].size() > 0 
            && RestContext.request.params.get('student_Name') != null))
        {
            String studentName = RestContext.request.params.get('student_Name');

            List<Academy_Certification_Student__c> students = New  List<Academy_Certification_Student__c>();
            try{
                students = [SELECT Student_Id__c, Contact__r.Name, Contact__r.MailingCity, Contact__r.MailingState, Contact__r.MailingCountry  FROM Academy_Certification_Student__c 
                                    WHERE Academy_Certification_Student__c.Contact__r.Name =: studentName];

                if (students.size()>0)
                {
                    res.responseBody = Blob.valueOf(JSON.serialize(students));
                    res.statusCode = 200;
                }   
                else 
                {
                    res.responseBody = Blob.valueOf('{"errorMessage":"No student registered for '+studentName+'"}');
                    res.statusCode = 200;
                }

            } catch (exception e) {
                System.debug(e.getMessage());
                return;
            }
        } 
        else {
            res.statusCode = 200;
            res.responseBody = Blob.valueOf('{"errorMessage":"Forbidden"}');            
        }        
    }

}