objects/Academy_API_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>trusted_IP_Address__c</fullName>
        <label>trusted IP Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy API Settings</label>
</CustomObject>

objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration Date of certification based on approved Examination date.</description>
        <formula>IF(ISBLANK(Certification_Examination__r.Date__c),TODAY()-1,
	(DATE(YEAR( DATEVALUE(Certification_Examination__r.Date__c)) + 1,
			MONTH(DATEVALUE(Certification_Examination__r.Date__c)), 
				DAY(DATEVALUE(Certification_Examination__r.Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <formula>Certification_Student__r.Contact__r.FirstName + &apos; &apos;+ &apos; &apos;+  Certification_Student__r.Contact__r.LastName</formula>
        <label>Student Name</label>
        <type>Text</type>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Image__c</fullName>
        <description>This field will be used to determinate the Certification Logo that will be rendered on the Verification Site</description>
        <inlineHelpText>Value must match the program.</inlineHelpText>
        <label>Image</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Release Manager</fullName>
                </value>
                <value>
                    <fullName>Change Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AcademyCertification.cls
@RestResource(UrlMapping='/AcademyCertifications')
global without sharing class AcademyCertification {

    public class Error {
        public String errorMessage;
    }

    public static AcademyCertification.Error err = new AcademyCertification.Error();

    @HttpGet
    global static void show() {
        RestResponse res = new RestResponse();
        res = RestContext.response;
        Boolean isFromTrustedIPAddress = [SELECT Id FROM Academy_API_Settings__c WHERE trusted_IP_Address__c = :RestContext.request.headers.get('Idtoken')].size() > 0;
        String studentId = RestContext.request.params.get('student_Id');

        System.debug(RestContext.request.headers);
        System.debug(RestContext.request.headers.get('Idtoken'));
        System.debug(RestContext.request.remoteAddress);

        if(!(isFromTrustedIPAddress && String.isNotBlank(studentId))) {
            res.statusCode = 200;
            res.responseBody = Blob.valueOf('{"errorMessage":"Forbidden"}');
            return;
        }

        try {
            List<Academy_Certification__c> student_Certifications = new List<Academy_Certification__c>();
            Student_Certifications = [
                    SELECT Certification_Program__r.Name, Certification_Program__r.Image__c,
                            Expiration_Date__c, Student_Name__c, Status__c
                    FROM Academy_Certification__c
                    WHERE Certification_Student__c = :studentId
            ];

            if(Student_Certifications.isEmpty()) {
                res.responseBody = Blob.valueOf('{"errorMessage":"No certification available for ' + studentId + '"}');
            } else {
                res.responseBody = Blob.valueOf(JSON.serialize(Student_Certifications));
            }

        } catch(Exception excp) {
            System.debug(excp.getMessage());
            res.statusCode = 200;
            res.responseBody = Blob.valueOf('{"errorMessage":"No certification available for ' + studentId + '"}');
            return;
        }
    }
}