objects/Academy_Certification_Delivery__c.object
<CustomObject>
    <description>Academy Certification Delivery holds the date and type of certification.</description>
    <fields>
        <fullName>Academy_Certification_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academy Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Deliveries</relationshipLabel>
        <relationshipName>Academy_Certification_Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Academy Certification Program, for example: Release Manager I</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Deliveries</relationshipLabel>
        <relationshipName>Academy_Certification_Deliveries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>OnSite</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Delivery</label>
    <nameField>
        <displayFormat>ACD-{0000}</displayFormat>
        <label>Academy Certification Delivery</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Chamilo_Id__c</fullName>
        <externalId>true</externalId>
        <label>Chamilo Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Chamilo_Id__c</fullName>
        <description>Id of the User in Chamilo, auto-populated if is a new user</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the User in Chamilo, auto-populated if is a new user</inlineHelpText>
        <label>Chamilo Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AcademyCertificationDeliveryHelper.cls
/**
 * Created by gaviriajesus on 22/05/2018.
 */

public with sharing class AcademyCertificationDeliveryHelper {


    public static Map<Id, Academy_Certification_Delivery__c> deliverMap = new Map<Id, Academy_Certification_Delivery__c>();

    public static void prepareData(List<Academy_Certification_Delivery__c> deliveries){
        Set<Id> ids = new Set<Id>();
        for(Academy_Certification_Delivery__c s : deliveries){
            if(s.Academy_Certification_Student__c != null && s.Certification_Program__c != null){
                ids.add(s.Id);
            }
        }
        if(ids.size()>0){
            deliverMap = new Map<Id, Academy_Certification_Delivery__c>([select Id, Academy_Certification_Student__r.Chamilo_Id__c, Certification_Program__r.Chamilo_Id__c from Academy_Certification_Delivery__c where Id IN:ids]);
        }
        system.debug(deliverMap);
    }

    public static void SubscribeUserToCourse(Academy_Certification_Delivery__c delivery){
        system.debug(delivery);
        if(deliverMap.containsKey(delivery.Id) &&  delivery.Type__c == 'Online'){
            List<AcademyAPI.Part> parts = AcademyAPI.getPartsForSubscribeUserToCourse(deliverMap.get(delivery.Id).Academy_Certification_Student__r.Chamilo_Id__c, deliverMap.get(delivery.Id).Certification_Program__r.Chamilo_Id__c);
            AcademyAPI.sendSOAPrequest(JSON.serialize(parts), 'SubscribeUserToCourse','urn:WSService', 'WSCourse', null);
        }

    }
}