objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Examination</label>
        <referenceTo>Academy_Certification_Examination__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Examination__c.object
<CustomObject>
    <description>Exams records applied to student in order to support achieved certifications</description>
    <fields>
        <fullName>Academy_Certification2__c</fullName>
        <label>Academy Certification</label>
        <referenceTo>Academy_Certification__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations (Academy Certification)</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the certification program</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date when exam was or will be applied.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <inlineHelpText>Number between 0 and 100</inlineHelpText>
        <label>Grade</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Examination Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Examination</label>
    <nameField>
        <displayFormat>ACE-{000000}</displayFormat>
        <label>Academy Certification Examination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Copado_Version__c</fullName>
        <description>Current Copado version, to identify features covered on certification</description>
        <label>Copado Version</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <label>Student Email</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Student Id to identify student from external platforms</description>
        <externalId>true</externalId>
        <label>Student Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/downloadCertifiedLogoImageTest.cls
@isTest
public class downloadCertifiedLogoImageTest {
    @testSetup
    public static void setupMethod(){
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
            UserRoleId = portalRole.Id,
            ProfileId = profile1.Id,
            Username = System.now().millisecond() + 'ewrwertest2@test.com',
            Alias = 'batman',
            Email='new.helloworld@test.com',
            EmailEncodingKey='UTF-8',
            Firstname='test',
            Lastname='test',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        Database.insert(portalAccountOwner1);
        system.assertNotEquals(null,portalAccountOwner1.Id, 'System Administrator User can not created.');
        User user1 = new User();
        System.runAs ( portalAccountOwner1 ) {
            //Create account
            Account portalAccount1 = new Account(
                Name = 'TestAccount',
                OwnerId = portalAccountOwner1.Id
            );
            Database.insert(portalAccount1);
            system.assertNotEquals(null,portalAccount1.Id, 'Account can not created.');
            
            //Create contact
            Contact contact1 = new Contact(
                FirstName = 'Test',
                Lastname = 'McTesty',
                AccountId = portalAccount1.Id,
                Email = System.now().millisecond() + 'test@test.com'
            );
            Database.insert(contact1);
            system.assertNotEquals(null,contact1.Id, 'Contact can not created.');
            
            //Create Portal user
            Profile portalProfile = [SELECT Id FROM Profile where name='CUSTOM Community Guest Login' Limit 1];
            system.assertNotEquals(null,portalProfile.Id, 'CUSTOM Community Guest Login Profile not found in system.');
            user1 = new User(
                Username = System.now().millisecond() + 'test12345@test.com',
                ContactId = contact1.Id,
                ProfileId = portalProfile.Id,
                Alias = 'test123',
                Email = 'test12345@test.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'McTesty',
                CommunityNickname = 'test12345',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US'
            );
            Database.insert(user1);
            system.assertNotEquals(null,user1.Id, 'Portal user not created.');
            
            Academy_Certification_Program__c Academy_Certification_Program = new Academy_Certification_Program__c();
            Academy_Certification_Program__c Academy_Certification_ProgramDev = new Academy_Certification_Program__c();
            SYSTEM.runAs(user1){
                Academy_Certification_Program.Name ='Test Administrator';
                Academy_Certification_Program.Copado_Version__c = '10';
                Academy_Certification_Program.Status__c = 'Valid';
                Insert Academy_Certification_Program;
                
                Academy_Certification_ProgramDev.Name ='Test Developer';
                Academy_Certification_ProgramDev.Copado_Version__c = '10';
                Academy_Certification_ProgramDev.Status__c = 'Valid';
                Insert Academy_Certification_ProgramDev;
                
                Academy_Certification_Student__c Academy_Certification_Student = new Academy_Certification_Student__c();
                Academy_Certification_Student.Contact__c = user1.ContactId;
                Academy_Certification_Student.Student_Email__c  = user1.Email;
                Insert Academy_Certification_Student;
                Academy_Certification_Student.Student_Id__c = Academy_Certification_Student.Id;
                Update Academy_Certification_Student;
                
                
                Academy_Certification__c  Academy_Certification = new Academy_Certification__c();
                Academy_Certification.Certification_Program__c = Academy_Certification_Program.Id;
                Academy_Certification.Certification_Student__c = Academy_Certification_Student.Id;
                //Academy_Certification.Certification_Examination__c = Academy_Certification_Examination.Id;
                Academy_Certification.Status__c = 'Valid';
                Insert Academy_Certification;
                
                Academy_Certification_Examination__c Academy_Certification_Examination = new Academy_Certification_Examination__c();
                Academy_Certification_Examination.Certification_Program__c = Academy_Certification_Program.Id;
                Academy_Certification_Examination.Certification_Student__c = Academy_Certification_Student.Id;
                Academy_Certification_Examination.Academy_Certification2__c = Academy_Certification.Id;
                Academy_Certification_Examination.Date__c = System.now();
                Academy_Certification_Examination.Grade__c = 80;
                Academy_Certification_Examination.Status__c = 'Approved';
                Insert Academy_Certification_Examination;
                
                Academy_Certification.Certification_Examination__c = Academy_Certification_Examination.Id;
                Update Academy_Certification;
                
                
                
                
                Academy_Certification__c  Academy_Certification1 = new Academy_Certification__c();
                Academy_Certification1.Certification_Program__c = Academy_Certification_ProgramDev.Id;
                Academy_Certification1.Certification_Student__c = Academy_Certification_Student.Id;
                //Academy_Certification.Certification_Examination__c = Academy_Certification_Examination.Id;
                Academy_Certification1.Status__c = 'Valid';
                Insert Academy_Certification1;

                Academy_Certification__c  Academy_Certification2 = new Academy_Certification__c();
                Academy_Certification2.Certification_Program__c = Academy_Certification_ProgramDev.Id;
                Academy_Certification2.Certification_Student__c = Academy_Certification_Student.Id;
                //Academy_Certification.Certification_Examination__c = Academy_Certification_Examination.Id;
                Academy_Certification2.Status__c = 'Expired';
                Insert Academy_Certification2;

                Academy_Certification_Examination__c Academy_Certification_Examination1 = new Academy_Certification_Examination__c();
                Academy_Certification_Examination1.Certification_Program__c = Academy_Certification_ProgramDev.Id;
                Academy_Certification_Examination1.Certification_Student__c = Academy_Certification_Student.Id;
                Academy_Certification_Examination1.Academy_Certification2__c = Academy_Certification1.Id;
                Academy_Certification_Examination1.Date__c = System.now();
                Academy_Certification_Examination1.Grade__c = 80;
                Academy_Certification_Examination1.Status__c = 'Approved';
                Insert Academy_Certification_Examination1;
                
                Academy_Certification1.Certification_Examination__c = Academy_Certification_Examination.Id;
                Update Academy_Certification1;
                system.debug(Academy_Certification1);
            }
            ContentVersion contentVersion_1 = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            SharingOption = 'A'
            
        );
        insert contentVersion_1;
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = Academy_Certification_Program.Id;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        
        }
    }
    @isTest
    public static void test1(){
        User loggedInUser = [SELECT Id ,FirstName from User WHERE email =: 'new.helloworld@test.com' LIMIT 1];
        system.assertNotEquals(null,loggedInUser.Id, 'system admin user not found in system.');
        User PortalUser = [SELECT Id ,Email,contactId,FirstName from User WHERE email =: 'test12345@test.com' LIMIT 1];
        system.assertNotEquals(null,PortalUser.Id, 'Portal user not found in system.');
        Test.startTest();
        system.runAs(PortalUser){
            downloadCertifiedLogoImage.checkUserIsCertified();
            downloadCertifiedLogoImage.downloadCertificate();
        }
        //system.assertNotEquals(null,ctrl, 'CommunityContactUpdateSchedulerClass controller instance is null.');
        Test.stopTest();
    }
    
}