objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Examination</label>
        <referenceTo>Academy_Certification_Examination__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Earned_Date__c</fullName>
        <description>Earned date of Certification. Comes from first Examination Date</description>
        <label>Earned Date</label>
        <summarizedField>Academy_Certification_Examination__c.Date__c</summarizedField>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Academy_Certification_Examination__c.Academy_Certification2__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration Date of certification based on approved Examination date.</description>
        <formula>IF(ISBLANK(Certification_Examination__r.Date__c),TODAY()-1,
	(DATE(YEAR( DATEVALUE(Certification_Examination__r.Date__c)) + 1,
			MONTH(DATEVALUE(Certification_Examination__r.Date__c)), 
				DAY(DATEVALUE(Certification_Examination__r.Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Examination__c.object
<CustomObject>
    <description>Exams records applied to student in order to support achieved certifications</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the certification program</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Examination Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Examination</label>
    <nameField>
        <displayFormat>ACE-{000000}</displayFormat>
        <label>Academy Certification Examination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Progress__c</fullName>
        <label>Progress</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Section_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Section Item</label>
        <referenceTo>redwing__Training_Plan_Section_Item__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Is_Maintenance_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to decide if this learning plan is part of an certification maintenance</description>
        <label>Is Maintenance Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maintenance_Expiration_Date__c</fullName>
        <description>Field to decide when the maintenance will expired. Required by a validation rule if Is Maintenance Plan checkbox is checked</description>
        <label>Maintenance Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Days_for_Reminder__c</fullName>
        <label>Schedule Days for Reminder</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redwing__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section</label>
    <nameField>
        <label>Learning Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only published learning objects can be added to a Learning Plan</errorMessage>
            <filterItems>
                <field>redwing__Learning__c.redwing__Is_Published_Formula__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>NOTE: Only published learning objects can be associated to a Learning Plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Section Item</label>
    <nameField>
        <displayFormat>LPSI-{0000000}</displayFormat>
        <label>Learning Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AcademyMaintenanceReminderTableCtr.cls
public without sharing class AcademyMaintenanceReminderTableCtr {

    public String contactIdApex { get; set; }

    public AcademyMaintenanceReminderTableCtr() {

    }

    public List<AcademyCertificationMaintenanceStatus> getContactCertifications() {
        List<AcademyCertificationMaintenanceStatus> certificationMaintenanceStatuses = new List<AcademyCertificationMaintenanceStatus>();

        List<Academy_Certification__c> certifications = [
                SELECT Id, Name, Certification_Program__r.Name, Expiration_Date__c, Status__c, Certification_Examination__r.Learning__r.Name, Earned_Date__c
                FROM Academy_Certification__c
                WHERE Certification_Student__r.Contact__c = :contactIdApex
        ];

        if(certifications == null || certifications.isEmpty()) {
            return certificationMaintenanceStatuses;
        }

        Map<Id, redwing__Training_Plan__c> activeMaintenancePlans = new Map<Id, redwing__Training_Plan__c>([
                SELECT Id, Name, redwing__Start_Date__c, Schedule_Days_for_Reminder__c, Maintenance_Expiration_Date__c, redwing__End_Date__c
                FROM redwing__Training_Plan__c
                WHERE Is_Maintenance_Plan__c = TRUE
                AND redwing__Start_Date__c < :Date.today()
                AND Maintenance_Expiration_Date__c >= :Date.today()
        ]);
        System.debug('Total active maintenance: ' + activeMaintenancePlans.keySet().size());

        List<redwing__Learning_Assignment__c> completedAssignments = [
                SELECT Id, redwing__Contact__c, redwing__Training_Plan__c
                FROM redwing__Learning_Assignment__c
                WHERE redwing__Training_Plan__c IN :activeMaintenancePlans.keySet()
                AND redwing__Progress__c = 'Completed'
                AND redwing__Contact__c = :contactIdApex
        ];

        System.debug('Total completed maintenance: ' + completedAssignments.size());

        Set<String> completedPrograms = new Set<String>();
        for(redwing__Learning_Assignment__c tps : completedAssignments){
            completedPrograms.add(tps.redwing__Training_Plan__c);
        }


        List<redwing__Training_Plan_Section_Item__c> sectionItems = [SELECT Id, redwing__Learning__r.Academy_Certification_Program__c,
                redwing__Training_Plan_Section__r.redwing__Training_Plan__c
        FROM redwing__Training_Plan_Section_Item__c
        WHERE redwing__Training_Plan_Section__r.redwing__Training_Plan__c IN :activeMaintenancePlans.keySet()
        AND redwing__Learning__r.Academy_Certification_Program__c != NULL];
        System.debug('Total sectionItems maintenance: ' + sectionItems.size());

        /*if(sectionItems.isEmpty()) {
            return certificationMaintenanceStatuses;
        }*/

        Map<String, String> activePrograms = new Map<String, String> ();
        for(redwing__Training_Plan_Section_Item__c tps : sectionItems){
            activePrograms.put(tps.redwing__Learning__r.Academy_Certification_Program__c, tps.redwing__Training_Plan_Section__r.redwing__Training_Plan__c);
        }

        for(Academy_Certification__c ac : certifications) {
            if(activePrograms.containsKey(ac.Certification_Program__c)){
                if(completedPrograms.contains(activePrograms.get(ac.Certification_Program__c))){
                    AcademyCertificationMaintenanceStatus acms = new AcademyCertificationMaintenanceStatus(ac.Certification_Program__r.Name, 'Maintenance completed', 'No Action Needed', ac.Expiration_Date__c);
                    certificationMaintenanceStatuses.add(acms);
                } else {
                    AcademyCertificationMaintenanceStatus acms = new AcademyCertificationMaintenanceStatus(ac.Certification_Program__r.Name, 'Maintenance not completed', 'Complete maintenance exam', ac.Expiration_Date__c);
                    certificationMaintenanceStatuses.add(acms);
                }
            } else {
                AcademyCertificationMaintenanceStatus acms = new AcademyCertificationMaintenanceStatus(ac.Certification_Program__r.Name, 'Maintenance not needed', 'No Action Needed', ac.Expiration_Date__c);
                certificationMaintenanceStatuses.add(acms);
            }

        }

        return certificationMaintenanceStatuses;

    }

    public class AcademyCertificationMaintenanceStatus {
        public String credentialName { get; set; }
        public String credentialStatus { get; set; }
        public String actionsToTake { get; set; }
        public Date expirationDate { get; set; }

        public AcademyCertificationMaintenanceStatus(String credentialName, String credentialStatus, String actionsToTake, Date expirationDate) {
            this.credentialName = credentialName;
            this.credentialStatus = credentialStatus;
            this.actionsToTake = actionsToTake;
            this.expirationDate = expirationDate;
        }
    }

}