objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Examination</label>
        <referenceTo>Academy_Certification_Examination__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Examination__c.object
<CustomObject>
    <description>Exams records applied to student in order to support achieved certifications</description>
    <fields>
        <fullName>Academy_Certification2__c</fullName>
        <label>Academy Certification</label>
        <referenceTo>Academy_Certification__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations (Academy Certification)</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the certification program</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date when exam was or will be applied.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Examination Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Examination</label>
    <nameField>
        <displayFormat>ACE-{000000}</displayFormat>
        <label>Academy Certification Examination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Copado_Version__c</fullName>
        <description>Current Copado version, to identify features covered on certification</description>
        <label>Copado Version</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <label>Student Email</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>Academy_Certification_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academy Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Is_Maintenance_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to decide if this learning plan is part of an certification maintenance</description>
        <label>Is Maintenance Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maintenance_Expiration_Date__c</fullName>
        <description>Field to decide when the maintenance will expired. Required by a validation rule if Is Maintenance Plan checkbox is checked</description>
        <label>Maintenance Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redwing__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redwing__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section</label>
    <nameField>
        <label>Learning Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only published learning objects can be added to a Learning Plan</errorMessage>
            <filterItems>
                <field>redwing__Learning__c.redwing__Is_Published_Formula__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>NOTE: Only published learning objects can be associated to a Learning Plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Section__c</fullName>
        <label>Learning Plan Section</label>
        <referenceTo>redwing__Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section Item</label>
    <nameField>
        <displayFormat>LPSI-{0000000}</displayFormat>
        <label>Learning Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestLearningPlanAnnouncementExtension.cls
@IsTest
private with sharing class TestLearningPlanAnnouncementExtension {

    @TestSetup static void setupData() {

        Academy_Certification_Program__c acp = new Academy_Certification_Program__c();
        acp.Name = 'ADMINISTRATOR';
        acp.Status__c = 'Valid';
        acp.Copado_Version__c = 'v15';
        insert acp;

        redwing__Training_Plan__c maintenance = new redwing__Training_Plan__c();
        maintenance.Name = 'Admin Maintenance';
        maintenance.Is_Maintenance_Plan__c = true;
        maintenance.redwing__Start_Date__c = Date.today();
        maintenance.redwing__End_Date__c = Date.today().addMonths(6);
        maintenance.Maintenance_Expiration_Date__c = Date.today().addMonths(6);
        insert maintenance;

        redwing__Learning__c learning = new redwing__Learning__c();
        learning.Name = 'Admin Maintenance';
        learning.Academy_Certification_Program__c = acp.Id;
        learning.redwing__Published__c = true;
        insert learning;

        redwing__Training_Plan_Section__c tps = new redwing__Training_Plan_Section__c();
        tps.Name = 'Admin Certification Maintenance';
        tps.redwing__Training_Plan__c = maintenance.Id;
        insert tps;

        redwing__Training_Plan_Section_Item__c tpsc = new redwing__Training_Plan_Section_Item__c();
        tpsc.redwing__Training_Plan_Section__c = tps.Id;
        tpsc.redwing__Learning__c = learning.Id;
        insert tpsc;

        List<Contact> academyContacts = new List<Contact>();

        for(Integer i = 1; i <= 20; i++){
            Contact academyContact = new Contact();
            academyContact.FirstName = 'Academy ' + i;
            academyContact.LastName = 'Test';
            academyContact.Email = 'academy' + i + '@copado.com';
            academyContacts.add(academyContact);
        }
        insert academyContacts;

    }

    @IsTest static void testWithResultAttachment(){
        //added for coverage for now
        AcademyCertificationStudentHandler acsh = new AcademyCertificationStudentHandler();
        AcademyCertificationStudentHelper.tester();
        redwing__Training_Plan__c currentPlan = [SELECT Id FROM redwing__Training_Plan__c WHERE Name = 'Admin Maintenance'];

        //test with result attachment
        Attachment resultAttachment = new Attachment(Name = 'Maintenance Open Mail Results', Body = Blob.valueOf('test'), ParentId = currentPlan.Id);
        insert resultAttachment;
        //added to get coverage on empty methods
        acsh.beforeDelete((SObject) resultAttachment);
        acsh.afterDelete((SObject) resultAttachment);
        Test.setCurrentPage(Page.LearningPlanAnnouncement);
        LearningPlanAnnouncementExtension lpae = new LearningPlanAnnouncementExtension(new ApexPages.StandardController(currentPlan));

        System.assertEquals(true, ApexPages.hasMessages(), 'When there is attachment for result page has messages');
        System.assertEquals('Email already sent!', ApexPages.getMessages()[0].getDetail(), ' When there is result attachment email sent message is shown');
        System.assertEquals(true, lpae.emailSent, 'emailSent field is true');

    }

    @IsTest static void testWithStartDateNull(){
        redwing__Training_Plan__c currentPlan = [SELECT Id, redwing__Start_Date__c, redwing__End_Date__c FROM redwing__Training_Plan__c WHERE Name = 'Admin Maintenance'];
        currentPlan.redwing__Start_Date__c = null;
        currentPlan.redwing__End_Date__c = null;
        update currentPlan;

        Test.setCurrentPage(Page.LearningPlanAnnouncement);
        LearningPlanAnnouncementExtension lpae = new LearningPlanAnnouncementExtension(new ApexPages.StandardController(currentPlan));

        System.assertEquals(true, ApexPages.hasMessages(), 'When start date of learning plan is null, page has messages');
        System.assertEquals('Maintenance in the future or does not has a Start Date.', ApexPages.getMessages()[0].getDetail(), ' When  start date of learning plan is null message is shown');

    }

    @IsTest static void testWithNotMaintenancePlan(){
        redwing__Training_Plan__c currentPlan = [SELECT Id, redwing__Start_Date__c FROM redwing__Training_Plan__c WHERE Name = 'Admin Maintenance'];
        currentPlan.Is_Maintenance_Plan__c = false;
        update currentPlan;

        Test.setCurrentPage(Page.LearningPlanAnnouncement);
        LearningPlanAnnouncementExtension lpae = new LearningPlanAnnouncementExtension(new ApexPages.StandardController(currentPlan));

        System.assertEquals(true, ApexPages.hasMessages(), 'When learning plan is not maintenance, page has messages');
        System.assertEquals('This learning plan is not a maintenance plan.', ApexPages.getMessages()[0].getDetail(), ' When learning plan is not maintenance message is shown');

    }

    @IsTest static void testWithNoCertifiedPerson(){
        redwing__Training_Plan__c currentPlan = [SELECT Id, redwing__Start_Date__c FROM redwing__Training_Plan__c WHERE Name = 'Admin Maintenance'];

        Test.setCurrentPage(Page.LearningPlanAnnouncement);
        LearningPlanAnnouncementExtension lpae = new LearningPlanAnnouncementExtension(new ApexPages.StandardController(currentPlan));

        System.assertEquals(true, ApexPages.hasMessages(), 'When there is no one with that certification, page has messages');
        System.assertEquals('No one found for this maintenance program.', ApexPages.getMessages()[0].getDetail(), ' When there are no one with th related certification message is shown');

    }

    @IsTest static void testWithCertifiedPerson(){
        redwing__Training_Plan__c currentPlan = [SELECT Id, redwing__Start_Date__c FROM redwing__Training_Plan__c WHERE Name = 'Admin Maintenance'];
        Academy_Certification_Program__c acp = [SELECT Id FROM Academy_Certification_Program__c WHERE Name = 'ADMINISTRATOR'];
        List<Contact> academyContacts = [SELECT Id FROM Contact WHERE LastName = 'Test'];

        List<Academy_Certification_Student__c> academyStudents = new List<Academy_Certification_Student__c>();
        for(Integer i = 0; i < 20; i++){
            Academy_Certification_Student__c academyStudent = new Academy_Certification_Student__c();
            academyStudent.Contact__c = academyContacts[i].Id;
            academyStudent.Student_Email__c = 'academy' + (i + 1) + '@copado.com';
            academyStudents.add(academyStudent);
        }

        insert academyStudents;

        List<Academy_Certification__c> academyCertifications = new List<Academy_Certification__c>();
        for(Academy_Certification_Student__c acs : academyStudents){
            Academy_Certification__c ac = new Academy_Certification__c();
            ac.Certification_Program__c = acp.Id;
            ac.Certification_Student__c = acs.Id;
            ac.Status__c = 'Valid';
            academyCertifications.add(ac);
        }

        insert academyCertifications;

        List<Academy_Certification_Examination__c> academyExaminations = new List<Academy_Certification_Examination__c>();
        Map<Id, Academy_Certification__c> academyCertificationMap = new Map<Id, Academy_Certification__c>();
        for(Academy_Certification__c ac :  academyCertifications){
            Academy_Certification_Examination__c ace = new Academy_Certification_Examination__c();
            ace.Academy_Certification2__c = ac.Id;
            ace.Certification_Student__c = ac.Certification_Student__c;
            ace.Certification_Program__c = acp.Id;
            ace.Status__c = 'Approved';
            ace.Date__c = Date.today().addMonths(-1);
            academyExaminations.add(ace);
            academyCertificationMap.put(ac.Id, ac);
        }

        insert academyExaminations;

        for(Academy_Certification_Examination__c ace : academyExaminations){
            academyCertificationMap.get(ace.Academy_Certification2__c).Certification_Examination__c = ace.Id;
        }

        update academyCertificationMap.values();

        Test.setCurrentPage(Page.LearningPlanAnnouncement);
        LearningPlanAnnouncementExtension lpae = new LearningPlanAnnouncementExtension(new ApexPages.StandardController(currentPlan));

        Test.startTest();
        lpae.sendEmailToCertifiedUsers();
        Test.stopTest();
        System.assertEquals(true, lpae.emailSent, 'Email sent is true');

        Attachment resultAttachment = [SELECT Id, Body FROM Attachment WHERE Name = 'Maintenance Open Mail Results' AND ParentId = :currentPlan.Id];
        System.assertNotEquals(null, resultAttachment);
        System.assert(resultAttachment.Body.toString().contains('Total success: 20'));

    }

}