objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Achievement</label>
        <referenceTo>redwing__Training_Plan_Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>Academy_Certification_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academy Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Is_Maintenance_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to decide if this learning plan is part of an certification maintenance</description>
        <label>Is Maintenance Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maintenance_Expiration_Date__c</fullName>
        <description>Field to decide when the maintenance will expired. Required by a validation rule if Is Maintenance Plan checkbox is checked</description>
        <label>Maintenance Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Days_for_Reminder__c</fullName>
        <label>Schedule Days for Reminder</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redwing__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <inlineHelpText>Only Active Learning Plans will be visible to learners, Draft plans will be visible for Learning Admins</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Section</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only sections from the parent Learning Plan can be selected</errorMessage>
            <filterItems>
                <field>redwing__Training_Plan_Section__c.redwing__Training_Plan__c</field>
                <operation>equals</operation>
                <valueField>$Source.redwing__Training_Plan__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Learning Plan Assignments</relationshipLabel>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Assignments</relationshipLabel>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Assignment</label>
    <nameField>
        <displayFormat>LPAS-{0000000}</displayFormat>
        <label>Learning Plan Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section</label>
    <nameField>
        <label>Learning Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only published learning objects can be added to a Learning Plan</errorMessage>
            <filterItems>
                <field>redwing__Learning__c.redwing__Is_Published_Formula__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>NOTE: Only published learning objects can be associated to a Learning Plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Section__c</fullName>
        <label>Learning Plan Section</label>
        <referenceTo>redwing__Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section Item</label>
    <nameField>
        <displayFormat>LPSI-{0000000}</displayFormat>
        <label>Learning Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SchMaintenanceReminderEmails.cls
public without sharing class SchMaintenanceReminderEmails implements Schedulable {

    public static String academyEmailId;
    public static String templateId;

    public void execute(SchedulableContext sc) {
        List<redwing__Training_Plan__c> plans = [
                SELECT Id, Name, redwing__Start_Date__c, Schedule_Days_for_Reminder__c, Maintenance_Expiration_Date__c, redwing__End_Date__c
                FROM redwing__Training_Plan__c
                WHERE Is_Maintenance_Plan__c = TRUE
                AND redwing__Start_Date__c < :Date.today()
                AND Maintenance_Expiration_Date__c >= :Date.today()
                AND Schedule_Days_for_Reminder__c != NULL
        ];

        if(plans.isEmpty()) {
            return;
        }

        List<redwing__Training_Plan__c> reminderPlansForTomorrow = new List<redwing__Training_Plan__c>();
        List<redwing__Training_Plan__c> reminderPlans = new List<redwing__Training_Plan__c>();
        Set<Id> trainingPlanIds = new Set<Id>();

        for(redwing__Training_Plan__c tp : plans) {
            List<String> scheduleDays = tp.Schedule_Days_for_Reminder__c.split(';');
            for(String day : scheduleDays) {
                Integer untilReminderDay = -1 * Integer.valueOf(day);
                Date reminderDate = tp.Maintenance_Expiration_Date__c.addDays(untilReminderDay);
                if(reminderDate == Date.today()) {
                    System.debug('We will need to send reminder for ' + tp.Name);
                    reminderPlans.add(tp);
                    trainingPlanIds.add(tp.Id);
                } else if(reminderDate == Date.today().addDays(1)) {
                    reminderPlansForTomorrow.add(tp);
                }
            }
        }

        if(reminderPlans.isEmpty() && reminderPlansForTomorrow.isEmpty()) {
            System.debug('We wont send reminders for today');
            return;
        } else if(!reminderPlansForTomorrow.isEmpty()) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(new List<String>{
                    'academy@copado.com'
            });
            email.setSubject('Tomorrow Reminder for Certification Maintenance');
            email.setPlainTextBody('Hello Academy Team, Here is the list of maintenance Ids that will be reminded to students: ' + reminderPlansForTomorrow);
            email.setSaveAsActivity(true);
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>{
                    email
            };
            Messaging.sendEmail(emails, false);
            return;
        } else if(reminderPlans.isEmpty()) {
            return;
        }

        templateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'Academy_Maintenance_Reminder'].Id;
        academyEmailId = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'academy@copado.com'].Id;

        Map<Id, Set<Id>> mapTrainingWithContactToSend = SchMaintenanceReminderEmails.prepareData(trainingPlanIds);
        Set<Id> contactsWithoutMaintenanceTotal = new Set<Id>();
        for(Integer i = 0; i < reminderPlans.size(); i++) {
            Set<Id> contactsWithoutMaintenance = new Set<Id>();
            if (mapTrainingWithContactToSend.containsKey(reminderPlans[i].Id)) {
                contactsWithoutMaintenance = mapTrainingWithContactToSend.get(reminderPlans[i].Id);
            }
            
            if(contactsWithoutMaintenance.isEmpty()) {
                continue;
            }
            if(!contactsWithoutMaintenanceTotal.isEmpty()){
                for(Id cid : contactsWithoutMaintenance){
                    if(contactsWithoutMaintenanceTotal.contains(cid)) contactsWithoutMaintenance.remove(cid);
                }
            } 
            SchMaintenanceReminderEmails.sendEmailToMaintenanceUsers(reminderPlans[i].Id, contactsWithoutMaintenance);   
            contactsWithoutMaintenanceTotal.addAll(contactsWithoutMaintenance);
        }

    }

    public static Map<Id, Set<Id>> prepareData(Set<Id> trainingPlanIds) {
        Map<Id, Date> certificationWithStartDate = new Map<Id, Date>();
        Map<Id, Set<Id>> mapCompletedAssignmentContactIds = new Map<Id, Set<Id>>();
        Map<Id, Set<Id>> mapExpiredCertWithContact = new Map<Id, Set<Id>>();
        Map<Id, Id> mapCertificationWithTrainingPlan = new Map<Id, Id>();
        Map<Id, Set<Id>> mapCertificationWithContact = new Map<Id, Set<Id>>();
        Map<Id, Set<Id>> mapTrainingWithContactToSend = new Map<Id, Set<Id>>();
        Map<Id, Id> trainingPlanWithAchivementId = new Map<Id, Id>();

        for (redwing__Training_Plan_Section_Item__c planSec : [SELECT Id, redwing__Learning__r.Academy_Certification_Program__c,
                        redwing__Training_Plan_Section__r.redwing__Training_Plan__c, redwing__Training_Plan_Section__r.redwing__Training_Plan__r.redwing__Start_Date__c
                        FROM redwing__Training_Plan_Section_Item__c
                        WHERE redwing__Training_Plan_Section__r.redwing__Training_Plan__c IN :trainingPlanIds
                        AND redwing__Learning__r.Academy_Certification_Program__c != NULL]) {
            mapCertificationWithTrainingPlan.put(planSec.redwing__Learning__r.Academy_Certification_Program__c, planSec.redwing__Training_Plan_Section__r.redwing__Training_Plan__c);
            certificationWithStartDate.put(planSec.redwing__Learning__r.Academy_Certification_Program__c, planSec.redwing__Training_Plan_Section__r.redwing__Training_Plan__r.redwing__Start_Date__c);
        }

        for (redwing__Training_Plan_Achievement__c tpa : [Select Id, redwing__Achievement__c From redwing__Training_Plan_Achievement__c
                    Where redwing__Achievement__r.Certification_Program__c IN :mapCertificationWithTrainingPlan.keySet() ]) {
            trainingPlanWithAchivementId.put(tpa.Id, tpa.redwing__Achievement__c);
        }

        for (redwing__Training_Plan_Assignment__c planAssignment : [SELECT Id, redwing__Contact__c, redwing__Training_Plan__c
                FROM redwing__Training_Plan_Assignment__c
                WHERE redwing__Training_Plan__c IN :trainingPlanIds
                AND redwing__Status__c = 'Completed']) {
            if (!mapCompletedAssignmentContactIds.containsKey(planAssignment.redwing__Training_Plan__c)) {
                mapCompletedAssignmentContactIds.put(planAssignment.redwing__Training_Plan__c, new Set<Id>());
            }
            mapCompletedAssignmentContactIds.get(planAssignment.redwing__Training_Plan__c).add(planAssignment.redwing__Contact__c);
        }

        for (redwing__Achievement_Assignment__c aas : [SELECT Id, redwing__Achievement__r.Certification_Program__c, redwing__Contact__c, redwing__Training_Plan_Achievement__c
                        FROM redwing__Achievement_Assignment__c
                        WHERE redwing__Achievement__c IN :trainingPlanWithAchivementId.values() 
                        AND redwing__Training_Plan_Achievement__c IN :trainingPlanWithAchivementId.keySet()
                        AND redwing__Contact__c != NULL AND redwing__Status__c = 'Expired']) {
            if (!mapExpiredCertWithContact.containsKey(aas.redwing__Achievement__r.Certification_Program__c)) {
                mapExpiredCertWithContact.put(aas.redwing__Achievement__r.Certification_Program__c, new Set<Id>());
            }
            mapExpiredCertWithContact.get(aas.redwing__Achievement__r.Certification_Program__c).add(aas.redwing__Contact__c);
        }
        for (Academy_Certification__c ac : [SELECT Id, Certification_Student__r.Contact__c, Earned_Date__c, Certification_Student__r.Contact__r.Name, Certification_Student__r.Contact__r.Email, Certification_Program__c
                        FROM Academy_Certification__c
                        WHERE Certification_Program__c IN :certificationWithStartDate.keySet()
                        AND Certification_Student__r.Contact__c != NULL]) {
            if (!mapCertificationWithContact.containsKey(ac.Certification_Program__c)) {
                mapCertificationWithContact.put(ac.Certification_Program__c, new Set<Id>());
            }
            if (ac.Earned_Date__c < certificationWithStartDate.get(ac.Certification_Program__c)) {
                mapCertificationWithContact.get(ac.Certification_Program__c).add(ac.Certification_Student__r.Contact__c);
            }
        }

        for (Id certId : mapCertificationWithContact.keySet()) {
            Set<Id> conIdsToBeUpdate = mapCertificationWithContact.get(certId);
            Id tPlanId = mapCertificationWithTrainingPlan.containsKey(certId) ? mapCertificationWithTrainingPlan.get(certId) : null;

            if (mapExpiredCertWithContact.containsKey(certId)) {
                for (Id conId : mapExpiredCertWithContact.get(certId)) {
                    if (conIdsToBeUpdate.contains(conId)) {
                        conIdsToBeUpdate.remove(conId);
                    }
                }
            }

            if (tPlanId != null && mapCompletedAssignmentContactIds.containsKey(tPlanId)) {
                for (Id conId : mapCompletedAssignmentContactIds.get(tPlanId)) {
                    if (conIdsToBeUpdate.contains(conId)) {
                        conIdsToBeUpdate.remove(conId);
                    }
                }
            }

            mapTrainingWithContactToSend.put(tPlanId, conIdsToBeUpdate);
        }

        return mapTrainingWithContactToSend;
    }

    public static void sendEmailToMaintenanceUsers(String planId, Set<Id> contactIds) {
        List<Id> contactIdList = new List<Id>();
        contactIdList.addAll(contactIds);
        BatchAcademyEmail bae = new BatchAcademyEmail();
        bae.emailWhatId = planId;
        bae.targetObjectIds = contactIdList;
        bae.orgWideEmailId = academyEmailId;
        bae.templateId = templateId;
        bae.typeOfEmail = 'Reminder';
        Database.executeBatch(bae, 20);
    }
}