objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Earned_Date__c</fullName>
        <description>Earned date of Certification. Comes from first Examination Date</description>
        <label>Earned Date</label>
        <summarizedField>Academy_Certification_Examination__c.Date__c</summarizedField>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Academy_Certification_Examination__c.Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Academy_Certification_Examination__c.Academy_Certification2__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration Date of certification based on approved Examination date.</description>
        <formula>IF(ISBLANK(Certification_Examination__r.Date__c),TODAY()-1,
	(DATE(YEAR( DATEVALUE(Certification_Examination__r.Date__c)) + 1,
			MONTH(DATEVALUE(Certification_Examination__r.Date__c)), 
				DAY(DATEVALUE(Certification_Examination__r.Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JBCXM__SurveyParticipant__c.object
<CustomObject>
    <description>This is used to store survey participants</description>
    <fields>
        <fullName>JBCXM__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Participants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SuP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>Academy_Certification_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academy Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Is_Certification_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a certification plan or not?</description>
        <inlineHelpText>Is it a certification plan or not?</inlineHelpText>
        <label>Is Certification Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Maintenance_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to decide if this learning plan is part of an certification maintenance</description>
        <label>Is Maintenance Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>redwing__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section</label>
    <nameField>
        <label>Learning Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only published learning objects can be added to a Learning Plan</errorMessage>
            <filterItems>
                <field>redwing__Learning__c.redwing__Is_Published_Formula__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>NOTE: Only published learning objects can be associated to a Learning Plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Section__c</fullName>
        <label>Learning Plan Section</label>
        <referenceTo>redwing__Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section Item</label>
    <nameField>
        <displayFormat>LPSI-{0000000}</displayFormat>
        <label>Learning Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LearningPlanAnnouncementExtension.cls
public with sharing class LearningPlanAnnouncementExtension {

    public redwing__Training_Plan__c currentPlan { get; set; }
    private Id certificationProgramId;
    private Set<Id> contactIds;
    public transient List<Academy_Certification__c> certifications { get; set; }
    public transient List<Academy_Certification__c> certificationsToShow { get; set; }
    public Boolean emailSent { get; set; }
    public Integer totalSuccess { get; set; }
    public Integer totalError { get; set; }
    public String errorMessages { get; set; }
    public String academyEmailId;
    public String templateId;

    public LearningPlanAnnouncementExtension(ApexPages.StandardController stdController) {
        List<Attachment> attachments = [SELECT Id FROM Attachment WHERE Name = 'Maintenance Open Mail Results' AND ParentId = :stdController.getId()];
        currentPlan = new redwing__Training_Plan__c();
        if(attachments.size() > 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Email already sent!'));
            emailSent = true;
            return;
        }
        emailSent = false;
        currentPlan = [
                SELECT Id, Is_Maintenance_Plan__c, Is_Certification_Plan__c, Name, redwing__Start_Date__c
                FROM redwing__Training_Plan__c
                WHERE Id = :stdController.getId()
        ];

        if(currentPlan.redwing__Start_Date__c == NULL || currentPlan.redwing__Start_Date__c > Date.today()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Maintenance in the future or does not has a Start Date.'));
            emailSent = true;

            return;
        }

        if(!currentPlan.Is_Maintenance_Plan__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This learning plan is not a maintenance plan.'));
            emailSent = true;
            return;
        }


        List<redwing__Training_Plan_Section_Item__c> sectionItems = [SELECT Id, redwing__Learning__r.Academy_Certification_Program__c FROM redwing__Training_Plan_Section_Item__c WHERE redwing__Training_Plan_Section__r.redwing__Training_Plan__c = :currentPlan.Id AND redwing__Learning__r.Academy_Certification_Program__c != NULL LIMIT 1];

        if(sectionItems.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Could not find responding Certification Program. Please check the data.'));
            emailSent = true;
            return;
        }

        templateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'Maintenance_Exam_Window_Open2'].Id;
        academyEmailId = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'academy@copa.do'].Id;

        certificationProgramId = sectionItems[0].redwing__Learning__r.Academy_Certification_Program__c;
        certifications = new List<Academy_Certification__c>();
        totalSuccess = 0;
        totalError = 0;
        errorMessages = '';
        findUsersToNotify();
    }

    public void findUsersToNotify() {
        certifications = [
                SELECT Id, Certification_Student__r.Contact__c, Certification_Student__r.Contact__r.Name, Certification_Student__r.Contact__r.Email, Certification_Program__c
                FROM Academy_Certification__c
                WHERE Earned_Date__c < :currentPlan.redwing__Start_Date__c
                AND Expiration_Date__c >= :Date.today()
                AND Certification_Program__c = :certificationProgramId
                AND Certification_Student__r.Contact__c != NULL
        ];

        if(certifications.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No one found for this maintenance program.'));
            return;
        }

        contactIds = new Set<Id>();
        Integer counter = 0;
        certificationsToShow = new List<Academy_Certification__c>();
        for(Academy_Certification__c ac : certifications) {
            contactIds.add(ac.Certification_Student__r.Contact__c);
            if(counter > 999) {
                continue;
            }
            counter++;
            certificationsToShow.add(ac);
        }


    }

    public PageReference sendEmailToCertifiedUsers() {

        if(emailSent) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Email already sent!'));
            return null;
        }

        List<Id> contactIdList = new List<Id>();
        contactIdList.addAll(contactIds);
        BatchAcademyEmail bae = new BatchAcademyEmail();
        bae.emailWhatId = currentPlan.Id;
        bae.targetObjectIds = contactIdList;
        bae.orgWideEmailId = academyEmailId;
        bae.templateId = templateId;
        Database.executeBatch(bae, 20);
        emailSent = true;
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'Email sending operation started!'));

        return null;
    }

}