objects/Academy_Certification_Delivery__c.object
<CustomObject>
    <description>Academy Certification Delivery holds the date and type of certification.</description>
    <fields>
        <fullName>Academy_Certification_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academy Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Deliveries</relationshipLabel>
        <relationshipName>Academy_Certification_Deliveries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Delivery</label>
    <nameField>
        <displayFormat>ACD-{0000}</displayFormat>
        <label>Academy Certification Delivery</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/amc__Time_Log__c.object
<CustomObject>
    <description>Enables project team members to log time against Actions</description>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TLN-{00000000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Configuration_Execution__c.object
<CustomObject>
    <label>Configuration Execution</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Configuration Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuration Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Configuration_Step__c.object
<CustomObject>
    <label>Configuration Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Line_Item__c.object
<CustomObject>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Contract Line Item Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado1p__Platform_Job_Execution__c.object
<CustomObject>
    <description>This object is used to track every C1P job execution, one will be created per each request.</description>
    <label>Platform Job Execution</label>
    <nameField>
        <displayFormat>PJE-{00000}</displayFormat>
        <label>Platform Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Job Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Release__c.object
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Demo__c.object
<CustomObject>
    <description>This object keeps all the information related to Demos.</description>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interactive_Validation_Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>Validation_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Validation Execution</label>
        <referenceTo>Validation_Execution__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interactive Validation Step Execution</label>
    <nameField>
        <label>Interactive Validation Step Execution Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validation Step Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__SalesOrder__c.object
<CustomObject>
    <description>Kugamon - Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>SO-{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ltcomm__Learning_Order__c.object
<CustomObject>
    <label>Learning Order</label>
    <nameField>
        <displayFormat>LRDR-{000000}</displayFormat>
        <label>Learning Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Psydo_Case__c.object
<CustomObject>
    <description>This is a trigger object to insert/update the actual data</description>
    <label>Psydo Case</label>
    <nameField>
        <displayFormat>PC{00000}</displayFormat>
        <label>Public Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Psydo Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__ILT_Roster__c.object
<CustomObject>
    <label>ILT Roster</label>
    <nameField>
        <displayFormat>RSTR-{00000000}</displayFormat>
        <label>ILT Roster Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILT Rosters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>Configuration_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Configuration Execution</label>
        <referenceTo>Configuration_Execution__c</referenceTo>
        <relationshipLabel>Step Executions</relationshipLabel>
        <relationshipName>Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Configuration_Step__c</fullName>
        <label>Configuration Step</label>
        <referenceTo>Configuration_Step__c</referenceTo>
        <relationshipLabel>Step Executions</relationshipLabel>
        <relationshipName>Step_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Step Execution</label>
    <nameField>
        <label>Step Execution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Validation_Execution__c.object
<CustomObject>
    <label>Validation Execution</label>
    <nameField>
        <displayFormat>VE-{000000}</displayFormat>
        <label>Validation Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Validation Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TriggerFactory.cls
/**
 * Class TriggerFactory
 *
 * Used to instantiate and execute Trigger Handlers associated with sObjects.
 */
public with sharing class TriggerFactory
{
    /**
     * Public static method to create and execute a trigger handler
     *
     * Arguments:   Schema.sObjectType soType - Object type to process (SObject.sObjectType)
     *
     * Throws a TriggerException if no handler has been coded.
     */
    public static void createHandler(Schema.sObjectType soType)
    {
        // Get a handler appropriate to the object being processed
        ITrigger handler = getHandler(soType);
        
        // Make sure we have a handler registered, new handlers must be registered in the getHandler method.
        
        if (handler == null)
        {
            throw new TriggerException('No Trigger Handler registered for Object Type: ' + soType);
        }
        
        // Execute the handler to fulfil the trigger
        execute(handler);
    }
    
    /**
     * private static method to control the execution of the handler
     *
     * Arguments:   ITrigger handler - A Trigger Handler to execute
     */ 
    private static void execute(ITrigger handler)
    {
        // Before Trigger
        if (Trigger.isBefore)
        {
            // Call the bulk before to handle any caching of data and enable bulkification
            handler.bulkBefore();
            
            // Iterate through the records to be deleted passing them to the handler.
            if (Trigger.isDelete)
            {
                for (SObject so : Trigger.old)
                {
                    handler.beforeDelete(so);
                }
            }
            // Iterate through the records to be inserted passing them to the handler.
            else if (Trigger.isInsert)
            {
                for (SObject so : Trigger.new)
                {
                    handler.beforeInsert(so);
                }
            }
            // Iterate through the records to be updated passing them to the handler.
            else if (Trigger.isUpdate)
            {
                for (SObject so : Trigger.old)
                {
                    handler.beforeUpdate(so, Trigger.newMap.get(so.Id));
                }
            }
        }
        else
        {
            // Call the bulk after to handle any caching of data and enable bulkification
            handler.bulkAfter();
            
            // Iterate through the records deleted passing them to the handler.
            if (Trigger.isDelete)
            {
                for (SObject so : Trigger.old)
                {
                    handler.afterDelete(so);
                }
            }
            // Iterate through the records inserted passing them to the handler.
            else if (Trigger.isInsert)
            {
                for (SObject so : Trigger.new)
                {
                    handler.afterInsert(so);
                }
            }
            // Iterate through the records updated passing them to the handler.
            else if (Trigger.isUpdate)
            {
                for (SObject so : Trigger.old)
                {
                    handler.afterUpdate(so, Trigger.newMap.get(so.Id));
                }
            }
        }
        
        // Perform any post processing
        handler.andFinally();
    }
    
    /**
     * private static method to get the appropriate handler for the object type.
     * Modify this method to add any additional handlers.
     *
     * Arguments:   Schema.sObjectType soType - Object type tolocate (SObject.sObjectType)
     *
     * Returns:     ITrigger - A trigger handler if one exists or null.
     */
    @TestVisible
    private static ITrigger getHandler(Schema.sObjectType soType)
    {
        if (soType == Account.sObjectType) {
            return new AccountHandler();
        }
        if (soType == Contact.sObjectType) {
            return new ContactTriggerHandler();
        }
        if (soType == Psydo_Case__c.sObjectType) {
            return new PsydoCaseTriggerHandler();
        }
        if (soType == Contract_Line_Item__c.sObjectType) {
            return new ContractLineItemTriggerHandler();
        }
        if (soType == Case.sObjectType) {
            return new CaseTriggerHandler();
        }
        if (soType == SBQQ__Quote__c.sObjectType){
            return new CPQQuoteTriggerHandler();
        }
        if (soType == Task.sObjectType){
            return new TaskTriggerHandler();
        }
        if (soType == EmailMessage.sObjectType){
            return new EmailMessageTriggerHandler();
        }
        if (soType == Order.sObjectType){
            return new OrderTriggerHandler();
        }
        if (soType == copado__Release__c.sObjectType){
            return new ReleaseTriggerHandler();
        }
        if (soType == Salesforce_Org__c.sObjectType){
            return new SalesforceOrgHandler();
        }
        if (soType == Demo__c.sObjectType){
            return new MeetingTriggerHandler();
        }
        if (soType == sfLma__License__c.sObjectType){
            return new LicenseHandler();
        }
        if (soType == Academy_Certification_Student__c.sObjectType){
            return new AcademyCertificationStudentHandler();
        }
        if (soType == Academy_Certification_Delivery__c.sObjectType){
            return new AcademyCertificationDeliveryHandler();
        }
        if (soType == amc__Time_Log__c.sObjectType){
            return new MC_TimeLogTriggerHandler();
        }
        if (soType == Playground_Job__c.sObjectType){
            return new PlaygroundJobTriggerHandler();
        }
        if (soType == Lead.sObjectType){
            return new LeadTriggerHandler();
        }
        if (soType == ltcomm__Learning_Order__c.sObjectType){
            return new LearningOrderTriggerHandler();
        }


        if (soType == OpportunityLineItem.sObjectType){
            return new OpportunityLineItemTriggerHandler();
        }
        if (soType == Opportunity.sObjectType){
            return new OpportunityTriggerHandler();
        }
         if (soType == redwing__ILT_Roster__c.sObjectType){
            return new ILT_RosterTriggerHandler();  
        }
        if (soType == Step_Execution__c.sObjectType){
           return new StepExecutionTriggerHelper();
        }
        if (soType == copado1p__Platform_Job_Execution__c.sObjectType){
            return new PlatformJobExecutionTriggerHelper();
        }
        if (soType == Interactive_Validation_Step_Execution__c.sObjectType){
            return new InteractiveValidStepExeTriggerHelper();
        }
        if (soType == kugo2p__SalesOrder__c.sObjectType){
            return new KugamonOrderTriggerHandler();
        }
        if (soType == Campaign.sObjectType){
            return new SalesforceCampaignTriggerHandler();
        }
        if (soType == Validation_Execution__c.sObjectType){
            return new ValidationExecutionTriggerHelper();
        }
        if (soType == Configuration_Execution__c.sObjectType){
            return new ConfigExecutionTriggerHelper();
        }
        if (soType == Configuration_Step__c.sObjectType){
           return new ConfigurationStepTriggerHelper();
        }

        return null;
    }
}