objects/Academy_API_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>trusted_IP_Address__c</fullName>
        <label>trusted IP Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy API Settings</label>
</CustomObject>

objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Examination__c.object
<CustomObject>
    <description>Exams records applied to student in order to support achieved certifications</description>
    <fields>
        <fullName>Academy_Certification2__c</fullName>
        <label>Academy Certification</label>
        <referenceTo>Academy_Certification__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations (Academy Certification)</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the certification program</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date when exam was or will be applied.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Examination Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Examination</label>
    <nameField>
        <displayFormat>ACE-{000000}</displayFormat>
        <label>Academy Certification Examination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Chamilo_Id__c</fullName>
        <externalId>true</externalId>
        <label>Chamilo Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Copado_Version__c</fullName>
        <description>Current Copado version, to identify features covered on certification</description>
        <label>Copado Version</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Chamilo_Id__c</fullName>
        <description>Id of the User in Chamilo, auto-populated if is a new user</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the User in Chamilo, auto-populated if is a new user</inlineHelpText>
        <label>Chamilo Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Student Id to identify student from external platforms</description>
        <externalId>true</externalId>
        <label>Student Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestAcademyStudents.cls
@isTest
private class TestAcademyStudents {

	@isTest 
	private static void testAcademyStudentUnknownRequestError() {
		Academy_API_Settings__c AAS = new Academy_API_Settings__c();
    	AAS.trusted_IP_Address__c = 'AC16DFF0C26F327074C5079287876515B25FD91D3AD3D1E4C434341296B6CA40';
    	AAS.Name='ValidNode';
    	insert (AAS);
     	RestRequest re = new RestRequest();
     	RestResponse rp = new RestResponse();
     	re.requestURI = '/services/apexrest/';
     	re.remoteAddress = '192.168.1.1';
     	re.addHeader('httpMethod', 'GET');
     	re.addHeader('Idtoken', 'AC16DFF0C26F327074C5079287876515B25FD91D3AD3D1E4C434341296B6CA40XXX');
     	re.addParameter('student_Name', 'Federico Mahuel');
     	RestContext.request = re;
     	RestContext.response = rp;
        Test.startTest();
     	AcademyStudents.show();
     	System.assertEquals(rp.responseBody,Blob.valueOf('{"errorMessage":"Forbidden"}'));
        Test.stopTest();
	}
    
    @isTest 
	private static void testAcademyStudentUnknownRequest() {
		Academy_API_Settings__c AAS = new Academy_API_Settings__c();
    	AAS.trusted_IP_Address__c = 'AC16DFF0C26F327074C5079287876515B25FD91D3AD3D1E4C434341296B6CA40';
    	AAS.Name='ValidNode';
    	insert (AAS);
     	RestRequest re = new RestRequest();
     	RestResponse rp = new RestResponse();
     	re.requestURI = '/services/apexrest/';
     	re.remoteAddress = '192.168.1.1';
     	re.addHeader('httpMethod', 'GET');
     	re.addHeader('Idtoken', 'AC16DFF0C26F327074C5079287876515B25FD91D3AD3D1E4C434341296B6CA40');
     	re.addParameter('student_Name', 'Federico Mahuel');
     	RestContext.request = re;
     	RestContext.response = rp;
        Test.startTest();
     	AcademyStudents.show();
     	System.assertEquals(rp.responseBody,Blob.valueOf('{"errorMessage":"No student registered for Federico Mahuel"}'));
        Test.stopTest();
	}

	@isTest
    private static void testAcademyStudentKnownRequest() {
        RestResponse rp = new RestResponse();
        Contact c = new Contact(FirstName ='David1', LastName ='Pinett1',Email = 'pinett1@copa.do');
        insert c;
        Test.startTest();
        String b = '<?xml version="1.0" encoding="ISO-8859-1"?><SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:WSUser.CreateUserResponse xmlns:ns1="urn:WSService"><return xsi:type="xsd:int">115</return></ns1:WSUser.CreateUserResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>';
        Test.setMock(HttpCalloutMock.class, new testHttpCalloutMock(200,'Success', b));
        Academy_Certification_Student__c cs = new Academy_Certification_Student__c();
        cs.Student_Id__c = 'user1@demo.com';
        cs.Contact__c = c.Id;
        //cs.Chamilo_id__c = '12';
        insert cs;
        Academy_Certification_Program__c acp = new Academy_Certification_Program__c(Name = 'Student', Copado_Version__c = 'V10', Status__c = 'Valid');
	    insert acp;
        Academy_Certification__c ac = new Academy_Certification__c(Certification_Student__c=cs.id, Certification_Program__c =acp.id, Status__c='Valid');
        insert ac;
	    Academy_Certification_Examination__c  ace = new Academy_Certification_Examination__c (Certification_Program__c=acp.Id, Certification_Student__c=cs.id,Status__c = 'Approved',Date__c = datetime.newInstance(2018, 9, 15, 12, 30, 0), Academy_Certification2__c = ac.Id);
	    insert ace;

        Academy_API_Settings__c AAS = new Academy_API_Settings__c();
        AAS.trusted_IP_Address__c = 'AC16DFF0C26F327074C5079287876515B25FD91D3AD3D1E4C434341296B6CA40';
        AAS.Name='ValidNode';
        insert (AAS);
        RestRequest re = new RestRequest();
        re.requestURI = '/services/apexrest/';
        re.addHeader('httpMethod', 'GET');
        re.addHeader('Idtoken', 'AC16DFF0C26F327074C5079287876515B25FD91D3AD3D1E4C434341296B6CA40');
        re.addParameter('student_Name', 'David Pinett');
        RestContext.request = re;
        RestContext.response = rp;
        AcademyStudents.show();
        Test.stopTest();
	}

}