objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration Date of certification based on approved Examination date.</description>
        <formula>IF(ISBLANK(Certification_Examination__r.Date__c),TODAY()-1,
	(DATE(YEAR( DATEVALUE(Certification_Examination__r.Date__c)) + 1,
			MONTH(DATEVALUE(Certification_Examination__r.Date__c)), 
				DAY(DATEVALUE(Certification_Examination__r.Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Achievement__c.object
<CustomObject>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Achievements</relationshipLabel>
        <relationshipName>Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Expiration_Date__c</fullName>
        <inlineHelpText>Expired achievements will not be displayed in the users profile page</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Achievement</label>
        <referenceTo>redwing__Training_Plan_Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CertificationExpirationBatch.cls
global class CertificationExpirationBatch implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id, redwing__Achievement__c,redwing__Achievement__r.Certification_Program__r.Name, redwing__Status__c, redwing__Expiration_Date__c, redwing__Contact__c FROM redwing__Achievement_Assignment__c WHERE redwing__Contact__c!=NULL AND redwing__Training_Plan_Achievement__r.redwing__Training_Plan__r.Is_Certification_Plan__c = TRUE]);
    }
    
    global void execute(Database.BatchableContext bc, List<redwing__Achievement_Assignment__c> scope){
        Set<String> contactIds = new Set<String>();
        for(redwing__Achievement_Assignment__c achievementObj : scope){
            contactIds.add(achievementObj.redwing__Contact__c);
        }
        Map<String,Academy_Certification_Student__c> certificationStudentMap = new Map<String,Academy_Certification_Student__c>([SELECT Id,Contact__c FROM Academy_Certification_Student__c WHERE Contact__c IN:contactIds ]);
        Map<String,Academy_Certification__c> expiredCertificationMap = new Map<String,Academy_Certification__c>([SELECT Id,Certification_Student__r.Contact__c,Certification_Program__c,Expiration_Date__c,Status__c FROM Academy_Certification__c WHERE Certification_Student__c IN:certificationStudentMap.keySet() AND Status__c = 'Expired' ]);
        Set<String> expiredCertificateContactIds = new Set<String>();
        Set<String> expiredCertificateProgramIds = new Set<String>();

        // Map to store the expired certificates, by using key as combination of Contact and Certification Program Id
        // and value as expired certificate record.
        Map<String,Academy_Certification__c> certificationWithContactIdMap = new Map<String,Academy_Certification__c>();
        for(String recordId : expiredCertificationMap.keySet()){
            certificationWithContactIdMap.put(String.valueof(expiredCertificationMap.get(recordId).Certification_Student__r.Contact__c) + String.valueof(expiredCertificationMap.get(recordId).Certification_Program__c),expiredCertificationMap.get(recordId));
            expiredCertificateContactIds.add(expiredCertificationMap.get(recordId).Certification_Student__r.Contact__c);
            expiredCertificateProgramIds.add(expiredCertificationMap.get(recordId).Certification_Program__c);
        }

        // List to store the valid certificates records of same certification program which have expired certificates
        // and same Contacts of expired certificates
        List<Academy_Certification__c> validCertificationList = new List<Academy_Certification__c>([SELECT Id,Certification_Student__r.Contact__c, Certification_Program__c FROM Academy_Certification__c WHERE Certification_Student__c IN :certificationStudentMap.keySet() AND Status__c = 'Valid' AND Certification_Student__r.Contact__c IN :expiredCertificateContactIds AND Certification_Program__c IN :expiredCertificateProgramIds]);

        // Map to store the valid certificates, by using key as combination of Contact and Certification Program Id
        // and value as expired certificate record.
        Map<String,Academy_Certification__c> contactCertificationProgramKeyWithValidCertificateMap = new Map<String,Academy_Certification__c>();
        for(Academy_Certification__c validCertificate : validCertificationList) {
            contactCertificationProgramKeyWithValidCertificateMap.put(String.valueof(validCertificate.Certification_Student__r.Contact__c) + String.valueof(validCertificate.Certification_Program__c), validCertificate);
        }

        map<String,redwing__Achievement_Assignment__c> updateAchievementAssignment = new map<String,redwing__Achievement_Assignment__c>();
        Map<String,redwing__Achievement_Assignment__c> expiredAchievementAssignmentMap= new map<String,redwing__Achievement_Assignment__c>([SELECT Id, redwing__Achievement__c,redwing__Achievement__r.Certification_Program__c, redwing__Status__c, redwing__Expiration_Date__c, redwing__Contact__c FROM redwing__Achievement_Assignment__c WHERE redwing__Contact__c IN: expiredCertificateContactIds AND redwing__Achievement__r.Certification_Program__c IN:expiredCertificateProgramIds  AND redwing__Training_Plan_Achievement__r.redwing__Training_Plan__r.Is_Certification_Plan__c = TRUE]);
        for(String recordId : expiredAchievementAssignmentMap.keySet()){
            String mapKey = String.valueof(expiredAchievementAssignmentMap.get(recordId).redwing__Contact__c) + String.valueof(expiredAchievementAssignmentMap.get(recordId).redwing__Achievement__r.Certification_Program__c);

            // Condition to update the status of Achievement Assignment to expired,
            // if no valid certificate for corresponding certification program is found.
            if(certificationWithContactIdMap.containsKey(mapKey) && !contactCertificationProgramKeyWithValidCertificateMap.containsKey(mapKey) 
               && expiredAchievementAssignmentMap.get(recordId).redwing__Status__c != 'Expired'){
                  redwing__Achievement_Assignment__c achievement = new redwing__Achievement_Assignment__c();
                  achievement.Id = recordId;
                  achievement.redwing__Status__c = 'Expired';
                  updateAchievementAssignment.put(recordId,achievement);
              }
            // Condition to update the status of Achievement Assignment to acquired,
            // if valid certificate for corresponding certification program is found.
            if(certificationWithContactIdMap.containsKey(mapKey) && contactCertificationProgramKeyWithValidCertificateMap.containsKey(mapKey) 
               && expiredAchievementAssignmentMap.get(recordId).redwing__Status__c == 'Expired'){
                  redwing__Achievement_Assignment__c achievement = new redwing__Achievement_Assignment__c();
                  achievement.Id = recordId;
                  achievement.redwing__Status__c = 'Acquired';
                  updateAchievementAssignment.put(recordId,achievement);
              }
        }
        if(updateAchievementAssignment.size()>0){
            UPDATE updateAchievementAssignment.values();
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
}