objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Achievements</fullName>
                    <default>true</default>
                    <label>Achievements</label>
                </value>
                <value>
                    <fullName>Certifications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__ILT_Class__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>ILT Classes</relationshipLabel>
        <relationshipName>ILT_Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ILT Class</label>
    <nameField>
        <label>ILT Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILT Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__ILT_Event__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>ILT Events</relationshipLabel>
        <relationshipName>ILT_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ILT Event</label>
    <nameField>
        <label>ILT Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILT Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__ILT_Event_Class__c.object
<CustomObject>
    <fields>
        <fullName>redwing__ILT_Event__c</fullName>
        <label>ILT Event</label>
        <referenceTo>redwing__ILT_Event__c</referenceTo>
        <relationshipLabel>ILT Event Classes</relationshipLabel>
        <relationshipName>ILT_Event_Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>redwing__Learning__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ILT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>ILT Event Classes</relationshipLabel>
        <relationshipName>ILT_Event_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ILT Event Class</label>
    <nameField>
        <displayFormat>ILTEC-{0000000}</displayFormat>
        <label>ILT Event Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ILT Event Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__ILT_Session__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ILT</fullName>
                    <default>true</default>
                    <label>ILT</label>
                </value>
                <value>
                    <fullName>vILT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ILT Session</label>
    <nameField>
        <label>ILT Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ILT Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Learning_Prerequisite__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipName>Prerequisite_Parent_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipName>Prerequisite_Parent_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Prerequisite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prerequisite</label>
        <referenceTo>redwing__Prerequisite__c</referenceTo>
        <relationshipLabel>Learning Prerequisites</relationshipLabel>
        <relationshipName>Prerequisite_Parents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Prerequisite</label>
    <nameField>
        <displayFormat>LPN-{0}</displayFormat>
        <label>Learning Prerequisite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Prerequisites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Prerequisite__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Instructor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Prerequisite</label>
    <nameField>
        <label>Prerequisite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prerequisites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Prerequisite_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Prerequisite Items</relationshipLabel>
        <relationshipName>Prerequisite_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Prerequisite Items</relationshipLabel>
        <relationshipName>Prerequisite_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Prerequisite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prerequisite</label>
        <referenceTo>redwing__Prerequisite__c</referenceTo>
        <relationshipLabel>Prerequisite Items</relationshipLabel>
        <relationshipName>Prerequisite_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Required_Status__c</fullName>
        <label>Required Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Prerequisite Item</label>
    <nameField>
        <label>Prerequisite Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prerequisite Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TrainingConsole.cls
public class TrainingConsole {
      
    //Get All Events List
    @AuraEnabled
    public static list<redwing__ILT_Event__c> getAllILTEvents(){
        RETURN [SELECT Id,name,redwing__Learning__c,redwing__Learning__r.Name, (SELECT Id,Name,redwing__Learning__c,redwing__Learning__r.Name FROM redwing__ILT_Event_Classes__r) FROM redwing__ILT_Event__c];
    }
    
    //get All Not Completed Prerequistite Items By LearningId
    @AuraEnabled
    public static PrerequisiteRequestResponse getPrerequistiteItemsByLearningId(String ILTEventLearningId){
        PrerequisiteRequestResponse PreResponse = new PrerequisiteRequestResponse();
        list<AchievementAssignmentWrap> AchievementAssignmentList = new list<AchievementAssignmentWrap>();
        List<redwing__Prerequisite_Item__c> Prerequisite_Items = new List<redwing__Prerequisite_Item__c>([SELECT Id ,Name,redwing__Prerequisite__c  FROM redwing__Prerequisite_Item__c WHERE redwing__Achievement__r.redwing__Type__c!= 'Certifications' AND redwing__Required_Status__c !='Completed' AND redwing__Prerequisite__c IN (SELECT redwing__Prerequisite__c FROM redwing__Learning_Prerequisite__c WHERE redwing__Learning__c =:ILTEventLearningId)]);
        PreResponse.Prerequisite_Items= new List<redwing__Prerequisite_Item__c>(Prerequisite_Items);
        List<String> PrequistiteItemNames = new List<String>();
        for(redwing__Prerequisite_Item__c Item : Prerequisite_Items){
            PrequistiteItemNames.add(Item.Name);
        }
        if(PrequistiteItemNames.size()>0){
           list<redwing__Achievement__c> Achievements = new list<redwing__Achievement__c>([SELECT Id,Name,(SELECT Id, Name,redwing__User__c,redwing__User__r.Name, redwing__Achievement__c, redwing__Acquisition_Date__c, redwing__Contact__c, redwing__Status__c,redwing__Achievement__r.redwing__Type__c FROM redwing__Achievement_Assignments__r) FROM redwing__Achievement__c WHERE Name In : PrequistiteItemNames]);
            for(redwing__Achievement__c Achievement : Achievements){
                for(redwing__Achievement_Assignment__c Assignment : Achievement.redwing__Achievement_Assignments__r){
                    if(Assignment.redwing__Achievement__r.redwing__Type__c!='Certifications'){
                        AchievementAssignmentWrap  achivementWrap = new AchievementAssignmentWrap();
                        achivementWrap.UserId = Assignment.redwing__User__c;
                        achivementWrap.UserName = Assignment.redwing__User__r.Name;
                        achivementWrap.PrerequisiteId = Achievement.Id ;
                        achivementWrap.PrerequisiteName = Achievement.Name;
                        achivementWrap.PrerequisiteItemId = Assignment.Id;
                        achivementWrap.status = Assignment.redwing__Status__c;
                        AchievementAssignmentList.add(achivementWrap);
                    }
                }
            }
        }
        PreResponse.AchievementAssignmentList= new List<AchievementAssignmentWrap>(AchievementAssignmentList);
        RETURN PreResponse;
    }
    
    //Training Console
    @AuraEnabled
    public static NewResponse GetILTCLassesByEventId(String eventId){
        NewResponse response = new NewResponse();
        Map<String,String> LearningIdWithEventClass = new Map<String,String>();
        MAP<Id,redwing__ILT_Event__c> ILTEventRecordMap = NEW MAP<Id,redwing__ILT_Event__c>([SELECT Id,name,redwing__Learning__c,redwing__Learning__r.Name, (SELECT Id,Name,redwing__Learning__c,redwing__Learning__r.Name FROM redwing__ILT_Event_Classes__r) FROM redwing__ILT_Event__c WHERE Id =:eventId]);
        for(String ILTEventId : ILTEventRecordMap.keyset()){
            if(ILTEventRecordMap.get(ILTEventId).redwing__ILT_Event_Classes__r!=NULL){
                for(redwing__ILT_Event_Class__c EventClass : ILTEventRecordMap.get(ILTEventId).redwing__ILT_Event_Classes__r){
                    LearningIdWithEventClass.put(EventClass.redwing__Learning__c,EventClass.Id);
                }
            }
        }
        response.AcademyCertificationPrograms = new List<Academy_Certification_Program__c>([SELECT Id,name FROM Academy_Certification_Program__c WHERE Status__c = 'Valid']);
        if(LearningIdWithEventClass.size()>0){
            List<String> ContactIds = new List<String>();
            Map<String,redwing__ILT_Roster__c> ContactIdWithRoaster = new Map<String,redwing__ILT_Roster__c>();
            MAP<Id,redwing__ILT_Class__c> ILTClasses = NEW MAP<Id,redwing__ILT_Class__c>([SELECT Id,name,redwing__Learning__c,redwing__Learning__r.Name,(SELECT  Id, Name, redwing__Attended__c, redwing__Learning_Assignment__c, redwing__Grade__c, redwing__ILT_Class__c, redwing__ILT_Session__c,redwing__ILT_Session__r.Name, redwing__Status__c, redwing__User__c,redwing__User__r.Name,redwing__User__r.ContactId, redwing__Registered_Date__c FROM redwing__ILT_Rosters__r) FROM redwing__ILT_Class__c WHERE redwing__Learning__c IN: LearningIdWithEventClass.keySet()]);
            system.debug(ILTClasses);
            response.ILTClasses = New  List<redwing__ILT_Class__c>();
            response.ILTClasses.addAll(ILTClasses.values());
            List<Academy_Certification__c> AcademyCertificationList = New  List<Academy_Certification__c>();
            Map<String,List<Academy_Certification__c>> ContactIdWithListOfAcademy_CertificationMap = new Map<String,List<Academy_Certification__c>>();
            if(ILTClasses.size()>0){
                for(redwing__ILT_Class__c ILTClass : ILTClasses.values()){
                    if(ILTClass.redwing__ILT_Rosters__r!=NULL){
                        for(redwing__ILT_Roster__c Roaster :ILTClass.redwing__ILT_Rosters__r){
                            system.debug(Roaster.redwing__Status__c);
                            ContactIds.add(Roaster.redwing__User__r.ContactId);
                            ContactIdWithRoaster.put(Roaster.redwing__User__r.ContactId,Roaster);
                        }
                    }
                }
                if(ContactIds.size()>0){
                    AcademyCertificationList =[SELECT Id,Certification_Student__c,Certification_Program__r.Name,Earned_Date__c,Certification_Student__r.Contact__c , Expiration_Date__c, Status__c FROM Academy_Certification__c WHERE Certification_Student__r.Contact__c IN: ContactIds];                                       
                    List<Academy_Certification__c> TempAcademy_Certification = new List<Academy_Certification__c>();
                    for(Academy_Certification__c Academy_Certification: AcademyCertificationList){
                        if(ContactIdWithListOfAcademy_CertificationMap.containsKey(Academy_Certification.Certification_Student__r.Contact__c)){
                            TempAcademy_Certification = new List<Academy_Certification__c>();
                            TempAcademy_Certification = ContactIdWithListOfAcademy_CertificationMap.get(Academy_Certification.Certification_Student__r.Contact__c);
                            TempAcademy_Certification.add(Academy_Certification);
                            ContactIdWithListOfAcademy_CertificationMap.put(Academy_Certification.Certification_Student__r.Contact__c,TempAcademy_Certification);
                        }
                        else{
                            TempAcademy_Certification = new List<Academy_Certification__c>();
                            TempAcademy_Certification.add(Academy_Certification);
                            ContactIdWithListOfAcademy_CertificationMap.put(Academy_Certification.Certification_Student__r.Contact__c,TempAcademy_Certification);
                        }
                    }
                     response.ContactIdWithListOfAcademy_CertificationMap = New Map<String,List<Academy_Certification__c>>(ContactIdWithListOfAcademy_CertificationMap);
                }
                return response;
            }
        }
        Return NULL;
    }
    
    //Training Console
    @AuraEnabled
    public static Map<String,List<Playground__c>> getPlaygroundsListByUserIds(String UserIdsString){
        Map<String,List<Playground__c>> contactIdWithPlayground = new Map<String,List<Playground__c>>();
        List<Playground__c> Playgrounds = new List<Playground__c>([SELECT Id,Name, User__c, Status__c FROM Playground__c WHERE User__c IN: JSON_String_To_list_parse(UserIdsString)]);
        List<Playground__c> tempPlaygroundList = new List<Playground__c>();
        for(Playground__c playground : Playgrounds){
            tempPlaygroundList = new List<Playground__c>();
            if(contactIdWithPlayground.containsKey(playground.User__c)){
                tempPlaygroundList = contactIdWithPlayground.get(playground.User__c);
                tempPlaygroundList.add(playground);
                contactIdWithPlayground.put(playground.User__c,tempPlaygroundList);
            }
            else{
                tempPlaygroundList.add(playground);
                contactIdWithPlayground.put(playground.User__c,tempPlaygroundList);
            }
        }
        if(contactIdWithPlayground.size()>0){
            RETURN contactIdWithPlayground;
        }
        RETURN NULL;
    }
    
    public static List<String> JSON_String_To_list_parse(String json) {
		return (List<String>) System.JSON.deserialize(json, List<String>.class);
	}
    
    Public Class NewResponse{
        @AuraEnabled public List<Academy_Certification_Program__c> AcademyCertificationPrograms;
        @AuraEnabled Public list<redwing__ILT_Class__c> ILTClasses;
        @AuraEnabled Public Map<String,List<Academy_Certification__c>> ContactIdWithListOfAcademy_CertificationMap;
    }
    
    public class responseWrap{
        @AuraEnabled public String ILTEventId;
        @AuraEnabled public String ILTEventName;
        @AuraEnabled public String ILTEventLearningId;
        @AuraEnabled public String ILTEventLearningName;
        @AuraEnabled public String ILTEventClassId;
        @AuraEnabled public String ILTEventClassName;
        @AuraEnabled public String ILTEventClassLearningId;
        @AuraEnabled public String ILTEventClassLearningName;
        @AuraEnabled public List<CertificateUserDetails> CertificateUserDetailList;
    }
    
    public class CertificateUserDetails{
        @AuraEnabled public String UserId;
        @AuraEnabled public String UserName;
        @AuraEnabled public String ContactId;
        @AuraEnabled public List<Academy_Certification__c> Academy_Certifications;
    }
    
    public class responseResult{
        @AuraEnabled public List<Academy_Certification_Program__c> AcademyCertificationPrograms;
        @AuraEnabled public List<redwing__Prerequisite_Item__c> BadgesList;
        @AuraEnabled public List<responseWrap> response;
    }
    
    public class AchievementAssignmentWrap{
        @AuraEnabled public String UserId;
        @AuraEnabled public String UserName;
        @AuraEnabled public String PrerequisiteId;
        @AuraEnabled public String PrerequisiteName;
        @AuraEnabled public String PrerequisiteItemId;
        @AuraEnabled public String status;
    }
    
    public class PrerequisiteRequestResponse{
        @AuraEnabled public List<redwing__Prerequisite_Item__c> Prerequisite_Items;
        @AuraEnabled public List<AchievementAssignmentWrap> AchievementAssignmentList;
    }
    
}