objects/Academy_Certification__c.object
<CustomObject>
    <description>Academy Certification per student</description>
    <fields>
        <fullName>Certification_Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Certification Examination</label>
        <referenceTo>Academy_Certification_Examination__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certifications</relationshipLabel>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification</label>
    <nameField>
        <displayFormat>ACD-{000000}</displayFormat>
        <label>Academy Certification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Examination__c.object
<CustomObject>
    <description>Exams records applied to student in order to support achieved certifications</description>
    <fields>
        <fullName>Academy_Certification2__c</fullName>
        <label>Academy Certification</label>
        <referenceTo>Academy_Certification__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations (Academy Certification)</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Certification_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the certification program</description>
        <label>Certification Program</label>
        <referenceTo>Academy_Certification_Program__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certification_Student__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Certification Student</label>
        <referenceTo>Academy_Certification_Student__c</referenceTo>
        <relationshipLabel>Academy Certification Examinations</relationshipLabel>
        <relationshipName>Academy_Certification_Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date when exam was or will be applied.</description>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Examination Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Examination</label>
    <nameField>
        <displayFormat>ACE-{000000}</displayFormat>
        <label>Academy Certification Examination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certification Examinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Academy_Certification_Program__c.object
<CustomObject>
    <description>Copado Academy Certification Programs</description>
    <fields>
        <fullName>Copado_Version__c</fullName>
        <description>Current Copado version, to identify features covered on certification</description>
        <label>Copado Version</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Certification Program,  Default will be valid.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Academy Certification Program</label>
    <nameField>
        <label>Certification Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academy Certification Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Academy_Certification_Student__c.object
<CustomObject>
    <description>Certified Contacts with a link to Certification Programs</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Academy_Certifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Student Id to identify student from external platforms</description>
        <externalId>true</externalId>
        <label>Student Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Academy Certification Student</label>
    <nameField>
        <displayFormat>ACS-{000000}</displayFormat>
        <label>Academy Certification</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academy Certifications Student</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestAcademyCertificationPDFMailer.cls
/**
 * Created by dineshdk on 19/08/2018.
 */
@isTest
public with sharing class TestAcademyCertificationPDFMailer {
    @isTest
    private static void TestAcademyCertificationPDFMailer() {

        testHttpCalloutMock requestCreateUser = new testHttpCalloutMock(200, 'Complete', '<?xml version="1.0" encoding="ISO-8859-1"?><SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:WSUser.CreateUserResponse xmlns:ns1="urn:WSService"><return xsi:type="xsd:int">115</return></ns1:WSUser.CreateUserResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>');
        testHttpCalloutMock requestIP = new testHttpCalloutMock(200, 'Complete', '192.168.0.0');
        Map<String, HttpCalloutMock> calloutMap = new Map<String, HttpCalloutMock>();
        calloutMap.put('https://academy.copa.do/main/webservices/soap.php', requestCreateUser);
        calloutMap.put('https://academy.copa.do/main/webservices/testip.php', requestIP);
        HttpCalloutMock multiCalloutMock = new MultiRequestMock(calloutMap);

        Contact con = new Contact(firstname = 'Dineshkumar', lastname = 'rajamani', email = 'din2262@gmail.com');
        insert con;
        Academy_Certification_Student__c acs = new Academy_Certification_Student__c(Student_Id__c = '2312', Contact__c = con.Id);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, multiCalloutMock);
        insert acs;
        Test.stopTest();
        Academy_Certification_Program__c acp = new Academy_Certification_Program__c(Name = 'Release Manager', Copado_Version__c = 'v1.1', Status__c = 'Valid');
        insert acp;
        List<Academy_Certification__c> listAcademy_certifications = new List<Academy_Certification__c>();
        Academy_Certification__c ac = new Academy_Certification__c(Certification_Program__c = acp.Id, Certification_Student__c = acs.Id, Status__c = 'Valid');
        listAcademy_certifications.add(ac);
        insert listAcademy_certifications;
        Academy_Certification_Examination__c ace = new Academy_Certification_Examination__c(Date__c = datetime.newInstance(2018, 9, 15, 12, 30, 0), Certification_Student__c = acs.Id, Certification_Program__c = acp.Id, Status__c = 'Approved', Academy_Certification2__c = listAcademy_certifications[0].Id);
        insert ace;

        listAcademy_certifications[0].Certification_Examination__c = ace.Id;
        update listAcademy_certifications;
        User thisUser = [SELECT Id FROM USER WHERE Id = :UserInfo.getUserId()];
        EmailTemplate validEmailTemplate = new EmailTemplate();
        System.runAs(thisUser) {
            validEmailTemplate.isActive = true;
            validEmailTemplate.Name = 'Copado certificate Email Content';
            validEmailTemplate.DeveloperName = 'Copado_certificate_Email_Content';
            validEmailTemplate.TemplateType = 'text';
            validEmailTemplate.FolderId = UserInfo.getUserId();

            insert validEmailTemplate;
        }

        Academy_Certification_Program__c academy_certification_program = [SELECT Id,Name FROM Academy_Certification_Program__c WHERE Id=:acp.Id ];
        EmailTemplate emailTemplate = [SELECT Id, DeveloperName FROM EmailTemplate WHERE Id = :validEmailTemplate.Id];
        System.assertEquals('Release Manager',academy_certification_program.name);
        System.assertEquals('Copado_certificate_Email_Content',emailTemplate.DeveloperName);
        System.debug('listAcademy_certifications...' + listAcademy_certifications);
        Map<Id, Academy_Certification__c> academy_certificationMap = new Map<Id, Academy_Certification__c>(listAcademy_certifications);
        AcademyCertificationPDFMailer.sendEmailMethood(new List<Id>(academy_certificationMap.keySet()));

    }
}