objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Batch_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Covering_Period_From__c</fullName>
        <inlineHelpText>This is the start date for the period that this batch payment covers.</inlineHelpText>
        <label>Covering Period From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Covering_Period_To__c</fullName>
        <inlineHelpText>This is the covering period to which invoices will be included.</inlineHelpText>
        <label>Covering Period To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Payment</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Batch Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JBCXM__CTA__c.object
<CustomObject>
    <fields>
        <fullName>JBCXM__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call To Actions</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Call To Action</label>
    <nameField>
        <label>Call To Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call To Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payable_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payable Invoices</relationshipLabel>
        <relationshipName>Payable_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The batch payment where this invoice was paid.</inlineHelpText>
        <label>Batch Payment</label>
        <referenceTo>Batch_Payment__c</referenceTo>
        <relationshipLabel>Payable Invoices</relationshipLabel>
        <relationshipName>Payable_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Due_Date__c</fullName>
        <label>Invoice Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The customer to which this invoice relates</inlineHelpText>
        <label>Related Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payable Invoices (Related Customer)</relationshipLabel>
        <relationshipName>Payable_Invoices_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Payment</fullName>
                    <default>true</default>
                    <label>Pending Payment</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payable Invoice</label>
    <nameField>
        <label>Payable Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payable Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PaymentManagerController.cls
public with sharing class PaymentManagerController {
	/*
	When contracts are created they are registered in Salesforce.
	We need to;
		- record what our debt to Salesforce is for outstanding contracts
		- easily calculate this month's payments to Salesforce
		- easily associate invoices received via email to contracts within 
	We need to controle
	*/
	public Batch_Payment__c batchPayment {get;set;}
	public List<Payable_Invoice__c> invoices {get;set;}
	public AsyncApexJob apexJob {get;set;}
	public boolean isProcessing {get;set;}
	public String apexJobId {get;set;}
	public boolean hasBatchPaymentId {get;set;}
	public String bpid{get;set;}

	public PaymentManagerController() {
		isProcessing = false;
		batchPayment = new Batch_Payment__c();
		bpid = ApexPages.currentPage().getParameters().get('bpid');
		hasBatchPaymentId = !String.isBlank(bpid);
		if(hasBatchPaymentId){
			try{
				batchPayment = [select Id, Name, Amount__c, Status__c, Payment_Date__c, Covering_Period_From__c, Covering_Period_To__c from Batch_Payment__c
			where Id=:bpid limit 1];
			}
			catch(Exception e){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ''+e.getMessage()));
			}
		}
	}
	public void getInvoices(){
		if(batchPayment.Covering_Period_From__c==null || batchPayment.Covering_Period_To__c==null){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You must select a "from" and "to" date range.'));
			return;
		}
		List<Payable_Invoice__c> tmp = [select Id, Name, Invoice_Amount__c, Status__c, Invoice_Date__c, Invoice_Due_Date__c, Related_Customer__r.Name, Batch_Payment__c from Payable_Invoice__c where Invoice_Due_Date__c >=:batchPayment.Covering_Period_From__c and Invoice_Due_Date__c <=:batchPayment.Covering_Period_To__c and Status__c='Pending Payment' and Account__r.Name='salesforce.com EMEA Limited' limit 3];
		if(tmp.size()==0){
			isProcessing = false;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There are no invoices in that date range.'));
			return;
		}
		//When the dates are selected we create a batch process to add the invoices to a job.
		AddInvoicesToPaymentBatch addInvoiceBatch = new AddInvoicesToPaymentBatch(batchPayment.Covering_Period_From__c, batchPayment.Covering_Period_To__c);
		ID batchprocessid = Database.executeBatch(addInvoiceBatch);
		AsyncApexJob aaj = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors FROM AsyncApexJob WHERE ID =:batchprocessid ];
        isProcessing = true;
        apexJobId = batchprocessid;
		invoices = new List<Payable_Invoice__c>();
	}
	public void markAsPaid(){
		
	}
}