objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreements</relationshipLabel>
        <relationshipName>Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agreement_Name__c</fullName>
        <label>Agreement Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copado_Signer__c</fullName>
        <defaultValue>&quot;0050N000007Zqd9&quot;</defaultValue>
        <label>Copado Signer</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0050N000007Zqd9</fullName>
                    <default>true</default>
                    <label>Walker Mitchell</label>
                </value>
                <value>
                    <fullName>0050N000007Zmh2</fullName>
                    <label>Ted Elliott</label>
                </value>
                <value>
                    <fullName>Greg Higgins</fullName>
                </value>
                <value>
                    <fullName>Arwa Kaddoura</fullName>
                    <isActive>false</isActive>
                    <label>Arwa Kaddoura</label>
                </value>
                <value>
                    <fullName>0050N00000813By</fullName>
                    <isActive>false</isActive>
                    <label>Simon Bishop</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Agreement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/contentDocumentLinkHandlerTest.cls
//Created by Englhard Consulting August 19th, 2019
@isTest
public class contentDocumentLinkHandlerTest {

    static testMethod void validateContentDocumentLinkHandler(){
        
        Account a = new Account();
        a.Name = 'Test';
        
        Insert a;
        
        Schema.DescribeFieldResult fieldResult = Agreement__c.Copado_Signer__c.getDescribe();
        LIST<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        Agreement__c c = new Agreement__c();
        
        c.Agreement_Name__c = 'Test';
        c.Account__c = a.Id;
        c.Copado_Signer__c = ple[0].value;
        
        insert c;
        
        ContentVersion file = new ContentVersion();
        file.VersionData = blob.valueOf('my attachment text');
        file.PathOnClient = 'textfile.txt';
        file.Title = 'textfile';
        file.IsMajorVersion = True;
        file.FirstPublishLocationId = c.Id;
        insert file;
        
    }
}