objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proforma Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PO_number__c</fullName>
        <label>PO number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/JBCXM__CTA__c.object
<CustomObject>
    <fields>
        <fullName>JBCXM__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call To Actions</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Call To Action</label>
    <nameField>
        <label>Call To Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call To Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SendInvoice.cls
public with sharing class SendInvoice {

    //public ApexPages.StandardController controller {get;set;}
    public Invoice__c inv{get;set;}
    public Contact con{get;set;}
    public String emailSubject {get;set;}

    public SendInvoice(ApexPages.StandardController stdController) {
        //controller = stdController;
        inv = [select id, name, account__r.billing_contact__c, account__r.Invoice_Email_Subject__c, Status__c, PO_number__c from Invoice__c where id=:stdController.getId()];
        List<Contact> t = [select id,name, email from contact where id = :inv.account__r.billing_contact__c];
        if(t.size()==1)con = t.get(0);
        emailSubject = getEmailSubject(inv.account__r.Invoice_Email_Subject__c, inv.PO_number__c);
    }

    public PageReference send(){
        if(inv.Status__c=='Draft' || inv.Status__c==''){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Invoices cannot be sent as draft.'));
            return null;
        }
        
        // Reference the attachment page, pass in the account ID
        PageReference pdf = Page.invoicePDF;
        pdf.getParameters().put('id',(String)inv.id);
        pdf.setRedirect(true);

        // Take the PDF content
        Blob b = (Test.IsRunningTest())? Blob.valueOf('UNIT.TEST') : pdf.getContent();

		Attachment a = new Attachment(parentId = inv.id,body = b, name = inv.name+'.pdf');
        insert a;
        
        if(this.con !=null){
         	// Create the email attachment
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.setFileName(inv.name+'.pdf');
            efa.setBody(b);
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
            
            
    
            // Sets the paramaters of the email
            email.setTemplateId([select Id,Name, Body from EmailTemplate where Name='Invoice Email' limit 1].Id);
            String[] emailAddresses = new String[]{con.email};
            email.setToAddresses( emailAddresses );
            system.debug('#### EMAILS: ' + emailAddresses.size());
            email.setWhatId(inv.Id);
            email.setTargetObjectId(con.id);
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});   
            if(r[0].isSuccess()){
                return new PageReference('/'+this.inv.id);   
            }
            else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,r[0].geterrors()[0].getMessage()));
                return null;
            }   
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.confirm,'Invoice only Attached to the record. No email sent, no billing contact defined'));
            return new PageReference('/'+this.inv.id);
        }
    }
    public String getEmailSubject(String ems, String POnumber){
        if(POnumber==null)return ems;		
        return ems.replaceAll('(?i)__po_number__', POnumber);
    }
}