objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proforma Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proforma Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_number__c</fullName>
        <label>PO number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_VAT_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This checkbox must be ticked for VAT line items.</inlineHelpText>
        <label>Is VAT Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateInvoiceFromOpportunityExtension.cls
public class CreateInvoiceFromOpportunityExtension {
    public Opportunity opportunity{get;set;}
    public Invoice__c invoice {get;set;}
    public Invoice__c dummyInvoice {get;set;}
    public Account account {get;set;}
    public Contact accsPayableContact {get;set;}
    public boolean createVATitem {get;set;}
    public ApexPages.StandardController controller{get;set;}
    public List<Invoice_Line_Item__c> ilis {get;set;}
    
    public double invSubTotal{get;set;}
    public double invVatTotal{get;set;}
    public double invTotal{get;set;}
    
    public boolean showAccountsPayableFields {get;set;}
    
    public static final String[] FIELDS = new String[] {'Id','Name','AccountId','PO_Number__c', 'CurrencyIsoCode'};
    
    public CreateInvoiceFromOpportunityExtension(ApexPages.StandardController stdController){
        invoice = new Invoice__c();
        dummyInvoice = new Invoice__c();
        controller = stdController;
        createVATitem = false;
        showAccountsPayableFields = false;
        if(!Test.isRunningTest())stdController.addFields(FIELDS);
        this.opportunity = (Opportunity)stdController.getRecord();
        createPreviewData();
    }
    
    public static Account getAccount(Id accountId){
        return [SELECT Id, Name, Type, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, VAT_Number__c, Billing_Name__c, Billing_Contact__c FROM Account where Id=:accountId limit 1];
    }
    public PageReference refresh(){
        createPreviewData();
        return null;
    }
    public void createPreviewData(){
        if(dummyInvoice.Account__c!=null){
            account = getAccount(dummyInvoice.Account__c);
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.INFO, 'Using Invoice Account (not Opportunity Account)'));
        }
        else{
            account = getAccount(opportunity.AccountId);
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.INFO, 'Using Opportunity Account for invoicing'));
        }
    	
        if(account.Billing_Contact__c==null){
            showAccountsPayableFields = true;
            AccsPayableContact = new Contact(FirstName='Accounts', LastName='Payable', AccountId=account.Id);
        }
        
        invoice.Opportunity__c = opportunity.Id;
        invoice.Account__c = account.Id;
        invoice.Invoice_Date__c = system.today();
        invoice.Due_Date__c = system.today().addDays(30);
        invoice.PO_number__c = opportunity.PO_Number__c;
        invoice.CurrencyIsoCode = opportunity.CurrencyIsoCode;
        
        //Create invoice LineItems
        ilis = new List<Invoice_Line_Item__c>();
        List<OpportunityLineItem> olis = [SELECT Id, Product2.Name, CurrencyIsoCode, Name, Quantity, TotalPrice, UnitPrice, OpportunityId, ListPrice FROM OpportunityLineItem where OpportunityId=:opportunity.Id];
        List<SBQQ__Quote__c> cpquotes = [SELECT SBQQ__StartDate__c, SBQQ__EndDate__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c = :opportunity.Id];
        
		invSubTotal = 0;
        invTotal = 0;
        invVatTotal = 0;
        for(OpportunityLineItem oli : olis){
            Invoice_Line_Item__c ili = new Invoice_Line_Item__c();
            ili.Invoice__c = invoice.Id;
            ili.Name = oli.Product2.Name;
            ili.CurrencyIsoCode = invoice.CurrencyIsoCode;
            ili.Quantity__c = oli.Quantity;
            ili.Unit_Price__c = oli.UnitPrice;
            invSubTotal = invSubTotal + oli.TotalPrice;

            if (!cpquotes.isEmpty()) {
                ili.Start_Date__c = cpquotes[0].SBQQ__StartDate__c;
                ili.End_Date__c = cpquotes[0].SBQQ__EndDate__c;
            }

            ilis.add(ili);
        }
        if(createVATitem){
            Invoice_Line_Item__c ivat = new Invoice_Line_Item__c();
            ivat.Name = 'VAT - 21%';
            ivat.Is_VAT_Item__c = true;
            ivat.CurrencyIsoCode = invoice.CurrencyIsoCode;
            ivat.Quantity__c = 1;
            invVatTotal = invSubTotal / 100 * 21;
            ivat.Unit_Price__c = invVatTotal;
            ilis.add(ivat);
        }
        invTotal = invSubTotal + invVatTotal;
    }
    
    public void updateAccount(){
        update account;
    }
    public void showCreateAcountsPayableContact(){
        if(account.Billing_Contact__c!=null){
            accsPayableContact = [select Id, FirstName, LastName, Email, Title, AccountId from Contact where Id=:account.Billing_Contact__c];
        }
        showAccountsPayableFields = true;
    }
    public void saveAccsPayableContact(){
        try{
            upsert accsPayableContact;
            account.Billing_Contact__c = accsPayableContact.Id;
            update account;
        	ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, 'Billing Contact Saved.'));
            showAccountsPayableFields = false;
        }
        catch(Exception e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, ''+e.getMessage()));
        }
    }
    public PageReference createInvoice(){
        PageReference pageRef = new PageReference('/');
        try{
            insert invoice;
            for(Invoice_Line_Item__c i : ilis){
                i.Invoice__c = invoice.Id;
            }
            insert ilis;
            return new PageReference('/'+invoice.Id);
        }
        catch(Exception e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, ''+e.getMessage()));
        	return null;
        }
    }
}