objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proforma Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_method__c</fullName>
        <label>Payment method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit card</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestSendInvoice.cls
@isTest
public class TestSendInvoice {
    static testMethod void fulltest(){
        Account purchaser = new Account(Name='Company Purchaser', CurrencyIsoCode='EUR', Billing_Name__c='Purchasing SL', VAT_Number__c='');
        purchaser.BillingStreet = 'My Street';
        purchaser.BillingCity = 'My City';
        purchaser.BillingState = 'My State';
        purchaser.BillingPostalCode = 'My zip code';
        purchaser.BillingCountry = 'My country';
        purchaser.Billing_Contact__c = null;
        purchaser.Invoice_Email_Subject__c = 'PO Number: __PO_Number__';
        insert purchaser;
        
        Contact testContact = new Contact(FirstName='Phil', LastName='Rackwitz', Email='pr@copado.test', AccountId=purchaser.Id);
        insert testContact;
        
        Invoice__c invoice = new Invoice__c(CurrencyIsoCode='EUR', Account__c=purchaser.Id, Status__c='Draft', Payment_method__c='Transfer');
        insert invoice;
        
        Test.setCurrentPageReference(new PageReference('/apex/SendInvoice?id='+invoice.Id));
		Test.startTest();
        
        SendInvoice ext = new SendInvoice(new Apexpages.StandardController(invoice));
        String result = ext.getEmailSubject('PONumber/Invoice', null);
        
        ext.send();
        testMethodUtilities.hasMessage('Invoices cannot be sent as draft.');
        
        invoice.Status__c = 'Pending Payment';
        update invoice;
        
		PageReference pageRef = ext.send();
        System.assertEquals(null, pageRef);
        testMethodUtilities.hasMessage('Invoice only Attached to the record. No email sent, no billing contact defined');
        
        purchaser.Billing_Contact__c = testContact.Id;
        update purchaser;
        
        ext = new SendInvoice(new Apexpages.StandardController(invoice));
        pageRef = ext.send();
        Test.stopTest();
        System.assertEquals('/'+invoice.Id, pageRef.getUrl());
    }
    static testMethod void testReplacePONumber(){
        Account a = new Account(Name='Company Purchaser',VAT_Number__c = '123445');
        insert a;
        
        Invoice__c invoice = new Invoice__c(CurrencyIsoCode='EUR', Account__c=a.Id, Status__c='Draft', Payment_method__c='Transfer');
        insert invoice;
        
        Test.setCurrentPageReference(new PageReference('/apex/SendInvoice?id='+invoice.Id));
		Test.startTest();
        
        SendInvoice ext = new SendInvoice(new Apexpages.StandardController(invoice));
        String result = ext.getEmailSubject('PONumber/Invoice', null);
        System.assertEquals('PONumber/Invoice', result);
        
        result = ext.getEmailSubject('My PO Number: __PO_NUMBER__', 'upperCase');
        System.assertEquals('My PO Number: upperCase', result);
        
        result = ext.getEmailSubject('My PO Number: __PO_Number__', 'mixedCase');
        System.assertEquals('My PO Number: mixedCase', result);
        
        result = ext.getEmailSubject('My PO Number: __po_number__', 'lowerCase');
        System.assertEquals('My PO Number: lowerCase', result);
        Test.stopTest();
    }
}