objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                </value>
                <value>
                    <fullName>CreateCoeCredential</fullName>
                </value>
                <value>
                    <fullName>CoE_Authorization</fullName>
                </value>
                <value>
                    <fullName>GitSetup</fullName>
                </value>
                <value>
                    <fullName>ProvisionLicenses</fullName>
                </value>
                <value>
                    <fullName>CreateEnvironment</fullName>
                </value>
                <value>
                    <fullName>CreateOrgCredentials</fullName>
                </value>
                <value>
                    <fullName>AuthorizeSandbox</fullName>
                </value>
                <value>
                    <fullName>AssignPermissionSet</fullName>
                </value>
                <value>
                    <fullName>ExecutePostInstallScript</fullName>
                </value>
                <value>
                    <fullName>CreateScratchOrgEnvironment</fullName>
                </value>
                <value>
                    <fullName>EnableUser</fullName>
                </value>
                <value>
                    <fullName>GitSetupFinish</fullName>
                </value>
                <value>
                    <fullName>CreateGitSnapshot</fullName>
                </value>
                <value>
                    <fullName>CreateBranches</fullName>
                </value>
                <value>
                    <fullName>CreateBoilerplate</fullName>
                </value>
                <value>
                    <fullName>AddingFinishingTouches</fullName>
                    <label>Adding Finishing Touches</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Signup_Request__c.object
<CustomObject>
    <description>This object captures the Signup Requests generated from the community and creates Trialforce orgs</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the community contact record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The default value is the country of the requesting org. The language of the trial organization is auto-determined based on the value of this field.</description>
        <inlineHelpText>Default value is the country of the requesting org. ISO-3166 country code (Alpha-2 code).  Full list of these codes at: https://www.iso.org/obp/ui/#search. The language of the trial organization is auto-determined based on this value.</inlineHelpText>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                    <default>true</default>
                    <label>US</label>
                </value>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Created_Org_Id__c</fullName>
        <inlineHelpText>The 15–character organization ID of the trial organization created. The system provides this read-only field once the sign-up request has been processed.</inlineHelpText>
        <label>Created Org Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is populated by the Playground Wizard so that ProcessBuilder can update the job and UI changes can be triggered via Playground Job Events.</inlineHelpText>
        <label>Playground Job</label>
        <referenceTo>Playground_Job__c</referenceTo>
        <relationshipLabel>Signup Request</relationshipLabel>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <inlineHelpText>The 15–character ID of the Trialforce template that is the basis for the trial sign-up. Salesforce must approve the template. If you don’t specify an edition, a template ID is required.</inlineHelpText>
        <label>Template</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <inlineHelpText>The username of the admin user for the trial sign-up. It must follow the address convention specified in RFC822: www.w3.org/Protocols/rfc822/#z10</inlineHelpText>
        <label>Username</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Custom Signup Request</label>
    <nameField>
        <displayFormat>SR{0000000000}</displayFormat>
        <label>Signup Request Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signup Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cps_PlaygroundWizardConnectTest.cls
@isTest
private class cps_PlaygroundWizardConnectTest {
    
    @testSetup static void setup(){
        Id communityProfileId = [SELECT Id FROM Profile WHERE Name = 'CUSTOM Customer Community Login User'].Id;
        Id permissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Community_Playground_User'].Id;

        Account account = new Account(Name='Copado, Inc.') ;
        insert account; 
       
        Contact contact = new Contact(AccountId=account.Id, FirstName='John', LastName='Doe', Email='testemail@emailtest.com');
        insert contact;
                  
        User user = new User(FirstName=contact.FirstName, LastName=contact.LastName, Email=contact.Email, ContactId=contact.Id,
                                Alias='myalias', EmailEncodingKey = 'UTF-8',
                                LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US',
                                ProfileId=communityProfileId, Country='United States', IsActive=true,
                                TimezoneSidKey='America/Los_Angeles', Username='demo1734@handomdemodomainz.djw.cmq');
       
        insert user;
        User currentUser = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
        System.runAs(currentUser){
            PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = user.Id, PermissionSetId = permissionSetId);
            insert psa;
        }
    }

    @isTest static void getPlaygroundJobs() {
        User portalUser = [SELECT Id FROM User WHERE Email='testemail@emailtest.com'];
        System.runAs(portalUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
            Test.startTest();
            List<Playground_Job__c> jobs = cps_PlaygroundWizardConnectController.getPlaygroundJobs(playground.Id);
            System.assertEquals(!jobs.isEmpty(), true);
            Test.stopTest();
        }
    }

    @isTest static void updateJobStatus() {
        User portalUser = [SELECT Id FROM User WHERE Email='testemail@emailtest.com'];
        System.runAs(portalUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
            List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
            Playground_Job__c job;
            Test.startTest();
            if(!jobs.isEmpty()){
                job = jobs.get(0);
            }
            Playground_Job__c updatedJob = cps_PlaygroundWizardConnectController.updateJobStatus(playground.Id, job.Id, 'In Progress');
            System.assertEquals(updatedJob.Status__c, 'In Progress');
            Test.stopTest();
        }
    }

    @isTest static void getAuthLink() {
        User communityUser = [SELECT Id FROM User WHERE Username = 'demo1734@handomdemodomainz.djw.cmq'];
        Test.startTest();
        System.runAs(communityUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
        }
        Playground__c playground = [SELECT Org_Credential__c FROM Playground__c WHERE Name = 'Test Playground'];
        copado__Org__c orgCredential = new copado__Org__c(Name = 'CoE', copado__Validated_Date__c = System.today(), copado__SFDC_Org_ID__c = playground.Id);
        insert orgCredential;
        playground.Org_Credential__c = orgCredential.Id;
        update playground;
        Test.stopTest();
        /*
        System.runAs(communityUser){
            Map<String, Object> authLinkMap = cps_PlaygroundWizardConnectController.GetAuthLink(playground.Id, 'https://login.salesforce.com');
            Playground_Job__c queriedPlaygroundJob = [SELECT Status__c
                                                        FROM Playground_Job__c 
                                                        WHERE Playground__c =: playground.Id 
                                                        AND Action__c = 'CoE_Authorization'];
            Playground_Job__c plagroundJob = (Playground_Job__c) authlinkMap.get('job');

            System.assertEquals(plagroundJob.Status__c, queriedPlaygroundJob.Status__c);
        }
        */
    }
 
    @isTest static void getAuthLink_badOrg() {
        User communityUser = [select Id, ContactId, Email from User where Username='demo1734@handomdemodomainz.djw.cmq'];
        
        Signup_Request__c sr = new Signup_Request__c();
		sr.First_Name__c = 'John';
		sr.Last_Name__c = 'Doe';
        sr.Company__c = 'Copado, Inc.';
        sr.Email__c = communityUser.Email;
        sr.Contact__c = communityUser.contactId;
		sr.Username__c = 'expected@username.copado.com';
		sr.Country__c = 'US';
        sr.Created_Org_Id__c = '00D00000d3d3D12';
        sr.Template__c = '0TT1i00000269iK';
		insert sr;
        
        System.runAs(communityUser){
            system.debug('Creating Playground');
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
        }
        system.debug('Creating Org Credential');
        copado__Org__c orgCredential = new copado__Org__c(Name='CoE', copado__Validated_Date__c=null, copado__Org_Type__c='Production/Developer');
        orgCredential.copado__Validated_Date__c=System.today();
        orgCredential.copado__Username__c = 'actual@username.copado.com';
        orgCredential.copado__SFDC_Org_ID__c = '00Dxxxxxxxxxxxxxxx';
        
        copado__Environment__c env = new copado__Environment__c(Name=orgCredential.Name, copado__Org_ID__c=orgCredential.copado__SFDC_Org_ID__c);
        env.copado__Type__c = orgCredential.copado__Org_Type__c;
        insert env;
        
        orgCredential.copado__Environment__c = env.Id;
        insert orgCredential;
        
        Playground__c playground = [SELECT Id, Org_Credential__c, Using_Trial_Org__c FROM Playground__c WHERE Name='Test Playground'];
        playground.Org_Credential__c = orgCredential.Id;
        update playground;
        system.debug('@@@ Playground: '+playground);
        
        Test.startTest();
        cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', createSuccessResponseString(), new Map<String,String>());
        Test.setMock(HttpCalloutMock.class, mock);
        system.debug('Getting authorization link');
        cps_PlaygroundWizardConnectController.getAuthLink(playground.Id, 'https://www.copado.com/someReturnUrl');
        Test.stopTest();

        Playground_Job__c authorizationJob = [SELECT Id, Status__c, Payload__c, Output__c from Playground_Job__c where Playground__c=:playground.Id and Action__c='CoE_Authorization'];
        Map<String, Object> result = (Map<String, Object>)JSON.deserializeUntyped(authorizationJob.Payload__c);
        Map<String, Object> dataResult = (Map<String, Object>)result.get('data');
        system.assertEquals('WRONG_ORG_AUTHENTICATED', authorizationJob.Output__c);
        system.assertEquals('Failed', authorizationJob.Status__c); //process builder will set this to in progress though.
        system.assertEquals('CoE_Authorization', result.get('action'));
        system.assertEquals(true, result.get('hasError'));
        String errorMessage = 'The Org that was just authenticated did not match the Copado Trial Org for this Playground. You must authenticate the Copado Trial Org created in the previous step to proceed.';
        system.assertEquals(errorMessage, dataResult.get('message'));        
    }

    @isTest static void getAuthLinkWithoutDate() {
        User communityUser = [SELECT Id FROM User WHERE Username = 'demo1734@handomdemodomainz.djw.cmq'];
        System.runAs(communityUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
        }
        Playground__c playground = [SELECT Org_Credential__c FROM Playground__c WHERE Name = 'Test Playground'];
        copado__Org__c orgCredential = new copado__Org__c(Name = 'CoE', copado__SFDC_Org_ID__c = playground.Id);
        insert orgCredential;
        playground.Org_Credential__c = orgCredential.Id;
        update playground;

        System.runAs(communityUser){
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new cps_GetAuthLinkMock());
            Map<String, Object> authLinkMap = cps_PlaygroundWizardConnectController.GetAuthLink(playground.Id, 'https://login.salesforce.com');

            Playground_Job__c queriedPlaygroundJob = [select Status__c from Playground_Job__c where Playground__c =: playground.Id and Action__c = 'CoE_Authorization'];
            Playground_Job__c plagroundJob = (Playground_Job__c) authlinkMap.get('job');
            
            //System.assertEquals(plagroundJob.Status__c, queriedPlaygroundJob.Status__c);
            System.assertEquals(authlinkMap.get('authorization_url'), 'https://mockresponse.com/test');
            Test.stopTest();
        }
    }

    @isTest static void setupGitWithCode() {
        User communityUser = [SELECT Id FROM User WHERE Username = 'demo1734@handomdemodomainz.djw.cmq'];
        System.runAs(communityUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
        }
        Playground__c playground = [SELECT Org_Credential__c FROM Playground__c WHERE Name='Test Playground'];
        copado__Org__c orgCredential = new copado__Org__c(Name='CoE', copado__SFDC_Org_ID__c=playground.Id);
        insert orgCredential;
        playground.Org_Credential__c = orgCredential.Id;
        update playground;

        System.runAs(communityUser){
            Test.startTest();
            cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', createSuccessResponseString(), new Map<String,String>());
            Test.setMock(HttpCalloutMock.class, mock);
            Playground_Job__c playgroundJob = cps_PlaygroundWizardConnectController.GitSetup(playground.Id, 'somecode');
            Playground_Job__c queriedPlaygroundJob = [SELECT Id, Status__c FROM Playground_Job__c WHERE Action__c = 'GitSetup'];
            System.assertEquals(playgroundJob.Id, queriedPlaygroundJob.Id);
            System.assertEquals(playgroundJob.Status__c, queriedPlaygroundJob.Status__c);
            Test.stopTest();
        }
    }

    @isTest static void setupGitWithoutCode() {
        User communityUser = [SELECT Id FROM User WHERE Username = 'demo1734@handomdemodomainz.djw.cmq'];
        System.runAs(communityUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
        }
        Playground__c playground = [SELECT Org_Credential__c FROM Playground__c WHERE Name = 'Test Playground'];
        copado__Org__c orgCredential = new copado__Org__c(Name = 'CoE', copado__SFDC_Org_ID__c = playground.Id);
        insert orgCredential;
        playground.Org_Credential__c = orgCredential.Id;
        update playground;

        System.runAs(communityUser){
            Test.startTest();
            cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', createSuccessResponseString(), new Map<String,String>());
            Test.setMock(HttpCalloutMock.class, mock);
            Playground_Job__c playgroundJob = cps_PlaygroundWizardConnectController.GitSetup(playground.Id, '');
            Playground_Job__c queriedPlaygroundJob = [SELECT Id, Status__c FROM Playground_Job__c WHERE Action__c = 'GitSetup'];
            System.assertEquals(playgroundJob.Id, queriedPlaygroundJob.Id);
            System.assertEquals(playgroundJob.Status__c, queriedPlaygroundJob.Status__c);
            Test.stopTest();
        }
    }

    @isTest static void getGithubSettings() {
        Test.startTest();
        Map<String, String> result = cps_PlaygroundWizardConnectController.getGithubSettings();
        system.assert(containsValue(result.keySet(), 'gitAuthUrl'));
        system.assert(containsValue(result.keySet(), 'gitClientId'));
        Test.stopTest();
    }

    private static boolean containsValue(Set<String> x, String y) {
        if (x.contains(y)) return true;
        else return false;
    }
    private static String createSuccessResponseString() {
        String responseString = '{"isSuccess":"'+true+'", "copadoJobId":"430c0e95-4771-4c66-9b42-d1eb277186b5"}';        
        return responseString;
    }
}