objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameter__c.object
<CustomObject>
    <description>A custom object for storing feature parameters.  A new record is created of this object for every feature parameter that is ADDED as part of an uploaded package version. This record is automatically created upon the first package install of that package version.</description>
    <label>Feature Parameter</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Feature Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameterInteger__c.object
<CustomObject>
    <description>Custom object that is part of FMA for storing Feature Parameter Overrides for integers

A new record is created of this object for every feature parameter that is ADDED as part of a package install in an org. This record is automatically created upon every package install.

The Feature Parameter object serves as an index.</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Value will be set to 0 when expired</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <formula>sfFma__License__r.Salesforce_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__FeatureParameter__c</fullName>
        <description>The parent Feature Parameter object.</description>
        <label>Feature Parameter</label>
        <referenceTo>sfFma__FeatureParameter__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sfFma__Value__c</fullName>
        <label>Feature Parameter Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature Parameter Integer</label>
    <nameField>
        <displayFormat>FPI-{0000}</displayFormat>
        <label>Feature Parameter Integer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameter Integers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Expiration__c</fullName>
        <description>Expiration Date of the License, 1/1/1970 represents a perpetual license</description>
        <label>Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__Org_Type__c</fullName>
        <label>Org Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>sfLma__Package__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__Package__c.object
<CustomObject>
    <description>A Package Object represents information about the package as it is defined in the developer&apos;s Salesforce Organization. A record is created or updated each time a new version of the package is uploaded to AppExchange.</description>
    <fields>
        <fullName>sfLma__Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestScheduleEmailAlertForSalesforceOrg.cls
@isTest
public class TestScheduleEmailAlertForSalesforceOrg {
	@isTest
    public static void unitTest(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount('Fake needed acc', 'EUR');
        insert acc;
        
        Contact con = TestDataFactory.createContact(acc.id,'Fakecon');
        insert con;
        
        Salesforce_Org__c org = TestDataFactory.createSalesforceOrg('Test Method Org');
        org.OrgId__c = '00D1l0000000dkE';
        org.Org_Type__c ='Production';
        insert org;
        
        sfLma__License__c lic = TestDataFactory.createLicense(org.Id,5);
        lic.sfLma__Subscriber_Org_ID__c = '00D1l0000000dkE';
        lic.sfLma__Expiration__c = Date.today()+7;
        lic.sfLma__Org_Type__c = 'Developer Edition';
        insert lic;
        
        sfLma__Package__c pack = TestDataFactory.craetePackage('Copado Deployer');
        pack.sfLma__Developer_Name__c = 'Copado BasePackage';
        insert pack;
        
        sfFma__FeatureParameter__c fpCCM = TestDataFactory.createFeatureParameter('copado__CCM_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        insert fpCCM;
        
        
        sfFma__FeatureParameterInteger__c fpi = TestDataFactory.createFeatureParameterInteger('copado__CCM_Licenses_Enabled',lic.Id, fpCCM.Id);   
        fpi.External_Id__c = org.Id + '_' + 'copado__CCM_Licenses_Enabled';
        fpi.Expiration_Date__c = System.Today().AddDays(7);
        fpi.sfFma__Value__c = 0;
        insert fpi;
        List<String> ccTo = new List<String>();
        ccTo.add('rranjan@copado.com');
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.settoAddresses(ccTo);
        mail.setSubject('Test');
        mail.setPlainTextBody('Test');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
        
        // This test runs a scheduled job at 12 AM daily
        String CRON_EXP = '0 0 0 ? * * *';
        // Schedule the test job
        String jobId = System.schedule('TestScheduledCalculateCurrentARROnQuote', CRON_EXP, new ScheduleEmailAlertForSalesforceOrg());
        Test.stopTest();
    }
}