objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Demo__c.object
<CustomObject>
    <description>This object keeps all the information related to Demos.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Demos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Demo_outcome__c</fullName>
        <label>Meeting outcome</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PS_Consumed_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Professional Services Consumed Time</description>
        <inlineHelpText>Professional Services Consumed Time In Hours</inlineHelpText>
        <label>PS Consumed Time</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting response</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Re-scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Call</fullName>
                </value>
                <value>
                    <fullName>Technical Demo</fullName>
                </value>
                <value>
                    <fullName>Trial Meeting</fullName>
                </value>
                <value>
                    <fullName>InfoSec</fullName>
                </value>
                <value>
                    <fullName>Onboarding Call</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Check-in Call</fullName>
                </value>
                <value>
                    <fullName>Renewal Call</fullName>
                </value>
                <value>
                    <fullName>Business Review</fullName>
                </value>
                <value>
                    <fullName>Support Call</fullName>
                </value>
                <value>
                    <fullName>Partner Meeting</fullName>
                </value>
                <value>
                    <fullName>Time Logging</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>Essentials</fullName>
                </value>
                <value>
                    <fullName>PoC</fullName>
                    <isActive>false</isActive>
                    <label>PoC</label>
                </value>
                <value>
                    <fullName>Setup Call</fullName>
                    <isActive>false</isActive>
                    <label>Setup Call</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Professional_Services_Allowance__c.object
<CustomObject>
    <description>To keep a track on Professional Services hours purchased by a customer</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Professional Services Allowance</relationshipLabel>
        <relationshipName>Professional_Services_Allowance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours_purchased__c</fullName>
        <label>Hours purchased</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Professional Services Allowance</label>
    <nameField>
        <displayFormat>PSA-{00000}</displayFormat>
        <label>Professional Services Allowance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Services Allowance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestMeetingTrigger.cls
@isTest
private class TestMeetingTrigger {

private static Demo__c meeting = new Demo__c();
public static Account account = new Account();
private static Professional_Services_Allowance__c	psa = new Professional_Services_Allowance__c();

	
	static void prepareData() {
		account.Name = 'Account Name';
		insert account;
		System.debug('Account ID'+account.id);
		psa.Account__c = account.Id;
		psa.Hours_purchased__c = 69;
		insert psa;
	}
	
	@isTest static void testPSMeetingTrigger() {
		prepareData();
		meeting.Account__c = account.Id;
		System.debug('Meeting Account '+meeting.Account__c);
		meeting.Status__c ='Completed';
		meeting.Type__c = 'Professional Services';
		meeting.PS_Consumed_Time__c = 3;
		meeting.Date__c = Date.today();
		meeting.Demo_outcome__c ='';
		Demo__c m = meeting;
		System.debug(meeting);
		insert meeting;
		System.assertEquals([SELECT PS_Available_Hours__c FROM Account WHERE Id = :account.Id].PS_Available_Hours__c,66);
	}
	
}