objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/amc__Action__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to link an action to an account. this is required to ensure we can deduct assigned hours for clients.</description>
        <inlineHelpText>Field used to link an action to an account. this is required to ensure we can deduct assigned hours for clients.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MC Actions</relationshipLabel>
        <relationshipName>MC_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amc__Hours_Completed__c</fullName>
        <inlineHelpText>Roll up summary of the Hours Completed on Time Logs. Filtered to include Time Logs where Non Billable Tracker = FALSE AND Approval Status = Approved. (Previously Labelled Hours Completed)</inlineHelpText>
        <label>Hours Completed - Billable</label>
        <summarizedField>amc__Time_Log__c.amc__Hours_Completed__c</summarizedField>
        <summaryFilterItems>
            <field>amc__Time_Log__c.amc__Non_Billable_Tracker__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>amc__Time_Log__c.amc__Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved,</value>
        </summaryFilterItems>
        <summaryForeignKey>amc__Time_Log__c.amc__Action__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>amc__Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>amc__Milestone__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>amc__Non_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if this Action is Non Billable</inlineHelpText>
        <label>Non Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>amc__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populated automatically via trigger.</inlineHelpText>
        <label>Project</label>
        <referenceTo>amc__Project__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>PAN:{0000}</displayFormat>
        <label>Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/amc__Milestone__c.object
<CustomObject>
    <fields>
        <fullName>amc__Hours_Completed__c</fullName>
        <inlineHelpText>Identifies the number of billable hours completed for this Milestone. (Previously labelled Hours Completed)</inlineHelpText>
        <label>Hours Completed - Billable</label>
        <summarizedField>amc__Action__c.amc__Hours_Completed__c</summarizedField>
        <summaryForeignKey>amc__Action__c.amc__Milestone__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>amc__Non_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if this Milestone is Non Billable</inlineHelpText>
        <label>Non Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>amc__Project__c</fullName>
        <label>Project</label>
        <referenceTo>amc__Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/amc__Project__c.object
<CustomObject>
    <fields>
        <fullName>amc__Hours_Completed__c</fullName>
        <inlineHelpText>Identifies the number of billable hours completed for this Project. (Previously Labelled Hours Completed)</inlineHelpText>
        <label>Hours Completed - Billable</label>
        <summarizedField>amc__Milestone__c.amc__Hours_Completed__c</summarizedField>
        <summaryForeignKey>amc__Milestone__c.amc__Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>amc__Non_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if the entire Project is Non Billable</inlineHelpText>
        <label>Non Billable</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/amc__Role__c.object
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/amc__Time_Log__c.object
<CustomObject>
    <description>Enables project team members to log time against Actions</description>
    <fields>
        <fullName>ProfessionalServiceConsumption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to link the log to the consumption in order to enable updates. should be filled by a trigger.</description>
        <inlineHelpText>Field to link the log to the consumption in order to enable updates. should be filled by a trigger.</inlineHelpText>
        <label>Professional Service Consumption</label>
        <referenceTo>Professional_Service_Consumption__c</referenceTo>
        <relationshipLabel>Time Logs</relationshipLabel>
        <relationshipName>TimeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amc__Action__c</fullName>
        <inlineHelpText>Select the Action this Time Log relates to</inlineHelpText>
        <label>Action</label>
        <referenceTo>amc__Action__c</referenceTo>
        <relationshipLabel>Time Logs</relationshipLabel>
        <relationshipName>Time_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>amc__Billable_Hours_Completed__c</fullName>
        <formula>IF(!amc__Non_Billable_Indicator__c , amc__Hours_Completed__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billable Hours Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amc__Hours_Completed__c</fullName>
        <inlineHelpText>Shows the number of hours spent on the Action during this Time Log</inlineHelpText>
        <label>Hours Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amc__Non_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if this Time Log is Non Billable</inlineHelpText>
        <label>Non Billable</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TLN-{00000000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Professional_Service_Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Professional Service Consumption</relationshipLabel>
        <relationshipName>Professional_Service_Consumption</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours_consumed__c</fullName>
        <label>Hours consumed</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Id__c</fullName>
        <externalId>true</externalId>
        <label>Meeting Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Professional Service Consumption</label>
    <nameField>
        <displayFormat>PSC-{00000}</displayFormat>
        <label>Professional Service Consumption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Service Consumption</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MC_TimeLogTriggerTest.cls
/**
 * Created by kheidt on 2019-05-07.
 */

@IsTest
private class MC_TimeLogTriggerTest {

    static User adminUser;
    static User runningUser;
    static List<amc__Time_Log__c> timeLogs;
    static List<Professional_Service_Consumption__c> psConsumptions;
    static Account acct1;
    static Contact cnt;
    static Opportunity oppty1;
    static amc__Project__c mcProject;
    static amc__Role__c role;
    static amc__Milestone__c mcMilestone1;
    static amc__Milestone__c mcMilestone2;
    static amc__Action__c mcAction1;
    static amc__Action__c mcAction2;
    static amc__Time_Log__c timeLog1;
    static amc__Time_Log__c timeLog2;

    static void setup(){
        adminUser = TestDataFactory.setToAdmin(TestDataFactory.createUser());
        insert adminUser;

        System.runAs(adminUser) {
            runningUser = TestDataFactory.setToAdmin(TestDataFactory.createUser());
            runningUser.Alias = 'rrunni';
            runningUser.Username = 'running@user.copadotest';
            insert runningUser;
        }

        System.runAs(runningUser){
            acct1 = TestDataFactory.createAccount('TLTEST', 'EUR');
            insert acct1;

            cnt = TestDataFactory.createContact(acct1.Id, 'TLTest');
            insert cnt;

            oppty1 = TestDataFactory.createOpportunity(acct1, 'TLTST','New Customer');
            oppty1.Amount = 100;
            oppty1.Main_Problems__c = 'some';
            insert oppty1;

            role = TestDataFactory.createMCRole(runningUser);
            insert role;

            mcProject = TestDataFactory.createMCProject(acct1, oppty1, 'TL Test in Unit Test');
            insert mcProject;

            mcMilestone1 = TestDataFactory.createMCMilestone(mcProject,'1',role);
            insert mcMilestone1;

            mcAction1 = TestDataFactory.createMCAction(acct1, mcMilestone1, role,'1');
            insert mcAction1;

            mcMilestone2 = TestDataFactory.createMCMilestone(mcProject,'2',role);
            insert mcMilestone2;

            mcAction2 = TestDataFactory.createMCAction(acct1, mcMilestone2, role,'2');
            insert mcAction2;
        }
    }

    static testMethod void testSingleLog_NotBillable() {
        setup();

        Test.startTest();
        System.runAs(runningUser){
            timeLog1 = TestDataFactory.createMCTimeLog(mcAction1, true,role,2);
            insert timeLog1;
        }
        Test.stopTest();

        List<Professional_Service_Consumption__c> createdConsumptions = [SELECT ID FROM Professional_Service_Consumption__c];
        System.assertEquals(0, createdConsumptions.size());
    }

    static testMethod void testSingleLog_Billable() {
        setup();

        Test.startTest();
        System.runAs(runningUser){
            timeLog1 = TestDataFactory.createMCTimeLog(mcAction1, false, role, 2);
            insert timeLog1;
        }
        Test.stopTest();

        amc__Time_Log__c testLog = [SELECT Id, Name, ProfessionalServiceConsumption__c, amc__Billable_Hours_Completed__c FROM amc__Time_Log__c];
        Professional_Service_Consumption__c testConsumption = [SELECT Id, Meeting_Id__c, Hours_consumed__c FROM Professional_Service_Consumption__c];

        System.assertEquals(testLog.amc__Billable_Hours_Completed__c , testConsumption.Hours_consumed__c);
        System.assertEquals(testLog.Id, testConsumption.Meeting_Id__c);
        System.assertEquals(testConsumption.Id, testLog.ProfessionalServiceConsumption__c);
    }

    static testMethod void testMultipleLogs() {
        setup();

        timeLogs = new List<amc__Time_Log__c>();
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, true, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, false, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, true, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, false, role, i);
            timeLogs.add(log);
        }

        Test.startTest();
        System.runAs(runningUser){
            insert timeLogs;
        }
        Test.stopTest();

        Map<Id, amc__Time_Log__c> createdLogs = new Map<Id, amc__Time_Log__c>([
                SELECT Id, Name, ProfessionalServiceConsumption__c, amc__Billable_Hours_Completed__c
                FROM amc__Time_Log__c
                WHERE amc__Non_Billable__c = false
        ]);

        Map<Id,Professional_Service_Consumption__c> createdConsumptions = new Map<Id, Professional_Service_Consumption__c>([
                SELECT Id, Meeting_Id__c, Hours_consumed__c FROM Professional_Service_Consumption__c
        ]);

        System.assertEquals(40, createdConsumptions.size());

        System.assertEquals(createdLogs.values().size(),createdConsumptions.values().size());
        for(Professional_Service_Consumption__c psc : createdConsumptions.values()){
            System.assert(createdLogs.keySet().contains(psc.Meeting_Id__c));
        }

        for(amc__Time_Log__c tl : createdLogs.values()){
            System.assert(createdConsumptions.keySet().contains(tl.ProfessionalServiceConsumption__c));
            System.assertEquals(tl.amc__Billable_Hours_Completed__c, createdConsumptions.get(tl.ProfessionalServiceConsumption__c).Hours_consumed__c);
        }
    }

    static testMethod void testMultipleLogsNewAndUpdate() {
        setup();

        timeLogs = new List<amc__Time_Log__c>();
        List<amc__Time_Log__c> timeLogsToUpdate = new List<amc__Time_Log__c>();

        //create logs for insert
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, true, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, false, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, true, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, false, role, i);
            timeLogs.add(log);
        }

        //create logs for update
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, true, role, i);
            timeLogsToUpdate.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, false, role, i);
            timeLogsToUpdate.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, true, role, i);
            timeLogsToUpdate.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, false, role, i);
            timeLogsToUpdate.add(log);
        }

        insert timeLogsToUpdate;
        Integer listSize = timeLogsToUpdate.size();

        //update the value
        for(Integer i = 0; i< listSize; i++){
            timeLogsToUpdate[i].amc__Hours_Completed__c = i +10;
        }

        Test.startTest();
        System.runAs(runningUser){
            timeLogsToUpdate.addAll(timeLogs);
            upsert timeLogsToUpdate;

        }
        Test.stopTest();

        Map<Id, amc__Time_Log__c> createdLogs = new Map<Id, amc__Time_Log__c>([
                SELECT Id, Name, ProfessionalServiceConsumption__c, amc__Billable_Hours_Completed__c
                FROM amc__Time_Log__c
                WHERE amc__Non_Billable__c = false
        ]);

        Map<Id,Professional_Service_Consumption__c> createdConsumptions = new Map<Id, Professional_Service_Consumption__c>([
                SELECT Id, Meeting_Id__c, Hours_consumed__c FROM Professional_Service_Consumption__c
        ]);

        System.assertEquals(80, createdConsumptions.size());

        System.assertEquals(createdLogs.values().size(),createdConsumptions.values().size());
        for(Professional_Service_Consumption__c psc : createdConsumptions.values()){
            System.assert(createdLogs.keySet().contains(psc.Meeting_Id__c));
        }

        for(amc__Time_Log__c tl : createdLogs.values()){
            System.assert(createdConsumptions.keySet().contains(tl.ProfessionalServiceConsumption__c));
            System.assertEquals(tl.amc__Billable_Hours_Completed__c, createdConsumptions.get(tl.ProfessionalServiceConsumption__c).Hours_consumed__c);
        }
    }

    static testMethod void testMultipleLogs_SomeWithoutAccounts() {
        setup();
		Test.startTest();
        timeLogs = new List<amc__Time_Log__c>();
        List<amc__Time_Log__c> timeLogsToUpdate = new List<amc__Time_Log__c>();

        //remove account from action. if no account is specified, the logic should not consider it
        mcAction1.Account__c = null;
        update mcAction1;

        //create logs for insert
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, true, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, false, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, true, role, i);
            timeLogs.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, false, role, i);
            timeLogs.add(log);
        }

        //create logs for update
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, true, role, i);
            timeLogsToUpdate.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction1, false, role, i);
            timeLogsToUpdate.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, true, role, i);
            timeLogsToUpdate.add(log);
        }
        for(Integer i=0; i<20;i++ ){
            amc__Time_Log__c log = TestDataFactory.createMCTimeLog(mcAction2, false, role, i);
            timeLogsToUpdate.add(log);
        }

        insert timeLogsToUpdate;
        Integer listSize = timeLogsToUpdate.size();

        //update the value
        for(Integer i = 0; i< listSize; i++){
            timeLogsToUpdate[i].amc__Hours_Completed__c = i +10;
        }

        
        System.runAs(runningUser){
            timeLogsToUpdate.addAll(timeLogs);
            upsert timeLogsToUpdate;

        }
        

        Map<Id, amc__Time_Log__c> createdLogs = new Map<Id, amc__Time_Log__c>([
                SELECT Id, Name, ProfessionalServiceConsumption__c, amc__Billable_Hours_Completed__c
                FROM amc__Time_Log__c
                WHERE amc__Non_Billable__c = false
                AND amc__Action__r.Account__c != null
        ]);

        Map<Id,Professional_Service_Consumption__c> createdConsumptions = new Map<Id, Professional_Service_Consumption__c>([
                SELECT Id, Meeting_Id__c, Hours_consumed__c FROM Professional_Service_Consumption__c
        ]);
		Test.stopTest();
        System.assertEquals(40, createdConsumptions.size());

        for(Professional_Service_Consumption__c psc : createdConsumptions.values()){
            System.assert(createdLogs.keySet().contains(psc.Meeting_Id__c));
        }

        for(amc__Time_Log__c tl : createdLogs.values()){
            System.debug(LoggingLevel.INFO, 'key set: ' + createdConsumptions.keySet());
            System.debug(LoggingLevel.INFO, 'current Id: ' + tl.ProfessionalServiceConsumption__c);
            System.assert(createdConsumptions.keySet().contains(tl.ProfessionalServiceConsumption__c));
            System.assertEquals(tl.amc__Billable_Hours_Completed__c, createdConsumptions.get(tl.ProfessionalServiceConsumption__c).Hours_consumed__c);
        }
    }

    public static testmethod void testLogDeletion(){
        setup();
        Test.startTest();
        timeLog1 = TestDataFactory.createMCTimeLog(mcAction1, false, role,2);
        insert timeLog1;

        timeLog2 = TestDataFactory.createMCTimeLog(mcAction2, true, role, 3);
        insert timeLog2;

        List<Professional_Service_Consumption__c> createdConsumptions = [SELECT ID FROM Professional_Service_Consumption__c];
        System.assertEquals(1, createdConsumptions.size());

        
        System.runAs(runningUser){
            delete timeLog1;
            delete timeLog2;
        }
        
        createdConsumptions = [SELECT ID FROM Professional_Service_Consumption__c];
        Test.stopTest();
        System.assertEquals(0, createdConsumptions.size());

    }
}