objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Projects</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Email</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Project Team Members</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <label>Customer Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer Project Team Members</relationshipLabel>
        <relationshipName>Project_Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Only the Active Team Member will be able to access Project on Community.</inlineHelpText>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Super_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>A Super User by default will get all the other permissions.</inlineHelpText>
        <label>Is Super User</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{0000}</displayFormat>
        <label>Project Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomerProjectTriggerTest.cls
@IsTest
public class CustomerProjectTriggerTest {
	@IsTest
	public static void testUpdateProjectToActive() {
		Id communityProfileId = [SELECT Id FROM Profile WHERE Name = 'CUSTOM Customer Community Login User'].Id;
		Account account = new Account(Name='Test Project Trigger') ;
		insert account;

		Contact contact = new Contact(AccountId=account.Id, FirstName='Test Project Trigger', LastName='Contact', Email='testemailprojectconfiguration@emailtest.com');
		insert contact;

		User user = new User(FirstName=contact.FirstName, LastName=contact.LastName, Email=contact.Email, ContactId=contact.Id,
								Alias='myalias', EmailEncodingKey = 'UTF-8',
								LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US',
								ProfileId=communityProfileId, Country='United States', IsActive=true,
								TimezoneSidKey='America/Los_Angeles', Username='demo1734@handomdemodomainz.djw.cmq');
		insert user;

		// Create project and update it to active
		Test.startTest();

		Project__c project1 = new Project__c(Name='Test Project 1', Account__c=account.Id, IsActive__c=false);
		insert project1;

		Project_Team_Member__c ptmOfProject1 = new Project_Team_Member__c(Customer_Project__c=project1.Id, Contact__c=contact.Id, IsActive__c=true, Is_Super_User__c=true);
		insert ptmOfProject1;

		// Updating the project to active
		project1.IsActive__c = true;
		update project1;

		Test.stopTest();

		List<PermissionSetAssignment> psa = [SELECT Id From PermissionSetAssignment WHERE AssigneeId = : user.Id AND PermissionSet.Name = 'Customer_Project_Access_On_Community'];
		System.assertEquals(1, psa.size());
	}

	@IsTest
	public static void testUpdateProjectToInActive() {
		Id communityProfileId = [SELECT Id FROM Profile WHERE Name = 'CUSTOM Customer Community Login User'].Id;
		Account account = new Account(Name='Test Project Trigger') ;
		insert account;

		Contact contact = new Contact(AccountId=account.Id, FirstName='Test Project Trigger', LastName='Contact', Email='testemailprojectconfiguration@emailtest.com');
		insert contact;

		User user = new User(FirstName=contact.FirstName, LastName=contact.LastName, Email=contact.Email, ContactId=contact.Id,
								Alias='myalias', EmailEncodingKey = 'UTF-8',
								LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US',
								ProfileId=communityProfileId, Country='United States', IsActive=true,
								TimezoneSidKey='America/Los_Angeles', Username='demo1734@handomdemodomainz.djw.cmq');
		insert user;

		// Create project and update it to active
		Test.startTest();

		Project__c project1 = new Project__c(Name='Test Project 1', Account__c=account.Id, IsActive__c=true);
		insert project1;

		Project_Team_Member__c ptmOfProject1 = new Project_Team_Member__c(Customer_Project__c=project1.Id, Contact__c=contact.Id, IsActive__c=true, Is_Super_User__c=true);
		insert ptmOfProject1;

		// Updating the project to active
		project1.IsActive__c = false;
		update project1;

		Test.stopTest();

		List<PermissionSetAssignment> psa = [SELECT Id From PermissionSetAssignment WHERE AssigneeId = : user.Id AND PermissionSet.Name = 'Customer_Project_Access_On_Community'];
		System.assertEquals(0, psa.size());
	}
}