objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorization_URL__c</fullName>
        <label>Authorization URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InstanceUrl__c</fullName>
        <label>InstanceUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Sandbox Creation</fullName>
                </value>
                <value>
                    <fullName>Record Creation</fullName>
                </value>
                <value>
                    <fullName>Git</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/cps_PlaygroundWizardSetupTest.cls
@isTest
private class cps_PlaygroundWizardSetupTest {

  @testSetup static void setup(){
    Id communityProfileId = [SELECT Id FROM Profile WHERE Name = 'CUSTOM Customer Community Login User'].Id;
    Id permissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Community_Playground_User'].Id;

    Account account = new Account(Name ='Test Account 1') ;
    insert account;

    Contact contact = new Contact(LastName ='TestContact', AccountId = account.Id);
    insert contact;

    User user = new User(
      Alias = 'myalias', Email = 'testemail@emailtest.com',
      EmailEncodingKey = 'UTF-8', LastName = 'TestUser',
      LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US',
      ProfileId = communityProfileId, Country = 'United States',
      IsActive = true, ContactId = contact.Id,
      TimezoneSidKey = 'America/Los_Angeles', Username = 'demo2990@handomdemodomainz.djw.cmq');

    insert user;
    User currentUser = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
    System.runAs(currentUser){
      PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = user.Id, PermissionSetId = permissionSetId);
      insert psa;
    }
  }

  @isTest static void getPlaygroundJobs() {
    User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
    System.runAs(portalUser){
      Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
      Test.startTest();
      List<Playground_Job__c> jobs = cps_PlaygroundWizardSetupController.GetPlaygroundJobs(playground.Id);
      System.assertEquals(!jobs.isEmpty(), true);
      Test.stopTest();
    }
  }

  @isTest static void getPlaygroundJobsScratchOrgs() {
    User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
    System.runAs(portalUser){
      Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration - Scratch Orgs');
      Test.startTest();
      List<Playground_Job__c> jobs = cps_PlaygroundWizardSetupController.GetPlaygroundJobs(playground.Id);
      System.assertEquals(!jobs.isEmpty(), true);
      Test.stopTest();
    }
  }

  @isTest static void updateJobStatus() {
    User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
    System.runAs(portalUser){
      Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
      List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
      Playground_Job__c job;
      Test.startTest();
      if(!jobs.isEmpty()){
        job = jobs.get(0);
      }
      Playground_Job__c updatedJob = cps_PlaygroundWizardSetupController.updateJobStatus(playground.Id, job.Id, 'In Progress');
      System.assertEquals(updatedJob.Status__c, 'In Progress');
      Test.stopTest();
    }
  }

  @isTest static void updateJobStatusScratchOrg() {
    User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
    System.runAs(portalUser){
      Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration - Scratch Orgs');
      List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
      Playground_Job__c job;
      Test.startTest();
      if(!jobs.isEmpty()){
        job = jobs.get(0);
      }
      Playground_Job__c updatedJob = cps_PlaygroundWizardSetupController.updateJobStatus(playground.Id, job.Id, 'In Progress');
      System.assertEquals(updatedJob.Status__c, 'In Progress');
      Test.stopTest();
    }
  }

  @isTest static void getEnvironmentAuthorizationLinks() {
    User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
    System.runAs(portalUser){
      cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', createSuccessResponseString(), new Map<String,String>());
      Test.setMock(HttpCalloutMock.class, mock);
      Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
    }

    Playground__c playground = [SELECT Id FROM Playground__c WHERE Name = 'Test Playground'];
    List<Playground_Enviroment__c> environments = [SELECT Authorization_URL__c FROM Playground_Enviroment__c WHERE Playground__c = :playground.Id LIMIT 9];
    for(Playground_Enviroment__c env : environments){
      env.Authorization_URL__c = 'https://login.salesforce.com';
    }
    update environments;

    System.runAs(portalUser){
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new cps_GetAuthLinkMock());
      Map<String, String> retMap = cps_PlaygroundWizardSetupController.GetEnvironmentAuthorizationLinks(playground.Id);
      System.debug('####@@@@retMap: ' + retMap);

      System.assertEquals(retMap.get('Copado'), 'https://mockresponse.com/test&login_hint=null');
      Test.stopTest();
    }
  }

  @isTest static void getEnvironmentAuthorizationLinksFullConfigScratchOrg() {
    User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
    System.runAs(portalUser){
      cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', createSuccessResponseString(), new Map<String,String>());
      Test.setMock(HttpCalloutMock.class, mock);
      Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration - Scratch Orgs');
    }

    Playground__c playground = [SELECT Id FROM Playground__c WHERE Name = 'Test Playground'];
    List<Playground_Enviroment__c> environments = [SELECT Authorization_URL__c FROM Playground_Enviroment__c WHERE Playground__c = :playground.Id LIMIT 9];
    for(Playground_Enviroment__c env : environments){
      env.Authorization_URL__c = 'https://test.salesforce.com';
      env.Access_Token__c = 'accesstoken';
      env.InstanceUrl__c = 'https://environment-url.my.salesforce.com/';
      env.Type__c = 'Scratch_Org';
    }
    update environments;

    System.runAs(portalUser){
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new cps_GetAuthLinkScratchOrgMock());
      Map<String, String> retMap = cps_PlaygroundWizardSetupController.GetEnvironmentAuthorizationLinks(playground.Id);
      System.debug('####@@@@retMap: ' + retMap);

      System.assertEquals(retMap.get('Production'), 'https://environment-url.my.salesforce.com/secur/frontdoor.jsp?sid=accesstoken&retURL=%2F&login_hint=null.production');
      Test.stopTest();
    }
  }

  private static String createSuccessResponseString() {
    String responseString = '{"isSuccess":"'+true+'", "copadoJobId":"430c0e95-4771-4c66-9b42-d1eb277186b5"}';
    return responseString;
  }

  @isTest static void getEnvironmentCoEAuthorizationLinkFullConfigScratchOrg() {
    User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
    System.runAs(portalUser){
      cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', createSuccessResponseString(), new Map<String,String>());
      Test.setMock(HttpCalloutMock.class, mock);
      Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration - Scratch Orgs');
    }

    Playground__c playground = [SELECT Id FROM Playground__c WHERE Name = 'Test Playground'];
    List<Playground_Enviroment__c> environments = [SELECT Authorization_URL__c FROM Playground_Enviroment__c WHERE Playground__c = :playground.Id LIMIT 9];
    for(Playground_Enviroment__c env : environments){
      env.Authorization_URL__c = 'https://test.salesforce.com';
      env.Access_Token__c = 'accesstoken';
      env.InstanceUrl__c = 'https://environment-url.my.salesforce.com/';
      env.Type__c = 'Scratch_Org';
    }

    Playground_Enviroment__c env = environments[0];
      env.Authorization_URL__c = 'https://login.salesforce.com';
      env.Type__c = 'CoE_Org';

    update environments;
    update env;

    System.runAs(portalUser){
      Test.startTest();
      Test.setMock(HttpCalloutMock.class, new cps_GetCopadoAuthLinkWithFrontdoorMock());
      Map<String, String> retMap = cps_PlaygroundWizardSetupController.GetEnvironmentAuthorizationLinks(playground.Id);
      System.debug('####@@@@retMap: ' + retMap);

      System.assertEquals(retMap.get('Copado'), 'https://trialorgfrontdoor.my.salesforce.com/secur/frontdoor.jsp?sid=accesstoken&retURL=%2F&login_hint=null');
      Test.stopTest();
    }
  }
}