objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Interactive_Validation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interactive Validation</label>
    <nameField>
        <label>Interactive Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interactive_Validation_Step__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dev1</fullName>
                </value>
                <value>
                    <fullName>Dev2</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExecutionDetails__c</fullName>
        <label>ExecutionDetails</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExecutionOrder__c</fullName>
        <label>ExecutionOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interactive_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation</label>
        <referenceTo>Interactive_Validation__c</referenceTo>
        <relationshipLabel>Interactive Validation Steps</relationshipLabel>
        <relationshipName>Interactive_Validation_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Validate Data</fullName>
                </value>
                <value>
                    <fullName>Validate Metadata</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interactive Validation Step</label>
    <nameField>
        <label>Interactive Validation Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validation Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Achievement__c.object
<CustomObject>
    <fields>
        <fullName>ReputationPoints__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reputation Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>redwing__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Achievements</fullName>
                    <default>true</default>
                    <label>Achievements</label>
                </value>
                <value>
                    <fullName>Certifications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>Interactive_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation</label>
        <referenceTo>Interactive_Validation__c</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <inlineHelpText>Only Active Learning Plans will be visible to learners, Draft plans will be visible for Learning Admins</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>redwing__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>Section</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Assignments</relationshipLabel>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Assignment</label>
    <nameField>
        <displayFormat>LPAS-{0000000}</displayFormat>
        <label>Learning Plan Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Training_Plan_Section_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Section Assignment</label>
    <nameField>
        <displayFormat>LPSA-{0000000}</displayFormat>
        <label>Learning Plan Section Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AchievementAssignmentHandlerTest.cls
@isTest
private class AchievementAssignmentHandlerTest {
    static testMethod void updateReputationPoints() { 
     //create a user
        User u = new User();
        u.LastName = 'achtest';
        u.Username = 'test@achievement-trigger-copadouser.com';
        u.Email = 'test@achievement-trigger-copadouser.com';
        u.Alias = 'testuser';
        u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
        u.TimeZoneSidKey = 'GMT';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        insert u;
        
    // create an achievement
    
        redwing__Achievement__c badge = new redwing__Achievement__c();
        badge.Name = 'test badge';
        badge.redwing__Type__c = 'Achievements';
        badge.ReputationPoints__c = 3;
        insert badge;

    //create an achievement assginment 
    
        redwing__Achievement_Assignment__c badgea = new redwing__Achievement_Assignment__c();
        badgea.redwing__User__c = u.Id;
        badgea.redwing__Achievement__c  = badge.Id;
        badgea.redwing__Status__c = 'Eligible';
        insert badgea;
        badgea.redwing__Status__c = 'Acquired';
        update badgea;
        
        NetworkMember nw = [SELECT Id, ReputationPoints FROM NetworkMember WHERE MemberId = :u.Id];
        System.assertEquals(4, nw.ReputationPoints);
    } 
    
    static testMethod void updateReputationPointsWhenItIsNull() { 
     //create a user
        User u = new User();
        u.LastName = 'achtest';
        u.Username = 'test@achievement-trigger-null-copadouser.com';
        u.Email = 'test@achievement-trigger-null-copadouser.com';
        u.Alias = 'testuser';
        u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
        u.TimeZoneSidKey = 'GMT';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        insert u;
        
    // create an achievement
    
        redwing__Achievement__c badge = new redwing__Achievement__c();
        badge.Name = 'test badge';
        badge.redwing__Type__c = 'Achievements';
        badge.ReputationPoints__c = null;
        insert badge;

    //create an achievement assginment 
    
        redwing__Achievement_Assignment__c badgea = new redwing__Achievement_Assignment__c();
        badgea.redwing__User__c = u.Id;
        badgea.redwing__Achievement__c  = badge.Id;
        badgea.redwing__Status__c = 'Eligible';
        insert badgea;
        badgea.redwing__Status__c = 'Acquired';
        update badgea;
        
        NetworkMember nw = [SELECT Id, ReputationPoints FROM NetworkMember WHERE MemberId = :u.Id];
        System.assertEquals(1, nw.ReputationPoints);
    } 
    
    static testMethod void updateAchivementStatusEligible() { 
     //create a user
        User u = new User();
        u.LastName = 'achtest';
        u.Username = 'test@achievement-trigger-copadouser.com';
        u.Email = 'test@achievement-trigger-copadouser.com';
        u.Alias = 'testuser';
        u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
        u.TimeZoneSidKey = 'GMT';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        insert u;
        
        Account testAccount = new Account(Name='Test');
        insert testAccount;
        
        Contact testContact = new Contact(LastName='test', AccountId=testAccount.Id);
        insert testContact;
    // create an achievement
    
        redwing__Achievement__c badge = new redwing__Achievement__c();
        badge.Name = 'test badge';
        badge.redwing__Type__c = 'Achievements';
        badge.ReputationPoints__c = 3;
        insert badge;
        
        Interactive_Validation__c validation = new Interactive_Validation__c(Name='IV Config Step Deff', Status__c = 'Active');
        insert validation;
        
        List<Interactive_Validation_Step__c> configSteps = new List<Interactive_Validation_Step__c>();
        configSteps.add(new Interactive_Validation_Step__c(Interactive_Validation__c=validation.Id, Name='Step A', ExecutionOrder__c=1, Environment__c='Dev1', Type__c='Validate Data', ExecutionDetails__c='test'));
        configSteps.add(new Interactive_Validation_Step__c(Interactive_Validation__c=validation.Id, Name='Step B', ExecutionOrder__c=2, Environment__c='Dev1', Type__c='Validate Metadata', ExecutionDetails__c='test'));
        insert configSteps;
        
        redwing__Training_Plan__c trainingPlan = TestDataFactory.createTrainingPlan('Test Developer');
        INSERT trainingPlan;
        
        redwing__Training_Plan_Assignment__c trainingPlanAssignment = TestDataFactory.createTrainingPlanAssignment(u.Id,testContact.Id,trainingPlan.Id);
        INSERT trainingPlanAssignment;
        
        redwing__Learning__c learning = TestDataFactory.createLearning('Test Learning');
        learning.Interactive_Validation__c = validation.Id;
        learning.Is_Dynamic__c = true;
        INSERT learning;
        
        redwing__Training_Plan_Section__c trainingPlanSection = TestDataFactory.createTrainigPlanSection('Test',trainingPlan.Id);
        INSERT trainingPlanSection;
        
        redwing__Training_Plan_Section_Assignment__c trainingPlanSectionAssignment = TestDataFactory.createTrainingPlanSectionAssignment(u.Id,trainingPlanSection.Id,trainingPlanAssignment.Id);
        INSERT trainingPlanSectionAssignment;
        
        redwing__Training_Plan_Section_Item__c trainingPlanSectionItem = TestDataFactory.createTrainingPlanSectionItem(learning.Id,trainingPlanSection.Id);
        INSERT trainingPlanSectionItem;
        
        redwing__Learning_Assignment__c learningAssignment = TestDataFactory.createLearningAssignment(testContact.Id,u.Id,trainingPlan.Id,learning.Id,trainingPlanSection.Id,trainingPlanSectionAssignment.Id,trainingPlanSectionItem.Id);
        INSERT learningAssignment;
        
        redwing__Training_Plan_Achievement__c Training_Plan_Achievement = new redwing__Training_Plan_Achievement__c();
        Training_Plan_Achievement.redwing__Training_Plan__c = trainingPlan.Id;
        Training_Plan_Achievement.redwing__Achievement__c = badge.Id;
        Insert Training_Plan_Achievement;

    //create an achievement assginment 
    
        redwing__Achievement_Assignment__c badgea = new redwing__Achievement_Assignment__c();
        badgea.redwing__User__c = u.Id;
        badgea.redwing__Achievement__c  = badge.Id;
        badgea.redwing__Training_Plan_Achievement__c = Training_Plan_Achievement.Id;
        badgea.redwing__Status__c = 'Eligible';
        insert badgea;
        badgea.redwing__Status__c = 'Acquired';
        update badgea;
        
        NetworkMember nw = [SELECT Id, ReputationPoints FROM NetworkMember WHERE MemberId = :u.Id];
        System.assertEquals(1, nw.ReputationPoints);
    } 
}