objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Batch_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Covering_Period_From__c</fullName>
        <inlineHelpText>This is the start date for the period that this batch payment covers.</inlineHelpText>
        <label>Covering Period From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Covering_Period_To__c</fullName>
        <inlineHelpText>This is the covering period to which invoices will be included.</inlineHelpText>
        <label>Covering Period To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Payment</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Batch Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/JBCXM__CTA__c.object
<CustomObject>
    <fields>
        <fullName>JBCXM__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call To Actions</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Call To Action</label>
    <nameField>
        <label>Call To Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call To Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payable_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payable Invoices</relationshipLabel>
        <relationshipName>Payable_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Batch_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The batch payment where this invoice was paid.</inlineHelpText>
        <label>Batch Payment</label>
        <referenceTo>Batch_Payment__c</referenceTo>
        <relationshipLabel>Payable Invoices</relationshipLabel>
        <relationshipName>Payable_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Due_Date__c</fullName>
        <label>Invoice Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The customer to which this invoice relates</inlineHelpText>
        <label>Related Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payable Invoices (Related Customer)</relationshipLabel>
        <relationshipName>Payable_Invoices_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Payment</fullName>
                    <default>true</default>
                    <label>Pending Payment</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payable Invoice</label>
    <nameField>
        <label>Payable Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payable Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AddInvoicesToPaymentBatch.cls
global class AddInvoicesToPaymentBatch implements Database.Batchable<sObject> {
	
	String query;
	global final  Date fromDate;
	global final  Date toDate;
	
	global AddInvoicesToPaymentBatch(Date fd, Date td) {
		fromDate = fd;
		toDate = td;
		query = 'select Id, Name, Invoice_Amount__c, Status__c, Invoice_Date__c, Invoice_Due_Date__c, Related_Customer__r.Name, Batch_Payment__c from Payable_Invoice__c where Invoice_Due_Date__c >='+String.valueOf(fromDate)+' and Invoice_Due_Date__c <='+String.valueOf(toDate)+' and Status__c=\'Pending Payment\' and Account__r.Name=\'salesforce.com EMEA Limited\'';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		if(fromDate==null || toDate==null){
   			system.debug('Nothing to run. One of the dates was null: fromDate('+fromDate+') toDate('+toDate+')');
   			return;
   		}
		if(scope.size()>0){
			// First create Batch_Payment.
			Batch_Payment__c batchPayment = new Batch_Payment__c();
			List<Batch_Payment__c> bps = [select Id, Name, Amount__c, Status__c, Payment_Date__c, Covering_Period_From__c, Covering_Period_To__c from Batch_Payment__c
			where Covering_Period_From__c=:fromDate and Covering_Period_To__c=:toDate and Status__c='Draft'];
			system.debug('### bps returned '+bps);
			if(bps.size()>0){
				system.debug('### TAKING FIRST PAYMENT: '+bps[0]);
				batchPayment = bps[0];
			}
			else{
				system.debug('### CREATING NEW PAYMENT: ');
				batchPayment.Covering_Period_From__c = fromDate;
				batchPayment.Covering_Period_To__c = toDate;
				batchPayment.Status__c = 'Draft';
				insert batchPayment;
			}
			system.debug('### USING THIS PAYMENT: '+batchPayment);
			// Then add invoices to batch payment.
			batchPayment.Amount__c = 0;
			for(SObject so : scope){
				Payable_Invoice__c i = (Payable_Invoice__c)so;
				system.debug('### ITERATING SCOPE: '+i);
				i.Batch_Payment__c = batchPayment.Id;
				batchPayment.Amount__c = batchPayment.Amount__c+i.Invoice_Amount__c;
			}

			system.debug('### UPDATING SCOPE: '+scope);
			update scope;

			system.debug('### UPDATING batchPayment: '+batchPayment);
			update batchPayment;
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}