objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/amc__Action__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to link an action to an account. this is required to ensure we can deduct assigned hours for clients.</description>
        <inlineHelpText>Field used to link an action to an account. this is required to ensure we can deduct assigned hours for clients.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MC Actions</relationshipLabel>
        <relationshipName>MC_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amc__Hours_Completed__c</fullName>
        <inlineHelpText>Roll up summary of the Hours Completed on Time Logs. Filtered to include Time Logs where Non Billable Tracker = FALSE AND Approval Status = Approved. (Previously Labelled Hours Completed)</inlineHelpText>
        <label>Hours Completed - Billable</label>
        <summarizedField>amc__Time_Log__c.amc__Hours_Completed__c</summarizedField>
        <summaryFilterItems>
            <field>amc__Time_Log__c.amc__Non_Billable_Tracker__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>amc__Time_Log__c.amc__Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved,</value>
        </summaryFilterItems>
        <summaryForeignKey>amc__Time_Log__c.amc__Action__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>amc__Milestone__c</fullName>
        <label>Milestone</label>
        <referenceTo>amc__Milestone__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>amc__Non_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if this Action is Non Billable</inlineHelpText>
        <label>Non Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>amc__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Populated automatically via trigger.</inlineHelpText>
        <label>Project</label>
        <referenceTo>amc__Project__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>PAN:{0000}</displayFormat>
        <label>Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/amc__Milestone__c.object
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/amc__Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/amc__Time_Log__c.object
<CustomObject>
    <description>Enables project team members to log time against Actions</description>
    <fields>
        <fullName>ProfessionalServiceConsumption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to link the log to the consumption in order to enable updates. should be filled by a trigger.</description>
        <inlineHelpText>Field to link the log to the consumption in order to enable updates. should be filled by a trigger.</inlineHelpText>
        <label>Professional Service Consumption</label>
        <referenceTo>Professional_Service_Consumption__c</referenceTo>
        <relationshipLabel>Time Logs</relationshipLabel>
        <relationshipName>TimeLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amc__Action__c</fullName>
        <inlineHelpText>Select the Action this Time Log relates to</inlineHelpText>
        <label>Action</label>
        <referenceTo>amc__Action__c</referenceTo>
        <relationshipLabel>Time Logs</relationshipLabel>
        <relationshipName>Time_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>amc__Billable_Hours_Completed__c</fullName>
        <formula>IF(!amc__Non_Billable_Indicator__c , amc__Hours_Completed__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billable Hours Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amc__Date__c</fullName>
        <inlineHelpText>date the work was completed</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>amc__Hours_Completed__c</fullName>
        <inlineHelpText>Shows the number of hours spent on the Action during this Time Log</inlineHelpText>
        <label>Hours Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amc__Non_Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Identifies if this Time Log is Non Billable</inlineHelpText>
        <label>Non Billable</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Log</label>
    <nameField>
        <displayFormat>TLN-{00000000}</displayFormat>
        <label>Time Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Professional_Service_Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Professional Service Consumption</relationshipLabel>
        <relationshipName>Professional_Service_Consumption</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours_consumed__c</fullName>
        <label>Hours consumed</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Date__c</fullName>
        <description>When were the professional services given</description>
        <label>Meeting Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Meeting_Id__c</fullName>
        <externalId>true</externalId>
        <label>Meeting Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Meeting_Notes__c</fullName>
        <label>Meeting Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Professional Service Consumption</label>
    <nameField>
        <displayFormat>PSC-{00000}</displayFormat>
        <label>Professional Service Consumption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Service Consumption</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MC_TimeLogHelper.cls
/**
 * Created by kheidt on 2019-05-06.
 */

public with sharing class MC_TimeLogHelper {


    public Map<Id, amc__Time_Log__c> timeLogMap                            = new Map<Id, amc__Time_Log__c>();
    public Map<Id, Professional_Service_Consumption__c> psConsumptionMap   = new Map<Id, Professional_Service_Consumption__c>();
    public List<amc__Time_Log__c> timeLogs = new List<amc__Time_Log__c>();
    public List<Professional_Service_Consumption__c> psConsumptions = new List<Professional_Service_Consumption__c>();

    public void convertTimeLogsToConsumption(Map<Id, amc__Time_Log__c> logMap){
        //set main class variables
        timeLogMap = setTimeLogMap(logMap);
        System.debug('set the time log map: ' + timeLogMap);

        Set<Id> pscIds = new Set<Id>();
        for(amc__Time_Log__c tl : timeLogMap.values()){
            if(tl.ProfessionalServiceConsumption__c != null){
                pscIds.add(tl.ProfessionalServiceConsumption__c);
            }
        }

        psConsumptionMap = this.getPSConsumptionMap(pscIds);
        System.debug('set the consumption map: ' + psConsumptionMap);

        //run logic
        this.linkLogsAndConsumption();
    }

    public Map<Id, Professional_Service_Consumption__c> getPSConsumptionMap(Set<Id> psIds){
        Map<Id, Professional_Service_Consumption__c> psMap = new Map<Id, Professional_Service_Consumption__c>(
        [
                SELECT Id, Name, Hours_consumed__c, Account__c
                FROM Professional_Service_Consumption__c
                WHERE Id IN :psIds
        ]
        );

        this.psConsumptionMap = psMap;
        return psMap;
    }

    public Map<Id, amc__Time_Log__c> setTimeLogMap( Map<Id, amc__Time_Log__c> tlMap){

        this.timeLogMap = this.getTimeLogMap(tlMap.keySet());
        return timeLogMap;
    }

    //link time logs and maps

    public void linkLogsAndConsumption(){

        System.debug('starting the for loop');

        for(Id i:timeLogMap.keySet()){
            amc__Time_Log__c tl = timeLogMap.get(i);
            Professional_Service_Consumption__c thisPS;

            //only consider billable items:
            if(!tl.amc__Non_Billable__c) {

                System.debug('This log is billable: ' + tl);

                //for each time log, get the consumption record
                if (tl.ProfessionalServiceConsumption__c != null || tl.ProfessionalServiceConsumption__c == '') {

                    //if the log already has a consumption, we will just get it from the map.
                    thisPS = psConsumptionMap.get(tl.ProfessionalServiceConsumption__c);
                }
                //for time logs without consumption, we need to create the consumption record
                else {

                    //create empty parent relationship record, required according to apex logic
                    Professional_Service_Consumption__c relation = new Professional_Service_Consumption__c(
                            Meeting_Id__c = tl.Id
                    );

                    tl.ProfessionalServiceConsumption__r = relation;

                    //create the real record we want to store in the database
                    thisPS = this.createPSConsumption(tl);

                    //we need to update the child records with the new reference
                    timeLogs.add(tl);
                }

                //set the hours on the consumption. works for new logs and if you change hours later on
                thisPS = this.updatePSConsumption(tl, thisPS);

                psConsumptions.add(thisPS);

            } else{
                System.debug(System.LoggingLevel.INFO , 'the following log is not billable: ' + tl);
            }
        }

        //perform DML
        upsert psConsumptions;
        upsert timeLogs;
    }

    public void deleteRelatedConsumption(amc__Time_Log__c log){

        Professional_Service_Consumption__c delPsc;

        //get related consumption
        if(log.ProfessionalServiceConsumption__c != null) {

            delPsc = getPSConsumption(log.ProfessionalServiceConsumption__c);

            System.debug('The following consumption will be deleted: ' + delPsc);
            delete delPsc;
        } else{
            System.debug('The log which was deleted has no Consumption related to it');
        }
    }

    //get time logs
    public Professional_Service_Consumption__c getPSConsumption(String psID){

        Professional_Service_Consumption__c ps = [
                SELECT Id, Name, Hours_consumed__c, Account__c
                FROM Professional_Service_Consumption__c
                WHERE Id = :psID
        ];

        return ps;
    }

    public Professional_Service_Consumption__c createPSConsumption(amc__Time_Log__c timeLog){

        Professional_Service_Consumption__c ps = new Professional_Service_Consumption__c();



        ps.Account__c = timeLog.amc__Action__r.Account__c;
        ps.Meeting_Id__c = timeLog.Id;
        ps.Meeting_Date__c = Date.today();
        ps.Meeting_Notes__c = 'Auto created with the time log';
        ps.Meeting_Date__c = timeLog.amc__Date__c;

        return ps;
    }

    public Professional_Service_Consumption__c updatePSConsumption(
            amc__Time_Log__c timeLog,
            Professional_Service_Consumption__c ps
    ){

        ps.Hours_consumed__c = timeLog.amc__Billable_Hours_Completed__c;

        return ps;
    }

    public Map<Id, amc__Time_Log__c> getTimeLogMap(Set<Id> logIds){
        Map<Id, amc__Time_Log__c> newMap = new Map<Id, amc__Time_Log__c>(
        [
                SELECT
                        Id,
                        Name,
                        ProfessionalServiceConsumption__c,
                        amc__Non_Billable__c,
                        amc__Hours_Completed__c,
                        amc__Billable_Hours_Completed__c,
                        amc__Action__r.Account__c,
                        amc__Action__r.amc__Milestone__r.amc__Project__r.Name,
                        ProfessionalServiceConsumption__r.Meeting_Id__c,
                        amc__Date__c
                FROM amc__Time_Log__c
                WHERE Id IN :logIds
                AND amc__Action__r.Account__c != null
        ]);
        return newMap;
    }
}