objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proforma Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Days_to_Pay__c</fullName>
        <formula>Payment_Date__c -  Invoice_Date__c</formula>
        <label>Days to Pay</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discounted_Amount__c</fullName>
        <formula>if( Discount__c&gt;0, (Invoice_Amount__c +  VAT_Amount__c ) * Discount__c ,Discount_off__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discounted Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <summarizedField>Invoice_Line_Item__c.Total_Price__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice_Line_Item__c.Is_VAT_Item__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Sub_total__c -  Discounted_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VAT_Amount__c</fullName>
        <label>VAT Amount</label>
        <summarizedField>Invoice_Line_Item__c.Total_Price__c</summarizedField>
        <summaryFilterItems>
            <field>Invoice_Line_Item__c.Is_VAT_Item__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_VAT_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This checkbox must be ticked for VAT line items.</inlineHelpText>
        <label>Is VAT Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Unit_Price__c * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/JBCXM__CTA__c.object
<CustomObject>
    <fields>
        <fullName>JBCXM__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call To Actions</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Call To Action</label>
    <nameField>
        <label>Call To Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call To Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/invoicePDFextension.cls
public with sharing class invoicePDFextension {
    public Invoice__c invoice {get;set;}
    public List<Invoice_Line_Item__c> lineItems {get;set;}
    
    public invoicePDFextension(ApexPages.StandardController stdController) {
        invoice = (Invoice__c)stdController.getRecord();
        invoice = [SELECT Id, Name, Account__c, Account__r.Name, Account__r.VAT_Number__c, Account__r.Billing_Name__c,
                            Account__r.BillingStreet, Account__r.BillingCity, Account__r.BillingState, Account__r.BillingPostalCode, Account__r.BillingCountry, 
                            Invoice_Date__c, Days_to_Pay__c,Invoice_Amount__c, Total_Amount__c, VAT_Amount__c, Discounted_Amount__c
            FROM Invoice__c
            WHERE Id = :stdController.getId() LIMIT 1];
        lineItems = new List<Invoice_Line_Item__c>();
        lineItems = [SELECT Id, Name, Unit_Price__c, Quantity__c, Total_Price__c, Invoice__c, Start_Date__c, End_Date__c FROM Invoice_Line_Item__c WHERE Invoice__c = :invoice.Id AND Is_VAT_Item__c = false];
    }
}