objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Org_Id__c</fullName>
        <formula>LEFT(Org_Credential__r.copado__Environment__r.copado__Org_ID__c,15)</formula>
        <label>Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Indicates the stage of the playground creation. If stage is not Completed when a user returns to a playground the user will land the said stage.</description>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                    <default>true</default>
                    <label>CreateTrialOrg</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
                <value>
                    <fullName>PostInstallScript</fullName>
                </value>
                <value>
                    <fullName>Setup</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                    <isActive>false</isActive>
                    <label>Install</label>
                </value>
                <value>
                    <fullName>Start</fullName>
                    <isActive>false</isActive>
                    <label>Start</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Org_Id__c</fullName>
        <label>Org Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                </value>
                <value>
                    <fullName>CreateCoeCredential</fullName>
                </value>
                <value>
                    <fullName>CoE_Authorization</fullName>
                </value>
                <value>
                    <fullName>GitSetup</fullName>
                </value>
                <value>
                    <fullName>ProvisionLicenses</fullName>
                </value>
                <value>
                    <fullName>CreateEnvironment</fullName>
                </value>
                <value>
                    <fullName>CreateOrgCredentials</fullName>
                </value>
                <value>
                    <fullName>AuthorizeSandbox</fullName>
                </value>
                <value>
                    <fullName>AssignPermissionSet</fullName>
                </value>
                <value>
                    <fullName>ExecutePostInstallScript</fullName>
                </value>
                <value>
                    <fullName>CreateScratchOrgEnvironment</fullName>
                </value>
                <value>
                    <fullName>EnableUser</fullName>
                </value>
                <value>
                    <fullName>GitSetupFinish</fullName>
                </value>
                <value>
                    <fullName>CreateGitSnapshot</fullName>
                </value>
                <value>
                    <fullName>CreateBranches</fullName>
                </value>
                <value>
                    <fullName>CreateBoilerplate</fullName>
                </value>
                <value>
                    <fullName>AddingFinishingTouches</fullName>
                    <label>Adding Finishing Touches</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Sandbox Creation</fullName>
                </value>
                <value>
                    <fullName>Record Creation</fullName>
                </value>
                <value>
                    <fullName>Git</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Are_Playgrounds_Under_Maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be retrieved to check if playgrounds are available for creation (false) or they are under maintenance, so users will not be able to create a new one or continue one in progress</description>
        <label>Are Playgrounds Under Maintenance</label>
        <type>Checkbox</type>
    </fields>
    <label>Playground Setting</label>
    <pluralLabel>Playground Settings</pluralLabel>
</CustomObject>

classes/cps_PlaygroundWizardControllerTest.cls
@isTest
private class cps_PlaygroundWizardControllerTest {

	@testSetup static void setup(){
		Id communityProfileId = [SELECT Id FROM Profile WHERE Name = 'CUSTOM Customer Community Login User'].Id;
		Id permissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Community_Playground_User'].Id;

        Account account = new Account(Name ='Test Account 1') ;
        insert account;

        Contact contact = new Contact(LastName ='TestContact', AccountId = account.Id, Allowed_Playgrounds__c = 10, Is_Playgrounds_Test_User__c = true);
        insert contact;

        User user = new User(
        						Alias = 'myalias', Email = 'testemail@emailtest.com',
                				EmailEncodingKey = 'UTF-8', LastName = 'TestUser',
                				LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US',
                				ProfileId = communityProfileId, Country = 'United States',
                				IsActive = true, ContactId = contact.Id,
                				TimezoneSidKey = 'America/Los_Angeles', Username = 'demo7251@handomdemodomainz.djw.cmq');

        insert user;
        User currentUser = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
        System.runAs(currentUser){
        	PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = user.Id, PermissionSetId = permissionSetId);
        	insert psa;
        }
    }

	@isTest static void getSessionId() {
		User portalUser = [SELECT Id, Allowed_Playgrounds__c FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Test.startTest();
			String sessionId = cps_PlaygroundWizardController.getSessionId();
			Test.stopTest();
			system.assert(sessionId!=null);
		}
	}

	@isTest static void getAllowedPlaygrounds() {
		User portalUser = [SELECT Id, Allowed_Playgrounds__c FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Test.startTest();
			Decimal allowedPlaygrounds = cps_PlaygroundWizardController.GetAllowedPlaygrounds();
			System.assertEquals(allowedPlaygrounds, portalUser.Allowed_Playgrounds__c);
			Test.stopTest();
		}
	}

	@isTest static void getAvailablePlayground_NotNull() {
		User portalUser = [SELECT Id, ContactId FROM User WHERE Email = 'testemail@emailtest.com'];
		portalUser.Allowed_Playgrounds__c = 55;
		update portalUser;

		System.runAs(portalUser){
			Test.startTest();
			Decimal result = cps_PlaygroundWizardController.GetAvailablePlaygrounds();
			system.assertEquals(55, result);
			Test.stopTest();
		}
	}

	@isTest static void getAvailablePlayground_null() {
		User portalUser = [SELECT Id, ContactId FROM User WHERE Email = 'testemail@emailtest.com'];
		portalUser.Allowed_Playgrounds__c = null;
		update portalUser;

		System.runAs(portalUser){
			Test.startTest();
			Decimal result = cps_PlaygroundWizardController.GetAvailablePlaygrounds();
			system.assertEquals(0, result);
			Test.stopTest();
		}
	}

	@isTest static void deletePlayground() {
		User portalUser = [select Id from User where Email='testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
		}
		Playground_Enviroment__c playgroundEnv = [select Id, Org_Id__c from Playground_Enviroment__c where Playground__r.Name='Test Playground' and Type__c='CoE_Org' limit 1];
		playgroundEnv.Org_Id__c = '00D000000000000000';
		update playgroundEnv;

		System.runAs(portalUser){
			Playground__c playground = [select Id, Name from Playground__c where Name='Test Playground'];

			cps_C1PJobMock mock = new cps_C1PJobMock(201, 'OK', '', new Map<String,String>());
        	Test.setMock(HttpCalloutMock.class, mock);

			Test.startTest();
			cps_PlaygroundWizardController.DeletePlayground(playground.Id);
			List<Playground__c> emptyPlaygroundList = [select Name from Playground__c where Id=:playground.Id];
			System.assert(emptyPlaygroundList.isEmpty());
			Test.stopTest();
		}
	}

	@isTest static void getPlayground() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			Test.startTest();
			Playground__c queriedPlayground = cps_PlaygroundWizardController.getPlayground(playground.Id);
			System.assertEquals(queriedPlayground.Name, 'Test Playground');
			Test.stopTest();
		}
	}

	@isTest static void getMyPlaygrounds() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			Playground__c playground2 = cps_PlaygroundWizardStartController.createPlayground('Test Playground 2', 'Full Configuration');
			Playground__c playground3 = cps_PlaygroundWizardStartController.createPlayground('Test Playground 3', 'Full Configuration');
			Test.startTest();
			List<Playground__c> queriedPlaygrounds = cps_PlaygroundWizardController.GetMyPlaygrounds();
			System.assertEquals(queriedPlaygrounds.size(), 3);
			Test.stopTest();
		}
	}

	@isTest static void updatePlaygroundStage() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			Test.startTest();
			Playground__c updatedPlayground = cps_PlaygroundWizardController.updatePlaygroundStage(playground.Id, 'Completed');
			Playground__c queriedPlayground = [SELECT Stage__c FROM Playground__c WHERE Id =: playground.Id];
			System.assertEquals(updatedPlayground.Stage__c, queriedPlayground.Stage__c);
			Test.stopTest();
		}
	}

	@isTest static void updateJobStatus_InProgress() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
			Playground_Job__c job;
			Test.startTest();
			if(!jobs.isEmpty()){
				job = jobs.get(0);
			}
			Playground_Job__c updatedJob = cps_PlaygroundWizardController.updateJobStatus(playground.Id, job.Id, 'In Progress');
			System.assertEquals(updatedJob.Status__c, 'In Progress');
			Test.stopTest();
		}
	}

	@isTest static void updateJobStatus_Failed() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
			Playground_Job__c job;
			if(!jobs.isEmpty()) job = jobs.get(0);

			Test.startTest();
			Playground_Job__c updatedJob = cps_PlaygroundWizardController.updateJobStatus(playground.Id, job.Id, 'Failed');
			Playground__c result = [select Status__c from Playground__c where Id=:playground.Id limit 1];
			System.assertEquals('Failed', result.Status__c);
			Test.stopTest();
		}
	}

	@isTest static void getPlaygroundJobs() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			Test.startTest();
			List<Playground_Job__c> jobs = cps_PlaygroundWizardController.GetPlaygroundJobs(playground.Id);
			System.assertEquals(!jobs.isEmpty(), true);
			Test.stopTest();
		}
	}

	@isTest static void getPlaygroundDetails() {
		User portalUser = [SELECT Id, Allowed_Playgrounds__c FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			List<Playground_Enviroment__c> pgEnvs = [select Id from Playground_Enviroment__c where Playground__c=:playground.Id];
			Test.startTest();
			Map<String, Object> result = cps_PlaygroundWizardController.getPlaygroundDetails(playground.Id);
			Playground__c playgroundResult = (Playground__c)result.get('playground');
			List<Playground_Enviroment__c> envsResult = (List<Playground_Enviroment__c>)result.get('environments');
			Test.stopTest();

			System.assertEquals(pgEnvs.size(), envsResult.size());
		}
	}

	@isTest static void callStandardC1PAction() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', createSuccessResponseString(), new Map<String,String>());
            Test.setMock(HttpCalloutMock.class, mock);
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
			Test.startTest();
			Playground_Job__c job = cps_PlaygroundWizardController.callStandardC1PAction(playground.Id, 'ExecutePostInstallScript');
			Playground_Job__c queriedJob = [SELECT Id, Status__c FROM Playground_Job__c WHERE Action__c = 'ExecutePostInstallScript'];
			System.assertEquals(job.Id, queriedJob.Id);
			System.assertEquals(job.Status__c, queriedJob.Status__c);
			Test.stopTest();
		}
	}

	@isTest static void getPlaygroundUnderMaintenanceTest() {
		User portalUser = [SELECT Id FROM User WHERE Email = 'testemail@emailtest.com'];
		System.runAs(portalUser){
			Test.startTest();
			Playground_Setting__mdt playgroundSetting = cps_PlaygroundWizardController.getPlaygroundUnderMaintenance();
			System.assert(!playgroundSetting.Are_Playgrounds_Under_Maintenance__c);
			Test.stopTest();
		}
	}

	private static String createSuccessResponseString() {
        String responseString = '{"isSuccess":"'+true+'", "copadoJobId":"430c0e95-4771-4c66-9b42-d1eb277186b5"}';
        return responseString;
    }
}