objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Signup_Request__c.object
<CustomObject>
    <description>This object captures the Signup Requests generated from the community and creates Trialforce orgs</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The default value is the country of the requesting org. The language of the trial organization is auto-determined based on the value of this field.</description>
        <inlineHelpText>Default value is the country of the requesting org. ISO-3166 country code (Alpha-2 code).  Full list of these codes at: https://www.iso.org/obp/ui/#search. The language of the trial organization is auto-determined based on this value.</inlineHelpText>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                    <default>true</default>
                    <label>US</label>
                </value>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>33</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is populated by the Playground Wizard so that ProcessBuilder can update the job and UI changes can be triggered via Playground Job Events.</inlineHelpText>
        <label>Playground Job</label>
        <referenceTo>Playground_Job__c</referenceTo>
        <relationshipLabel>Signup Request</relationshipLabel>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <inlineHelpText>The 15–character ID of the Trialforce template that is the basis for the trial sign-up. Salesforce must approve the template. If you don’t specify an edition, a template ID is required.</inlineHelpText>
        <label>Template</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <inlineHelpText>The username of the admin user for the trial sign-up. It must follow the address convention specified in RFC822: www.w3.org/Protocols/rfc822/#z10</inlineHelpText>
        <label>Username</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Custom Signup Request</label>
    <nameField>
        <displayFormat>SR{0000000000}</displayFormat>
        <label>Signup Request Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signup Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/newTrialSignupController_test.cls
@isTest
public with sharing class newTrialSignupController_test {

    @testSetup static void setup(){
        Id communityProfileId = [SELECT Id FROM Profile WHERE Name = 'CUSTOM Customer Community Login User'].Id;
        Id permissionSetId = [SELECT Id FROM PermissionSet WHERE Name = 'Community_Playground_User'].Id;

        Account account = new Account(Name='Copado, Inc.') ;
        insert account; 
       
        Contact contact = new Contact(FirstName='John', LastName='Doe', Email='john.doe@copado.com', AccountId=account.Id);
        insert contact;
                  
        User user = new User(FirstName=contact.FirstName, LastName=contact.LastName, Email=contact.Email, CompanyName=account.Name, ContactId=contact.Id,
                                Alias='myalias', IsActive=true, 
                                EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId=communityProfileId, Country='US',
                                TimezoneSidKey='America/Los_Angeles', Username='demo1734@rand3141592654.abc.def');
        insert user;
        User currentUser = [SELECT Id FROM User WHERE Id=:UserInfo.getUserId()];
        
        System.runAs(currentUser){
            PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = user.Id, PermissionSetId = permissionSetId);
            insert psa;
        }
    }

    static testMethod void getUserInfo() {
        User u = newTrialSignupController.getUserInfo();
        system.assertEquals(UserInfo.getUserId(), u.Id);
    }
    static testMethod void getSignupRequest() {
        Signup_Request__c sr = new Signup_Request__c();
        sr.First_Name__c = 'John';
        sr.Last_Name__c = 'Doe';
        sr.Company__c = 'Copado, Inc.';
        sr.Country__c = 'US';
        sr.Email__c = 'john.doe@copado.com';
        sr.Username__c = 'jon.doe@copado.com.test';
        sr.Template__c = '0TT1i00000269iK';
        insert sr;

        test.startTest();
        Signup_Request__c result = newTrialSignupController.getSignupRequest(sr.Id);
        system.assertEquals(sr.Id, result.Id);
        system.assertEquals('New', result.Status__c); //default status;
        test.stopTest();
    }
    static testMethod void createSignupRequest_goodUserName() {
        User portalUser = [select Id, FirstName, LastName, Email, CompanyName, Country, ContactId from User where Email='john.doe@copado.com'];
        System.runAs(portalUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
            List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
            
            String username = generateRandomString(10) + '@company.com';
            String domain = 'testdomain';
            String country = 'US';

            test.startTest();
            newTrialSignupController.createSignupRequest(username, domain, country, playground.Id);
            test.stopTest();
            Signup_Request__c result = getSignupRequestResult();
            system.assertNotEquals(null, result.Id);
            system.assertEquals('New', result.Status__c);
            system.assertEquals(portalUser.FirstName, result.First_Name__c);
            system.assertEquals(portalUser.LastName, result.Last_Name__c);
            system.assertEquals(portalUser.Email, result.Email__c);
            system.assertEquals(username.toLowerCase(), result.Username__c);
            system.assertEquals(portalUser.CompanyName, result.Company__c);
            system.assertEquals(portalUser.Id, result.User__c);
            system.assert( result.Domain__c.length()<=33 );
            system.assert( result.Template__c.startsWith('0TT') );
            
            portalUser = [select Id, Country from User where Email='john.doe@copado.com'];
            system.assertEquals(country, portalUser.Country);
        }
    }
    static testMethod void createSignupRequest_baddomain() {
        User portalUser = [select Id, FirstName, LastName, Email, CompanyName, Country, ContactId from User where Email='john.doe@copado.com'];
        System.runAs(portalUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
            List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
            
            String username = generateRandomString(10) + '@company.com';
            String domain = 'test     domain';
            String country = 'US';

            test.startTest();
            try {
                newTrialSignupController.createSignupRequest(username, domain, country, playground.Id);
            }
            catch(Exception e) {
                String expectedException = 'Invalid Subdomain. Select a name that does not contain double hyphens, spaces, end in a hyphen, include restricted words (e.g. sfdc) or exceed 22 characters.';
                system.assertEquals(expectedException, e.getMessage());
            }
            test.stopTest();
            try {
            	Signup_Request__c result = getSignupRequestResult();
            }
            catch(Exception e){
                //record should not have saved.
                system.assertEquals('List has no rows for assignment to SObject', e.getMessage());
            }
        }
    }
    static testMethod void createSignupRequest_badUsername() {
        User portalUser = [select Id, FirstName, LastName, Email, CompanyName, Country, ContactId from User where Email='john.doe@copado.com'];
        System.runAs(portalUser){
            Playground__c playground = cps_PlaygroundWizardStartController.createPlayground('Test Playground', 'Full Configuration');
            List<Playground_Job__c> jobs = cps_PlaygroundWizardInstallController.GetPlaygroundJobs(playground.Id);
            
            String username = 'company.com';
            String domain = 'testdomain';
            String country = 'US';

            test.startTest();
            try {
                newTrialSignupController.createSignupRequest(username, domain, country, playground.Id);
            }
            catch(Exception e) {
                String expectedException = 'The username provided is not in a valid email address format.  Please see the example provided in the help text.';
                system.assertEquals(expectedException, e.getMessage());
            }
            test.stopTest();
            try {
            	Signup_Request__c result = getSignupRequestResult();
            }
            catch(Exception e){
                //record should not have saved.
                system.assertEquals('List has no rows for assignment to SObject', e.getMessage());
            }
        }
    }

    private static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        String randStr = '';
        while (randStr.length() < len) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
    private static Signup_Request__c getSignupRequestResult() {
        return [select Id, First_Name__c, Last_Name__c, Email__c, Company__c, User__c, Country__c, Domain__c, Username__c, Status__c, Template__c from Signup_Request__c limit 1];
    }
}