objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado1p__Platform_Job__c.object
<CustomObject>
    <description>This object defines the Job that Copado 1 Platform can run</description>
    <fields>
        <fullName>copado1p__Branch__c</fullName>
        <description>The branch of the defined repository where copado_start.sh should exist</description>
        <inlineHelpText>The branch of the defined repository where copado_start.sh should exist</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado1p__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository record where external code is.</description>
        <inlineHelpText>Git Repository record where external code is.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Platform Jobs</relationshipLabel>
        <relationshipName>Platform_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado1p__VM_Provider__c</fullName>
        <description>Virtual Machine Provider, the external platform where VM will be initialised and Job will be executed.</description>
        <inlineHelpText>Virtual Machine Provider, the external platform where VM will be initialised and Job will be executed.</inlineHelpText>
        <label>VM Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>copado1p__VM_Providers</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado1p__isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether this job may be run. Inactive jobs will not be executed.</description>
        <inlineHelpText>Determines whether this job may be run. Inactive jobs will not be executed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Platform Job</label>
    <nameField>
        <label>Platform Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado1p__Platform_Job_Execution__c.object
<CustomObject>
    <description>This object is used to track every C1P job execution, one will be created per each request.</description>
    <fields>
        <fullName>copado1p__Platform_Job__c</fullName>
        <label>Platform Job</label>
        <referenceTo>copado1p__Platform_Job__c</referenceTo>
        <relationshipLabel>Platform Job Executions</relationshipLabel>
        <relationshipName>Platform_Job_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Platform Job Execution</label>
    <nameField>
        <displayFormat>PJE-{00000}</displayFormat>
        <label>Platform Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Job Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Platform_Job_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Platform Job that relates to this Playground Job</description>
        <label>Platform Job Execution</label>
        <referenceTo>copado1p__Platform_Job_Execution__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/copado1p__VM_Providers.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Heroku</fullName>
        <default>true</default>
        <label>Heroku</label>
    </customValue>
    <description>Virtual Machine Providers</description>
    <masterLabel>VM Providers</masterLabel>
</GlobalValueSet>

classes/PlaygroundJobTriggerTest.cls
@isTest
public class PlaygroundJobTriggerTest {

    @testSetup 
    static void methodName() {
        copado.GlobalAPI.UserLicense copadoUserLicense = new copado.GlobalAPI.UserLicense(UserInfo.getUserId(),false,false,false,true,false);
        copado.GlobalAPI gapi = new copado.GlobalAPI();
        gapi.upsertCopadoLicense(UserInfo.getUserId(), copadoUserLicense);
    }
    
    static testMethod void tesSuccess() {
        Account testAccount = new Account(Name='Test');
        insert testAccount;
        
        Contact testContact = new Contact(LastName='test', AccountId=testAccount.Id);
        insert testContact;
        
        Playground__c pg = new Playground__c(Name='Test 1', Contact__c=testContact.Id);
        insert pg;
        
        copado__Git_Repository__c gr = new copado__Git_Repository__c();
        insert gr;
        
        copado__Org__c o = new copado__Org__c(Name='test');
        insert o;
        
        copado1p__Platform_Job__c pj = new copado1p__Platform_Job__c(Name='C1P Rules Job');
        pj.copado1p__isActive__c = true;
        pj.copado1p__Git_Repository__c = gr.id;
        pj.copado1p__Branch__c = 'master';
        pj.copado1p__VM_Provider__c = 'Heroku';
        pj.copado1p__Branch__c = 'standard-1x';
        insert pj;
        
        copado1p__Platform_Job_Execution__c pje = new copado1p__Platform_Job_Execution__c(copado1p__Platform_Job__c=pj.Id);
        insert pje;
        
        Playground_Job__c playJob = new Playground_Job__c(Name='Test', Playground__c=pg.Id);
        playJob.Platform_Job_Execution__c = pje.Id;
        insert playJob;
        
        Test.startTest();
        
        playJob.Status__c = 'In progress';
        playJob.Payload__c = null;
        update playJob;
        Playground_Job__c result = getResult(playJob.Id);
        system.assertEquals(result.Status__c, 'In progress');
        system.assertEquals(result.Payload__c, null);
        
        playJob.Status__c = 'In progress';
        playJob.Payload__c = '%7B%22action%22%3A%22CreateCoeCredential%22%2C%22hasError%22%3Afalse%2C%22data%22%3A%7B%22Name%22%3A%22test%22%2C%22copado__Org_Type__c%22%3A%22test%22%2C%22copado__Test_Frequency__c%22%3A%22None%22%2C%22Id%22%3A%22123%22%7D%7D';
        update playJob;
        result = getResult(playJob.Id);
        system.assertEquals(result.Status__c, 'Completed');
        String expected = EncodingUtil.urlDecode(playJob.Payload__c, 'UTF-8');
        system.assertEquals(expected, result.Payload__c);
        
        playJob.Status__c = 'In progress';
        playJob.Payload__c = '%7B%22action%22%3A%22CreateCoeCredential%22%2C%22hasError%22%3Atrue%2C%22data%22%3A%7B%22Name%22%3A%22test%22%2C%22copado__Org_Type__c%22%3A%22test%22%2C%22copado__Test_Frequency__c%22%3A%22None%22%2C%22Id%22%3A%22123%22%7D%7D';
        update playJob;
        result = getResult(playJob.Id);
        system.assertEquals(result.Status__c, 'Failed');
        expected = EncodingUtil.urlDecode(playJob.Payload__c, 'UTF-8');
        system.assertEquals(expected, result.Payload__c);
    }
    private static Playground_Job__c getResult(Id recordId) {
        return [select Id, Status__c, Payload__c from Playground_Job__c where Id=:recordId limit 1];
    }
}