objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_Signup_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by the wizard when a signup request is created via playground so that ProcessBuilder can handle updates.</inlineHelpText>
        <label>Custom Signup Request</label>
        <referenceTo>Signup_Request__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Signup_Request__c.object
<CustomObject>
    <description>This object captures the Signup Requests generated from the community and creates Trialforce orgs</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the community contact record</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The default value is the country of the requesting org. The language of the trial organization is auto-determined based on the value of this field.</description>
        <inlineHelpText>Default value is the country of the requesting org. ISO-3166 country code (Alpha-2 code).  Full list of these codes at: https://www.iso.org/obp/ui/#search. The language of the trial organization is auto-determined based on this value.</inlineHelpText>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                    <default>true</default>
                    <label>US</label>
                </value>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AN</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Expired__c</fullName>
        <formula>NOW() &gt;= CreatedDate + 30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <inlineHelpText>The 15–character ID of the Trialforce template that is the basis for the trial sign-up. Salesforce must approve the template. If you don’t specify an edition, a template ID is required.</inlineHelpText>
        <label>Template</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <inlineHelpText>The username of the admin user for the trial sign-up. It must follow the address convention specified in RFC822: www.w3.org/Protocols/rfc822/#z10</inlineHelpText>
        <label>Username</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Custom Signup Request</label>
    <nameField>
        <displayFormat>SR{0000000000}</displayFormat>
        <label>Signup Request Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signup Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestExpirePlaygrounds.cls
@IsTest
private with sharing class TestExpirePlaygrounds {
    @TestSetup
    static void makeData() {
        Account account = new Account(Name = 'Test Account 1');
        insert account;

        Contact contactOne = new Contact(FirstName = 'John', LastName = 'Doe', Email = 'john.doe@copado.com', AccountId = account.Id);
        Contact contactTwo = new Contact(FirstName = 'Jen', LastName = 'Doe', Email = 'jen.doe@copado.com', AccountId = account.Id);
        Contact contactThree = new Contact(FirstName = 'Peter', LastName = 'Graph', Email = 'pete.graph@copado.com', AccountId = account.Id);

        insert new List<Contact>{ contactOne, contactTwo, contactThree };
    }

    @IsTest
    static void testPlaygroundExpirationBatch() {
        Id johnId;
        Id jenId;
        Id peteId;
        for (Contact contactItem : [SELECT Id, Email FROM Contact WHERE Account.Name = 'Test Account 1']) {
            switch on contactItem.Email {
                when 'john.doe@copado.com' {
                    johnId = contactItem.Id;
                }
                when 'jen.doe@copado.com' {
                    jenId = contactItem.Id;
                }
                when 'pete.graph@copado.com' {
                    peteId = contactItem.Id;
                }
            }
        }

        Signup_Request__c signupReqOne = new Signup_Request__c();
        signupReqOne.First_Name__c = 'John';
        signupReqOne.Last_Name__c = 'Doe';
        signupReqOne.Company__c = 'Copado, Inc.';
        signupReqOne.Country__c = 'US';
        signupReqOne.Email__c = 'john.doe@copado.com';
        signupReqOne.Username__c = 'jon.doe@copado.com.test';
        signupReqOne.Template__c = '0TT1i00000269iK';

        Signup_Request__c signupReqTwo = new Signup_Request__c();
        signupReqTwo.First_Name__c = 'Jen';
        signupReqTwo.Last_Name__c = 'Doe';
        signupReqTwo.Company__c = 'Copado, Inc.';
        signupReqTwo.Country__c = 'US';
        signupReqTwo.Email__c = 'jen.doe@copado.com';
        signupReqTwo.Username__c = 'jen.doe@copado.com.test';
        signupReqTwo.Template__c = '0TT1i00000269iK';

        Signup_Request__c signupReqThree = new Signup_Request__c();
        signupReqThree.First_Name__c = 'Peter';
        signupReqThree.Last_Name__c = 'Graph';
        signupReqThree.Company__c = 'Copado, Inc.';
        signupReqThree.Country__c = 'US';
        signupReqThree.Email__c = 'pete.gr@copado.com';
        signupReqThree.Username__c = 'pete.gr@copado.coom.test';
        signupReqThree.Template__c = '0TT1i00000269iK';

        insert new List<Signup_Request__c>{ signupReqOne, signupReqTwo, signupReqThree };

        Test.setCreatedDate(signupReqOne.Id, DateTime.newInstance(2018, 12, 12));
        Test.setCreatedDate(signupReqTwo.Id, DateTime.newInstance(2018, 12, 12));

        Playground__c playGroundOne = new Playground__c();
        playGroundOne.Name = 'John Playground';
        playGroundOne.Contact__c = johnId;
        playGroundOne.Custom_Signup_Request__c = signupReqOne.Id;

        Playground__c playGroundTwo = new Playground__c();
        playGroundTwo.Name = 'Jen Playground';
        playGroundTwo.Contact__c = jenId;
        playGroundTwo.Custom_Signup_Request__c = signupReqTwo.Id;

        Playground__c playGroundThree = new Playground__c();
        playGroundThree.Name = 'Pete Playground';
        playGroundThree.Contact__c = peteId;
        playGroundThree.Custom_Signup_Request__c = signupReqThree.Id;

        insert new List<Playground__c>{ playGroundOne, playGroundTwo, playGroundThree };

        Test.startTest();
        List<Playground__c> testPlaygrounds = [
            SELECT Id, Name, Status__c, Custom_Signup_Request__r.Is_Expired__c, Custom_Signup_Request__r.CreatedDate
            FROM Playground__c
        ];

        for (Playground__c playGroundItem : testPlaygrounds) {
            switch on playGroundItem.Name {
                when 'John Playground' {
                    System.assertNotEquals('Expired', playGroundItem.Status__c, 'Status must be different from "Expired"');
                    System.assertEquals(true, playGroundItem.Custom_Signup_Request__r.Is_Expired__c);
                }
                when 'Jen Playground' {
                    System.assertNotEquals('Expired', playGroundItem.Status__c, 'Status must be different from "Expired"');
                    System.assertEquals(true, playGroundItem.Custom_Signup_Request__r.Is_Expired__c);
                }
                when 'Pete Playground' {
                    System.assertNotEquals('Expired', playGroundItem.Status__c, 'Status must be different from "Expired"');
                    System.assertEquals(false, playGroundItem.Custom_Signup_Request__r.Is_Expired__c);
                }
            }
        }

        ExpiredPlaygroundsBatch expiredPlaygrounds = new ExpiredPlaygroundsBatch();
        database.executebatch(expiredPlaygrounds, 200);

        Test.stopTest();

        testPlaygrounds = [SELECT Id, Name, Status__c, Custom_Signup_Request__r.Is_Expired__c FROM Playground__c];
        for (Playground__c playGroundItem : testPlaygrounds) {
            switch on playGroundItem.Name {
                when 'John Playground' {
                    System.assertEquals('Expired', playGroundItem.Status__c, 'Status must be "Expired"');
                    System.assertEquals(true, playGroundItem.Custom_Signup_Request__r.Is_Expired__c);
                }
                when 'Jen Playground' {
                    System.assertEquals('Expired', playGroundItem.Status__c, 'Status must be "Expired"');
                    System.assertEquals(true, playGroundItem.Custom_Signup_Request__r.Is_Expired__c);
                }
                when 'Pete Playground' {
                    System.assertNotEquals('Expired', playGroundItem.Status__c, 'Status must be different from "Expired"');
                    System.assertEquals(false, playGroundItem.Custom_Signup_Request__r.Is_Expired__c);
                }
            }
        }
    }

    @IsTest
    static void testPlaygroundExpirationSchdulable() {
        Test.startTest();
        String strCrnExp = Datetime.now().addSeconds(5).format('s m H d M ? yyyy');
        String jobId = System.schedule('testScheduleExpiredPlaygrounds', strCrnExp, new ExpiredPlaygroundsSchedulable());
        Test.stopTest();
        CronTrigger cronTrigger = [SELECT Id FROM CronTrigger WHERE id = :jobId];
        System.assertNotEquals(null, cronTrigger, 'Cron is not created properly');
    }
}