objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Demo__c.object
<CustomObject>
    <description>This object keeps all the information related to Demos.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Demos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Demo_outcome__c</fullName>
        <label>Meeting outcome</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>PS_Consumed_Time__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Professional Services Consumed Time</description>
        <inlineHelpText>Professional Services Consumed Time In Hours</inlineHelpText>
        <label>PS Consumed Time</label>
        <precision>5</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting response</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Re-scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Call</fullName>
                </value>
                <value>
                    <fullName>Technical Demo</fullName>
                </value>
                <value>
                    <fullName>Trial Meeting</fullName>
                </value>
                <value>
                    <fullName>InfoSec</fullName>
                </value>
                <value>
                    <fullName>Onboarding Call</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Check-in Call</fullName>
                </value>
                <value>
                    <fullName>Renewal Call</fullName>
                </value>
                <value>
                    <fullName>Business Review</fullName>
                </value>
                <value>
                    <fullName>Support Call</fullName>
                </value>
                <value>
                    <fullName>Partner Meeting</fullName>
                </value>
                <value>
                    <fullName>Time Logging</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>Essentials</fullName>
                </value>
                <value>
                    <fullName>PoC</fullName>
                    <isActive>false</isActive>
                    <label>PoC</label>
                </value>
                <value>
                    <fullName>Setup Call</fullName>
                    <isActive>false</isActive>
                    <label>Setup Call</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Professional_Service_Consumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Professional Service Consumption</relationshipLabel>
        <relationshipName>Professional_Service_Consumption</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours_consumed__c</fullName>
        <label>Hours consumed</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meeting_Date__c</fullName>
        <description>When were the professional services given</description>
        <label>Meeting Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Meeting_Id__c</fullName>
        <externalId>true</externalId>
        <label>Meeting Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Meeting_Notes__c</fullName>
        <label>Meeting Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Professional Service Consumption</label>
    <nameField>
        <displayFormat>PSC-{00000}</displayFormat>
        <label>Professional Service Consumption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Professional Service Consumption</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MeetingTriggerHelper.cls
public class MeetingTriggerHelper {
	private static List<Demo__c> meetingList = new List<Demo__c>();
	private static List<Professional_Service_Consumption__c> professionalServicesConsumptionList 
	= new List<Professional_Service_Consumption__c>();   

	public static void prepareMeetingToMap(){
		if (Trigger.isDelete) return;
		for (SObject newMeeting : Trigger.new){
			Demo__c meeting = (Demo__c)newMeeting;
			meetingList.add(meeting);
		}
		professionalServicesConsumptionsToCreate();
	}

	public static void professionalServicesConsumptionsToCreate(){
		for (Demo__c m : meetingList){
			if (m.Account__c != null && m.PS_Consumed_Time__c != null && m.Status__c =='Completed'
				&& m.Type__c =='Professional Services' && m.Date__c != null){
				Professional_Service_Consumption__c psc = new Professional_Service_Consumption__c();
				psc.Account__c = m.Account__c;
				psc.Hours_consumed__c = m.PS_Consumed_Time__c;
				psc.Meeting_Id__c = m.id;
				psc.Meeting_Date__c =m.Date__c;
				psc.Meeting_Notes__c=m.Demo_outcome__c;
				professionalServicesConsumptionList.add(psc);
			}
		}
	}

	public static void insertProfessionalServicesConsumptions(){
		if(professionalServicesConsumptionList.size()>0){
			upsert professionalServicesConsumptionList Meeting_Id__c;
		}
	}

}