objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Key_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The org to which the contract is applied.</inlineHelpText>
        <label>Salesforce Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (for Salesforce Org)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__KugamonSetting__c.object
<CustomObject>
    <description>Kugamon - Main object that controls Kugamon application behavior. Only one Kugamon Settings record is allowed. For Admin use only.</description>
    <label>Kugamon Setting</label>
    <nameField>
        <label>Kugamon Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kugamon Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Generic External Id for data migration purposes</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameter__c.object
<CustomObject>
    <description>A custom object for storing feature parameters.  A new record is created of this object for every feature parameter that is ADDED as part of an uploaded package version. This record is automatically created upon the first package install of that package version.</description>
    <label>Feature Parameter</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Feature Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameterInteger__c.object
<CustomObject>
    <description>Custom object that is part of FMA for storing Feature Parameter Overrides for integers

A new record is created of this object for every feature parameter that is ADDED as part of a package install in an org. This record is automatically created upon every package install.

The Feature Parameter object serves as an index.</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Value will be set to 0 when expired</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <formula>sfFma__License__r.Salesforce_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__FeatureParameter__c</fullName>
        <description>The parent Feature Parameter object.</description>
        <label>Feature Parameter</label>
        <referenceTo>sfFma__FeatureParameter__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sfFma__Value__c</fullName>
        <label>Feature Parameter Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature Parameter Integer</label>
    <nameField>
        <displayFormat>FPI-{0000}</displayFormat>
        <label>Feature Parameter Integer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameter Integers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Expiration__c</fullName>
        <description>Expiration Date of the License, 1/1/1970 represents a perpetual license</description>
        <label>Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>sfLma__Package__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__Package__c.object
<CustomObject>
    <description>A Package Object represents information about the package as it is defined in the developer&apos;s Salesforce Organization. A record is created or updated each time a new version of the package is uploaded to AppExchange.</description>
    <fields>
        <fullName>sfLma__Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestAccountFeatureManagerController.cls
@isTest
private class TestAccountFeatureManagerController {
    
    @isTest static void testAFMC() {
        Account acc = TestDataFactory.createAccount('Fake needed acc', 'EUR');
        insert acc;
        
        Contact con = TestDataFactory.createContact(acc.id,'Fakecon');
        insert con;
        
        Salesforce_Org__c org = TestDataFactory.createSalesforceOrg('Test Method Org');
        org.OrgId__c = '00D1l0000000dkE';
        insert org;
        
        sfLma__License__c lic = TestDataFactory.createLicense(org.Id,5);
        lic.sfLma__Subscriber_Org_ID__c = '00D1l0000000dkE';
        lic.sfLma__Expiration__c = Date.today()+1;
        insert lic;
        
        sfLma__Package__c pack = TestDataFactory.craetePackage('Copado Deployer');
        pack.sfLma__Developer_Name__c = 'Copado BasePackage';
        insert pack;
        
        sfFma__FeatureParameter__c fpCCM = TestDataFactory.createFeatureParameter('copado__CCM_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        insert fpCCM;
        
        sfFma__FeatureParameter__c fpCAD = TestDataFactory.createFeatureParameter('copado__CAD_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        insert fpCAD;
        sfFma__FeatureParameter__c fpCCH = TestDataFactory.createFeatureParameter('copado__CCH_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
           
        insert fpCCH;
        sfFma__FeatureParameter__c fpCSTL = TestDataFactory.createFeatureParameter('copado__CST_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
         
        insert fpCSTL;
        sfFma__FeatureParameter__c fpEE =  TestDataFactory.createFeatureParameter('copado__EE_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        
        insert fpEE;
        sfFma__FeatureParameter__c fpCSTM =  TestDataFactory.createFeatureParameter('copado__CST_Minutes_Packages',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        insert fpCSTM;
        sfFma__FeatureParameter__c fpCBM = TestDataFactory.createFeatureParameter('copado__CBM_Branches',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
          
        insert fpCBM;
        
        //CCM Feature Parameter
        sfFma__FeatureParameterInteger__c fpi = TestDataFactory.createFeatureParameterInteger('copado__CCM_Licenses_Enabled',lic.Id, fpCCM.Id);   
        fpi.External_Id__c = org.Id + '_' + 'copado__CCM_Licenses_Enabled';
        fpi.Expiration_Date__c = null;
        fpi.sfFma__Value__c = 0;
        insert fpi;
        
        //CAD Feature Parameter
        fpi = TestDataFactory.createFeatureParameterInteger('copado__CAD_Licenses_Enabled',lic.Id, fpCAD.Id);
        fpi.External_Id__c = org.Id + '_' + 'copado__CAD_Licenses_Enabled';
        fpi.Expiration_Date__c = null;
        fpi.sfFma__Value__c = 0;
        insert fpi;
        
        //CCH Feature Parameter
        fpi = TestDataFactory.createFeatureParameterInteger('copado__CCH_Licenses_Enabled',lic.Id, fpCCH.Id);
            fpi.External_Id__c = org.Id + '_' + 'copado__CCH_Licenses_Enabled';
            fpi.Expiration_Date__c = null;
            fpi.sfFma__Value__c = 0;
        insert fpi;
        
        //CST Licenses Feature Parameter
        fpi = TestDataFactory.createFeatureParameterInteger('copado__CST_Licenses_Enabled',lic.Id, fpCSTL.Id);
        fpi.External_Id__c = org.Id + '_' + 'copado__CST_Licenses_Enabled';
        fpi.Expiration_Date__c = null;
        fpi.sfFma__Value__c = 0;
        insert fpi;
        
        //EE Licenses Feature Parameter
        fpi = TestDataFactory.createFeatureParameterInteger('copado__EE_Licenses_Enabled',lic.Id, fpEE.Id);
        fpi.External_Id__c = org.Id + '_' + 'copado__EE_Licenses_Enabled';
        fpi.Expiration_Date__c = null;
        fpi.sfFma__Value__c = 0;
        insert fpi;
        
        //CST Minutes Packages Feature Parameter
        fpi = TestDataFactory.createFeatureParameterInteger('copado__CST_Minutes_Packages',lic.Id, fpCSTM.Id);
        fpi.External_Id__c = org.Id + '_' + 'copado__CST_Minutes_Packages';
        fpi.Expiration_Date__c = null;
        fpi.sfFma__Value__c = 0;
        insert fpi;
        
        //CBM Licenses Feature Parameter
        fpi = TestDataFactory.createFeatureParameterInteger('copado__CBM_Branches',lic.Id, fpCBM.Id);
            fpi.External_Id__c = org.Id + '_' + 'copado__CBM_Branches';
            fpi.Expiration_Date__c = null;
            fpi.sfFma__Value__c = 0;
        insert fpi;
        Test.startTest();
        
        Id pricebookId = Test.getStandardPricebookId();  
        Pricebook2 p2 = TestDataFactory.createPricebook(); 
        p2.CurrencyIsoCode = 'EUR';
        insert p2; 
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(p2.name); 
        insert testKugamonSetting ;
        
        Contract cont = TestDataFactory.createDraftContract(acc.Id, acc.CurrencyIsoCode);
        cont.Key_Contact__c = con.Id;
        cont.StartDate = Date.today()-1;
        cont.ContractTerm = 12;
        insert cont;
        
        AccountFeatureManagerController controller  = new AccountFeatureManagerController(new ApexPages.StandardController(org));
        System.assert(!testMethodUtilities.hasMessage('This org does not have a contract.'));
        
        controller.getorgFeatures();
        System.assertEquals(7, controller.orgFeatures.size());
        
        controller.updateorgFeatures();
        
        Test.stopTest();
    }
    
    @isTest static void testWithoutContract() {
        
        Salesforce_Org__c org = TestDataFactory.createSalesforceOrg('I have no contract!');
        insert org;
        
        Test.startTest();
        
        AccountFeatureManagerController controller = new AccountFeatureManagerController(new ApexPages.StandardController(org));
        System.assert(testMethodUtilities.hasMessage('This org does not have an activated contract.'));
        
        Test.stopTest();
    }
}