objects/Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Test Profile</label>
</CustomObject>

objects/Demo__c.object
<CustomObject>
    <description>This object keeps all the information related to Demos.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Demos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Demos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Account)</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Step__c</fullName>
        <inlineHelpText>This field does not get mapped to the opportunity.</inlineHelpText>
        <label>Next Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/AutoConvertLead.cls
public class AutoConvertLead {

	@InvocableMethod
	public static void AutoConvertLeadsApex(List<Id> MeetingIds) {

        LeadStatus CLeadStatus= [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = true LIMIT 1];

        List<Database.LeadConvert> MassLeadconvert = new List<Database.LeadConvert>();

        List<Demo__c> Lmeetings = [SELECT Id, Lead__c, Account__c FROM Demo__c WHERE Id IN :MeetingIds];
        List<Id> LeadsId = new List<Id>();
        List<Opportunity> OpportunityToUpdate = new List<Opportunity>();

        for(Demo__c meeting: Lmeetings) {
            Database.LeadConvert Leadconvert = new Database.LeadConvert();
            Leadconvert.setLeadId(meeting.Lead__c);
            LeadsId.add(Leadconvert.getLeadID()); 
            if (meeting.Account__c != null) { 
                Leadconvert.setAccountId(meeting.Account__c);
            }           
            Leadconvert.setConvertedStatus(CLeadStatus.MasterLabel);
            Leadconvert.setDoNotCreateOpportunity(FALSE);
            MassLeadconvert.add(Leadconvert);
        }
        
        if (!MassLeadconvert.isEmpty()) {
            List<Database.LeadConvertResult> lcr = Database.convertLead(MassLeadconvert);

            for (Lead l : [SELECT Id, Description, Next_Step__c, ConvertedOpportunityId 
                                                        FROM Lead WHERE Id IN :LeadsId]){
                Opportunity Opp = new Opportunity(
                                                Id = l.ConvertedOpportunityId, 
                                                NextStep = l.Next_Step__c, 
                                                Description = l.Description,
                                                Main_Problems__c = 'Opportunity from Demo'
                                                );
                OpportunityToUpdate.add(Opp);
            }
            update OpportunityToUpdate;
        }
    }
}