objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Psydo_Case__c.object
<CustomObject>
    <description>This is a trigger object to insert/update the actual data</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseComment__c</fullName>
        <label>CaseComment</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Psydo Case</label>
    <nameField>
        <displayFormat>PC{00000}</displayFormat>
        <label>Public Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Psydo Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPsydoCaseTrigger.cls
@isTest
private class TestPsydoCaseTrigger {
	static testMethod void runTest_WITH_Comments(){
		Account testAccount = testMethodUtilities.createAccount('TestMethodCopadoTestMethod', '123orgId123');
        Contact testContact = testMethodUtilities.createContact(testAccount.Id,'Mark','Benioff','ceo@salesforce.com', '123userId123');
        Case testCase = new Case(AccountId=testAccount.Id, ContactId=testContact.Id);
        testCase.Subject = 'test subject';
        testCase.Description = 'My Description';
        testCase.Origin = 'Email';
        testCase.Status = 'New';
        testCase.Type = 'Question';
		testCase.Priority = 'High';
		insert testCase;

		String caseNumber = [select Id, CaseNumber from Case where Id=:testCase.Id limit 1].CaseNumber;

		Psydo_Case__c pc = new Psydo_Case__c(Record_Id__c=testCase.Id);
		pc.Status__c = 'Closed';
		pc.Action__c = 'Update';
		pc.CaseComment__c = 'My Comment';
		Test.startTest();
		insert pc;
		Test.stopTest();
		Case result = [select Id, Status from Case where Id=:testCase.Id limit 1];
		List<CaseComment> ccsResult = [select Id, ParentId, CommentBody from CaseComment where ParentId=:result.Id];
		system.assertEquals(1, ccsResult.size());
		system.assertEquals('Closed', result.Status);
	}
	static testMethod void runTest_WITHOUT_Comments(){
		Account testAccount = testMethodUtilities.createAccount('TestMethodCopadoTestMethod', '123orgId123');
        Contact testContact = testMethodUtilities.createContact(testAccount.Id,'Mark','Benioff','ceo@salesforce.com', '123userId123');
        Case testCase = new Case(AccountId=testAccount.Id, ContactId=testContact.Id);
        testCase.Subject = 'test subject';
        testCase.Description = 'My Description';
        testCase.Origin = 'Email';
        testCase.Status = 'New';
        testCase.Type = 'Question';
		testCase.Priority = 'High';
		insert testCase;

		String caseNumber = [select Id, CaseNumber from Case where Id=:testCase.Id limit 1].CaseNumber;

		Psydo_Case__c pc = new Psydo_Case__c(Record_Id__c=testCase.Id);
		pc.Status__c = 'Closed';
		pc.Action__c = 'Update';
		pc.CaseComment__c = null;
		Test.startTest();
		insert pc;
		Test.stopTest();
		Case result = [select Id, Status from Case where Id=:testCase.Id limit 1];
		List<CaseComment> ccsResult = [select Id, ParentId, CommentBody from CaseComment where ParentId=:result.Id];
		system.assertEquals(0, ccsResult.size());
		system.assertEquals('Closed', result.Status);
	}
	static testMethod void testUnusedMethods(){
		Account testAccount = testMethodUtilities.createAccount('TestMethodCopadoTestMethod', '123orgId123');
        Contact testContact = testMethodUtilities.createContact(testAccount.Id,'Mark','Benioff','ceo@salesforce.com', '123userId123');
        Case testCase = new Case(AccountId=testAccount.Id, ContactId=testContact.Id);
        testCase.Subject = 'test subject';
        testCase.Description = 'My Description';
        testCase.Origin = 'Email';
        testCase.Status = 'New';
        testCase.Type = 'Question';
		testCase.Priority = 'High';
		insert testCase;
		Psydo_Case__c pc = new Psydo_Case__c(Record_Id__c=testCase.Id);
		insert pc;
		Test.startTest();
		update pc;
		delete pc;
		undelete pc;
		Test.stopTest();
	}
}