objects/CHANNEL_ORDERS__Customer__c.object
<CustomObject>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Org ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CHANNEL_ORDERS__Partner_Contract_Terms__c.object
<CustomObject>
    <label>Partner Contract Terms</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Contract Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CHANNEL_ORDERS__Partner_Product_Catalog__c.object
<CustomObject>
    <fields>
        <fullName>CHANNEL_ORDERS__Partner_Contract_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Contract Terms</label>
        <referenceTo>CHANNEL_ORDERS__Partner_Contract_Terms__c</referenceTo>
        <relationshipLabel>Partner Product Catalog</relationshipLabel>
        <relationshipName>Partner_Product_Catalog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Product Catalog</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Product Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CHANNEL_ORDERS__Service_Order__c.object
<CustomObject>
    <fields>
        <fullName>CHANNEL_ORDERS__Created_with_new_COA__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This represents the Service Order record being created with a COA version higher than 1.17.</description>
        <label>Created with new COA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_Org_ID__c</fullName>
        <inlineHelpText>Please note that Org IDs are case sensitive.</inlineHelpText>
        <label>Org ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <referenceTo>CHANNEL_ORDERS__Customer__c</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Service_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Order_Type__c</fullName>
        <description>We want to show the user the field Order_Type_Formula__c  instead of this one</description>
        <label>Order Type Internal</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initial</fullName>
                </value>
                <value>
                    <fullName>Add-On</fullName>
                </value>
                <value>
                    <fullName>Reduction</fullName>
                </value>
                <value>
                    <fullName>Cancellation Order</fullName>
                </value>
                <value>
                    <fullName>Upgrade - Partner App</fullName>
                </value>
                <value>
                    <fullName>Upgrade - Org Edition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Partner_Contract_Rules__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>CHANNEL_ORDERS__Partner_Contract_Terms__c</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Service_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Service_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Service_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Order</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Custom_Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The org to which the contract is applied.</inlineHelpText>
        <label>Salesforce Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (for Salesforce Org)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__KugamonSetting__c.object
<CustomObject>
    <description>Kugamon - Main object that controls Kugamon application behavior. Only one Kugamon Settings record is allowed. For Admin use only.</description>
    <label>Kugamon Setting</label>
    <nameField>
        <label>Kugamon Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kugamon Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__UnproratedNetPrice__c</fullName>
        <description>The full-term Net Unit Price.</description>
        <inlineHelpText>The full term net price for individual line.</inlineHelpText>
        <label>Full-Term Net Unit Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Opportunity that is in question, as it related to this org. This will be used by Sales Engineers for Orgs that are spun for trial purposes to win an opportunity.</description>
        <inlineHelpText>Link to the opportunity related to this org.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Salesforce Orgs</relationshipLabel>
        <relationshipName>Salesforce_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Corporate Entity to which the Salesforce Org is related.</description>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salesforce Orgs</relationshipLabel>
        <relationshipName>Salesforce_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestContractOrderExtension.cls
@isTest
public class TestContractOrderExtension {
    static testMethod void validateErrorNoOrg(){
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 p2 = new Pricebook2(Name='Test', CurrencyIsoCode='EUR', IsActive=true);
        insert p2;
        
        Account ca = TestDataFactory.createAccount('Copado Solutions SL','EUR');
        ca.Billing_Name__c='Copado Solutions SL';
        ca.BillingStreet='Avenida de Valdemarin 140, Bajo C';
        ca.BillingCity='Madrid'; 
        ca.BillingState='Madrid'; 
        ca.BillingPostalCode='28023'; 
        ca.BillingCountry='ES';
        insert ca;
        
        Opportunity o = TestDataFactory.createOpportunity(ca, 'My Opp', 'New Customer');
        o.AccountId=ca.Id;
        o.CloseDate=Date.today();
        o.Main_Problems__c = 'Opp Main problem';
        o.Amount = 100;
        o.LeadSource='Customer';
        insert o;
        
        kugo2p__KugamonSetting__c testKugamonSetting = testMethodUtilities.createKugamonSetting(p2.name);
        
       	Contract c = TestDataFactory.createDraftContract(ca.Id,ca.CurrencyIsoCode);
        c.StartDate=Date.today();
        insert c;
        
        order testOrder = TestDataFactory.createOrder(ca.Id,c,p2,Date.today(),Date.today().addYears(1).addDays(-1));
        testOrder.Status='Draft';
        testOrder.OpportunityId = o.Id;
        insert testOrder;
        
        ContractOrderExtension ext = new ContractOrderExtension(new ApexPages.StandardController(testOrder));
        ext.init();
        System.assert(testMethodUtilities.hasMessage('You must add a Salesforce Org to the order before proceeding.'));
    }
    
    static testMethod void fullTest_withCreateCustomer(){
        User usAdmin = TestDataFactory.getAdminUser();
        System.runAs(usAdmin){
            System.debug('### fullTest_withCreateCustomer');
            Id pricebookId = Test.getStandardPricebookId();
            Pricebook2 p2 = new Pricebook2(Name='Test', CurrencyIsoCode='EUR', IsActive=true);
            insert p2;
            
            Product2 p = TestDataFactory.createProduct('My Test', 'Membership fees', null);
            insert p;
            
            PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=p.Id, UnitPrice=5, IsActive=true,CurrencyIsoCode='EUR');
            insert standardPrice;
            
            PricebookEntry customPrice = new PricebookEntry(Pricebook2Id=p2.Id, Product2Id=p.Id, UnitPrice=5, IsActive=true,CurrencyIsoCode='EUR');
            insert customPrice;
            
            CHANNEL_ORDERS__Partner_Contract_Terms__c sfdcContract = TestDataFactory.createPartnerContractTerms('Ltd*_ISVForce_EUR2');
            insert sfdcContract;
            
            CHANNEL_ORDERS__Partner_Product_Catalog__c soli1=  TestDataFactory.createPartnerProductCatalog('EE license',sfdcContract.Id);
            insert soli1;
            p.Partner_Product_Catalog__c = soli1.Id;
            update p;
            
            Account ca = TestDataFactory.createAccount('Copado Solutions SL','EUR');
            ca.Billing_Name__c='Copado Solutions SL';
            ca.BillingStreet='Avenida de Valdemarin 140, Bajo C';
            ca.BillingCity='Madrid'; 
            ca.BillingState='Madrid'; 
            ca.BillingPostalCode='28023'; 
            ca.BillingCountry='ES';
            insert ca;
            
            Salesforce_Org__c sa = new Salesforce_Org__c(Name='ProductionOrg', Parent_Account__c=ca.Id, OrgId__c='00Db0000000IH73');
            insert sa;
            
            Opportunity o = TestDataFactory.createOpportunity(ca, 'My Opp', 'New Customer');
            o.AccountId=ca.Id;
            o.CloseDate=Date.today();
            o.Main_Problems__c = 'Opp Main problem';
            o.Amount = 100;
            o.LeadSource='Customer';
            insert o;
            
            OpportunityLineItem oli = TestDataFactory.createOpportunityLineItem(o.Id,customPrice.Id);
            insert oli;
            
            List<OpportunityLineItemSchedule> newOliSchedules = new List<OpportunityLineItemSchedule>();
            for(Integer i=0; i<p.NumberOfRevenueInstallments; i++){
                OpportunityLineItemSchedule oliSchedule = new OpportunityLineItemSchedule(OpportunityLineItemId=oli.Id, Type='Revenue');
                oliSchedule.ScheduleDate = oli.ServiceDate.addMonths(i);
                oliSchedule.Revenue = customPrice.UnitPrice * oli.Quantity;
                newOliSchedules.add(oliSchedule);
            }
            insert newOliSchedules;
            
            kugo2p__KugamonSetting__c testKugamonSetting = testMethodUtilities.createKugamonSetting(p2.name);
            
            Contract c = TestDataFactory.createDraftContract(ca.Id,ca.CurrencyIsoCode);
            c.StartDate=Date.today();
            c.Custom_Salesforce_Org__c=sa.Id;
            c.Opportunity__c=o.Id;
            insert c;
            
            order testOrder = TestDataFactory.createOrder(ca.Id,c,p2,Date.today(),Date.today().addYears(1).addDays(-1));
            testOrder.Status='Draft';
            testOrder.OpportunityId = o.Id;
            testOrder.Custom_Salesforce_Org__c = sa.Id;
            insert testOrder;
            
            orderItem oi = TestDataFactory.createOrderItem(customPrice,testOrder.Id,oli.Quantity,oli.UnitPrice);
            oi.SBQQ__UnproratedNetPrice__c = 5.48;
            insert oi;
            
            ApexPages.StandardController sc = new ApexPages.StandardController(testOrder);
            ContractOrderExtension ext = new ContractOrderExtension(sc);
            ext.init();
            PageReference pageRef = ext.createOrder();
            
            List<CHANNEL_ORDERS__Customer__c> custs = [SELECT Id, CHANNEL_ORDERS__Customer_Org_ID__c FROM CHANNEL_ORDERS__Customer__c WHERE CHANNEL_ORDERS__Customer_Org_ID__c=:sa.OrgId__c.substring(0,15)];
            System.assertEquals(1, custs.size());
            
            CHANNEL_ORDERS__Partner_Contract_Terms__c testOrderPartnerContractTerm = new CHANNEL_ORDERS__Partner_Contract_Terms__c();
            insert testOrderPartnerContractTerm;
            
            CHANNEL_ORDERS__Service_Order__c  testChannelOrderServiceOrder =TestDataFactory.createChannelOrdersServiceOrder();
            testChannelOrderServiceOrder.CHANNEL_ORDERS__Customer_Org_ID__c=sa.OrgId__c;
            testChannelOrderServiceOrder.CHANNEL_ORDERS__Customer__c=custs[0].Id;
            testChannelOrderServiceOrder.CHANNEL_ORDERS__Created_with_new_COA__c=true;
            testChannelOrderServiceOrder.CHANNEL_ORDERS__Partner_Contract_Rules__c = sfdcContract.Id;
            testChannelOrderServiceOrder.CHANNEL_ORDERS__Order_Type__c = 'Initial';
            insert testChannelOrderServiceOrder;
            
            List<CHANNEL_ORDERS__Service_Order__c> result = [SELECT Id, Name, Contract__c, CHANNEL_ORDERS__Customer__c, CurrencyIsoCode, CHANNEL_ORDERS__Created_with_new_COA__c, CHANNEL_ORDERS__Customer_Org_ID__c, CHANNEL_ORDERS__Order_Type__c FROM CHANNEL_ORDERS__Service_Order__c WHERE Order__c=:testOrder.Id];
            System.assertEquals(1, result.size(), 'Service Order Size');
            System.assertEquals(true, result[0].CHANNEL_ORDERS__Created_with_new_COA__c);
            System.assertEquals(sa.OrgId__c, result[0].CHANNEL_ORDERS__Customer_Org_ID__c);
            System.assertEquals(custs[0].Id, result[0].CHANNEL_ORDERS__Customer__c);
        }
    }
    
    static testMethod void testConvertedCurrency(){
        Salesforce_Org__c sa = new Salesforce_Org__c(Name='ProductionOrg', OrgId__c='00Db0000000IH73');
        insert sa;
        
        ContractOrderExtension ext = new ContractOrderExtension(new ApexPages.StandardController(new Order(Custom_Salesforce_Org__c=sa.Id)));
        ext.init();
        
        List<CurrencyType> result = ext.getCurrencyRates();
        System.assertEquals(2, result.size());
        
        Double eur = ext.getConvertedAmount('GBP', Double.valueOf(9027.0));
        System.assertEquals(10620.0, eur);
    }
}