objects/CHANNEL_ORDERS__Customer__c.object
<CustomObject>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_Company_Name__c</fullName>
        <label>Company Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Org ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_State__c</fullName>
        <label>State/Province/Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_ZIP_Postal_Code__c</fullName>
        <label>ZIP/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CHANNEL_ORDERS__Partner_Product_Catalog__c.object
<CustomObject>
    <fields>
        <fullName>CHANNEL_ORDERS__Billing_Frequency__c</fullName>
        <description>Controls the frequency in which this Product is Billed, unit is Months.</description>
        <label>Billing Frequency</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Cancellation_Terms__c</fullName>
        <description>Controls the Cancellation time for this Product, unit is Days.</description>
        <label>Cancellation Terms (Days)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Contract_Auto_Renew__c</fullName>
        <description>Controls if a contract for this product is Auto Renewed or not.</description>
        <label>Contract Auto Renew</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Contract_Length__c</fullName>
        <description>Controls the length of a contract for this Product, unit is Months.</description>
        <label>Contract Length</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Custom_Unit__c</fullName>
        <description>Represents the custom unit value when Pricing Unit is set to &apos;Custom&apos;.</description>
        <label>Custom Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Fixed_Price__c</fullName>
        <label>Fixed Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Floor_Price__c</fullName>
        <label>Floor Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__PNR__c</fullName>
        <label>PNR %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Partner_Contract_Terms__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Contract Terms</label>
        <referenceTo>CHANNEL_ORDERS__Partner_Contract_Terms__c</referenceTo>
        <relationshipLabel>Partner Product Catalog</relationshipLabel>
        <relationshipName>Partner_Product_Catalog</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Pricing_Type__c</fullName>
        <label>Pricing Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PNR</fullName>
                </value>
                <value>
                    <fullName>FIXED</fullName>
                </value>
                <value>
                    <fullName>LIST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Pricing_Unit__c</fullName>
        <description>Represents the unit used by the Partner to sell this product.</description>
        <label>Pricing Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Org</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Product_ID__c</fullName>
        <label>Product ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Renewal_Terms__c</fullName>
        <description>Represents the length of a renewed contract for this product, unit is Months.</description>
        <label>Renewal Terms (Months)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Product Catalog</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Product Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CHANNEL_ORDERS__Service_Order__c.object
<CustomObject>
    <fields>
        <fullName>CHANNEL_ORDERS__Billing_Frequency__c</fullName>
        <label>Billing Frequency</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Contract_Length__c</fullName>
        <inlineHelpText>Length of Contract (In Months).  If your contract does not allow you to override the default Contract Length policy, this field should be left blank.</inlineHelpText>
        <label>Contract Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Created_with_new_COA__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This represents the Service Order record being created with a COA version higher than 1.17.</description>
        <label>Created with new COA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer_Org_ID__c</fullName>
        <inlineHelpText>Please note that Org IDs are case sensitive.</inlineHelpText>
        <label>Org ID</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name</label>
        <referenceTo>CHANNEL_ORDERS__Customer__c</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Service_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Date_Partner_Received_Customer_Order__c</fullName>
        <label>Date Partner Received Customer Order</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Renewal_Terms__c</fullName>
        <label>Renewal Terms (Months)</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Service Orders</relationshipLabel>
        <relationshipName>Service_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Order</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Service Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CHANNEL_ORDERS__Service_Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>CHANNEL_ORDERS__Fixed_Price__c</fullName>
        <description>Field retired in Channel Order App v2.0. Use CHANNEL_ORDERS__pc_Fixed_Price__c instead.</description>
        <formula>if( CHANNEL_ORDERS__Pricing_Type__c = &quot;PNR&quot;, &quot; &quot;,

if (round(CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Fixed_Price__c,0) = CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Fixed_Price__c, text(CHANNEL_ORDERS__Partner_Order__r.CHANNEL_ORDERS__Partner_Contract_Rules__r.CHANNEL_ORDERS__Default_Contract_Currency__c) &amp; &quot; &quot; &amp; text(CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Fixed_Price__c) &amp; &quot;.00&quot;, 

text(CHANNEL_ORDERS__Partner_Order__r.CHANNEL_ORDERS__Partner_Contract_Rules__r.CHANNEL_ORDERS__Default_Contract_Currency__c) &amp; &quot; &quot; &amp; text(CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Fixed_Price__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fixed Price (deprecated)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Floor_Price__c</fullName>
        <description>Field retired in Channel Order App v2.0.</description>
        <formula>if( CHANNEL_ORDERS__Pricing_Type__c = &quot;FIXED&quot;, &quot; &quot;,

if (round(CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Floor_Price__c,0) = CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Floor_Price__c, text(CHANNEL_ORDERS__Partner_Order__r.CHANNEL_ORDERS__Partner_Contract_Rules__r.CHANNEL_ORDERS__Default_Contract_Currency__c) &amp; &quot; &quot; &amp; text(CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Floor_Price__c) &amp; &quot;.00&quot;,

text(CHANNEL_ORDERS__Partner_Order__r.CHANNEL_ORDERS__Partner_Contract_Rules__r.CHANNEL_ORDERS__Default_Contract_Currency__c) &amp; &quot; &quot; &amp; text(CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Floor_Price__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Floor Price (deprecated)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__PNR__c</fullName>
        <description>Percent net revenue of the product at the time the order was created. This field must be explicitly set when using the API.</description>
        <formula>CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__PNR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PNR %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Pricing_Type__c</fullName>
        <description>Field retired in Channel Order App v2.0. Use CHANNEL_ORDERS__pc_Pricing_Type__c instead.</description>
        <formula>TEXT(CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Pricing_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Type (deprecated)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CHANNEL_ORDERS__Product_ID__c</fullName>
        <description>ID of the product.</description>
        <formula>CHANNEL_ORDERS__Product_Name__r.CHANNEL_ORDERS__Product_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product ID</label>
        <type>Text</type>
    </fields>
    <label>Service Order Detail</label>
    <nameField>
        <displayFormat>SOD-{0000000000}</displayFormat>
        <label>Service Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Order Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Custom_Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>SBQQ__UnproratedNetPrice__c</fullName>
        <description>The full-term Net Unit Price.</description>
        <inlineHelpText>The full term net price for individual line.</inlineHelpText>
        <label>Full-Term Net Unit Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractOrderExtension.cls
public with sharing class ContractOrderExtension {
    public Order order {get;set;}
    public List<OrderItem> ois {get;set;}
    public List<OIWrapper> wois {get;set;}
    public List<CurrencyType> cts {get;set;}
    public Map<String, double> rates {get;set;} 
    public CHANNEL_ORDERS__Customer__c scust {get;set;}
    public CHANNEL_ORDERS__Service_Order__c so {get;set;}
    public List<CHANNEL_ORDERS__Service_Order_Detail__c> solis {get;set;}

    public class OIWrapper{
        public OrderItem wcli {get;set;}
        public double totalPrice {get;set;}
        public double convertedMonthlyAmount {get;set;}
        public OIWrapper(OrderItem c, double cma){
            this.wcli = c;
            this.convertedMonthlyAmount = cma;
            this.totalPrice = c.UnitPrice * c.Quantity;
        }
    }
    
    public ContractOrderExtension(ApexPages.StandardController stdController){
        order = (Order)stdController.getRecord();
    }
    
    public PageReference init(){
        wois = new List<OIWrapper>();
        rates = new Map<String, double>();
        solis = new List<CHANNEL_ORDERS__Service_Order_Detail__c>();
        so = new CHANNEL_ORDERS__Service_Order__c();
        System.debug('#### init');
        
        if(order.Custom_Salesforce_Org__c==null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'You must add a Salesforce Org to the order before proceeding.'));
            return null;
        }
        
        try{            
            for(CurrencyType ct : getCurrencyRates()){
                rates.put(ct.IsoCode, ct.ConversionRate);
            }
            order = [SELECT Id, CurrencyIsoCode, Name, Custom_Salesforce_Org__c, Custom_Salesforce_Org__r.OrgId__c, AccountId, Account.Billing_Name__c, Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingPostalCode, Account.BillingCountry, OpportunityId, Opportunity.Name, EffectiveDate, EndDate from Order where Id=:order.Id limit 1];
            
            ois = [SELECT Id, CurrencyIsoCode, Quantity, UnitPrice,	SBQQ__UnproratedNetPrice__c, PricebookEntry.Product2.Name,
                    PricebookEntry.Product2.Partner_Product_Catalog__c, 
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Billing_Frequency__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Cancellation_Terms__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Contract_Auto_Renew__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Contract_Length__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Custom_Unit__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Fixed_Price__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Floor_Price__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__PNR__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Pricing_Type__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Product_ID__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Renewal_Terms__c,
                    PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Pricing_Unit__c
                    FROM OrderItem WHERE OrderId=:order.Id and PricebookEntry.Product2.Partner_Product_Catalog__c!=null];
    		
            List<CHANNEL_ORDERS__Customer__c> custs = [SELECT Id, CHANNEL_ORDERS__Customer_Org_ID__c, CHANNEL_ORDERS__Customer_Company_Name__c, CHANNEL_ORDERS__Customer_Street__c, CHANNEL_ORDERS__Customer_City__c, CHANNEL_ORDERS__Customer_State__c, CHANNEL_ORDERS__Customer_ZIP_Postal_Code__c, CHANNEL_ORDERS__Customer_Country__c  from CHANNEL_ORDERS__Customer__c where CHANNEL_ORDERS__Customer_Org_ID__c=:order.Custom_Salesforce_Org__r.OrgId__c.subString(0,15)];
            scust = new CHANNEL_ORDERS__Customer__c();
            if(custs.size()>0){
                scust = custs.get(0);
            }
            else{
                scust.CHANNEL_ORDERS__Customer_Company_Name__c = order.Account.Billing_Name__c;
                scust.CHANNEL_ORDERS__Customer_Org_ID__c = order.Custom_Salesforce_Org__r.OrgId__c.subString(0,15);
                scust.CHANNEL_ORDERS__Customer_Street__c = order.Account.BillingStreet;
                scust.CHANNEL_ORDERS__Customer_City__c = order.Account.BillingCity;
                scust.CHANNEL_ORDERS__Customer_State__c = order.Account.BillingState;
                scust.CHANNEL_ORDERS__Customer_ZIP_Postal_Code__c = order.Account.BillingPostalCode;
                scust.CHANNEL_ORDERS__Customer_Country__c = order.Account.BillingCountry;
                insert scust;
            }
            
            so.Order__c = order.Id;
            so.CHANNEL_ORDERS__Created_with_new_COA__c = true;
            so.CHANNEL_ORDERS__Customer_Org_ID__c = order.Custom_Salesforce_Org__r.OrgId__c.subString(0,15);
            so.CHANNEL_ORDERS__Customer__c = scust.Id;
            so.CHANNEL_ORDERS__Date_Partner_Received_Customer_Order__c = system.today();
            so.CHANNEL_ORDERS__I_certify__c = 'Yes';
            so.CHANNEL_ORDERS__Order_Type__c = 'Initial';
            so.CHANNEL_ORDERS__X62Org_To_Partner_Org_Email__c = 'sfdc_service_order@e-au107j40bklzxpq53bhqlwngucqhsgvrgw8f8jiu62hpfrt2c.b-yn5reaw.eu2.apex.salesforce.com';
            so.CHANNEL_ORDERS__Override_Level__c = 'Order';
            so.CHANNEL_ORDERS__Related_Opportunity__c = order.OpportunityId;
            so.CHANNEL_ORDERS__Service_Start_Date__c = (order.EffectiveDate>=system.today())?order.EffectiveDate:system.today().addMonths(1).toStartOfMonth();
	        so.CHANNEL_ORDERS__Partner_Contract_Rules__c = [select Id from CHANNEL_ORDERS__Partner_Contract_Terms__c limit 1].Id;
            System.debug('#######@'+ [select Id from CHANNEL_ORDERS__Partner_Contract_Terms__c limit 1]);
            
            for(OrderItem oi : ois){
                double cma = getConvertedAmount(oi.CurrencyIsoCode, double.valueOf(oi.SBQQ__UnproratedNetPrice__c));
                system.debug('### Contract line items '+cma );
                wois.add(new OIWrapper(oi, cma));
                solis.add(new CHANNEL_ORDERS__Service_Order_Detail__c(
					CurrencyIsoCode='EUR',
                    CHANNEL_ORDERS__pct_Currency__c='EUR',
                    CHANNEL_ORDERS__Application__c='Copado Deployer',
                    CHANNEL_ORDERS__Customer_Price_Per_Month__c=Decimal.valueOf(cma).setscale(2, System.RoundingMode.DOWN),
                    CHANNEL_ORDERS__Product_Name__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__c,
                    CHANNEL_ORDERS__Quantity__c=oi.Quantity,
                    CHANNEL_ORDERS__Product_Line_Description__c=order.Opportunity.Name,
                    CHANNEL_ORDERS__pc_Billing_Frequency__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Billing_Frequency__c,
                    CHANNEL_ORDERS__pc_Cancellation_Terms__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Cancellation_Terms__c,
                    CHANNEL_ORDERS__pc_Contract_Auto_Renew__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Contract_Auto_Renew__c,
                    CHANNEL_ORDERS__pc_Contract_Length__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Contract_Length__c,
                    CHANNEL_ORDERS__pc_Custom_Unit__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Custom_Unit__c,
                    CHANNEL_ORDERS__pc_Fixed_Price__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Fixed_Price__c,
                    CHANNEL_ORDERS__pc_Floor_Price__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Floor_Price__c,
                    CHANNEL_ORDERS__pc_Partner_Contract_Term__c=so.CHANNEL_ORDERS__Partner_Contract_Rules__c,
                    CHANNEL_ORDERS__pc_PNR__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__PNR__c,
                    CHANNEL_ORDERS__pc_Pricing_Type__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Pricing_Type__c,
                    CHANNEL_ORDERS__pc_Product_ID__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Product_ID__c,
                    CHANNEL_ORDERS__pc_Renewal_Terms__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Renewal_Terms__c,
                    CHANNEL_ORDERS__pc_Pricing_Unit__c=oi.PricebookEntry.Product2.Partner_Product_Catalog__r.CHANNEL_ORDERS__Pricing_Unit__c
                ));
            }
        }
        catch(Exception e){
            System.debug('#### Exception message: ' + e.getMessage()+' '+e.getLineNumber()+' '+e.getStackTraceString());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage()+' '+e.getLineNumber()+' '+e.getStackTraceString()));
        }
        return null;
    }
    public List<CurrencyType> getCurrencyRates(){
        if(Test.isRunningTest()){
            List<CurrencyType> cts = new List<CurrencyType>();
            cts.add(new CurrencyType(IsoCode='EUR', ConversionRate=1.00, DecimalPlaces=2, IsActive=true, IsCorporate=true));
            cts.add(new CurrencyType(IsoCode='GBP', ConversionRate=0.85, DecimalPlaces=2, IsActive=true, IsCorporate=false));
            return cts;
        }
        else{
            return [SELECT Id, IsoCode, ConversionRate, DecimalPlaces, IsActive, IsCorporate FROM CurrencyType];
        }
    }
    public Double getConvertedAmount(String curr, Double amount){
        if(rates==null || rates.isEmpty() || !rates.keySet().contains(curr))return amount;
        return amount / rates.get(curr);
    }
    public PageReference createOrder(){
        System.debug('#### Create Order');
        Savepoint sp = Database.setSavepoint();
        try{
            System.debug('aaaaa');
            insert so;
            System.debug('bbbbb');
            for(CHANNEL_ORDERS__Service_Order_Detail__c soli : solis){
                soli.CHANNEL_ORDERS__Partner_Order__c=so.Id;
            }
            insert solis;
            System.debug('ccccc');
	        return new PageReference('/'+so.Id);
        }
        catch(Exception e){
            Database.rollback(sp);
            System.debug('#### Exception message: '+e.getMessage());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ''+e.getMessage()));
            return null;
        }
    }
}