objects/Community_Badge_Social_Sharing__mdt.object
<CustomObject>
    <description>This custom metadata stores configuration for certification badges which can be shared on social media like Linkedin, Twitter.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Contains the description of certification badge.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <description>Contains the redirect url for community badge.</description>
        <label>Redirect URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Contains the title of certification badge.</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <description>Unique name of certification program.</description>
        <label>Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Community Badge Social Sharing</label>
    <pluralLabel>Community Badge Social Sharings</pluralLabel>
</CustomObject>

classes/BadgePreviewController.cls
/**
 * An apex page controller that provides the preview of certification badges on Twitter and Linkedin
 */
public class BadgePreviewController {

	public String title { get; set;}
   	public String description { get; set;}
   	public String badgeImageUrlPath { get; set; }
	public String linkType { get; set; }
	public String redirectUrl { get; set; }

	/**
	 * Constructor to set the values for title, badgeImageUrlPath, description, redirectUrl based on query params.
	 */
	public badgePreviewController() {
		setDefaultValues();
		linkType = ApexPages.currentPage().getParameters().get('ty');
		String badgeName = ApexPages.currentPage().getParameters().get('name');
		if('badge'.equalsIgnoreCase(linkType) && !String.isBlank(badgeName)) {
			List<Community_Badge_Social_Sharing__mdt> communityBadgeSocialSharing = [SELECT Title__c, Description__c, Redirect_URL__c , Unique_Name__c FROM Community_Badge_Social_Sharing__mdt WHERE Unique_Name__c = :badgeName.replace('_', ' ') LIMIT 1];
			if(!communityBadgeSocialSharing.isEmpty()) {
				title = communityBadgeSocialSharing[0].Title__c;
				description = communityBadgeSocialSharing[0].Description__c;
				badgeImageUrlPath = '/s/sfsites/c/resource/Community/CommunityResources/badges/' + badgeName + '.png';
				redirectUrl = communityBadgeSocialSharing[0].Redirect_URL__c;
			}
		}
	}
	/**
	 * Set default values for title, badgeImageUrlPath, and redirectUrl
	 */
	private void setDefaultValues() {
		title = 'Copado';
		badgeImageUrlPath = '/s/sfsites/c/resource/Community/CommunityResources/copadoIcons/FaviconIcon.png';
		redirectUrl = System.Label.Copado_Community_URL;
	}
}