objects/Configuration_Step__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Script__c</fullName>
        <label>Apex Script</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Configuration_Steps_Definition__c</fullName>
        <label>Configuration Steps Definition</label>
        <referenceTo>Configuration_Steps_Definition__c</referenceTo>
        <relationshipLabel>Configuration Steps</relationshipLabel>
        <relationshipName>Configuration_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dev1</fullName>
                </value>
                <value>
                    <fullName>Dev2</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Package_Id__c</fullName>
        <label>Package Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Installation_Key__c</fullName>
        <description>An alphanumeric value to install a key-protected package. Leave this  blank for packages without keys.</description>
        <inlineHelpText>Installation key for key-protected packages. The field value is encoded on save.</inlineHelpText>
        <label>Installation Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Package Installation</fullName>
                </value>
                <value>
                    <fullName>Metadata Deploy</fullName>
                </value>
                <value>
                    <fullName>Data Deploy</fullName>
                </value>
                <value>
                    <fullName>Anonymous Apex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Configuration Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Configuration_Steps_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Configuration Steps Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Steps Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ConfigurationStepTriggerHelperTest.cls
@isTest
public with sharing class ConfigurationStepTriggerHelperTest {
	@testSetup 
    static void testDataSetup(){
        copado.GlobalAPI.UserLicense copadoUserLicense = new copado.GlobalAPI.UserLicense(UserInfo.getUserId(),false,false,false,true,false);
        copado.GlobalAPI gapi = new copado.GlobalAPI();
        gapi.upsertCopadoLicense(UserInfo.getUserId(), copadoUserLicense);
        
        Configuration_Steps_Definition__c configStepDef = new Configuration_Steps_Definition__c(Name='My Config Step Definition', Status__c = 'Active');
        insert configStepDef;
    }
    
     static testMethod void testPackageKeyEncryptiongOnInsertUpdate() {
        Test.setMock(HttpCalloutMock.class, new cps_MockHttpResponseGeneratorC1P());
        Configuration_Steps_Definition__c configStepDef = [Select Id From Configuration_Steps_Definition__c Where Name = 'My Config Step Definition']; 

        String packageInstallationKey = 'test#123#$';
        Configuration_Step__c cs = new Configuration_Step__c(Configuration_Steps_Definition__c = configStepDef.Id, Name = 'Package with Key', Order__c = 1, Org__c = 'Dev1', Type__c = 'Package Installation', Package_Id__c = 'test', Package_Installation_Key__c = packageInstallationKey);
        test.startTest();
        insert cs;
        cs = [Select Id, Package_Installation_Key__c From Configuration_Step__c Where Name = 'Package with Key'];
		
		// Verify Package Installation Key value encrypted while saving 
        System.assertNotEquals(packageInstallationKey, cs.Package_Installation_Key__c);
        
        String packageInstallationKeyUpdated = 'new-test#123';
        cs.Package_Installation_Key__c = packageInstallationKeyUpdated;
        
        update cs;
        test.stopTest();
        
		cs = [Select Id, Package_Installation_Key__c From Configuration_Step__c Where Name = 'Package with Key'];
		
        // Verify Package Installation Key value encrypted while updating with new value
        System.assertNotEquals(packageInstallationKeyUpdated, cs.Package_Installation_Key__c);
    }
    
    static testMethod void testPackageWithoutKey() {
        Test.setMock(HttpCalloutMock.class, new cps_MockHttpResponseGeneratorC1P());
        Configuration_Steps_Definition__c configStepDef = [Select Id From Configuration_Steps_Definition__c Where Name = 'My Config Step Definition']; 

        Configuration_Step__c cs = new Configuration_Step__c(Configuration_Steps_Definition__c = configStepDef.Id, Name = 'Package without Key', Order__c = 1, Org__c = 'Dev1', Type__c = 'Package Installation', Package_Id__c = 'test', Package_Installation_Key__c = null);
        test.startTest();
        insert cs;
        cs = [Select Id, Package_Installation_Key__c From Configuration_Step__c Where Name = 'Package without Key'];
		test.stopTest();
        
		// Verify no encryption for null value of Package Installation Key
        System.assertEquals(null, cs.Package_Installation_Key__c);
    }
    
    static testMethod void testCSDelete() {
        Test.setMock(HttpCalloutMock.class, new cps_MockHttpResponseGeneratorC1P());
        Configuration_Steps_Definition__c configStepDef = [Select Id From Configuration_Steps_Definition__c Where Name = 'My Config Step Definition']; 

        Configuration_Step__c cs = new Configuration_Step__c(Configuration_Steps_Definition__c = configStepDef.Id, Name='Apex Script', Order__c = 1, Org__c = 'Dev1', Type__c = 'Anonymous Apex', Apex_Script__c = 'test script');
        insert cs;
        test.startTest();
        cs = [Select Id, Name From Configuration_Step__c Where Name = 'Apex Script'];
        System.assertNotEquals(null, cs);
        delete cs;
        test.stopTest();
        
        // Configuration Step deleted successfully
		cs = [Select Id, IsDeleted from Configuration_Step__c WHERE Id = :cs.Id ALL ROWS];
		System.assertEquals(cs.IsDeleted, true);
    }
}