objects/Configuration_Step__c.object
<CustomObject>
    <fields>
        <fullName>Package_Installation_Key__c</fullName>
        <description>An alphanumeric value to install a key-protected package. Leave this  blank for packages without keys.</description>
        <inlineHelpText>Installation key for key-protected packages. The field value is encoded on save.</inlineHelpText>
        <label>Installation Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Configuration Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ConfigurationStepTriggerHelper.cls
public with sharing class ConfigurationStepTriggerHelper implements ITrigger {
    public void bulkBefore(){}
    
    public void bulkAfter(){}
    
    public void beforeInsert(SObject so){
        Configuration_Step__c cs = (Configuration_Step__c)so;
        if(cs.Package_Installation_Key__c != null && cs.Package_Installation_Key__c != ''){
           cs.Package_Installation_Key__c = cps_Crypto.encryptString(cs.Package_Installation_Key__c);
        }
    }
    
    public void beforeUpdate(SObject oldSo, SObject so){
        Configuration_Step__c oldCs = (Configuration_Step__c)oldSo;
        Configuration_Step__c cs = (Configuration_Step__c)so;
        if(cs.Package_Installation_Key__c != null && cs.Package_Installation_Key__c != '' && (cs.Package_Installation_Key__c != oldCs.Package_Installation_Key__c)){
           cs.Package_Installation_Key__c = cps_Crypto.encryptString(cs.Package_Installation_Key__c); 
        }
    }
    public void beforeDelete(SObject so){}
    
    public void afterInsert(SObject so){}
    
    public void afterUpdate(SObject oldSo, SObject so){}
    
    public void afterDelete(SObject so){}
    public void andFinally(){}
}