objects/Configuration_Execution__c.object
<CustomObject>
    <fields>
        <fullName>JobId__c</fullName>
        <label>JobId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Learning_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Assignment</label>
        <referenceTo>redwing__Learning_Assignment__c</referenceTo>
        <relationshipLabel>Configuration Executions</relationshipLabel>
        <relationshipName>Configuration_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Platform_Job_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Platform Job Execution</label>
        <referenceTo>copado1p__Platform_Job_Execution__c</referenceTo>
        <relationshipLabel>Configuration Executions</relationshipLabel>
        <relationshipName>Configuration_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Configuration Execution</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Configuration Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuration Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Configuration_Step__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Script__c</fullName>
        <label>Apex Script</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dev1</fullName>
                </value>
                <value>
                    <fullName>Dev2</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Package_Id__c</fullName>
        <label>Package Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Installation_Key__c</fullName>
        <description>An alphanumeric value to install a key-protected package. Leave this  blank for packages without keys.</description>
        <inlineHelpText>Installation key for key-protected packages. The field value is encoded on save.</inlineHelpText>
        <label>Installation Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Package Installation</fullName>
                </value>
                <value>
                    <fullName>Metadata Deploy</fullName>
                </value>
                <value>
                    <fullName>Data Deploy</fullName>
                </value>
                <value>
                    <fullName>Anonymous Apex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Configuration Step</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Interactive_Modules_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>C1P_API_Endpoint__c</fullName>
        <label>C1P API Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>C1P_API_Key__c</fullName>
        <label>C1P API Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Readonly_Key__c</fullName>
        <label>Github Readonly Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Repository_URL__c</fullName>
        <label>Github Repository URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform_Job_Id__c</fullName>
        <label>Platform Job Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_API_Key__c</fullName>
        <label>Production API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X_Client_Key__c</fullName>
        <label>X-Client-Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Interactive Modules Setting</label>
    <pluralLabel>Interactive Modules Setting</pluralLabel>
</CustomObject>

objects/Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>ApiKey__c</fullName>
        <label>ApiKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Configuration Execution</label>
        <referenceTo>Configuration_Execution__c</referenceTo>
        <relationshipLabel>Step Executions</relationshipLabel>
        <relationshipName>Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Configuration_Step__c</fullName>
        <label>Configuration Step</label>
        <referenceTo>Configuration_Step__c</referenceTo>
        <relationshipLabel>Step Executions</relationshipLabel>
        <relationshipName>Step_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JobID__c</fullName>
        <externalId>true</externalId>
        <label>Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Learning_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Assignment</label>
        <referenceTo>redwing__Learning_Assignment__c</referenceTo>
        <relationshipLabel>Step Executions</relationshipLabel>
        <relationshipName>Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrgCredentialId__c</fullName>
        <label>OrgCredentialId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Platform_Job_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Platform Job Execution</label>
        <referenceTo>copado1p__Platform_Job_Execution__c</referenceTo>
        <relationshipLabel>Step Executions</relationshipLabel>
        <relationshipName>Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Instance_URL__c</fullName>
        <label>Target Instance URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Org_Credential_Id__c</fullName>
        <label>Trial Org Credential Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Step Execution</label>
    <nameField>
        <label>Step Execution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Step_Execution_Event__e.object
<CustomObject>
    <description>This is the event object for monitoring Step Execution changes</description>
    <fields>
        <fullName>Learning_Assignment_Id__c</fullName>
        <label>Learning Assignment Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isFinished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isFinished</label>
        <type>Checkbox</type>
    </fields>
    <label>Step Execution Event</label>
    <pluralLabel>Step Execution Events</pluralLabel>
</CustomObject>

classes/ConfigExecutionTriggerHelper.cls
public with sharing class ConfigExecutionTriggerHelper implements ITrigger {
    public void bulkBefore(){}
    
    public void bulkAfter(){}
    
    public void beforeInsert(SObject so){}
    
    public void beforeUpdate(SObject oldSo, SObject so){
        Configuration_Execution__c oldCe = (Configuration_Execution__c)oldSo;
        Configuration_Execution__c ce = (Configuration_Execution__c)so;
		resetJob(oldCe, ce);
        checkPayload(oldCe, ce);
    }
    public void beforeDelete(SObject so){}
    
    public void afterInsert(SObject so){}
    
    public void afterUpdate(SObject oldSo, SObject so){
        Configuration_Execution__c oldCe = (Configuration_Execution__c)oldSo;
        Configuration_Execution__c ce = (Configuration_Execution__c)so;
		sendCalloutRequest(oldCe, ce);
        stepExecutionStatusChange(oldCe, ce);
    }
    
    public void afterDelete(SObject so){}
    public void andFinally(){}

    public void resetJob(Configuration_Execution__c oldCe, Configuration_Execution__c ce){
        if((oldCe.Status__c =='Failed' || oldCe.Status__c == 'Completed') && (ce.Status__c == 'Pending' || ce.Status__c == 'In progress')) {
            ce.Payload__c = null;
            ce.JobId__c = null;
            ce.Platform_Job_Execution__c = null;
        }
    }

    public void checkPayload(Configuration_Execution__c oldCe, Configuration_Execution__c ce){
        if(ce.Payload__c == null) {return;}
        try {
            String payload = EncodingUtil.urlDecode(ce.Payload__c, 'UTF-8');
            ce.Payload__c = payload;
        	Map<String, Object> payloadObj = cps_InteractiveModule_Utils.parsePayload(ce.Payload__c);

            if (payloadObj.containsKey('hasError') && (payloadObj.get('hasError') == 'false' || payloadObj.get('hasError') == false)) {

                if (payloadObj.containsKey('data')) {
                    List<Object> data = (List<Object>)payloadObj.get('data');

                    List<Step_Execution__c> stepExecution = new List<Step_Execution__c>();
                    for (Object sr : data) {
                        Map<String, Object> stepResult = (Map<String, Object>)sr;
                        for (String pKey : stepResult.keySet()) {
                            if (pKey instanceOf Id && String.valueOf(Id.valueOf(pKey).getSObjectType()) == 'Step_Execution__c') {
                                Map<String, Object> stepResultJSON = (Map<String, Object>)stepResult.get(pKey);
                                String stepExecutionPayload = JSON.serialize(stepResultJSON);
                                stepExecution.add(new Step_Execution__c(
                                    Id = pKey,
                                    Payload__c = stepExecutionPayload
                                ));
                            }
                        }
                    }

                    if (!stepExecution.isEmpty()) {
                        update stepExecution;
                    }
                }
            	ce.Status__c = 'Completed';
            } else {
            	ce.Status__c = 'Failed';
            }
        }
        catch (Exception e) {
        }
    }
    public void stepExecutionStatusChange(Configuration_Execution__c oldCe, Configuration_Execution__c ce){
        if(oldCe.Status__c != ce.Status__c && (ce.Status__c == 'Pending' || ce.Status__c == 'In progress' || ce.Status__c == 'Failed')) {
            List<Step_Execution__c> stepExeToBeUpdate = new List<Step_Execution__c>();
            for(Step_Execution__c se : [Select Id, Name, Status__c From Step_Execution__c 
                                                                Where Configuration_Execution__c =:ce.Id
                                                                AND Status__c <> 'Completed']){
                se.Status__c = (ce.Status__c == 'Failed') ? 'Pending' : ce.Status__c;
                stepExeToBeUpdate.add(se);
            }

            if(!stepExeToBeUpdate.isEmpty()){
                update stepExeToBeUpdate;
            }
        }

        if (oldCe.Status__c != ce.Status__c) {
            Step_Execution_Event__e stepExeEvent = new Step_Execution_Event__e(
                Record_Id__c = ce.Id,
                Status__c = ce.Status__c,
                IsFinished__c = (ce.Status__c == 'Completed' || ce.Status__c == 'Failed'),
                Learning_Assignment_Id__c = ce.Learning_Assignment__c
            );
    
            EventBus.publish(stepExeEvent);
        }
    }

    public void sendCalloutRequest(Configuration_Execution__c oldCe, Configuration_Execution__c ce){
        if(oldCe.Status__c != ce.Status__c && ce.Status__c == 'In progress') {

            Interactive_Modules_Setting__mdt interactiveModulesSetting = [
                SELECT C1P_API_Endpoint__c, Platform_Job_Id__c, C1P_API_Key__c, Production_API_Key__c, X_Client_Key__c, Github_Repository_URL__c, Github_Readonly_Key__c
                FROM Interactive_Modules_Setting__mdt
                WHERE QualifiedApiName = :cps_InteractiveModule_Utils.SETTINGS_NAME LIMIT 1];
            Map<String, String> paramBodyToBeSend = new Map<String, String>();
            List<Map<String, Map<String, String>>> paramBodySetupList = new List<Map<String, Map<String, String>>>();

            for(Step_Execution__c se : [Select Id, ApiKey__c, Target_Instance_URL__c, OrgCredentialId__c, Trial_Org_Credential_Id__c,
                            Configuration_Step__r.Type__c, Configuration_Step__r.Apex_Script__c, Configuration_Step__r.Branch__c,
                            Configuration_Step__r.Package_Id__c, Configuration_Step__r.Org__c, Configuration_Step__r.Package_Installation_Key__c
                            From Step_Execution__c 
                            Where Configuration_Execution__c =: ce.Id AND Status__c <> 'Completed']){

                Map<String, String> paramBody = new Map<String, String>();
            
                if(se.Configuration_Step__r.Type__c == 'Package Installation'){
                    paramBody.put('ACTION', 'INSTALL_PACKAGE');
                    paramBody.put('PACKAGE_ID', se.Configuration_Step__r.Package_Id__c);
                    String packageInstallationKey = (se.Configuration_Step__r.Package_Installation_Key__c != null) ? cps_Crypto.decryptString(se.Configuration_Step__r.Package_Installation_Key__c) : '';
                    paramBody.put('PACKAGE_INSTALLATION_KEY', packageInstallationKey);
                } else if(se.Configuration_Step__r.Type__c == 'Metadata Deploy'){
                    paramBody.put('ACTION', 'DEPLOY_METADATA');
                    paramBody.put('BRANCH_NAME', se.Configuration_Step__r.Branch__c);
                    paramBody.put('PRIVATE_REPOSITORY_URL', interactiveModulesSetting.Github_Repository_URL__c);
                    paramBody.put('GITHUB_READONLY_KEY', interactiveModulesSetting.Github_Readonly_Key__c);
                    
                } else if(se.Configuration_Step__r.Type__c == 'Anonymous Apex'){
                    paramBody.put('ACTION', 'ANONYMOUS_EXECUTION');
                    String apexScript = EncodingUtil.urlEncode(se.Configuration_Step__r.Apex_Script__c, 'UTF-8').replace('+', '%20');
                    paramBody.put('APEX_BODY', apexScript);
                } else if(se.Configuration_Step__r.Type__c == 'Data Deploy'){
                    paramBody.put('ACTION', 'DATA_IMPORT');
                    List<String> contDocIds = new List<String>();
                    List<ContentVersion> contVersions = new List<ContentVersion>();
                    Map<String, String> contVersionData = new Map<String, String>();
                    for(ContentDocumentLink contLink : [Select ContentDocumentId From ContentDocumentLink Where LinkedEntityId =:se.Configuration_Step__c]){
                        contDocIds.add(contLink.ContentDocumentId);
                    }
                    if (!contDocIds.isEmpty()) {
                        for(ContentVersion contVersion : [Select Id, Title, VersionData, FileExtension, FileType 
                                From ContentVersion Where FileType = 'JSON' AND ContentDocumentId IN:contDocIds]){
                            contVersionData.put(contVersion.Title+'.'+contVersion.FileExtension, contVersion.VersionData.toString());
                        }
                    }

                    String allDataContent = EncodingUtil.urlEncode(JSON.serialize(contVersionData), 'UTF-8').replace('+', '%20');
                    paramBody.put('IMPORT_DATA_JSON', allDataContent);
                }
                
                String api_key = (se.ApiKey__c != null) ? cps_Crypto.decryptString(se.ApiKey__c) : '';
    
                paramBody.put('StepExecution', se.Id);
                paramBody.put('API_KEY_TARGET_ORG', api_key);
                paramBody.put('INSTANCE_URL_TARGET_ORG', se.Target_Instance_URL__c);
                paramBody.put('ORG_CREDENTIAL_ID_TARGET_ORG', se.OrgCredentialId__c);
                paramBody.put('C1P_ORGCREDENTIALID_CLIENT', se.Trial_Org_Credential_Id__c);
    
                paramBody.put('API_KEY', interactiveModulesSetting.Production_API_Key__c);
                paramBody.put('X_CLIENT_KEY', interactiveModulesSetting.X_Client_Key__c);

                Map<String, Map<String, String>> paramBodySetupMap = new Map<String, Map<String, String>>();
                paramBodySetupMap.put(se.Id, paramBody);
                paramBodySetupList.add(paramBodySetupMap);
            }
            paramBodyToBeSend.put('ACTION', 'SETUP');
            paramBodyToBeSend.put('SETUP_LIST', JSON.serialize(paramBodySetupList));
            cps_InteractiveModule_Utils.startC1PJob(paramBodyToBeSend, ce.Id);
        }
    }
}