objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The org to which the contract is applied.</inlineHelpText>
        <label>Salesforce Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (for Salesforce Org)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Salesforce Org Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credits_Top_Up__c</fullName>
        <label>Credits Top-Up</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>License_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License User</label>
        <referenceTo>Salesforce_User__c</referenceTo>
        <relationshipLabel>Salesforce Orgs</relationshipLabel>
        <relationshipName>Salesforce_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensed_Seats__c</fullName>
        <label>Licensed Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Top_Up_Date__c</fullName>
        <inlineHelpText>This is a date which will be queried by Heroku to perform the top-ups on a daily basis</inlineHelpText>
        <label>Next Top-Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Corporate Entity to which the Salesforce Org is related.</description>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salesforce Orgs</relationshipLabel>
        <relationshipName>Salesforce_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Expiration_Date__c</fullName>
        <label>Trial Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Channel Partner / Reseller</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_User__c.object
<CustomObject>
    <description>This object holds the Users linked to the Salesforce Orgs.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Salesforce Users</relationshipLabel>
        <relationshipName>Salesforce_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Salesforce User</label>
    <nameField>
        <displayFormat>SU-{0000000}</displayFormat>
        <label>Salesforce User Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>Salesforce_User__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the Contact associated with the license after the partner converts the Lead to a contact as part of Lead Conversion process</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N30000001JvR6EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Expiration__c</fullName>
        <description>Expiration Date of the License, 1/1/1970 represents a perpetual license</description>
        <label>Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__Install_Date__c</fullName>
        <description>The Date this Package Version was initially installed by the developer. (Does not get updated as part of upgrades.)</description>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__License_Status__c</fullName>
        <formula>$RecordType.Name</formula>
        <label>License Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Licensed_Seats__c</fullName>
        <description>A text field which displays the number of Licensed Seats or “Site License” based on the numeric field</description>
        <formula>IF( sfLma__Seats__c &gt;=0,  TEXT(sfLma__Seats__c ), &quot;Site License&quot;)</formula>
        <label>Licensed Seats</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SalesforceOrgService.cls
/**
 * This class is a replacement for the former AccountService
 */
public with sharing class SalesforceOrgService {

    public static Map<Id, sfLma__License__c> licenseMap;
    public static Map<Id, Contract> contractMap;
    public static boolean salesforceOrgTriggerActive = true;

    public static void prepareData(List<SObject> records) {

        licenseMap = new Map<Id, sfLma__License__c>();
        contractMap = new Map<Id, Contract>();
        Set<Id> orgIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();

        for(SObject so : records){
            Salesforce_Org__c newOrg = (Salesforce_Org__c)so;
            orgIds.add(newOrg.Id);
            accIds.add(newOrg.Parent_Account__c);
        }

        List<sfLma__License__c> licenses = [select Id, Salesforce_Org__c, Salesforce_User__c, sfLma__Contact__c, sfLma__License_Status__c, sfLma__Install_Date__c, sfLma__Licensed_Seats__c, sfLma__Expiration__c from sfLma__License__c where Salesforce_Org__c IN :orgIds];
        for(sfLma__License__c l : licenses){
            licenseMap.put(l.Salesforce_Org__c, l);
        }

        try {
            List<Contract> cs = [
                    SELECT Id, StartDate, AccountId
                    FROM Contract
                    WHERE AccountId IN :accIds AND Status = 'Activated'
                    ORDER BY EndDate DESC
            ];

            for (Contract cont : cs) {
                contractMap.put(cont.AccountId, cont);
            }
        }
        catch (QueryException e) {
            //This exception happens when the running user has no permissions on Contracts (LicenseManagerApp user actually...)
            //We ignore this exception so that the LMA user won't have to update the Next Top Up date, Sales will.
        }

    }


    public static void updateOrgLicensingInfo(Salesforce_Org__c o) {

        sfLma__License__c l = licenseMap.get(o.Id);

        if(l != null){
            o.Org_Type__c = (l.sfLma__Licensed_Seats__c=='Site License')?'Sandbox':'Production';
            if(l.sfLma__License_Status__c=='Uninstalled'){
                o.Account_Status__c = 'Inactive';
                o.Licensed_Seats__c = 0;
                o.Credits_Top_Up__c = 0;
                o.Type__c = 'Prospect';
            }
            else if(l.sfLma__License_Status__c=='Suspended'){
                o.Account_Status__c = 'Suspended';
            }
            o.Trial_Expiration_Date__c = l.sfLma__Expiration__c;
            if(o.License_User__c==null)o.License_User__c=l.Salesforce_User__c;

        }
    }

    public static void setTopUpDate(Salesforce_Org__c o) {
        if (o.Type__c == 'Customer' && o.Next_Top_Up_Date__c == null) {
            if (contractMap.containsKey(o.Parent_Account__c)) {
                if (contractMap.get(o.Parent_Account__c).StartDate != null) {
                    o.Next_Top_Up_Date__c = contractMap.get(o.Parent_Account__c).StartDate.addMonths(1);
                }
            }
        }
        else if (o.Type__c == 'Prospect') {
            o.Next_Top_Up_Date__c = null;
        }
    }
}