objects/Contract_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CL-{00000}</displayFormat>
        <label>Contract Line Item Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <formula>PricebookEntry.UnitPrice - (PricebookEntry.UnitPrice * Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractLineItemTriggerHelper.cls
public with sharing class ContractLineItemTriggerHelper {
	public static Map<Id, QuoteLineItem> qliMap = new Map<Id, QuoteLineItem>();

	public static void prepareData(List<SObject> records){		
		Set<Id> qliIds = new Set<Id>();
		for(SObject so : records){
			Contract_Line_Item__c cli = (Contract_Line_Item__c)so;
			qliIds.add(cli.Quote_Line_Item__c);
		}
		qliMap = new Map<Id, QuoteLineItem>([select Id, Product2Id, Unit_Price__c, Quantity, Discount, CurrencyIsoCode, Total_Price__c from QuoteLineItem where Id IN :qliIds]);
	}
	public static void setProductLookup(Contract_Line_Item__c cli){
		if(cli.Quote_Line_Item__c==null)return;
		cli.Product__c = qliMap.get(cli.Quote_Line_Item__c).Product2Id;
		if(qliMap.containsKey(cli.Quote_Line_Item__c)){
			cli.Quantity__c = qliMap.get(cli.Quote_Line_Item__c).Quantity;
			cli.Total_Price__c = qliMap.get(cli.Quote_Line_Item__c).Total_Price__c;
			cli.Unit_Price__c = qliMap.get(cli.Quote_Line_Item__c).Unit_Price__c;
		}
	}
	public static void setCurrency(Contract_Line_Item__c cli){
		if(cli.Quote_Line_Item__c==null)return;
		cli.CurrencyIsoCode = qliMap.get(cli.Quote_Line_Item__c).CurrencyIsoCode;
	}
}