objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Non_Standard_ACV__c</fullName>
        <label>Non Standard ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_1st_yr_ARR__c</fullName>
        <label>Order 1st yr ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_ACV__c</fullName>
        <label>Order ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Current_ARR__c</fullName>
        <label>Order Current ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_method__c</fullName>
        <label>Payment method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BACS/Bank transfer</fullName>
                </value>
                <value>
                    <fullName>Direct debit</fullName>
                </value>
                <value>
                    <fullName>Credit card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__KugamonSetting__c.object
<CustomObject>
    <description>Kugamon - Main object that controls Kugamon application behavior. Only one Kugamon Settings record is allowed. For Admin use only.</description>
    <fields>
        <fullName>kugo2p__PaymentMethod__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Debit/Credit Card</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Wire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>kugo2p__Warehouse__c</referenceTo>
        <relationshipLabel>Kugamon Settings</relationshipLabel>
        <relationshipName>Kugamon_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Kugamon Setting</label>
    <nameField>
        <label>Kugamon Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kugamon Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__SalesOrder__c.object
<CustomObject>
    <description>Kugamon - Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <fields>
        <fullName>Non_Standard_ACV__c</fullName>
        <formula>Quote__r.Non_Standard_ACV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non Standard ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Salesforce CPQ Quote</description>
        <inlineHelpText>Salesforce CPQ Quote</inlineHelpText>
        <label>Quote Number</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kuga_sub__ContractNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contract Number.

Contract Number is automatically filled/generated for New Orders on Order Approval or Release based upon Kugamon Settings (Initiate Order Subscription Management). Required for Expansion and Renewal Orders. 
Screen reader support enabled.</description>
        <label>Contract Number</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contributing Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kuga_sub__GenerateRenewalOpportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether a Renewal Opportunity will be generated by this Order upon Order Approval or Order Release based on the presence of a Renewable Service.</description>
        <label>Generate Renewal Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>kuga_sub__GenerateSubscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether a Subscription will be generated by this Order upon Order Approval or Order Release based on if Order Service Lines’ underlying Product record has the Create Subscription field is Checked.</description>
        <inlineHelpText>Subscription record creation is based on if the underlying Product is set to Create Subscription.</inlineHelpText>
        <label>Generate Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>kugo2p__Competitors__c</fullName>
        <label>Competitor(s)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__ContactBilling__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Billing</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SalesOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__ContactBuying__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Buying</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__ContactShipping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact Shipping</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>SalesOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__PaymentMethod__c</fullName>
        <description>Filled from Payment Method on the Quote if Order is generated from Quote; otherwise, from Payment Method on the Additional Account Info.

If Online Checkout is enabled, Payment Method not equal to &quot;Invoice&quot; will display [Accept &amp; Pay] on Online Order.</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Debit/Credit Card</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Wire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__RecordStatus__c</fullName>
        <defaultValue>&quot;Draft&quot;</defaultValue>
        <description>Valid Statuses are: Draft, Sent, Approved, Released, and Cancelled. Released Order status cannot be manually changed; use Status formula field instead. Cancelled Order status cannot be changed at all.</description>
        <inlineHelpText>Valid Statuses are: Draft, Sent, Approved, Released, and Cancelled. Released Order status cannot be manually changed; use Status formula field instead. Cancelled Order status cannot be changed at all.</inlineHelpText>
        <label>Record Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__Warehouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse</label>
        <referenceTo>kugo2p__Warehouse__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>SO-{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__Warehouse__c.object
<CustomObject>
    <description>Kugamon - Related object to Kugamon Settings to store Warehouse locations. For Admin use only.</description>
    <fields>
        <fullName>kugo2p__KugamonSetting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Kugamon Setting</label>
        <referenceTo>kugo2p__KugamonSetting__c</referenceTo>
        <relationshipLabel>Warehouses</relationshipLabel>
        <relationshipName>Warehouses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestKugamonOrderTriggerHelper.cls
@isTest
private class TestKugamonOrderTriggerHelper {
   
    @isTest 
    public static void testMethod1() {
         
        Account accObj = TestDataFactory.createAccount('KugaHelper', 'EUR');
        insert accObj;
        
        Contact conObj = TestDataFactory.createContact(accObj.id,'TestKugamonOrderTriggerHelper');
        conObj.MailingStreet = 'E5';
        conObj.MailingCity = 'Bengalore';
        conObj.MailingState = 'Karnataka';
        conObj.MailingCountry = 'India';
        Insert conObj;      
        
        Product2 prod = TestDataFactory.createProduct('Copado Standard Edition','Licenses ',null);
        prod.kuga_sub__Renewable__c = true;
        Insert prod; 
        
        //New Opportunity
        Opportunity newOpp = TestDataFactory.createOpportunity(accObj, 'TestNewOpp', 'New Customer');
        newOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New').getRecordTypeId();        
        insert newOpp;  
        
        SBQQ__Quote__c newQuote = TestDataFactory.createCPQuote(newOpp);
        newQuote.SBQQ__Primary__c = true;
        newQuote.Payment_Method__c = 'ACH';
        Insert newQuote;
        
        SBQQ__QuoteLine__c newQLine = TestDataFactory.createCPQQuoteLine(newQuote.Id,prod.Id);
        insert newQLine ; 
        
        Pricebook2 pb = TestDataFactory.createPricebook(); 
        pb.CurrencyIsoCode = 'EUR';
        insert pb;  
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(pb.name);       
        insert testKugamonSetting ; 
        Test.startTest(); 
        Contract cont = TestDataFactory.createDraftContract(accObj.Id,'EUR');
        cont.StartDate = Date.newInstance(2023, 04, 09);
        cont.ContractTerm = 12;       
        insert cont;
              
        kugo2p__SalesOrder__c newOrderObj = TestDataFactory.createKugamonOrder(accObj.id);
        newOrderObj.kugo2p__ContactBilling__c = conObj.id;
        newOrderObj.kugo2p__ContactBuying__c = conObj.id;
        newOrderObj.kugo2p__ContactShipping__c = conObj.id;  
        //newOrderObj.kugo2p__Warehouse__c = wareObj.Id;                   
        newOrderObj.RecordTypeId = Schema.SObjectType.kugo2p__SalesOrder__c.getRecordTypeInfosByName().get('New').getRecordTypeId();            
        newOrderObj.kugo2p__Opportunity__c = newOpp.Id;
        newOrderObj.kugo2p__Competitors__c = 'Testing New Order';
        newOrderObj.kugo2p__PaymentMethod__c = 'Invoice';
        Insert newOrderObj;        
        newOrderObj.kuga_sub__ContractNumber__c = cont.Id;
        newOrderObj.kugo2p__RecordStatus__c = 'Released';      
        update newOrderObj;               
        Test.stopTest();                      
    }
    @isTest
    public static void testMethod2(){      
         
        Account accObj = TestDataFactory.createAccount('TestKugaHelper', 'EUR');
        insert accObj;
        
        Contact conObj = TestDataFactory.createContact(accObj.id,'TestKugamonOrderTriggerHelper');
        conObj.MailingStreet = 'E5';
        conObj.MailingCity = 'Bengalore';
        conObj.MailingState = 'Karnataka';
        conObj.MailingCountry = 'India';
        Insert conObj;        
         
        //Expansion Opportunity
        Opportunity expansionOpp = TestDataFactory.createOpportunity(accObj, ' 1EE', 'Add-on');
        expansionOpp.Value_Prop_ID__c = 'Test';
        expansionOpp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Expansion').getRecordTypeId();
        insert expansionOpp;
        
        SBQQ__Quote__c expansionQuote = TestDataFactory.createCPQuote(expansionOpp);
        expansionQuote.SBQQ__Primary__c = true;
        expansionQuote.Payment_Method__c = 'ACH';
        Insert expansionQuote;          
        
        Product2 prod2 = TestDataFactory.createProduct('Copado Admin','Licenses ',null);
        Insert prod2;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=prod2.Id, UnitPrice=5, IsActive=true,CurrencyIsoCode='EUR');
        insert standardPrice; 
           
        Test.startTest();
        
        SBQQ__QuoteLine__c expansionQLine = TestDataFactory.createCPQQuoteLine(expansionQuote.Id,prod2.Id);
        Insert expansionQLine ;  
        
        
        Pricebook2 pb = TestDataFactory.createPricebook(); 
        pb.CurrencyIsoCode = 'EUR';
        insert pb;  
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(pb.name);       
        insert testKugamonSetting ;     
        
        kugo2p__Warehouse__c wareObj = TestDataFactory.createWarehouse('test',testKugamonSetting.id);
        Insert wareObj;
        
        Contract cont = TestDataFactory.createDraftContract(accObj.Id,'EUR');
        cont.StartDate = Date.newInstance(2023, 04, 09);
        cont.ContractTerm = 12;     
        cont.Order_ACV__c = 1000 ; 
        cont.Order_1st_yr_ARR__c = 1000 ; 
        cont.Order_Current_ARR__c = 1000 ; 
        cont.Non_Standard_ACV__c = 1000 ;  
        insert cont;
        Id expansionRecTypeId = Schema.SObjectType.kugo2p__SalesOrder__c.getRecordTypeInfosByName().get('Expansion').getRecordTypeId();
        kugo2p__SalesOrder__c orderObj = TestDataFactory.createKugamonOrder(accObj.id);
        orderObj.kugo2p__ContactBilling__c = conObj.id;
        orderObj.kugo2p__ContactBuying__c = conObj.id;
        orderObj.kugo2p__ContactShipping__c = conObj.id;
        orderObj.kugo2p__Warehouse__c = wareObj.Id;        
        orderObj.RecordTypeId = Schema.SObjectType.kugo2p__SalesOrder__c.getRecordTypeInfosByName().get('Expansion').getRecordTypeId();
        orderObj.kuga_sub__GenerateSubscription__c = true;        
        orderObj.kuga_sub__GenerateRenewalOpportunity__c =true;      
        orderObj.Quote__c = expansionQuote.Id;
        orderObj.kugo2p__Opportunity__c = expansionOpp.Id;
        orderObj.kuga_sub__ContractNumber__c = cont.Id;
        orderObj.kugo2p__RecordStatus__c = 'Released'; 
        Insert orderObj;        
        Update orderObj;               
        Test.stopTest();
    }  
}