objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Order_ACV__c</fullName>
        <label>Order ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kuga_sub__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Renewal Opportunity for the next Contract period.</description>
        <label>Current Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Parent Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__KugamonSetting__c.object
<CustomObject>
    <description>Kugamon - Main object that controls Kugamon application behavior. Only one Kugamon Settings record is allowed. For Admin use only.</description>
    <label>Kugamon Setting</label>
    <nameField>
        <label>Kugamon Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kugamon Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
        <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__SalesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales rep responsible for this quote if different from the user who owns the quote record.</description>
        <inlineHelpText>Sales rep responsible for this quote if different from the user who owns the quote record.</inlineHelpText>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SetContractToExpiredReplacementTest.cls
@isTest
private class SetContractToExpiredReplacementTest {
    @isTest 
    private static void testContractsForTrigger(){
       
        Pricebook2 p2 = TestDataFactory.createPricebook(); 
        p2.CurrencyIsoCode = 'EUR';
        insert p2;         
        
        Product2 p = TestDataFactory.createProduct('Enterprise', 'Licenses',null);
        insert p;        
        
        Account a = TestDataFactory.createAccountNew('Test_Account_Trigger','EUR');
        insert a;
       
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(p2.name); 
        insert testKugamonSetting ;
        
        Contract c1 = TestDataFactory.createDraftContract(a.Id,'EUR');
        c1.StartDate = Date.newInstance(2023, 04, 09);
        c1.ContractTerm = 12;
        insert c1; 
        
        Contract c2 = TestDataFactory.createDraftContract(a.Id,'EUR');
        c2.StartDate = Date.newInstance(2024, 04, 09);
        c2.ContractTerm = 12;
        insert c2;        
        
        c1 = [select Id, Status from Contract where Id=: c1.Id];     
        
        System.assertEquals(a.Name, 'Test_Account_Trigger');
        System.assertEquals(c2.Status, 'Draft');
        
    }
    
    @isTest 
    private static void testContractActivationDraftStatus(){
        Account a = TestDataFactory.createAccountNew('Test_Account_Trigger','EUR');
        insert a;
        
        Entitlement ent = TestDataFactory.createEntitlementPremier(a.Id);
        ent.Name='Premier Support';        
        ent.StartDate=Date.today().addDays(-1);      
        ent.Access_Code__c = 123456;              
        insert ent;
        
        Pricebook2 p2 = TestDataFactory.createPricebook(); 
        p2.CurrencyIsoCode = 'EUR';
        insert p2; 
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(p2.name); 
        insert testKugamonSetting ;
        
        Contract c1 = TestDataFactory.createDraftContract(a.Id,'EUR');        
        c1.EndDate = Date.today().addDays(7).addMonths(12);
        insert c1;  
        Contract cc = [Select id, Status, EndDate from Contract where id = : c1.id LIMIT 1];        
        Entitlement entitlementobj = [select StartDate,EndDate from Entitlement where Id=: ent.Id LIMIT 1];
               
        System.assertEquals('Activated',cc.Status);
        System.assertEquals(entitlementobj.EndDate, cc.EndDate);
    }
      
    @isTest 
    private static void testContractHelper(){
    
        Pricebook2 p2 = TestDataFactory.createPricebook(); 
        p2.CurrencyIsoCode = 'EUR';
        insert p2;       
                
        Product2 p = TestDataFactory.createProduct('Enterprise', 'Licenses',null);
        insert p;  
                
        Account a = TestDataFactory.createAccountNew('Test_Account_Trigger','EUR');
        insert a; 
        
        Contact con = new Contact(FirstName='Test', LastName='Test', AccountId=a.Id);
        insert con; 
        
        Id usrId = userinfo.getUserId();
        Date endDate = system.Today().addYears(1);
        
        Id renewRecdTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        Opportunity renewalOpp = new Opportunity(Name='My Opp', AccountId=a.Id, RecordTypeId = renewRecdTypeId , StageName='Marketing Qualification', CloseDate=Date.today()+10, CurrencyIsoCode='EUR');
        renewalOpp.Amount = 99.0;
        renewalOpp.LeadSource = 'Advertisement' ;
        insert renewalOpp;  
        
        SBQQ__Quote__c renewQuote = new SBQQ__Quote__c(SBQQ__Account__c = a.Id,SBQQ__Opportunity2__c=renewalOpp.id,SBQQ__SalesRep__c=usrId,SBQQ__Primary__c=true,SBQQ__PrimaryContact__c=con.Id,SBQQ__StartDate__c=system.today().addYears(1),SBQQ__EndDate__c = endDate.addYears(1),Renewal_ACV__c = 70000);
        insert renewQuote;   
        
        renewalOpp.SBQQ__PrimaryQuote__c = renewQuote.Id;
        update renewalOpp;
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(p2.name); 
        insert testKugamonSetting ;
        
        Contract c = TestDataFactory.createDraftContract(a.Id,'EUR');        
        c.EndDate = Date.today().addDays(7).addMonths(12);
        c.kuga_sub__RenewalOpportunity__c = renewalOpp.Id;
        c.Order_ACV__c = 40000;           
        insert c;    
    }  
}