objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Custom_Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The org to which the contract is applied.</inlineHelpText>
        <label>Salesforce Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (for Salesforce Org)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Corporate Entity to which the Salesforce Org is related.</description>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salesforce Orgs</relationshipLabel>
        <relationshipName>Salesforce_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameter__c.object
<CustomObject>
    <description>A custom object for storing feature parameters.  A new record is created of this object for every feature parameter that is ADDED as part of an uploaded package version. This record is automatically created upon the first package install of that package version.</description>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Feature Parameter</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Feature Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameterInteger__c.object
<CustomObject>
    <description>Custom object that is part of FMA for storing Feature Parameter Overrides for integers

A new record is created of this object for every feature parameter that is ADDED as part of a package install in an org. This record is automatically created upon every package install.

The Feature Parameter object serves as an index.</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Value will be set to 0 when expired</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <formula>sfFma__License__r.Salesforce_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__FeatureParameter__c</fullName>
        <description>The parent Feature Parameter object.</description>
        <label>Feature Parameter</label>
        <referenceTo>sfFma__FeatureParameter__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__License__c</fullName>
        <label>License</label>
        <referenceTo>sfLma__License__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sfFma__Value__c</fullName>
        <label>Feature Parameter Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature Parameter Integer</label>
    <nameField>
        <displayFormat>FPI-{0000}</displayFormat>
        <label>Feature Parameter Integer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameter Integers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountFeatureManagerController.cls
public with sharing class AccountFeatureManagerController {
    private Salesforce_Org__c org {get;set;}
	public List<sfFma__FeatureParameterInteger__c> orgFeatures {get;set;}
	public Contract contractForOrg {get;set;}

	public AccountFeatureManagerController(ApexPages.StandardController stdController) {
        org = (Salesforce_Org__c)stdController.getRecord();
		org = [SELECT Id, Parent_Account__c FROM Salesforce_Org__c WHERE Id = :org.Id];
		getorgFeatures();
		List<Contract> cs = [SELECT Id, ContractNumber, Custom_Salesforce_Org__c, StartDate, EndDate, Status
		  					   FROM Contract WHERE AccountId = :org.Parent_Account__c AND Status = 'Activated' ORDER BY EndDate DESC LIMIT 1];
		if(cs.size()== 1){
			contractForOrg = cs.get(0);
		}
		else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This org does not have an activated contract.'));
		}
	}
	public void getorgFeatures(){
		orgFeatures = new List<sfFma__FeatureParameterInteger__c>();
		orgFeatures = [select Id, sfFma__FullName__c, Expiration_Date__c, sfFma__Value__c, sfFma__License__c, sfFma__FeatureParameter__c
		from sfFma__FeatureParameterInteger__c
        where sfFma__License__r.Salesforce_Org__c =:org.Id
        and sfFma__FullName__c != null];
		for (sfFma__FeatureParameterInteger__c fpi: orgFeatures) {
			if (fpi.sfFma__Value__c == null) fpi.sfFma__Value__c = 0;
		}
		system.debug('### fetched records: '+orgFeatures.size());
	}
	public void updateorgFeatures(){
		update orgFeatures;
        syncFeatures(org.Id);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Features are being synchronised.'));
	}
    @future(callout=true)
	private static void syncFeatures(Id orgId){
		admin_utilities.syncFeatures(orgId);
	}

}