objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ACV__c</fullName>
        <label>ACV</label>
        <summarizedField>Order.ACV__c</summarizedField>
        <summaryForeignKey>Order.ContractId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Order_ACV__c</fullName>
        <label>Order ACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kuga_sub__RenewalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Renewal Opportunity for the next Contract period.</description>
        <label>Current Renewal Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Parent Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>SBQQ__PrimaryQuote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to primary quote on this opportunity.</description>
        <inlineHelpText>Salesforce CPQ uses this to point to the primary quote on this opportunity.</inlineHelpText>
        <label>Primary Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>PrimaryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContractHelper.cls
//This class is called from SetContractToExpiredReplacement trigger
public class ContractHelper {

     //This method updates Renewal Quote and Renewal opportunity's Renewal ACV field from Contract's Order ACV field.
    public static void UpdateRenewalQuote(set<Id> contractIds) { 
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        List<SBQQ__Quote__c> updateList = new List<SBQQ__Quote__c>();
        List<Opportunity> updateOpptyList = new List<Opportunity>();
        
        for(Contract con : [Select Id, Order_ACV__c, kuga_sub__RenewalOpportunity__c, kuga_sub__RenewalOpportunity__r.SBQQ__PrimaryQuote__c, 
                                    kuga_sub__RenewalOpportunity__r.SBQQ__PrimaryQuote__r.Renewal_ACV__c, kuga_sub__RenewalOpportunity__r.isClosed,
                                    kuga_sub__RenewalOpportunity__r.SBQQ__PrimaryQuote__r.ACV__c,
                                    kuga_sub__RenewalOpportunity__r.Renewal_ACV__c, 
                                    kuga_sub__RenewalOpportunity__r.SBQQ__PrimaryQuote__r.SBQQ__Status__c
                                    from Contract where Id IN: contractIds AND
                                    kuga_sub__RenewalOpportunity__r.RecordTypeId=:recordTypeId AND
                                    kuga_sub__RenewalOpportunity__r.SBQQ__PrimaryQuote__c != null]) {            
          
              if(con.Order_ACV__c != null) {                   
                  if(con.kuga_sub__RenewalOpportunity__r.SBQQ__PrimaryQuote__r.SBQQ__Status__c == 'Draft') {
                      SBQQ__Quote__c quote = new SBQQ__Quote__c(Id=con.kuga_sub__RenewalOpportunity__r.SBQQ__PrimaryQuote__c);                 
                      quote.Renewal_ACV__c = con.Order_ACV__c;      
                      updateList.add(quote);  
                      if(con.kuga_sub__RenewalOpportunity__r.isClosed == false) {                  
                          Opportunity opp = new Opportunity(Id=con.kuga_sub__RenewalOpportunity__c);
                          opp.Renewal_ACV__c = con.Order_ACV__c; 
                          //system.debug('****************'+opp.SBQQ__PrimaryQuote__r.ACV__c+opp.Renewal_ACV__c+opp.Quote_ACV__c);
                          /*if(opp.SBQQ__PrimaryQuote__r.ACV__c != null) {
                              opp.Incremental_ACV__c = opp.SBQQ__PrimaryQuote__r.ACV__c - opp.Renewal_ACV__c; 
                          } else {
                              opp.Incremental_ACV__c = 0 - opp.Renewal_ACV__c; 
                          }  */                           
                          updateOpptyList.add(opp);
                      } 
                  }              
              }                         
        }        
        if(updateList.size()>0 && !updateList.isEmpty()) {
             try {           
                update updateList;                    
             } catch(Exception e) {
                    System.debug(e);
             }               
        }  
        
        if(updateOpptyList.size()>0 && !updateOpptyList.isEmpty()) {
             try {           
                update updateOpptyList;                    
             } catch(Exception e) {
                    System.debug(e);
             }               
        }      
    }
}