objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ACV__c</fullName>
        <label>ACV</label>
        <summarizedField>Order.ACV__c</summarizedField>
        <summaryForeignKey>Order.ContractId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Key_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/kugo2p__KugamonSetting__c.object
<CustomObject>
    <description>Kugamon - Main object that controls Kugamon application behavior. Only one Kugamon Settings record is allowed. For Admin use only.</description>
    <label>Kugamon Setting</label>
    <nameField>
        <label>Kugamon Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kugamon Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountACVPopuplateSchedullerTest.cls
@isTest
private class AccountACVPopuplateSchedullerTest{
    @testSetup
    public static void setupMethod(){
        
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 p2 = TestDataFactory.createPricebook(); 
        p2.CurrencyIsoCode = 'EUR';
        insert p2; 
        
        Product2 p = TestDataFactory.createProduct('Enterprise', 'Licenses',null);
        p.Family='Membership fees';
        p.Credits_to_be_assigned__c=0;
        insert p;
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=p.Id, UnitPrice=5, IsActive=true,CurrencyIsoCode='EUR');
        insert standardPrice;
        
        Account a = TestDataFactory.createAccount('My Account', 'EUR');
        insert a;
        
        Contact con = TestDataFactory.createContact(a.Id,'Test');
        insert con;
        
        Id RecdTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New').getRecordTypeId();
        Opportunity o = TestDataFactory.createOpportunity(a,'My Opp','New Customer');
        o.RecordTypeId = RecdTypeId;
        insert o;
        
        OpportunityLineItem oli = TestDataFactory.createOpportunityLineItem(o.Id,standardPrice.id);
        insert oli;
        
        SBQQ__Quote__c quote = TestDataFactory.createCPQuote(o);
        insert quote;
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(p2.name); 
        insert testKugamonSetting;
        
        //Create contract
        Contract c = TestDataFactory.createDraftContract(a.Id, a.CurrencyIsoCode);
        c.Key_Contact__c = con.Id;
        c.Opportunity__c = o.Id;
        Insert c;
        //Update contract
        c.Status = 'Activated';
        update c;
        
    }
    static testMethod void testScheduler(){
        Test.startTest();
        AccountACVPopuplateBatch cb = New AccountACVPopuplateBatch();
        list<contract> contracts  =  new list<contract>([SELECT Id,AccountId,Account.ACV__c, Opportunity__c, Opportunity__r.ACV__c FROM Contract]);
        Database.QueryLocator ql = cb.start(null);
        cb.execute(null,contracts);
        cb.Finish(null);
        
        // AccountACVPopuplateBatch batchCtrl = new AccountACVPopuplateBatch(); 
        //Id BatchId = database.executebatch(batchCtrl);       
        AccountACVPopuplateSchedullerCron ctrl = new AccountACVPopuplateSchedullerCron();      
        //String cronExp = '0 30 0 ? * * *';
        //system.schedule('Account ACV Popuplate Scheduller', cronExp, ctrl);
        // system.assertNotEquals(null,ctrl, 'AccountACVPopuplateSchedullerCron controller instance is null.');
        Test.stopTest();
    }
}