objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Key_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The org to which the contract is applied.</inlineHelpText>
        <label>Salesforce Org</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (for Salesforce Org)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Copado_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Lead_Owner__c</fullName>
        <label>Default Lead Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Copado Settings</label>
</CustomObject>

objects/kugo2p__KugamonSetting__c.object
<CustomObject>
    <description>Kugamon - Main object that controls Kugamon application behavior. Only one Kugamon Settings record is allowed. For Admin use only.</description>
    <label>Kugamon Setting</label>
    <nameField>
        <label>Kugamon Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kugamon Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Next_Contact__c</fullName>
        <label>Next Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Step__c</fullName>
        <inlineHelpText>This field does not get mapped to the opportunity.</inlineHelpText>
        <label>Next Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <description>This field is used for the batch lead conversion and should be left blank.</description>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>License_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License User</label>
        <referenceTo>Salesforce_User__c</referenceTo>
        <relationshipLabel>Salesforce Orgs</relationshipLabel>
        <relationshipName>Salesforce_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensed_Seats__c</fullName>
        <label>Licensed Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Top_Up_Date__c</fullName>
        <inlineHelpText>This is a date which will be queried by Heroku to perform the top-ups on a daily basis</inlineHelpText>
        <label>Next Top-Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Corporate Entity to which the Salesforce Org is related.</description>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Salesforce Orgs</relationshipLabel>
        <relationshipName>Salesforce_Orgs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Expiration_Date__c</fullName>
        <label>Trial Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Channel Partner / Reseller</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_User__c.object
<CustomObject>
    <description>This object holds the Users linked to the Salesforce Orgs.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Salesforce Users</relationshipLabel>
        <relationshipName>Salesforce_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Salesforce User</label>
    <nameField>
        <displayFormat>SU-{0000000}</displayFormat>
        <label>Salesforce User Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameter__c.object
<CustomObject>
    <description>A custom object for storing feature parameters.  A new record is created of this object for every feature parameter that is ADDED as part of an uploaded package version. This record is automatically created upon the first package install of that package version.</description>
    <label>Feature Parameter</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Feature Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>Salesforce_User__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Expiration__c</fullName>
        <description>Expiration Date of the License, 1/1/1970 represents a perpetual license</description>
        <label>Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead generated from this install. This field becomes blank once the lead is converted to an account / contact in the lead conversion process</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>R00N30000001JvRAEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>sfLma__Package__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__Package__c.object
<CustomObject>
    <description>A Package Object represents information about the package as it is defined in the developer&apos;s Salesforce Organization. A record is created or updated each time a new version of the package is uploaded to AppExchange.</description>
    <fields>
        <fullName>sfLma__Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSalesforceOrgService.cls
@isTest
private class TestSalesforceOrgService {

    static testMethod void testSalesforceOrgService() {

        Copado_Settings__c custSet = TestDataFactory.createCopadoSetting();                
        custSet.Default_Lead_Owner__c = UserInfo.getUserId();
        insert custSet;
        
        Account a = TestDataFactory.createAccount('Fake Needed Account', 'EUR');
        insert a;

        Contact cntc = TestDataFactory.createContact(a.Id, 'Fake Needed Contact');
        cntc.Email = 'Theo' + 'testclass' + '@copa.do.testclass';
        insert cntc;

        Lead lead = TestDataFactory.createLead('Test', 'Copado Test');
        lead.FirstName = 'Org';
        lead.LeadSource = 'Package Installation';
        lead.Rating = 'Tier 2';
        lead.Next_Step__c = 'Next';
        lead.Next_Contact__c = System.today();
        lead.NumberOfEmployees = 98;
        lead.Industry = 'Banking and Finance';
        lead.Email = 'test@salesforce.org';
        insert lead;
        
        Salesforce_Org__c sforg = TestDataFactory.createSalesforceOrg('Test Method Org');
        sforg.OrgId__c = '00D1l0000000dkE';
        insert sforg;
        
        sfLma__License__c lic = TestDataFactory.createLicense(sforg.Id,5);
        lic.sfLma__Subscriber_Org_ID__c = 'COPADOTESTID';
        lic.sfLma__Expiration__c = Date.today()+1;
        lic.sfLma__Lead__c = lead.Id;
        insert lic;    
        
        sfLma__Package__c pack = TestDataFactory.craetePackage('Copado Deployer');
        pack.sfLma__Developer_Name__c = 'Copado BasePackage';
        insert pack;
        
        sfFma__FeatureParameter__c fpCCM = TestDataFactory.createFeatureParameter('copado__CCM_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        insert fpCCM;
        
        sfFma__FeatureParameter__c fpCAD = TestDataFactory.createFeatureParameter('copado__CAD_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        insert fpCAD;
        sfFma__FeatureParameter__c fpCCH = TestDataFactory.createFeatureParameter('copado__CCH_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
           
        insert fpCCH;
        sfFma__FeatureParameter__c fpCSTL = TestDataFactory.createFeatureParameter('copado__CST_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
         
        insert fpCSTL;
        sfFma__FeatureParameter__c fpEE =  TestDataFactory.createFeatureParameter('copado__EE_Licenses_Enabled',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        
        insert fpEE;
        sfFma__FeatureParameter__c fpCSTM =  TestDataFactory.createFeatureParameter('copado__CST_Minutes_Packages',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
        insert fpCSTM;
        sfFma__FeatureParameter__c fpCBM = TestDataFactory.createFeatureParameter('copado__CBM_Branches',
                                                                                  'Integer','copado',
                                                                                  '10.0','LMO to Subscriber', pack.Id);
          
        insert fpCBM;
        Test.startTest();

        //We convert the Lead into the Salesforce Org that will create the empty feature parameter integers
        Database.BatchableContext dbc;
        List<sfLma__License__c> batch_scope = new List<sfLma__License__c>();
        batch_scope.add(lic);
        LeadConvertBatch batchApex = new LeadConvertBatch();
        batchApex.execute(dbc, batch_scope);

        Salesforce_User__c user = [SELECT Id FROM Salesforce_User__c WHERE Email__c = 'test@salesforce.org' LIMIT 1];
        System.assert(user != null);
        Salesforce_Org__c org = [SELECT Id, OrgId__c, Org_Type__c, Licensed_Seats__c, Trial_Expiration_Date__c, License_User__c, Type__c, Next_Top_Up_Date__c FROM Salesforce_Org__c WHERE OrgId__c = :LeadConvertBatch.ID15to18('COPADOTESTID') LIMIT 1];
        System.assertEquals('Production', org.Org_Type__c);
        System.assertEquals(Date.today()+1, org.Trial_Expiration_Date__c);

        org.Parent_Account__c = a.Id;
        
        Pricebook2 pb = TestDataFactory.createPricebook(); 
        pb.CurrencyIsoCode = 'EUR';
        insert pb;           
        
        kugo2p__KugamonSetting__c testKugamonSetting = TestDataFactory.createKugamonSetting(pb.name); 
        insert testKugamonSetting ;
        
        Contract c = TestDataFactory.createDraftContract(a.Id, a.CurrencyIsoCode);
        c.StartDate = Date.today();
        c.ContractTerm = 12;
        insert c;    
        
        Contract con = TestDataFactory.createDraftContract(a.Id, a.CurrencyIsoCode);
        con.Key_Contact__c = cntc.Id;
        con.StartDate = Date.today()-1;              
        insert con;
        con.Status = 'Activated';
        update con;

        org.Type__c = 'Customer';
        update org;

        org = [SELECT Id, OrgId__c, Org_Type__c, Licensed_Seats__c, Trial_Expiration_Date__c, License_User__c, Type__c, Next_Top_Up_Date__c FROM Salesforce_Org__c WHERE OrgId__c = :LeadConvertBatch.ID15to18('COPADOTESTID') LIMIT 1];
        System.assertEquals(con.StartDate.addMonths(1), org.Next_Top_Up_Date__c);

        org.Type__c = 'Prospect';
        update org;
        org = [SELECT Id, OrgId__c, Org_Type__c, Licensed_Seats__c, Trial_Expiration_Date__c, License_User__c, Type__c, Next_Top_Up_Date__c FROM Salesforce_Org__c WHERE OrgId__c = :LeadConvertBatch.ID15to18('COPADOTESTID') LIMIT 1];
        System.assertEquals(null, org.Next_Top_Up_Date__c);

        Test.stopTest();
    }
}