objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Credentials are authenticated. The Environment may have multiple Credentials which correspond to different users of the same Environment.</description>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Custom_Signup_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by the wizard when a signup request is created via playground so that ProcessBuilder can handle updates.</inlineHelpText>
        <label>Custom Signup Request</label>
        <referenceTo>Signup_Request__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <formula>LEFT(Org_Credential__r.copado__Environment__r.copado__Org_ID__c,15)</formula>
        <label>Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trial_Org_Id__c</fullName>
        <formula>LEFT(Custom_Signup_Request__r.Created_Org_Id__c,15)</formula>
        <inlineHelpText>This is the Org ID derived from the Custom Signup Request record.</inlineHelpText>
        <label>Trial Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Using_Trial_Org__c</fullName>
        <formula>AND(
 Trial_Org_Id__c == Org_Id__c,
 NOT(ISBLANK(Trial_Org_Id__c)),
 NOT(ISBLANK(Org_Id__c))
)</formula>
        <inlineHelpText>Validates if the Trial Org Id and the authenticated org Id are equal</inlineHelpText>
        <label>Using Trial Org</label>
        <type>Checkbox</type>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <label>Org Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                </value>
                <value>
                    <fullName>CreateCoeCredential</fullName>
                </value>
                <value>
                    <fullName>CoE_Authorization</fullName>
                </value>
                <value>
                    <fullName>GitSetup</fullName>
                </value>
                <value>
                    <fullName>ProvisionLicenses</fullName>
                </value>
                <value>
                    <fullName>CreateEnvironment</fullName>
                </value>
                <value>
                    <fullName>CreateOrgCredentials</fullName>
                </value>
                <value>
                    <fullName>AuthorizeSandbox</fullName>
                </value>
                <value>
                    <fullName>AssignPermissionSet</fullName>
                </value>
                <value>
                    <fullName>ExecutePostInstallScript</fullName>
                </value>
                <value>
                    <fullName>CreateScratchOrgEnvironment</fullName>
                </value>
                <value>
                    <fullName>EnableUser</fullName>
                </value>
                <value>
                    <fullName>GitSetupFinish</fullName>
                </value>
                <value>
                    <fullName>CreateGitSnapshot</fullName>
                </value>
                <value>
                    <fullName>CreateBranches</fullName>
                </value>
                <value>
                    <fullName>CreateBoilerplate</fullName>
                </value>
                <value>
                    <fullName>AddingFinishingTouches</fullName>
                    <label>Adding Finishing Touches</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Output__c</fullName>
        <label>Output</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Sandbox Creation</fullName>
                </value>
                <value>
                    <fullName>Record Creation</fullName>
                </value>
                <value>
                    <fullName>Git</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Copado_Client_Key__c</fullName>
        <label>Copado Client Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Client_Id__c</fullName>
        <label>Github Client Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Github_Token_Url__c</fullName>
        <label>Github Token Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Integration_User_Id__c</fullName>
        <label>Integration User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Playground Setting</label>
    <pluralLabel>Playground Settings</pluralLabel>
</CustomObject>

objects/Signup_Request__c.object
<CustomObject>
    <description>This object captures the Signup Requests generated from the community and creates Trialforce orgs</description>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>33</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is populated by the Playground Wizard so that ProcessBuilder can update the job and UI changes can be triggered via Playground Job Events.</inlineHelpText>
        <label>Playground Job</label>
        <referenceTo>Playground_Job__c</referenceTo>
        <relationshipLabel>Signup Request</relationshipLabel>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <inlineHelpText>The username of the admin user for the trial sign-up. It must follow the address convention specified in RFC822: www.w3.org/Protocols/rfc822/#z10</inlineHelpText>
        <label>Username</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Custom Signup Request</label>
    <nameField>
        <displayFormat>SR{0000000000}</displayFormat>
        <label>Signup Request Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signup Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cps_PlaygroundWizardConnectController.cls
public without sharing class cps_PlaygroundWizardConnectController {

    // Get all the playground jobs for a given playground
    @AuraEnabled
    public static List<Playground_Job__c> getPlaygroundJobs(String playgroundId){
        return cps_PlaygroundWizardController.GetPlaygroundJobs(playgroundId);
    }

    @AuraEnabled
    public static Playground_Job__c updateJobStatus(String playgroundId, String jobId, String status) {
        return cps_PlaygroundWizardController.UpdateJobStatus(playgroundId, jobId, status);
    }

    // Calls copado API to create the authorization link for a given environment
    @AuraEnabled
    public static Map<String, Object> getAuthLink(String playgroundId, String redirectUrl){

        Map<String, Object> ret = new Map<String, Object>();
        Playground__c playground = [SELECT Org_Credential__c, Org_Credential__r.copado__Validated_Date__c, Org_Credential__r.copado__Username__c, Org_Credential__r.copado__Environment__c,
                                    Custom_Signup_Request__c, Custom_Signup_Request__r.Username__c, Custom_Signup_Request__r.Domain__c,
                                    Using_Trial_Org__c, Trial_Org_Id__c, Org_Id__c FROM Playground__c WHERE Id = :playgroundId LIMIT 1];
        Playground_Setting__mdt setting = [SELECT Copado_Client_Key__c, Integration_User_Id__c FROM Playground_Setting__mdt WHERE DeveloperName =: cps_Helper.SETTINGS_NAME];

        String actionName = 'CoE_Authorization';
        Playground_Job__c job = [SELECT Id, Status__c, Payload__c, Output__c FROM Playground_Job__c WHERE Playground__c = :playgroundId AND Action__c = :actionName LIMIT 1];

        Map<String, Object> payloadObj = new Map<String, Object>();
        payloadObj.put('action', actionName);
        Map<String, Object> data = new Map<String, Object>();

        if ( playground.Org_Credential__r.copado__Validated_Date__c==null ||
            (playground.Org_Credential__r.copado__Validated_Date__c!=null && playground.Using_Trial_Org__c==false) ) {
            system.debug('#### ENTERED BECAUSE: '+playground.Using_Trial_Org__c);
            String orgId = playground.Org_Credential__c;
            String copadoUserId = setting.Integration_User_Id__c;
            String copadoOrgId = UserInfo.getOrganizationId();
            String endpoint = 'https://app-api.copado.com/Authorize/loginCustomRedirect?' + 'orgId=' + orgId + '&copadoOrgId=' + copadoOrgId + '&copadoUserId=' + copadoUserId + '&startURL=' + redirectUrl + '&url=' + redirectUrl;
            String clientKey = setting.Copado_Client_Key__c;
            String username = (playground.Custom_Signup_Request__r.Username__c!=null)? playground.Custom_Signup_Request__r.Username__c: '';

            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpoint);
            request.setMethod('GET');
            request.setHeader('X-Client-Key', clientKey);

            // Send request
            HttpResponse httpResponse = http.send(request);
            if (httpResponse.getStatusCode() == 302) {
                String usernameString = (String.isNotBlank(username))?'&prompt=login%20consent&login_hint='+username : '';
                String authLink = httpResponse.getHeader('Location')+usernameString;
                authLink = authLink.replace('login.salesforce.com', playground.Custom_Signup_Request__r.Domain__c+'.my.salesforce.com');
                ret.put('authorization_url', authLink);
            }
        }
        if (playground.Org_Credential__r.copado__Validated_Date__c!=null && playground.Using_Trial_Org__c==false) {
            try{
                copado__Org__c org = new copado__Org__c(Id=playground.Org_Credential__c);
                org.copado__Validated_Date__c = null;
                org.copado__SFDC_Org_ID__c = null;
                org.copado__username__c = null;
                update org;

                payloadObj.put('hasError', true);
                String errorMessage = 'The Org that was just authenticated did not match the Copado Trial Org for this Playground. You must authenticate the Copado Trial Org created in the previous step to proceed.';
                data.put('message', errorMessage);
                job.Output__c = 'WRONG_ORG_AUTHENTICATED';
                payloadObj.put('data', data);
            }
            catch(Exception e){
                throw e;
            }
        }
        if (playground.Using_Trial_Org__c==true) {
            job.Status__c = 'Completed';
            job.Output__c = null;
            payloadObj.put('hasError', false);
        }
        job.Payload__c = JSON.serializePretty(payloadObj);
        update job;

        ret.put('job', job);
        return ret;
    }

    // Makes a call to C1P to run a script that generates a github auth token (doesn't expire) and creates a Repo
    // script: gitRepoSetup.js
    // Because we need to pass in the AuthCode returned by the browser, we cannot move this into a ProcessBuilder job.
    @AuraEnabled
    public static Playground_Job__c GitSetup(String playgroundId, String gitAuthCode) {
        Playground__c playground = [SELECT Org_Credential__c FROM Playground__c WHERE Id = :playgroundId LIMIT 1];
        Playground_Enviroment__c playgroundEnv = [SELECT Name, Org_Credential__c, Playground__r.Name FROM Playground_Enviroment__c WHERE Playground__c = :playgroundId AND Type__c = 'CoE_Org' LIMIT 1];
        Playground_Setting__mdt playgroundSettings = [SELECT Github_Token_Url__c, Github_Client_Id__c, Github_Client_Secret__c
                                                        FROM Playground_Setting__mdt
                                                        WHERE DeveloperName =: cps_Helper.SETTINGS_NAME];

        String actionName = 'GitSetup';
        Playground_Job__c job = [SELECT Status__c, Action__c, JobId__c FROM Playground_Job__c
                                 WHERE Playground__c = :playgroundId AND Action__c = :actionName LIMIT 1];

        if (job.Status__c != 'Completed') {
            Map<String, String> paramBody = new Map<String, String>();
            paramBody.put('C1P_ORGCREDENTIALID_CLIENT', playground.Org_Credential__c);
            paramBody.put('ACTION', actionName);
            paramBody.put('GIT_AUTHCODE', gitAuthCode);
            paramBody.put('GIT_ENDPOINT', playgroundSettings.Github_Token_Url__c);
            paramBody.put('GIT_CLIENT_ID', playgroundSettings.Github_Client_Id__c);
            paramBody.put('GIT_CLIENT_SECRET', playgroundSettings.Github_Client_Secret__c);
            paramBody.put('GIT_REPONAME', 'Copado-' + playgroundEnv.Playground__r.Name.replaceAll(' ', ''));
            String jobId = cps_Helper.StartC1PJob(paramBody);

            job.JobId__c = jobId;
            job.Status__c = 'In progress';

            try{
                update job;
            }catch(Exception e){
                throw e;
            }
        }

        return job;
    }

    @AuraEnabled
    public static Map<String, String> getGithubSettings() {
        Playground_Setting__mdt playgroundSetting = [SELECT Github_Auth_Url__c, Github_Client_Id__c
                                                     FROM Playground_Setting__mdt
                                                     WHERE QualifiedApiName =: 'Default_Values'
                                                     LIMIT 1];

        Map<String, String> ret = new Map<String, String>();
        ret.put('gitAuthUrl', playgroundSetting.Github_Auth_Url__c);
        ret.put('gitClientId', playgroundSetting.Github_Client_Id__c);

        return ret;
    }
}