objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Cancellation_Reason__c</fullName>
        <description>Describes why the User Story was cancelled, so that this information is available.</description>
        <inlineHelpText>Describes why the User Story was cancelled, so that this information is available.</inlineHelpText>
        <label>Cancellation Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestReleaseTrigger.cls
@isTest
private class TestReleaseTrigger {
     static testMethod void TestAfterUpdate(){
        copado__Release__c firstRelease = TestDataFactory.createCopadoRelease('firstRelease'); //new copado__Release__c(Name='firstRelease');
        copado__Release__c secondRelease = TestDataFactory.createCopadoRelease('secondRelease'); // new copado__Release__c(Name='secondRelease');
        copado__Environment__c BPEnvironment = TestDataFactory.createEnvironment('BP'); //new copado__Environment__c(Name='BP');
        copado__Environment__c NotBPEnvironment = TestDataFactory.createEnvironment('Production'); //new copado__Environment__c(Name='Production');
        copado__User_Story__c firstReleaseUS1 = new copado__User_Story__c();
        copado__User_Story__c firstReleaseUS2 = new copado__User_Story__c();
        copado__User_Story__c secondReleaseUS1 = new copado__User_Story__c();
        copado__User_Story__c secondReleaseUS2 = new copado__User_Story__c();
        copado__Release__c[] releases = new List<copado__Release__c>{firstRelease,secondRelease};
        copado__User_Story__c[] userStories = new List<copado__User_Story__c>{firstReleaseUS1,firstReleaseUS2,secondReleaseUS1,secondReleaseUS2};
        insert releases;
        insert BPEnvironment;
        insert NotBPEnvironment;

        firstReleaseUS1.copado__Release__c = firstRelease.id;
        firstReleaseUS1.copado__Environment__c = BPEnvironment.id;
        firstReleaseUS1.copado__Status__c ='Ready for testing';
        secondReleaseUS1.copado__Status__c ='Cancelled';
        secondReleaseUS1.copado__Cancellation_Reason__c='Bad Commited';

        firstReleaseUS2.copado__Release__c = firstRelease.id;
        firstReleaseUS2.copado__Environment__c = BPEnvironment.id;
        secondReleaseUS1.copado__Release__c = firstRelease.id;
        secondReleaseUS1.copado__Environment__c = BPEnvironment.id;
        secondReleaseUS2.copado__Release__c = secondRelease.id;
        secondReleaseUS2.copado__Environment__c = NotBPEnvironment.id;
        insert userStories;

        firstRelease.copado__Status__c = 'Released';
        secondRelease.copado__Status__c = 'Released';
        update releases;

        //
        firstReleaseUS1.copado__Status__c = [select copado__Status__c from copado__User_Story__c where  id = :firstReleaseUS1.id limit 1].copado__Status__c;
        firstReleaseUS2.copado__Status__c = [select copado__Status__c from copado__User_Story__c where  id = :firstReleaseUS2.id limit 1].copado__Status__c;
        secondReleaseUS1.copado__Status__c = [select copado__Status__c from copado__User_Story__c where  id = :secondReleaseUS1.id limit 1].copado__Status__c;
        secondReleaseUS2.copado__Status__c = [select copado__Status__c from copado__User_Story__c where  id = :secondReleaseUS2.id limit 1].copado__Status__c;
    
    
        System.assertEquals(firstRelease.copado__Status__c,'Released');
        System.assertEquals(secondRelease.copado__Status__c,'Released');

        System.assertEquals('Released',firstReleaseUS1.copado__Status__c);
        System.assertEquals('Released',firstReleaseUS2.copado__Status__c);
        System.assertNotEquals('Released',secondReleaseUS1.copado__Status__c);
        System.assertEquals('Released',secondReleaseUS2.copado__Status__c);

        //For Test Coverage, Remove if Delete or Undelete is tested in another Method. 
        User adminUser = [SELECT Id FROM User WHERE Profile.Name ='System Administrator' AND isActive=true AND UserRole.Name ='System Administrator' LIMIT 1];
        System.runAs(adminUser) {
            delete releases;
        }
        undelete releases;

     }
    
}