objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/cps_InteractiveMudule_UtilsTest.cls
@isTest
public without sharing class cps_InteractiveMudule_UtilsTest {

    @testSetup 
    static void methodName() {
        copado.GlobalAPI.UserLicense copadoUserLicense = new copado.GlobalAPI.UserLicense(UserInfo.getUserId(),false,false,false,true,false);
        copado.GlobalAPI gapi = new copado.GlobalAPI();
        gapi.upsertCopadoLicense(UserInfo.getUserId(), copadoUserLicense);


        cps_PlaygroundWizardStartControllerTest.setup();
        User testUser = [select Id from User where Username='demo5645@handomdemodomainz.djw.cmq' limit 1];
        Playground__c thePlaygroundScratchOrg = new Playground__c();
        System.runAs(testUser){
            thePlaygroundScratchOrg = cps_PlaygroundWizardStartController.createPlayground('Test IV Playground Scratch Orgs', 'Full Configuration - Scratch Orgs');
            Test.setCreatedDate(thePlaygroundScratchOrg.Id, Date.today().addDays(-31));
        }

        Id adminProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
        User adminUser = new User(
            Alias = 'myalias', Email = 'testadminemail@emailtest.com',
                EmailEncodingKey = 'UTF-8', LastName = 'TestUser',
                LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US',
                ProfileId = adminProfileId, Country='United States', IsActive =true,
                TimezoneSidKey='America/Los_Angeles', Username='testadminemail@handomdemodomainz.djw.cmq');

        insert adminUser;
        System.runAs(adminUser){
            thePlaygroundScratchOrg.Status__c = 'Activated';
            update thePlaygroundScratchOrg;
        }
    }
    
    static testMethod void unitTests () {
        cps_InteractiveMudule_Utils.checkOrgType();

        String payload = '{"hasError":false}';
        cps_InteractiveMudule_Utils.parsePayload(payload);

        User testUser = [select Id from User where Username='demo5645@handomdemodomainz.djw.cmq' limit 1];
        System.runAs(testUser){
            List<Playground__c> playgrounds = cps_InteractiveMudule_Utils.getPlaygroundRecords();
        	system.assertEquals(1, playgrounds.size());
        }
    }

    static testMethod void testCreateFrontDoorRequest() {
        copado__Org__c o = new copado__Org__c(Name='test');
        insert o;
        
        cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', '', new Map<String,String>());
        Test.setMock(HttpCalloutMock.class, mock);
        
        test.startTest();
        cps_InteractiveMudule_Utils.createFrontDoorRequest(o.Id, null);
        test.stopTest();
    }
    
    static testMethod void testGetPlaygroundEnv() {
        cps_C1PJobMock mock = new cps_C1PJobMock(200, 'OK', '', new Map<String,String>());
        Test.setMock(HttpCalloutMock.class, mock);

        Playground__c playground = [SELECT Id FROM Playground__c WHERE Name = 'Test IV Playground Scratch Orgs'];
        List<Playground_Enviroment__c> playgroundEnvs = new List<Playground_Enviroment__c>();

        if (playground != null) {
            playgroundEnvs = cps_InteractiveMudule_Utils.getPlaygroundEnv(playground.Id);
        }
        
        test.startTest();
        if (!playgroundEnvs.isEmpty()) {
            cps_InteractiveMudule_Utils.getFrontDoorUrl(playgroundEnvs[0].Id);
        }
        test.stopTest();
    }
}