objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Custom_Signup_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated by the wizard when a signup request is created via playground so that ProcessBuilder can handle updates.</inlineHelpText>
        <label>Custom Signup Request</label>
        <referenceTo>Signup_Request__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Playground_Configuration__c</fullName>
        <inlineHelpText>Full configuration will create all records for your playground including the complete pipeline. Choose light configuration only if you have been specifically instructed to do so</inlineHelpText>
        <label>Playground Configuration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Configuration</fullName>
                    <default>true</default>
                    <label>Full Configuration</label>
                </value>
                <value>
                    <fullName>Light Configuration</fullName>
                </value>
                <value>
                    <fullName>Full Configuration - Scratch Orgs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorization_URL__c</fullName>
        <label>Authorization URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InstanceUrl__c</fullName>
        <label>InstanceUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Sandbox Creation</fullName>
                </value>
                <value>
                    <fullName>Record Creation</fullName>
                </value>
                <value>
                    <fullName>Git</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>C1P_API_Key__c</fullName>
        <label>C1P API Key</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copado_Client_Key__c</fullName>
        <label>Copado Client Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Playground Setting</label>
    <pluralLabel>Playground Settings</pluralLabel>
</CustomObject>

objects/Signup_Request__c.object
<CustomObject>
    <description>This object captures the Signup Requests generated from the community and creates Trialforce orgs</description>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>33</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is populated by the Playground Wizard so that ProcessBuilder can update the job and UI changes can be triggered via Playground Job Events.</inlineHelpText>
        <label>Playground Job</label>
        <referenceTo>Playground_Job__c</referenceTo>
        <relationshipLabel>Signup Request</relationshipLabel>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Signup Request</label>
    <nameField>
        <displayFormat>SR{0000000000}</displayFormat>
        <label>Signup Request Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signup Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cps_PlaygroundWizardSetupController.cls
public without sharing class cps_PlaygroundWizardSetupController {
  static final String BASE_COE_LOGIN_URL = 'https://login.salesforce.com';
  static final String BASE_SANDBOX_LOGIN_URL = 'https://test.salesforce.com';
  static final String SCRATCH_ORG_PLAYGROUND_TYPE = 'Full Configuration - Scratch Orgs';
  static final String COE_ORG_TYPE = 'CoE_Org';
  static final String SCRATCH_ORG_ORG_TYPE = 'Scratch_Org';

  @AuraEnabled
  public static Map<String, Object> getPlaygroundDetails(String playgroundId){
    return cps_PlaygroundWizardController.getPlaygroundDetails(playgroundId);
  }

  @AuraEnabled
  public static List<Playground_Job__c> getPlaygroundJobs(String playgroundId){
    return cps_PlaygroundWizardController.GetPlaygroundJobs(playgroundId);
  }

  @AuraEnabled
  public static Playground_Job__c updateJobStatus(String playgroundId, String jobId, String status) {
    return cps_PlaygroundWizardController.UpdateJobStatus(playgroundId, jobId, status);
  }

  @AuraEnabled
  public static Map<string, string> GetEnvironmentAuthorizationLinks(String playgroundId) {

    Playground__c playground = [SELECT Org_Credential__r.copado__Username__c, Custom_Signup_Request__r.Domain__c, Playground_Configuration__c FROM Playground__c WHERE Id = :playgroundId LIMIT 1];

    List<Playground_Enviroment__c> environments = [SELECT Name, Authorization_URL__c, Type__c,Access_Token__c ,InstanceUrl__c  FROM Playground_Enviroment__c WHERE Playground__c = :playgroundId LIMIT 9];
    Playground_Setting__mdt setting = [SELECT Copado_Client_Key__c, C1P_API_Key__c FROM Playground_Setting__mdt WHERE DeveloperName =: cps_Helper.SETTINGS_NAME LIMIT 1];

    Map<string, string> ret = new Map<string, string>();
    for (Playground_Enviroment__c e : environments) {
      Http http = new Http();
      HttpRequest request = new HttpRequest();
      request.setEndpoint(e.Authorization_URL__c);
      request.setMethod('GET');
      request.setHeader('X-Client-Key', setting.Copado_Client_Key__c);

      // Send request
      HttpResponse httpResponse = http.send(request);
      if (httpResponse.getStatusCode() == 302) {
        String authLink = httpResponse.getHeader('Location');
        String loginHint = '&login_hint=' + EncodingUtil.urlEncode(playground.Org_Credential__r.copado__Username__c + (e.Type__c == COE_ORG_TYPE ? '' : '.' + e.Name), 'UTF-8' ).toLowerCase();

        if(authLink.contains(BASE_COE_LOGIN_URL)){
          Http httpCoE_Org = new Http();
          HttpRequest requestCoE_Org = new HttpRequest();
          requestCoE_Org.setEndpoint('https://app-api.copado.com/json/v1/webhook/copadoSession/' + playground.Org_Credential__c + '?api_key=' + setting.C1P_API_Key__c);
          requestCoE_Org.setMethod('GET');
          requestCoE_Org.setHeader('X-Client-Key', setting.Copado_Client_Key__c);

          try{
            HttpResponse httpResponseCoE_Org = httpCoE_Org.send(requestCoE_Org);
            Map<String, Object> parsedResponse = parseJSON(httpResponseCoE_Org.getBody());
            String frontdoorUrl =  String.valueOf(parsedResponse.get('frontDoor'));

            String retUrl  = authlink.SubStringAfter(BASE_COE_LOGIN_URL);
            retUrl = retUrl.replace('prompt=login%20consent&', '');
            authlink = frontdoorUrl + '&retURL=' + EncodingUtil.urlEncode(retUrl, 'UTF-8');
          } catch(Exception excp) {
            throw excp;
          }
        } else if(authLink.contains(BASE_SANDBOX_LOGIN_URL)){
          if (SCRATCH_ORG_PLAYGROUND_TYPE == playground.Playground_Configuration__c && SCRATCH_ORG_ORG_TYPE == e.Type__c ) {
            String retUrl  = authlink.SubStringAfter(BASE_SANDBOX_LOGIN_URL);
            retUrl = retUrl.replace('prompt=login%20consent&', '');
            String frontdoorUrl = e.InstanceUrl__c + 'secur/frontdoor.jsp?sid=' + e.Access_Token__c;
            authlink = frontdoorUrl + '&retURL=' + EncodingUtil.urlEncode(retUrl, 'UTF-8');

          } else {
            authLink = authLink.replace(BASE_SANDBOX_LOGIN_URL, 'https://'+playground.Custom_Signup_Request__r.Domain__c+ (e.Type__c == COE_ORG_TYPE ? '' : '--' + e.Name).toLowerCase() + '.my.salesforce.com');
          }
        }
        ret.put(e.Name, authLink + loginHint);
      }
    }
    return ret;
  }

  private static Map<String, Object> parseJSON(String payloadString) {
    if(payloadString==null) return new Map<String, Object>();

    Map<String, Object> payloadObj = new Map<String, Object>();
    try{
      payloadObj = (Map<String, Object>) JSON.deserializeUntyped(payloadString);
    }
    catch(Exception e) {
      system.debug(payloadString);
      system.debug('@@@ Error parsing payloadString: '+e.getMessage());
    }
    return payloadObj;
  }
}