objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <formula>LEFT(Org_Credential__r.copado__Environment__r.copado__Org_ID__c,15)</formula>
        <label>Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Indicates the stage of the playground creation. If stage is not Completed when a user returns to a playground the user will land the said stage.</description>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                    <default>true</default>
                    <label>CreateTrialOrg</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
                <value>
                    <fullName>PostInstallScript</fullName>
                </value>
                <value>
                    <fullName>Setup</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                    <isActive>false</isActive>
                    <label>Install</label>
                </value>
                <value>
                    <fullName>Start</fullName>
                    <isActive>false</isActive>
                    <label>Start</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <label>Org Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>JobId__c</fullName>
        <externalId>true</externalId>
        <label>Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Sandbox Creation</fullName>
                </value>
                <value>
                    <fullName>Record Creation</fullName>
                </value>
                <value>
                    <fullName>Git</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>sfLma__Install_Date__c</fullName>
        <description>The Date this Package Version was initially installed by the developer. (Does not get updated as part of upgrades.)</description>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__License_Type__c</fullName>
        <description>This field indicates the type of license record. For example, if the license record is &quot;Read-Only&quot;, this license record cannot be modified.</description>
        <label>License Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Package_License_ID__c</fullName>
        <description>ID of package license for uninstall tracking</description>
        <label>Package License ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Seats__c</fullName>
        <description>number of seats covered by license</description>
        <label>Seats</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sfLma__Status__c</fullName>
        <description>This is the Status of the Package License in the Subscriber Org</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Uninstalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Used_Licenses__c</fullName>
        <label>Used Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cps_PlaygroundWizardFinishTest.cls
@isTest
private class cps_PlaygroundWizardFinishTest {

    /*
     * Setup for test. Creation of records.
     */
    @testSetup public static void testSetup() {
        cps_PlaygroundWizardStartControllerTest.setup();
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        Contact c = new Contact(LastName = 'Test');
        insert c;
        
        User u = new User(Alias = 'standt1',
                          Country='United Kingdom',
                          Email='demo8339@handomdemodomainz.djw.cmq',
                          EmailEncodingKey='UTF-8',
                          LastName='Testing',
                          ProfileId = p.Id,
                          LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US',
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName='demo8339@handomdemodomainz.djw.cmq');
        insert u;
        
        copado__Org__c o = new copado__Org__c(
            Name = 'TestOrg',
            copado__SFDC_Org_ID__c = '00Df4000003AqJXEA0_0050N000007nP8CQAU_3',
            copado__Org_Type__c = 'Production/Developer');
        insert o;
        String orgId = o.Id;
        
        Playground__c pg = new Playground__c(Name='Test Playground', Org_Credential__c=orgId, Contact__c=c.Id);
        insert pg;
        String pgId = pg.Id;
        //cps_PlaygroundWizardSetupController.SaveCopadoApiKey(pgId, 'e8284d79c0173d1a5dadd2c7ec3d9a22');
        
        Playground_Job__c pgJob = new Playground_Job__c(Name='Playground Job Test', JobId__c='818bcb93-1ac9-4d36-8261-eb83030fe75c', Playground__c=pgId);
        insert pgJob;
        String pgJobId = pgJob.Id;
        String copadoJobId = pgJob.JobId__c;
        
        Playground_Enviroment__c pgEnv = new Playground_Enviroment__c(Name='Playground Environment Test', Type__c='CoE_Org', Playground__c=pgId, Org_Credential__c=orgId, Org_Id__c='00D20000000m7c0EAA');
        insert pgEnv;

        sfLma__License__c license = new sfLma__License__c();
        license.sfLma__Status__c='Active';
        license.sfLma__Subscriber_Org_ID__c='00D20000000m7c0EAA';
        license.sfLma__Used_Licenses__c = 1;
        license.sfLma__Seats__c = -1;	         
        license.sfLma__Install_Date__c = system.today();
        license.sfLma__License_Type__c = 'Editable';
        license.sfLma__Package_License_ID__c = 'some package id';
        insert license;
    }
    
    @isTest static void testActivatePlayground() {
        List<Playground__c> pglist = [SELECT Id FROM Playground__c WHERE Name = 'Test Playground'];
        Id pgId = pglist[0].Id;
        
        Test.startTest();
            cps_PlaygroundWizardFinishController.ActivatePlayground(pgId);
            Playground__c pg = [SELECT Status__c, Stage__c FROM Playground__c WHERE Id =: pgId LIMIT 1];
            System.assertEquals(pg.Status__c, 'Activated');
            System.assertEquals(pg.Stage__c, 'Completed');
        Test.stopTest();
    }
    
    @isTest static void testDeletePlayground() {
        List<Playground__c> pglist = [SELECT Id FROM Playground__c WHERE Name = 'Test Playground'];
        Id pgId = pglist[0].Id;
        String errorMsg = '';
        
        Test.startTest();
            cps_PlaygroundWizardFinishController.DeletePlayground(pgId);
            try {
                Playground__c pg = [SELECT Id FROM Playground__c WHERE Id =: pgId LIMIT 1];
            } catch (Exception e) {
                errorMsg = e.getMessage();
            }
            System.assertEquals(errorMsg, 'List has no rows for assignment to SObject');
        Test.stopTest();
    }
    
    
}