objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReleaseTriggerHelper.cls
public with sharing class ReleaseTriggerHelper {
	
	private static Map<Id, List<copado__User_Story__c>> releases = new Map<Id, List<copado__User_Story__c>>();
	public static List<copado__User_Story__c> userStoriesToUpdate = new List<copado__User_Story__c>();

	public static void changeUserStoriesStatus(copado__Release__c oldSoRelease, copado__Release__c soRelease){ 

		if(releases.containsKey(soRelease.Id) && 
			(oldSoRelease.copado__Status__c != soRelease.copado__Status__c && soRelease.copado__Status__c == 'Released')){
			for (copado__User_Story__c us :releases.get(soRelease.Id)){
				us.copado__Status__c='Released';
				userStoriesToUpdate.add(us);
			}
		}	
	}

	public static void prepareData (Set<Id>  releasesId){
	for (copado__User_Story__c userStory : [SELECT Id, copado__Status__c, copado__Release__c FROM copado__User_Story__c WHERE
		copado__Status__c !='Cancelled' AND ((copado__Environment__r.Name LIKE '%BP%' OR copado__Environment__r.Name LIKE '%Patch%') AND copado__Release__c IN :releasesId)]){

			if(releases.containsKey(userStory.copado__Release__c)){
				List<copado__User_Story__c> listOfUS = releases.get(userStory.copado__Release__c);
				listOfUS.add(userStory);
			}
			else {
				List<copado__User_Story__c> listOfUS = new List<copado__User_Story__c>();
				listOfUS.add(userStory);
				releases.put(userStory.copado__Release__c,listOfUS);
			}
		}	
	}

	public static void updateUserStoriesStatus (){
		update userStoriesToUpdate;
	}
}