objects/Copado_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Lead_Owner__c</fullName>
        <label>Default Lead Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Copado Settings</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>OrgId__c</fullName>
        <description>This field is used for the batch lead conversion and should be left blank.</description>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Tokens__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for Service Token to confirm authenticity of inbound webService requests.</description>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Tokens</label>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Force_to_remain_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Force to remain Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Package_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package Version</label>
        <referenceTo>sfLma__Package_Version__c</referenceTo>
        <relationshipName>R00N30000001JvQxEAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Seats__c</fullName>
        <description>number of seats covered by license</description>
        <label>Seats</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sfLma__Status__c</fullName>
        <description>This is the Status of the Package License in the Subscriber Org</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Uninstalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Version_Number__c</fullName>
        <label>Version Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__Package_Version__c.object
<CustomObject>
    <description>This object represents a specific version of a package uploaded by the developer to the AppExchange. Licenses relate to this object, since a user has a specific version installed in their Salesforce organization.</description>
    <fields>
        <fullName>sfLma__Version_Number__c</fullName>
        <label>Version Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Package Version</label>
    <nameField>
        <label>Package Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCopadoLicenseService.cls
@isTest
public class TestCopadoLicenseService {
    static testMethod void testAccessAuthorizationMissingKey(){
        sfLma__License__c license = testLicenseHelper.createTestLicense(null);
        String postBody = TestLicenseHelper.getInput();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/updateLicense/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(postBody);
        
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        Test.stopTest();
        
        Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        String errorMessage = 'UNAUTHORIZED: You must specify a valid "apiKey"';
        system.assertEquals(401, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        system.assertEquals(errorMessage, wsr.statusMessage);
    }
    static testMethod void testAccessAuthorizationBadKey(){
        sfLma__License__c license = testLicenseHelper.createTestLicense(null);
        String postBody = TestLicenseHelper.getInput();
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/updateLicense/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(postBody);
        req.addHeader('apiKey', 'badKey');
        
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        Test.stopTest();
        
        Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        String errorMessage = 'UNAUTHORIZED: You must specify a valid "apiKey"';
        system.assertEquals(401, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        system.assertEquals(errorMessage, wsr.statusMessage);
    }
    static testMethod void testLicenseNotFoundException(){
        sfLma__License__c license = testLicenseHelper.createTestLicense(null);
        String postBody = TestLicenseHelper.getInput();
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/updateLicense/00DWrongId00D'; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(postBody);
        
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        Test.stopTest();
        
        Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        String errorMessage = 'Could not find license with orgId ("00DWrongId00D"): List has no rows for assignment to SObject';
        system.assertEquals(500, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        system.assertEquals(errorMessage, wsr.statusMessage);
    }
    static testMethod void testGetMethodSuccess(){
        Lead testLead = TestLicenseHelper.createTestLead();
        sfLma__License__c license = TestLicenseHelper.createTestLicense(testLead.Id);

        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/updateLicense/00D20000000m7c0EAA';
        req.httpMethod = 'GET';
        
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String licenseNumber = CopadoLicenseService.getLicenseByOrgId();
        Test.stopTest();
        
        system.assertEquals(license.sfLma__Package_Version__r.sfLma__Version_Number__c, licenseNumber);        
    }    
    static testMethod void testInvalidURL(){
        sfLma__License__c license = testLicenseHelper.createTestLicense(null);
        String postBody = TestLicenseHelper.getInput();
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/something/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(postBody);
    
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        Test.stopTest();
        
        Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        String errorMessage = 'The URL was parsed but the "provisionLicenses", "convertLead", "updateLicense" strings were not found. URL received:'+req.requestURI;
        system.assertEquals(500, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        system.assertEquals(errorMessage, wsr.statusMessage);
    }
    static testMethod void testPostEmptyBody_provisionLicenses(){
        sfLma__License__c license = testLicenseHelper.createTestLicense(null);
        String postBody = TestLicenseHelper.getInput();
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/provisionLicenses/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = null;
    
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        	Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        	LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        	system.assertEquals(500, wsr.status);
        	system.assertEquals(false, wsr.isSuccess);
        	system.assertEquals( 'When doing a POST, the body cannot be left empty.', wsr.statusMessage);
        Test.stopTest();
    }
    static testMethod void testPostEmptyBody_updateLicense(){
        sfLma__License__c license = testLicenseHelper.createTestLicense(null);
        String postBody = TestLicenseHelper.getInput();
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/updateLicense/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = null;
    
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        	Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        	LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        	system.assertEquals(500, wsr.status);
        	system.assertEquals(false, wsr.isSuccess);
        	system.assertEquals( 'When doing a POST, the body cannot be left empty.', wsr.statusMessage);
        Test.stopTest();
    }
    static testMethod void testPostSuccessProvisionLicenses(){
        
        Copado_Settings__c c = new Copado_Settings__c(Name='Default', Default_Lead_Owner__c=UserInfo.getUserId());
        insert c;
        
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c=UserInfo.getOrganizationId());
        insert org;

        Lead testLead = testLicenseHelper.createTestLead();
        sfLma__License__c license = testLicenseHelper.createTestLicense(testLead.Id);
		testLicenseHelper.createPackageAndFeatures();
        LicenseHelper.convertLeadToLicense(license.Id);
        
        
        String postBody = TestLicenseHelper.getInput();
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/provisionLicenses/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(postBody);
    
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        	Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        	LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        	//system.assertEquals(201, wsr.status);
        	//system.assertEquals(true, wsr.isSuccess);
        Test.stopTest();
    }
    static testMethod void testPostSuccessUpdateLicenses(){
        
        Copado_Settings__c c = new Copado_Settings__c(Name='Default', Default_Lead_Owner__c=UserInfo.getUserId());
        insert c;
        
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c='00D20000000m7c0EAA');
        insert org;

        Lead testLead = testLicenseHelper.createTestLead();
        sfLma__License__c license = testLicenseHelper.createTestLicense(testLead.Id);
		testLicenseHelper.createPackageAndFeatures();
        LicenseHelper.convertLeadToLicense(license.Id);
        
        String postBody = '{"status":"Suspended", "forceactive":true, "licenses":10}';
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/updateLicense/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(postBody);
    
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        	Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        	LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        	system.assertEquals(201, wsr.status);
        	system.assertEquals(true, wsr.isSuccess);
        	license = [select Id, Force_to_remain_Active__c, sfLma__Seats__c, sfLma__Status__c from sfLma__License__c where Id= :license.Id limit 1];
        	system.assertEquals(true, license.Force_to_remain_Active__c);
        	system.assertEquals(10, license.sfLma__Seats__c);
        	system.assertEquals('Suspended', license.sfLma__Status__c);
        Test.stopTest();
    }
    static testMethod void testPostSuccessConvertLead(){
        
        Copado_Settings__c c = new Copado_Settings__c(Name='Default', Default_Lead_Owner__c=UserInfo.getUserId());
        insert c;
        
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c='00D20000000m7c0EAA');
        insert org;

        Lead testLead = TestLicenseHelper.createTestLead();
        sfLma__License__c license = TestLicenseHelper.createTestLicense(testLead.Id);

        TestLicenseHelper.createPackageAndFeatures();
        
        
        String postBody = TestLicenseHelper.getInput();
        String apiKey = generateAPIkey();
        RestRequest req = new RestRequest();
        req.addHeader('apiKey', apiKey);
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CopadoLicenseService/convertLead/'+license.sfLma__Subscriber_Org_ID__c; //Request URL
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(postBody);
    
        RestContext.request = req;
        RestContext.response= res;
    	
        Test.startTest();
        	String result = CopadoLicenseService.enterMethods();
        	Object wsro = JSON.deserialize(result, System.Type.forName('LicenseHelper.webServiceResult'));
        	LicenseHelper.webServiceResult wsr = (LicenseHelper.webServiceResult)wsro;
        	system.assertEquals(201, wsr.status);
        	system.assertEquals(true, wsr.isSuccess);
        	system.assertEquals('Lead successfully converted and Account deleted.', wsr.statusMessage);
        Test.stopTest();
    }

    private static String generateAPIkey(){
        Service_Tokens__c st = new Service_Tokens__c(Name='AcademyCommunityIntegration');
        st.Token__c = 'abcd1234';
		insert st;
        return st.Token__c;
    }
}