objects/copado1p__Platform_Job__c.object
<CustomObject>
    <description>This object defines the Job that Copado 1 Platform can run</description>
    <fields>
        <fullName>copado1p__Branch__c</fullName>
        <description>The branch of the defined repository where copado_start.sh should exist</description>
        <inlineHelpText>The branch of the defined repository where copado_start.sh should exist</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado1p__Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository record where external code is.</description>
        <inlineHelpText>Git Repository record where external code is.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>copado__Git_Repository__c</referenceTo>
        <relationshipLabel>Platform Jobs</relationshipLabel>
        <relationshipName>Platform_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado1p__VM_Provider__c</fullName>
        <description>Virtual Machine Provider, the external platform where VM will be initialised and Job will be executed.</description>
        <inlineHelpText>Virtual Machine Provider, the external platform where VM will be initialised and Job will be executed.</inlineHelpText>
        <label>VM Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>copado1p__VM_Providers</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado1p__isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether this job may be run. Inactive jobs will not be executed.</description>
        <inlineHelpText>Determines whether this job may be run. Inactive jobs will not be executed.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Platform Job</label>
    <nameField>
        <label>Platform Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platform Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado1p__Platform_Job_Execution__c.object
<CustomObject>
    <description>This object is used to track every C1P job execution, one will be created per each request.</description>
    <fields>
        <fullName>copado1p__Copado_Job_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>This job Id is returned by Copado when an execution is started.</inlineHelpText>
        <label>Copado Job ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>copado1p__Platform_Job__c</fullName>
        <label>Platform Job</label>
        <referenceTo>copado1p__Platform_Job__c</referenceTo>
        <relationshipLabel>Platform Job Executions</relationshipLabel>
        <relationshipName>Platform_Job_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado1p__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Starting</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Platform Job Execution</label>
    <nameField>
        <displayFormat>PJE-{00000}</displayFormat>
        <label>Platform Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Job Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/copado1p__VM_Providers.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Heroku</fullName>
        <default>true</default>
        <label>Heroku</label>
    </customValue>
    <description>Virtual Machine Providers</description>
    <masterLabel>VM Providers</masterLabel>
</GlobalValueSet>

classes/PlatformJobExecutionTriggerHelperTest.cls
@isTest
public with sharing class PlatformJobExecutionTriggerHelperTest {
    
    @testSetup 
    static void methodName() {
        copado.GlobalAPI.UserLicense copadoUserLicense = new copado.GlobalAPI.UserLicense(UserInfo.getUserId(),false,false,false,true,false);
        copado.GlobalAPI gapi = new copado.GlobalAPI();
        gapi.upsertCopadoLicense(UserInfo.getUserId(), copadoUserLicense);
    }
    
    static testMethod void unitTests () {
        copado__Git_Repository__c gr = new copado__Git_Repository__c();
        insert gr;

        copado1p__Platform_Job__c pj = new copado1p__Platform_Job__c(Name='C1P Rules Job');
        pj.copado1p__isActive__c = true;
        pj.copado1p__Git_Repository__c = gr.id;
        pj.copado1p__Branch__c = 'master';
        pj.copado1p__VM_Provider__c = 'Heroku';
        pj.copado1p__Branch__c = 'standard-1x';
        insert pj;

        copado1p__Platform_Job_Execution__c pje = new copado1p__Platform_Job_Execution__c(copado1p__Platform_Job__c=pj.Id, copado1p__Status__c = 'Running', copado1p__Copado_Job_ID__c = '12345678');
        insert pje;

        Test.startTest();
        pje.copado1p__Status__c = 'Failure';
        update pje;
        Test.stopTest();
    }
}