objects/copado__Pull_Request__c.object
<CustomObject>
    <fields>
        <fullName>copado__State__c</fullName>
        <description>The state of the pull request</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Pull Requests</relationshipLabel>
        <relationshipName>Pull_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/copado__Pull_Request_Review__c.object
<CustomObject>
    <fields>
        <fullName>copado__Pull_Request__c</fullName>
        <label>Pull Request</label>
        <referenceTo>copado__Pull_Request__c</referenceTo>
        <relationshipName>Pull_Request_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Review_Action__c</fullName>
        <label>Review Action</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Review_Id__c</fullName>
        <externalId>true</externalId>
        <label>Review Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUpdateUserStoryDependsOnPullRRFlow.cls
@IsTest
public class TestUpdateUserStoryDependsOnPullRRFlow {
@testSetup static void setup() {      
        Id recordTypeIdUserStory = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('User Story').getRecordTypeId();
        copado__User_Story__c myUserStory = new copado__User_Story__c();
        myUserStory.copado__User_Story_Title__c = 'UserStoryTest1';
        myUserStory.copado__Status__c = 'Draft';
        myUserStory.RecordTypeId = recordTypeIdUserStory;
        insert myUserStory;
        
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        copado__Pull_Request__c pullRequest = new copado__Pull_Request__c();
        pullRequest.copado__User_Story__c = createdUserStory.Id;
    	pullRequest.copado__State__c = 'Opened';
		insert pullRequest;

    }
    
    @IsTest
    static void testPullRequestReviewApproved() {   
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        copado__Pull_Request__c createdPullRequest = [SELECT Id FROM copado__Pull_Request__c WHERE copado__User_Story__c = :createdUserStory.Id];
		copado__Pull_Request_Review__c createdPullRequestReview = new copado__Pull_Request_Review__c();
        createdPullRequestReview.copado__Review_Id__c = 'frantest1';
        createdPullRequestReview.copado__Pull_Request__c = createdPullRequest.Id;
        createdPullRequestReview.copado__Review_Action__c = 'Approved';
        createdPullRequestReview.copado__Username__c = 'fnunez';
        insert createdPullRequestReview;
        
        
        copado__User_Story__c assertUserStory = [SELECT Id, Pull_Requests_Counter__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('1/1', assertUserStory.Pull_Requests_Counter__c);
	}
    
    @IsTest
    static void testPullRequestReviewApprovedPullRequestClosed() {   
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        copado__Pull_Request__c createdPullRequest = [SELECT Id FROM copado__Pull_Request__c WHERE copado__User_Story__c = :createdUserStory.Id];
        createdPullRequest.copado__State__c = 'Closed';
        update createdPullRequest;
        
		copado__Pull_Request_Review__c createdPullRequestReview = new copado__Pull_Request_Review__c();
        createdPullRequestReview.copado__Review_Id__c = 'frantest1';
        createdPullRequestReview.copado__Pull_Request__c = createdPullRequest.Id;
        createdPullRequestReview.copado__Review_Action__c = 'Approved';
        createdPullRequestReview.copado__Username__c = 'fnunez';
        insert createdPullRequestReview;
        
        
        copado__User_Story__c assertUserStory = [SELECT Id, Pull_Requests_Counter__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals(null, assertUserStory.Pull_Requests_Counter__c);
	}
    
     @IsTest
    static void testPullRequestReviewTwoApproved() {   
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        copado__Pull_Request__c createdPullRequest = [SELECT Id FROM copado__Pull_Request__c WHERE copado__User_Story__c = :createdUserStory.Id];
        update createdPullRequest;
        
		copado__Pull_Request_Review__c createdPullRequestReview = new copado__Pull_Request_Review__c();
        createdPullRequestReview.copado__Review_Id__c = 'frantest1';
        createdPullRequestReview.copado__Pull_Request__c = createdPullRequest.Id;
        createdPullRequestReview.copado__Review_Action__c = 'Approved';
        createdPullRequestReview.copado__Username__c = 'fnunez';
        insert createdPullRequestReview;
        
        copado__Pull_Request_Review__c createdPullRequestReview2 = new copado__Pull_Request_Review__c();
        createdPullRequestReview2.copado__Review_Id__c = 'frantest2';
        createdPullRequestReview2.copado__Pull_Request__c = createdPullRequest.Id;
        createdPullRequestReview2.copado__Review_Action__c = 'Approved';
        createdPullRequestReview2.copado__Username__c = 'fnunez';
        insert createdPullRequestReview2;        
        
        copado__User_Story__c assertUserStory = [SELECT Id, Pull_Requests_Counter__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('2/1', assertUserStory.Pull_Requests_Counter__c);
	}
    
    @IsTest
    static void testPullRequestReviewApprovedAndNotApproved() {   
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        copado__Pull_Request__c createdPullRequest = [SELECT Id FROM copado__Pull_Request__c WHERE copado__User_Story__c = :createdUserStory.Id];
        update createdPullRequest;
        
		copado__Pull_Request_Review__c createdPullRequestReview = new copado__Pull_Request_Review__c();
        createdPullRequestReview.copado__Review_Id__c = 'frantest1';
        createdPullRequestReview.copado__Pull_Request__c = createdPullRequest.Id;
        createdPullRequestReview.copado__Review_Action__c = 'Approved';
        createdPullRequestReview.copado__Username__c = 'fnunez';
        insert createdPullRequestReview;
        
        copado__Pull_Request_Review__c createdPullRequestReview2 = new copado__Pull_Request_Review__c();
        createdPullRequestReview2.copado__Review_Id__c = 'frantest2';
        createdPullRequestReview2.copado__Pull_Request__c = createdPullRequest.Id;
        createdPullRequestReview2.copado__Review_Action__c = 'Not Approved';
        createdPullRequestReview2.copado__Username__c = 'fnunez';
        insert createdPullRequestReview2;        
        
        copado__User_Story__c assertUserStory = [SELECT Id, Pull_Requests_Counter__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('1/1', assertUserStory.Pull_Requests_Counter__c);
	}
    
    
}