objects/copado__Org__c.object
<CustomObject>
    <description>Org authenticated via OAuth that you will need in order to schedule a deployment, run or schedule a Git Snapshot, run or schedule Apex test for an Org and to add more Org credentials in the same Salesforce server (pod).</description>
    <fields>
        <fullName>copado__Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>All_Sandboxes_Authorized__c</fullName>
        <formula>Sandboxes_Authorized__c == 6</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If the &quot;SBs Authorized&quot; count is 6 formula evaluates to true</inlineHelpText>
        <label>All Sandboxes Authorized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Api_Key__c</fullName>
        <label>Api Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <inlineHelpText>The contents of this field is displayed on the detail page in the community when a playground fails fatally (ie no retries are available).</inlineHelpText>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Git_Username__c</fullName>
        <description>Git provider username.</description>
        <inlineHelpText>Git provider username.</inlineHelpText>
        <label>Git Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <formula>LEFT(Org_Credential__r.copado__Environment__r.copado__Org_ID__c,15)</formula>
        <label>Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground_Configuration__c</fullName>
        <inlineHelpText>Full configuration will create all records for your playground including the complete pipeline. Choose light configuration only if you have been specifically instructed to do so</inlineHelpText>
        <label>Playground Configuration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Configuration</fullName>
                    <default>true</default>
                    <label>Full Configuration</label>
                </value>
                <value>
                    <fullName>Light Configuration</fullName>
                </value>
                <value>
                    <fullName>Full Configuration - Scratch Orgs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Indicates the stage of the playground creation. If stage is not Completed when a user returns to a playground the user will land the said stage.</description>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                    <default>true</default>
                    <label>CreateTrialOrg</label>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
                <value>
                    <fullName>PostInstallScript</fullName>
                </value>
                <value>
                    <fullName>Setup</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                    <isActive>false</isActive>
                    <label>Install</label>
                </value>
                <value>
                    <fullName>Start</fullName>
                    <isActive>false</isActive>
                    <label>Start</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <label>Org Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                </value>
                <value>
                    <fullName>CreateCoeCredential</fullName>
                </value>
                <value>
                    <fullName>CoE_Authorization</fullName>
                </value>
                <value>
                    <fullName>GitSetup</fullName>
                </value>
                <value>
                    <fullName>ProvisionLicenses</fullName>
                </value>
                <value>
                    <fullName>CreateEnvironment</fullName>
                </value>
                <value>
                    <fullName>CreateOrgCredentials</fullName>
                </value>
                <value>
                    <fullName>AuthorizeSandbox</fullName>
                </value>
                <value>
                    <fullName>AssignPermissionSet</fullName>
                </value>
                <value>
                    <fullName>ExecutePostInstallScript</fullName>
                </value>
                <value>
                    <fullName>CreateScratchOrgEnvironment</fullName>
                </value>
                <value>
                    <fullName>EnableUser</fullName>
                </value>
                <value>
                    <fullName>GitSetupFinish</fullName>
                </value>
                <value>
                    <fullName>CreateGitSnapshot</fullName>
                </value>
                <value>
                    <fullName>CreateBranches</fullName>
                </value>
                <value>
                    <fullName>CreateBoilerplate</fullName>
                </value>
                <value>
                    <fullName>AddingFinishingTouches</fullName>
                    <label>Adding Finishing Touches</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <externalId>true</externalId>
        <label>Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>This field determines the order the jobs are displayed.</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sandbox_Name__c</fullName>
        <label>Sandbox Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Sandbox Creation</fullName>
                </value>
                <value>
                    <fullName>Record Creation</fullName>
                </value>
                <value>
                    <fullName>Git</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Are_Playgrounds_Under_Maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be retrieved to check if playgrounds are available for creation (false) or they are under maintenance, so users will not be able to create a new one or continue one in progress</description>
        <label>Are Playgrounds Under Maintenance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Copado_Client_Key__c</fullName>
        <label>Copado Client Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Playground_Wizard_under_maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will disable only the Wizard to create new Playgrounds and will show a message indicating that feature is currently under maintenance.</description>
        <label>Is Playground Wizard under maintenance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Licensing_Endpoint__c</fullName>
        <label>Licensing Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_API_Key__c</fullName>
        <label>Production API Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Playground Setting</label>
    <pluralLabel>Playground Settings</pluralLabel>
</CustomObject>

classes/cps_PlaygroundWizardController.cls
public without sharing class cps_PlaygroundWizardController {

    // Return current user session id for Lightning to connect with CometD
    @AuraEnabled
    public static String getSessionId() {
        return UserInfo.getSessionId();
    }

    // Query for how many playgrounds the user has been allowed
    @AuraEnabled
    public static Decimal GetAllowedPlaygrounds() {
        User currentUser = [SELECT ContactId, Allowed_Playgrounds__c
                                FROM User
                                WHERE Id = :UserInfo.getUserId()
                                LIMIT 1];

        if (currentUser == null) {
            return 1000;
        }
        else {
            return currentUser.Allowed_Playgrounds__c;
        }
    }

    // Query for how many playgrounds more can be created
    @AuraEnabled
    public static Decimal GetAvailablePlaygrounds() {
        User currentUser = [SELECT ContactId, Allowed_Playgrounds__c
                                FROM User
                                WHERE Id = :UserInfo.getUserId()
                                LIMIT 1];

        if (currentUser == null) {
            return 1000;
        }
        else {
            Decimal allowed = (currentUser.Allowed_Playgrounds__c==null)? 0: currentUser.Allowed_Playgrounds__c;
            Integer used = GetMyPlaygrounds().size();
            Decimal available = allowed - used;
            return available;
        }
    }

    // Deletes a playground
    @AuraEnabled
    public static void DeletePlayground(String playgroundId) {
        Playground_Enviroment__c playgroundEnv = [SELECT Org_Id__c FROM Playground_Enviroment__c WHERE Playground__c = :playgroundId AND Type__c = 'CoE_Org' LIMIT 1];
        Playground_Setting__mdt settings = [SELECT Production_Api_Key__c, Licensing_Endpoint__c
                                            FROM Playground_Setting__mdt
                                            WHERE DeveloperName =: cps_Helper.SETTINGS_NAME
                                            LIMIT 1];

        // If there isn't coe2coe auth then there also isn't an org
        if (playgroundEnv.Org_Id__c != null) {
            // Id has to be in 15 characters format
            String orgId = playgroundEnv.Org_Id__c;
            if(orgId.length() == 18) orgId = orgId.left(15);
            String apiKey = cps_Crypto.decryptString(settings.Production_Api_Key__c);
            String baseUrl = settings.Licensing_Endpoint__c;
            String updateEndpoint = baseUrl + '/updatelicense/' + orgId;
            String body = '{"status": "Suspended", "forceactive": true, "licenses": 1}';
            Integer responseCode = cps_Helper.makeRequest(updateEndpoint, apiKey, body);
        }

        Playground__c playground = [SELECT Name, Stage__c, Status__c FROM Playground__c WHERE Id = :playgroundId LIMIT 1];

        try{
            delete playground;
        }catch(Exception e){
            throw e;
        }
    }

    // Gets a playground id and returns its information to the frontend
    @AuraEnabled
    public static Playground__c getPlayground(String id) {
        Playground__c playground = [SELECT Name, Stage__c, Status__c, All_Sandboxes_Authorized__c FROM Playground__c WHERE Id = :id];
        return playground;
    }

    // Get all the playground for the current community user
    @AuraEnabled
    public static List<Playground__c> GetMyPlaygrounds() {
        List<Playground__c> playgrounds = [SELECT Name, Stage__c, Status__c, Playground_Configuration__c FROM Playground__c WHERE User__c = :UserInfo.getUserId()];

        return playgrounds;
    }

    // Updates playground stage from: Start, Connect, Install, Setup, Finish
    @AuraEnabled
    public static Playground__c updatePlaygroundStage(String playgroundId, String stage){
        Playground__c playground = [SELECT Name, Stage__c FROM Playground__c WHERE Id = :playgroundId LIMIT 1];
        playground.Stage__c = stage;

        try{
            update playground;
        }catch(Exception e){
            throw e;
        }

        return playground;
    }

    // Updates a given job status and returns the job information to the frontend
    @AuraEnabled
    public static Playground_Job__c UpdateJobStatus(String playgroundId, String jobId, String status){
        Playground_Job__c job = [select Id, Status__c, Payload__c, Playground__c from Playground_Job__c where Playground__c=:playgroundId and Id=:jobId];
        job.Status__c = status;

        if (status == 'Failed') {
            try {
            	Playground__c playground = new Playground__c(Id=playgroundId, Status__c = 'Failed');
                update playground;
            } catch (Exception e) {
                throw e;
            }
        }

        try {
            update job;
        } catch(Exception e){
            throw e;
        }
        return job;
    }

    @AuraEnabled
    public static List<Playground_Job__c> GetPlaygroundJobs(String playgroundId){
        List<Playground_Job__c> jobs = [select Id, Name, Action__c, Status__c, JobId__c, Sandbox_Name__c, Payload__c, Order__c,CreatedDate
                                        from Playground_Job__c
                                        where Playground__c=:playgroundId order by Order__c ASC];
        return jobs;
    }

    @AuraEnabled
    public static Map<String, Object> getPlaygroundDetails(String playgroundId) {
      Playground__c playground = [SELECT Name, Status__c, Stage__c, Playground_Configuration__c, Error_Message__c, All_Sandboxes_Authorized__c, Git_Username__c, Org_Credential__r.copado__Username__c, LastModifiedDate FROM Playground__c WHERE Id =: playgroundId LIMIT 1];

        List<Playground_Enviroment__c> environments = [SELECT Id, Name, Status__c, Type__c, LastModifiedDate FROM Playground_Enviroment__c WHERE Playground__c =: playgroundId];

        Map<String, Object> pgd = new Map<String, Object>();
        pgd.put('playground', playground);
        pgd.put('environments', environments);

      return pgd;
    }

    @AuraEnabled
    public static Playground_Job__c callStandardC1PAction(String playgroundId, String actionName) {
        Playground__c playground = [SELECT Org_Credential__c FROM Playground__c WHERE Id = :playgroundId LIMIT 1];

        Playground_Job__c job = [SELECT Status__c, Action__c, JobId__c FROM Playground_Job__c WHERE Playground__c = :playgroundId AND Action__c = :actionName LIMIT 1];

        if (job.Status__c != 'Completed') {
            Map<String, String> paramBody = new Map<String, String>();
            paramBody.put('ACTION', actionName);
            paramBody.put('C1P_ORGCREDENTIALID_CLIENT', playground.Org_Credential__c);
            String jobId = cps_Helper.StartC1PJob(paramBody);

            job.Status__c = 'In progress';
            job.JobId__c = jobId;

            try{
                update job;
            }catch(Exception e){
                throw e;
            }
        }

        return job;
    }

    @AuraEnabled
    public static Playground_Setting__mdt getPlaygroundUnderMaintenance() {
        Playground_Setting__mdt playgroundSetting = [
            SELECT Are_Playgrounds_Under_Maintenance__c, Is_Playground_Wizard_under_maintenance__c
            FROM Playground_Setting__mdt
            WHERE QualifiedApiName =: cps_Helper.SETTINGS_NAME
            LIMIT 1];

        Boolean isPlaygroundsTestUser = [
            SELECT Is_Playgrounds_Test_User__c
            FROM User
            WHERE Id = :UserInfo.getUserId()
            LIMIT 1
        ].Is_Playgrounds_Test_User__c;

        Boolean arePlaygroundsUnderMaintenance = playgroundSetting.Are_Playgrounds_Under_Maintenance__c && !isPlaygroundsTestUser;
        playgroundSetting.Are_Playgrounds_Under_Maintenance__c = arePlaygroundsUnderMaintenance;

        return playgroundSetting;
    }

    @AuraEnabled
    public static String createFrontDoorRequest(Id orgId) {
      Playground_Setting__mdt playgroundSetting = [select Copado_Client_Key__c from Playground_Setting__mdt where QualifiedApiName=:cps_Helper.SETTINGS_NAME limit 1];
      Playground_Enviroment__c playgroundEnviroment = [SELECT Authorization_URL__c, Playground__r.Api_Key__c FROM Playground_Enviroment__c WHERE Id = :orgId LIMIT 1];
      String OrgCredentialId = cps_Helper.getOrgCredentialIdFromAuthorizationUrl(playgroundEnviroment.Authorization_URL__c);

      Http http = new Http();
      HttpRequest request = new HttpRequest();
      request.setEndpoint('https://app-api.copado.com/json/v1/webhook/copadoSession/' + OrgCredentialId + '?api_key=' + cps_Crypto.decryptString(playgroundEnviroment.Playground__r.Api_Key__c));
      request.setMethod('GET');
      request.setHeader('X-Client-Key', playgroundSetting.Copado_Client_Key__c);

      HttpResponse httpResponse;

      try{
        httpResponse = http.send(request);
        return httpResponse.getBody();
      } catch(Exception e) {
        throw e;
      }
    }
}