objects/copado1p__Platform_Job_Execution__c.object
<CustomObject>
    <description>This object is used to track every C1P job execution, one will be created per each request.</description>
    <fields>
        <fullName>copado1p__Copado_Job_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>This job Id is returned by Copado when an execution is started.</inlineHelpText>
        <label>Copado Job ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>copado1p__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Starting</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Platform Job Execution</label>
    <nameField>
        <displayFormat>PJE-{00000}</displayFormat>
        <label>Platform Job Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Job Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Interactive_Validation_Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>ExecutionStatus__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_ID__c</fullName>
        <label>Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform_Job_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Platform Job Execution</label>
        <referenceTo>copado1p__Platform_Job_Execution__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interactive Validation Step Execution</label>
    <nameField>
        <label>Interactive Validation Step Execution Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validation Step Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>JobID__c</fullName>
        <externalId>true</externalId>
        <label>Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform_Job_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Platform Job Execution</label>
        <referenceTo>copado1p__Platform_Job_Execution__c</referenceTo>
        <relationshipLabel>Step Executions</relationshipLabel>
        <relationshipName>Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step Execution</label>
    <nameField>
        <label>Step Execution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PlatformJobExecutionService.cls
public with sharing class PlatformJobExecutionService {

    public static void updateRelatedStepExecution(copado1p__Platform_Job_Execution__c oldPje, copado1p__Platform_Job_Execution__c pje) {
        if (oldPje.copado1p__Status__c != pje.copado1p__Status__c && pje.copado1p__Copado_Job_ID__c != null) {
            String stepExecutionStatus;
            if (pje.copado1p__Status__c == 'Starting') {
                stepExecutionStatus = 'Pending';
            } else if (pje.copado1p__Status__c == 'Running') {
                stepExecutionStatus = 'In progress';
            } else if (pje.copado1p__Status__c == 'Success') {
                stepExecutionStatus = 'Completed';
            } else if (pje.copado1p__Status__c == 'Failure') {
                stepExecutionStatus = 'Failed';
            }

            // Update Step Execution for Interactive Module
            List<Step_Execution__c> stepExecutionToBeUpdate = new List<Step_Execution__c>();
            for (Step_Execution__c se : [Select Id, Status__c, Platform_Job_Execution__c From Step_Execution__c Where JobID__c =:pje.copado1p__Copado_Job_ID__c Order by LastModifiedDate DESC Limit 1]) {
                se.Status__c = stepExecutionStatus;
                se.Platform_Job_Execution__c = pje.Id;
                stepExecutionToBeUpdate.add(se);
            }

            if (!stepExecutionToBeUpdate.isEmpty()) {
                update stepExecutionToBeUpdate;
            }

            // Update Step Execution for Interactive Validation
            List<Interactive_Validation_Step_Execution__c> IVStepExecutionToBeUpdate = new List<Interactive_Validation_Step_Execution__c>();
            for (Interactive_Validation_Step_Execution__c se : [Select Id, ExecutionStatus__c, Platform_Job_Execution__c From Interactive_Validation_Step_Execution__c Where Job_ID__c =:pje.copado1p__Copado_Job_ID__c Order by LastModifiedDate DESC Limit 1]) {
                se.ExecutionStatus__c = stepExecutionStatus;
                se.Platform_Job_Execution__c = pje.Id;
                IVStepExecutionToBeUpdate.add(se);
            }

            if (!IVStepExecutionToBeUpdate.isEmpty()) {
                update IVStepExecutionToBeUpdate;
            }
            
        }
    }
}