objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>copado__Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>copado__Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Version__c</fullName>
        <description>When a Promotion linked to this Release is merged into the Main Branch of the deployment flow, Copado will tag the Main Branch with this version number. This value is typically a major (e.g. v7), minor (v7.3) or patch (v7.3.2) release.</description>
        <inlineHelpText>When a Promotion linked to this Release is merged into the Main Branch of the deployment flow, Copado will tag the Main Branch with this version number. This value is typically a major (e.g. v7), minor (v7.3) or patch (v7.3.2) release.</inlineHelpText>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Copado_Package_installerTest.cls
@isTest
public class Copado_Package_installerTest {

    static testMethod void test_GetAllReleaseRecords(){
        copado__Release__c Release = new copado__Release__c();
        Release.Visible_in_Community__c=true;
        Release.copado__Description__c ='Test Released';
        Release.copado__Version__c ='1.0';
        Release.Installation_Link_in_Sandbox__c ='https://test.salesforce.com/';
        Release.Installation_Link_in_Production__c ='https://login.salesforce.com/';
        Release.Documentation_Release_Notes__c ='Test Released Note';        
        Release.copado__Planned_Date__c = system.today();
        Release.copado__Status__c = 'Released';
        Insert Release;
        Copado_Package_installer.GetAllReleaseRecords();
    } 
}