objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Sprint__c.object
<CustomObject>
    <description>If a project is broken down into multiple sprints this object should be used.</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Test_Run__c.object
<CustomObject>
    <description>The execution of the test script.</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>copado__Sprint__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for testing</fullName>
                    <default>true</default>
                    <label>Ready for testing</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with comments</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>copado__Test_Script__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/copado__Test_Script__c.object
<CustomObject>
    <description>The template test script.</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <formula>copado__User_Story__r.copado__Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Sprint__c</fullName>
        <formula>copado__User_Story__r.copado__Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts (User Story)</relationshipLabel>
        <relationshipName>Test_Scripts_UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Test Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Test_Script_Step__c.object
<CustomObject>
    <fields>
        <fullName>copado__Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>copado__Test_Script__c</referenceTo>
        <relationshipName>Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/copado__Theme__c.object
<CustomObject>
    <description>A theme is a group of user stories which contribute to a common goal. It is the highest level of the user story hierarchy. On the other hand, an epic is a big user story that has to be divided into several user stories because it can&apos;t be completed within one sprint.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Apex_Tests_Passed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apex Tests Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Documentation_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Documentation Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Manual_Tests_Passed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Tests Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Pull_Requests_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pull Requests Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sprint where the User Story is planned.</description>
        <inlineHelpText>Sprint where the User Story is planned.</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>copado__Sprint__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Story_Points_Other__c</fullName>
        <label>Planned Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>copado__Story_Points_SFDC__c</fullName>
        <label>Actual Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>copado__Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A theme is a group of user stories which contribute to a common goal. It is the highest level of the user story hierarchy. On the other hand, an epic is a big user story that has to be divided into several user stories because it can&apos;t be completed within one sprint.</description>
        <inlineHelpText>A theme is a group of user stories which contribute to a common goal. It is the highest level of the user story hierarchy. On the other hand, an epic is a big user story that has to be divided into several user stories because it can&apos;t be completed within</inlineHelpText>
        <label>Theme</label>
        <referenceTo>copado__Theme__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUpdateUserStoryDependsOnTestRunsFlow.cls
@IsTest
public class TestUpdateUserStoryDependsOnTestRunsFlow {
    @testSetup static void setup() {      
        Profile p = [SELECT Id FROM Profile WHERE Name='Copado Admin']; 
        PermissionSet permissionSet = [SELECT Id FROM PermissionSet WHERE Name='Scrum_Master'];
        
        User user = new User(Alias = 'newUser', Email='newuser666@copadoAPOproduct.com',
                             EmailEncodingKey='UTF-8', LastName='Jeldrik', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = p.Id, FirstName='Jeldrik',
                             TimeZoneSidKey='America/Los_Angeles', UserName='newuser666@copadoAPOproduct.com');
        insert user;
        
        System.runAs(user) {
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = permissionSet.Id, AssigneeId = user.Id);
            insert psa;
        }

        List<User> users = new List<User>();
        for(Integer i=1;i<3;i++) {
            users.add(new User(Alias = 'User'+i, Email='user'+i+'@testorg.com', 
                               EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                               LocaleSidKey='en_US', ProfileId = p.Id, 
                               TimeZoneSidKey='America/Los_Angeles', UserName='user'+i+System.now().getTime()+'@testorg.com'));
        }
        
        insert users; 
        User user1 = [SELECT Id FROM User WHERE Alias = 'User1'];
        
        System.runAs(user) 
        {
            Id recordTypeIdUserStory = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('User Story').getRecordTypeId();
            copado__User_Story__c myUserStory = new copado__User_Story__c();
            myUserStory.copado__User_Story_Title__c = 'UserStoryTest1';
            myUserStory.copado__Status__c = 'Draft';
            myUserStory.RecordTypeId = recordTypeIdUserStory;
            myUserStory.copado__Story_Points_Other__c = 2;
            myUserStory.copado__Story_Points_SFDC__c = 2;
            myUserStory.copado__Pull_Requests_Approved__c  = true;
            myUserStory.copado__Apex_Tests_Passed__c = true;
            myUserStory.copado__Manual_Tests_Passed__c  = true;
            myUserStory.copado__Documentation_Complete__c  = true;
            myUserStory.copado__Pull_Requests_Approved__c  = true;
            myUserStory.Module__c = TestDataFactory.createModule('TestModule').Id;
            myUserStory.copado__Theme__c = TestDataFactory.createTheme('TestTheme').Id;
            myUserStory.copado__Project__c = TestDataFactory.createProject('TestProject').Id;
            myUserStory.copado__Sprint__c = TestDataFactory.createSprint('TestSprint').Id;
            myUserStory.Documentation_Completed__c = 'Completed';
            insert myUserStory;
        }
        
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        copado__Test_Script__c testScript = new copado__Test_Script__c();
        testScript.copado__User_Story__c = createdUserStory.Id;
        insert testScript;       
        
        copado__Test_Script__c createdTestScript = [SELECT Id FROM copado__Test_Script__c WHERE copado__User_Story__c = :createdUserStory.Id];
        
        copado__Test_Script_Step__c step = new copado__Test_Script_Step__c();
        step.copado__Test_Script__c = createdTestScript.Id;
        insert step; 
        
        copado__Test_Run__c testRun1 = new copado__Test_Run__c();
        testRun1.copado__Status__c = 'Ready for testing';
        testRun1.copado__Type__c = 'Usability';
        testRun1.copado__Test_Phase__c = 'Developer';
        testRun1.copado__Tester__c = user1.Id;
        testRun1.copado__Test_Script__c = createdTestScript.Id;
        testRun1.copado__User_Story__c = createdUserStory.Id;
        insert testRun1; 
        
        User user2 = [SELECT Id FROM User WHERE Alias = 'User2'];
        copado__Test_Run__c testRun2 = new copado__Test_Run__c();
        testRun2.copado__Status__c = 'Ready for testing';
        testRun2.copado__Type__c = 'Usability';
        testRun2.copado__Test_Phase__c = 'Developer';
        testRun2.copado__Tester__c = user2.Id;
        testRun2.copado__Test_Script__c = createdTestScript.Id;
        testRun2.copado__User_Story__c = createdUserStory.Id;
        insert testRun2;
        
    }
    
    @IsTest
    static void testOneTestInProgress() {
        User user1 = [SELECT Id FROM User WHERE Alias = 'User1'];
        copado__Test_Run__c createdTestRun = [SELECT Id FROM copado__Test_Run__c WHERE copado__Tester__c = :user1.Id];
        createdTestRun.copado__Status__c = 'In Progress';
        update createdTestRun;
        
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Testing in Progress', assertUserStory.copado__Status__c);
    }
    
    @IsTest
    static void testAllTestPassed() {
        User user1 = [SELECT Id FROM User WHERE Alias = 'User1'];
        copado__Test_Run__c createdTestRun1 = [SELECT Id FROM copado__Test_Run__c WHERE copado__Tester__c = :user1.Id];
        createdTestRun1.copado__Status__c = 'Passed';
        update createdTestRun1;
        
        User user2 = [SELECT Id FROM User WHERE Alias = 'User2'];
        copado__Test_Run__c createdTestRun2 = [SELECT Id FROM copado__Test_Run__c WHERE copado__Tester__c = :user2.Id];
        createdTestRun2.copado__Status__c = 'Passed with comments';
        update createdTestRun2;
        
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Manual_Tests_Passed__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals(true, assertUserStory.copado__Manual_Tests_Passed__c);
    }
    
    @IsTest
    static void testOneTestPassed() {     
        User user1 = [SELECT Id FROM User WHERE Alias = 'User1'];
        copado__Test_Run__c createdTestRun1 = [SELECT Id FROM copado__Test_Run__c WHERE copado__Tester__c = :user1.Id];
        createdTestRun1.copado__Status__c = 'Passed';
        update createdTestRun1;
        
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Draft', assertUserStory.copado__Status__c);
    }
    
    @IsTest
    static void testOneTestDeleted() {     
        User user1 = [SELECT Id FROM User WHERE Alias = 'User1'];
        copado__Test_Run__c createdTestRun1 = [SELECT Id FROM copado__Test_Run__c WHERE copado__Tester__c = :user1.Id];
        delete createdTestRun1;
        
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Draft', assertUserStory.copado__Status__c);
    }
    
    @IsTest
    static void testOneTestInProgressAndUserStoryCancelled() {
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        createdUserStory.copado__Status__c = 'Cancelled';
        createdUserStory.copado__Cancellation_Reason__c = 'Testing';
        update createdUserStory;
        
        User user1 = [SELECT Id FROM User WHERE Alias = 'User1'];
        copado__Test_Run__c createdTestRun = [SELECT Id FROM copado__Test_Run__c WHERE copado__Tester__c = :user1.Id];
        createdTestRun.copado__Status__c = 'In Progress';
        update createdTestRun;
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Cancelled', assertUserStory.copado__Status__c);
    }
    
    @IsTest
    static void testOneTestInProgressAndUserStoryReleased() {
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        createdUserStory.copado__Status__c = 'Released';
        update createdUserStory;
        
        User user1 = [SELECT Id FROM User WHERE Alias = 'User1'];
        copado__Test_Run__c createdTestRun = [SELECT Id FROM copado__Test_Run__c WHERE copado__Tester__c = :user1.Id];
        createdTestRun.copado__Status__c = 'In Progress';
        update createdTestRun;
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals('Released', assertUserStory.copado__Status__c);
    }
}