objects/Copado_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Lead_Owner__c</fullName>
        <label>Default Lead Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Copado Settings</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Next_Contact__c</fullName>
        <label>Next Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Step__c</fullName>
        <inlineHelpText>This field does not get mapped to the opportunity.</inlineHelpText>
        <label>Next Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <description>This field is used for the batch lead conversion and should be left blank.</description>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_User__c.object
<CustomObject>
    <description>This object holds the Users linked to the Salesforce Orgs.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Salesforce Users</relationshipLabel>
        <relationshipName>Salesforce_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Salesforce User</label>
    <nameField>
        <displayFormat>SU-{0000000}</displayFormat>
        <label>Salesforce User Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameter__c.object
<CustomObject>
    <description>A custom object for storing feature parameters.  A new record is created of this object for every feature parameter that is ADDED as part of an uploaded package version. This record is automatically created upon the first package install of that package version.</description>
    <fields>
        <fullName>sfFma__DataFlowDirection__c</fullName>
        <description>Determines whether data flows from the ISV to the subscriber (Feature Setting) or from the subscriber to the ISV (Usage Metric</description>
        <label>Data Flow Direction</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LMO to Subscriber</fullName>
                </value>
                <value>
                    <fullName>Subscriber to LMO</fullName>
                </value>
                <value>
                    <fullName>Provisioned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfFma__DataType__c</fullName>
        <description>Data type of the Feature Parameter.</description>
        <label>Data Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__IntroducedInPackageVersion__c</fullName>
        <description>The version of the package in which this feature parameter was first introduced</description>
        <label>Introduced in Package Version</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__Namespace_Prefix__c</fullName>
        <description>Namespace prefix of the Feature Parameter.</description>
        <label>Namespace Prefix</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__Package__c</fullName>
        <label>Package</label>
        <referenceTo>sfLma__Package__c</referenceTo>
        <relationshipLabel>Feature Parameters</relationshipLabel>
        <relationshipName>Feature_Parameters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Feature Parameter</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Feature Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameterInteger__c.object
<CustomObject>
    <description>Custom object that is part of FMA for storing Feature Parameter Overrides for integers

A new record is created of this object for every feature parameter that is ADDED as part of a package install in an org. This record is automatically created upon every package install.

The Feature Parameter object serves as an index.</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Value will be set to 0 when expired</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <formula>sfFma__License__r.Salesforce_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__FeatureParameter__c</fullName>
        <description>The parent Feature Parameter object.</description>
        <label>Feature Parameter</label>
        <referenceTo>sfFma__FeatureParameter__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__Value__c</fullName>
        <label>Feature Parameter Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature Parameter Integer</label>
    <nameField>
        <displayFormat>FPI-{0000}</displayFormat>
        <label>Feature Parameter Integer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameter Integers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>Salesforce_User__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Install_Date__c</fullName>
        <description>The Date this Package Version was initially installed by the developer. (Does not get updated as part of upgrades.)</description>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead generated from this install. This field becomes blank once the lead is converted to an account / contact in the lead conversion process</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>R00N30000001JvRAEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__License_Type__c</fullName>
        <description>This field indicates the type of license record. For example, if the license record is &quot;Read-Only&quot;, this license record cannot be modified.</description>
        <label>License Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Package_License_ID__c</fullName>
        <description>ID of package license for uninstall tracking</description>
        <label>Package License ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>sfLma__Package__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Seats__c</fullName>
        <description>number of seats covered by license</description>
        <label>Seats</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sfLma__Status__c</fullName>
        <description>This is the Status of the Package License in the Subscriber Org</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Uninstalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Used_Licenses__c</fullName>
        <label>Used Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__Package__c.object
<CustomObject>
    <description>A Package Object represents information about the package as it is defined in the developer&apos;s Salesforce Organization. A record is created or updated each time a new version of the package is uploaded to AppExchange.</description>
    <fields>
        <fullName>sfLma__Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestLicenseHelper.cls
@isTest
public with sharing class TestLicenseHelper {

    /**
	 * This test references the method on class LicenseHelper.ConvertLeadToLicense(Id LicenseId);
	*/
    static testMethod void LicenseHelperConvertLeadToLicense() {
        
        Copado_Settings__c c = new Copado_Settings__c(Name='Default', Default_Lead_Owner__c=UserInfo.getUserId());
        insert c;
        
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c='00D20000000m7c0EAA');
        insert org;

        Lead testLead = createTestLead();
        sfLma__License__c license = createTestLicense(testLead.Id);

        createPackageAndFeatures();
        
        Test.startTest();
        LicenseHelper.webServiceResult wsr = LicenseHelper.convertLeadToLicense(license.Id);
        Test.stopTest();
        
        system.assertEquals(201, wsr.status);
        system.assertEquals(true, wsr.isSuccess);
        
        sfLma__License__c result = getLicense(license.Id);
        system.assertEquals(null, result.sfLma__Lead__c);
        system.assertNotEquals(null, result.Salesforce_Org__c);
        system.assertNotEquals(null, result.Salesforce_User__c);
        
        // Validate that Account has been deleted.
        List<Account> accs = [select Id from Account];
        system.assertEquals(0, accs.size());
    }
    
    /**
	 * TestMethod for invalid json when privisioning licenses
	*/
    static testMethod void testlicenseProvisioningNullParams() {
        String input = '[{"test":{"test">1,test.test.}}]';
    	Test.startTest();
        LicenseHelper.webServiceResult wsr = LicenseHelper.provisionCopadoLicenses(null, input);
        system.assertEquals(500, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        
        wsr = new LicenseHelper.webServiceResult();
        wsr = LicenseHelper.provisionCopadoLicenses(null, '');
        system.assertEquals(500, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        Test.stopTest();
    }
    /**
	 * TestMethod for LicenseHelper.provisionCopadoLicenses
	 * @param licenseId			The license id to be provisioned
	 * @param body				The JSON content to be passed in for provisioning
	 * @return string			We will return HTTP Status codes as this method will be referenced in a WebService
	*/
    static testMethod void testlicenseProvisioning() {
        String input = getInput();
        
        Copado_Settings__c c = new Copado_Settings__c(Name='Default', Default_Lead_Owner__c=UserInfo.getUserId());
        insert c;
        
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c='00D20000000m7c0EAA');
        insert org;

        Lead testLead = createTestLead();
        sfLma__License__c license = createTestLicense(testLead.Id);
		createPackageAndFeatures();
        LicenseHelper.convertLeadToLicense(license.Id);
        
        Test.startTest();
        LicenseHelper.webServiceResult wsr = LicenseHelper.provisionCopadoLicenses(license.Id, input);
        Test.stopTest();
        
        //system.assertEquals(201, wsr.status);
        
        List<sfFma__FeatureParameterInteger__c> fpiResult = [select Id, sfFma__FullName__c, sfFma__Value__c, Expiration_Date__c from sfFma__FeatureParameterInteger__c];
        for(sfFma__FeatureParameterInteger__c r : fpiResult) {
            if (r.sfFma__FullName__c=='copado__EE_Licenses_Enabled') {
                system.assertEquals(1, r.sfFma__Value__c);
            	system.assertEquals(Date.today().addDays(10), r.Expiration_Date__c);
            }
            else if (r.sfFma__FullName__c=='copado__CCM_Licenses_Enabled') {
                system.assertEquals(5, r.sfFma__Value__c);
            	system.assertEquals(Date.newInstance(2020, 12, 31), r.Expiration_Date__c);
            }	
        }        
    }
    
    /** 
     * TestMethod for LicenseHelper.parseBody used by the Playground Creation Wizard
     */
    static testMethod void testParseBody() {
    	Map<String, Map<String, Object>> result = new Map<String, Map<String, Object>>();
        String input = getInput();
        result = LicenseHelper.parseBody(input);
     	system.assertEquals(2, result.size()); // copado__EE_Licenses_Enabled and copado__CCM_Licenses_Enabled defined;
        Map<String, Object> eeExample = result.get('copado__EE_Licenses_Enabled');
        system.assertEquals(1, Integer.valueOf(eeExample.get('licenses')));
        system.assertEquals(10, Integer.valueOf(eeExample.get('expireIn')));
        system.assertEquals(null, Date.valueOf(eeExample.get('expirationDate')));
        
        Map<String, Object> ccmExample = result.get('copado__CCM_Licenses_Enabled');
        system.assertEquals(5, Integer.valueOf(ccmExample.get('licenses')));
        system.assertEquals(null, Integer.valueOf(ccmExample.get('expireIn')));
        Date d = Date.valueOf(ccmExample.get('expirationDate').toString());
        system.assertEquals(Date.newInstance(2020, 12, 31), d);
    }
    
    /**
	 * TestMethod for LicenseHelper to update licenses. If all is correct we return a 201, Success repsonse object.
	*/
    static testMethod void testLicenseUpdate() {
        String input = '{"status": "Active","forceactive": true,"licenses": -1}';
        
        Copado_Settings__c c = new Copado_Settings__c(Name='Default', Default_Lead_Owner__c=UserInfo.getUserId());
        insert c;
        
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c='00D20000000m7c0EAA');
        insert org;

        Lead testLead = createTestLead();
        sfLma__License__c license = createTestLicense(testLead.Id);
        
        Test.startTest();
        LicenseHelper.webServiceResult wsr = LicenseHelper.updateLicense(license.Id, input);
        Test.stopTest();
        
        system.assertEquals(201, wsr.status);
        system.assertEquals(true, wsr.isSuccess);
    }
    /**
	 * TestMethod for LicenseHelper to update licenses. If all is correct we return a 201, Success repsonse object.
	*/
    static testMethod void testLicenseUpdate_errorParsinInput() {
        String input = '{"status": "Active","forceactive": "true","licenses": -1}';//true was made a string.
        
        Copado_Settings__c c = new Copado_Settings__c(Name='Default', Default_Lead_Owner__c=UserInfo.getUserId());
        insert c;
        
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c='00D20000000m7c0EAA');
        insert org;

        Lead testLead = createTestLead();
        sfLma__License__c license = createTestLicense(testLead.Id);
        
        Test.startTest();
        LicenseHelper.webServiceResult wsr = LicenseHelper.updateLicense(license.Id, input);
        system.assertEquals(500, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        system.assertEquals('Error parsing JSON: Invalid conversion from runtime type String to Boolean', wsr.statusMessage);
        
        input = '{"status": "Active","forceactive": true,"licenses": -1}'; // changed back to valid json to test next try/catch
        wsr = LicenseHelper.updateLicense('00D00D00D00D00D', input);
        system.assertEquals(500, wsr.status);
        system.assertEquals(false, wsr.isSuccess);
        system.debug('%%%% '+wsr.statusMessage);
        system.assert(wsr.statusMessage.contains('A matching license record could not be found using the record Id'));
        Test.stopTest();
        
    }
    public static String getInput(){
        return '[{"copado__EE_Licenses_Enabled":{"licenses":1, "expireIn":10, "expirationDate":null},"copado__CCM_Licenses_Enabled":{"licenses": 5, "expireIn":null, "expirationDate":"2020-12-31"}}]';
    }
    public static Lead createTestLead() {
        Lead lead = new Lead(Company='MyPlaygroundOrg', FirstName='Philipp', LastName='Rackwitz', LeadSource='Package Installation', Email='pr@copa.do');
        lead.OrgId__c = '00D20000000m7c0EAA';
        lead.Rating='Tier 2';
        lead.NumberOfEmployees=100;
        lead.Industry='Bank and Finance';
        lead.Next_Contact__c=System.today();
        lead.Next_Step__c='Next Step';
        insert lead;
        return lead;
    }
    public static sfLma__License__c createTestLicense(Id leadId) {
        sfLma__License__c license = new sfLma__License__c();
        license.sfLma__Lead__c = leadId;
        license.sfLma__Status__c='Active';
        license.sfLma__Subscriber_Org_ID__c='00D20000000m7c0EAA';
        license.sfLma__Used_Licenses__c = 1;
        license.sfLma__Seats__c = -1;	         
        license.sfLma__Install_Date__c = system.today();
        license.sfLma__License_Type__c = 'Editable';
        license.sfLma__Package_License_ID__c = 'some package id';
        insert license;
        return license;
    }
    private static sfLma__License__c getLicense(Id licenseId) {
        return [select Id, Name, IsDeleted, sfLma__Lead__c, Salesforce_Org__c, Salesforce_User__c from sfLma__License__c where IsDeleted=false and Id=:licenseId limit 1];
    }
    public static void createPackageAndFeatures(){
        sfLma__Package__c pack = new sfLma__Package__c(Name='Copado Deployer', sfLma__Developer_Name__c='Copado BasePackage');
        insert pack;

        List<sfFma__FeatureParameter__c> fpList = new List<sfFma__FeatureParameter__c>();
		sfFma__FeatureParameter__c fpCCM = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CCM_Licenses_Enabled',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpCCM);
		sfFma__FeatureParameter__c fpCAD = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CAD_Licenses_Enabled',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpCAD);
		sfFma__FeatureParameter__c fpCCH = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CCH_Licenses_Enabled',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpCCH);
		sfFma__FeatureParameter__c fpCSTL = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CST_Licenses_Enabled',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpCSTL);
		sfFma__FeatureParameter__c fpEE = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__EE_Licenses_Enabled',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpEE);
        sfFma__FeatureParameter__c fpADD = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__ADD_Licenses_Enabled',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpADD);
		sfFma__FeatureParameter__c fpCSTM = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CST_Minutes_Packages',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpCSTM);
		sfFma__FeatureParameter__c fpCBM = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CBM_Branches',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpCBM);
        		sfFma__FeatureParameter__c fpFunctions = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__Functions',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpFunctions);
        		sfFma__FeatureParameter__c fpFunctionsHL = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CustomFunctionHardCreditLimit',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpFunctionsHL);
        		sfFma__FeatureParameter__c fpFunctionsSL = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CustomFunctionSoftCreditLimit',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpFunctionsSL);
        		sfFma__FeatureParameter__c fpFunctionsU = new sfFma__FeatureParameter__c(
				sfFma__FullName__c = 'copado__CustomFunctionCreditUsage',
				sfFma__DataType__c = 'Integer',
				sfFma__Namespace_Prefix__c = 'copado',
				sfFma__DataFlowDirection__c = 'LMO to Subscriber',
				sfFma__IntroducedInPackageVersion__c = '10.0',
				sfFma__Package__c = pack.Id
		);
		fpList.add(fpFunctionsU);
		insert fpList;
    }
}