objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Has_Apex_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value automatically updated by Copado whenever there are Apex Classes added or committed in the User Story.</description>
        <inlineHelpText>Value automatically updated by Copado whenever there are Apex Classes added or committed in the User Story.</inlineHelpText>
        <label>Has Apex Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Story_Points_Other__c</fullName>
        <label>Planned Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestInvokeReleaseApprovalProcess.cls
@IsTest
public class TestInvokeReleaseApprovalProcess {
    @testSetup static void setup() {      
         copado__User_Story__c userStory = TestDataFactory.createUserStories('InvokeReleaseApprovalProcess1', 'Draft');
         userStory.copado__Has_Apex_Code__c = true;
         insert userStory; 
    }
    
    @IsTest
    static void executionSuccessNotAPO() {
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'InvokeReleaseApprovalProcess1'];
        createdUserStory.RecordTypeId = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('User Story').getRecordTypeId();
        createdUserStory.copado__Story_Points_Other__c = 2;
        update createdUserStory;
        
        InvokeReleaseApprovalProcess.InvocableVariables input = new InvokeReleaseApprovalProcess.InvocableVariables();
        input.userStoryId = createdUserStory.Id;
        List<InvokeReleaseApprovalProcess.InvocableVariables> inputs = new List<InvokeReleaseApprovalProcess.InvocableVariables>();
        inputs.add(input);
        List<InvokeReleaseApprovalProcess.ApprovalProcessResult> results = InvokeReleaseApprovalProcess.execute(inputs);

        System.assert(!results[0].ErrorMessage.contains('EPIC cannot be null'),results[0].ErrorMessage);
        System.assert(!results[0].ErrorMessage.contains('Planned Points cannot be null'),results[0].ErrorMessage);
        System.assert(results[0].ErrorMessage.contains('Realease cannot be null'),results[0].ErrorMessage);
    }
    
    @IsTest
    static void executionSuccessAPO() {
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'InvokeReleaseApprovalProcess1'];
        createdUserStory.RecordTypeId = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('APO User Story').getRecordTypeId();
        createdUserStory.copado__Story_Points_Other__c = 2;
        update createdUserStory;
        
        InvokeReleaseApprovalProcess.InvocableVariables input = new InvokeReleaseApprovalProcess.InvocableVariables();
        input.userStoryId = createdUserStory.Id;
        List<InvokeReleaseApprovalProcess.InvocableVariables> inputs = new List<InvokeReleaseApprovalProcess.InvocableVariables>();
        inputs.add(input);
        List<InvokeReleaseApprovalProcess.ApprovalProcessResult> results = InvokeReleaseApprovalProcess.execute(inputs);

        System.assert(!results[0].ErrorMessage.contains('Planned Points cannot be null'),results[0].ErrorMessage);
    }
}