objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>User Stories (Developer)</relationshipLabel>
        <relationshipName>User_Stories_developer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Progress__c</fullName>
        <label>Progress</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUserStoryChangesProcessBuilder.cls
@IsTest
public class TestUserStoryChangesProcessBuilder {
    @testSetup static void setup() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Copado Admin']; 
        List<User> users = new List<User>();
        for(Integer i=0;i<2;i++) {
            users.add(new User(Alias = 'User'+i, Email='user'+i+'@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='user'+i+System.now().getTime()+'@testorg.com'));
        }
        insert users;       
        
        copado__User_Story__c myUserStory = new copado__User_Story__c();
        myUserStory.copado__User_Story_Title__c = 'UserStoryTest1';
        myUserStory.copado__Status__c = 'Draft';
        insert myUserStory;
    }
    
    @IsTest
    static void testStatusChanged() {
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        createdUserStory.copado__Status__c = 'Completed';
        update createdUserStory;
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Progress__c FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals(100, assertUserStory.copado__Progress__c);
    }
    
    @IsTest
    static void testDeveloperChanged() {
        copado__User_Story__c createdUserStory = [SELECT Id, OwnerId FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        User user = [SELECT Id FROM User WHERE Alias = 'User1'];
        
        createdUserStory.copado__Developer__c = user.Id;
        update createdUserStory;
        
        copado__User_Story__c assertUserStory = [SELECT Id, OwnerId FROM copado__User_Story__c WHERE Id = :createdUserStory.Id];
        System.assertEquals(user.Id, assertUserStory.OwnerId);
    }
    
    @IsTest
    static void testsubtaskStatusChanged() {
        copado__User_Story__c createdUserStory = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        
        Id recordTypeIdUserStory = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('Subtask').getRecordTypeId();
        List<copado__User_Story__c> subtasks = new List<copado__User_Story__c>();
        for(Integer i=0;i<2;i++) {
            copado__User_Story__c subtask = new copado__User_Story__c();
        	subtask.copado__User_Story_Title__c = 'Subtask'+i;
        	subtask.copado__Status__c = 'Draft';
            subtask.RecordTypeId = recordTypeIdUserStory;
            subtask.Parent_User_Story__c = createdUserStory.Id;
            subtasks.add(subtask);
        }
        insert subtasks; 
        
        //Update one subtask to in progress
        copado__User_Story__c firstSubtask = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'Subtask0'];
        firstSubtask.copado__Status__c = 'Development In Progress';
        update firstSubtask;
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        System.assertEquals('Development In Progress', assertUserStory.copado__Status__c);
    }
}