objects/copado__Deployment_Flow__c.object
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pipeline</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestBackendReleaseWasReleasedPB.cls
@IsTest
public class TestBackendReleaseWasReleasedPB {
	@testSetup static void setup() {      
        copado__Release__c release1 = TestDataFactory.createRelease('DemoTestParent');
        release1.copado__Status__c = 'Released';
        insert release1;
        
        copado__Deployment_Flow__c flow = new copado__Deployment_Flow__c();
        flow.Name = 'TestFlow';
        insert flow;
        
        copado__Deployment_Flow__c createdFlow = [SELECT Id FROM copado__Deployment_Flow__c WHERE Name = 'TestFlow'];
        
        copado__Project__c project = new copado__Project__c();
        project.Name = 'ProjectTest';
        project.copado__Deployment_Flow__c = createdFlow.Id;
        insert project;
        
        copado__Release__c createdParentRelease = [SELECT Id FROM copado__Release__c WHERE Name = 'DemoTestParent'];
        copado__Release__c release2 = TestDataFactory.createRelease('DemoTestChild');
        release2.copado__Status__c = 'Released';
        release2.Parent_Release__c = createdParentRelease.Id;
        insert release2;
        
        copado__Project__c createdProject = [SELECT Id FROM copado__Project__c WHERE Name = 'ProjectTest'];
        
        Id recordTypeIdUserStory = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('User Story').getRecordTypeId();
        copado__User_Story__c myUserStory1 = TestDataFactory.createUserStories('UserStoryTest1','Released');
        myUserStory1.RecordTypeId = recordTypeIdUserStory;
        myUserStory1.copado__Release__c = createdParentRelease.Id;
        myUserStory1.copado__Project__c = createdProject.Id;
        insert myUserStory1;
        
        copado__Release__c createdChildRelease = [SELECT Id FROM copado__Release__c WHERE Name = 'DemoTestChild'];
        copado__User_Story__c myUserStory2 = TestDataFactory.createUserStories('UserStoryTest2','Released');
        myUserStory2.RecordTypeId = recordTypeIdUserStory;
        myUserStory2.copado__Release__c = createdChildRelease.Id;
        myUserStory2.copado__Project__c = createdProject.Id;
        insert myUserStory2;
    }
    
    @IsTest
    static void testReleaseReleased() {     
        copado__Release__c createdParentRelease = [SELECT Id FROM copado__Release__c WHERE Name = 'DemoTestParent'];
        createdParentRelease.copado__Status__c = 'Released';
        update createdParentRelease;
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        System.assertEquals('Released', assertUserStory.copado__Status__c);
        
        copado__Release__c assertChildRelease = [SELECT Id, copado__Status__c FROM copado__Release__c WHERE Name = 'DemoTestChild'];
        System.assertEquals('Released', assertChildRelease.copado__Status__c);
	}
    
    @IsTest
    static void testReleaseBeta() {     
        copado__Release__c createdParentRelease = [SELECT Id FROM copado__Release__c WHERE Name = 'DemoTestParent'];
        createdParentRelease.copado__Status__c = 'Beta';
        update createdParentRelease;
        
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        System.assertEquals('Beta', assertUserStory.copado__Status__c);
        
        copado__Release__c assertChildRelease = [SELECT Id, copado__Status__c FROM copado__Release__c WHERE Name = 'DemoTestChild'];
        System.assertEquals('Beta', assertChildRelease.copado__Status__c);
	}
    
    @IsTest
    static void testReleaseReadyForTesting() {     
        copado__Release__c createdParentRelease = [SELECT Id FROM copado__Release__c WHERE Name = 'DemoTestParent'];
        createdParentRelease.copado__Status__c = 'Ready for Testing';
        update createdParentRelease;
       
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        System.assertEquals('Ready for Regression', assertUserStory.copado__Status__c);
        
        copado__Release__c assertChildRelease = [SELECT Id, copado__Status__c FROM copado__Release__c WHERE Name = 'DemoTestChild'];
        System.assertEquals('Ready for Testing', assertChildRelease.copado__Status__c);
	}
    
    @IsTest
    static void testReleaseReadyForRelease() { 
        copado__Release__c createdParentRelease = [SELECT Id FROM copado__Release__c WHERE Name = 'DemoTestParent'];
        createdParentRelease.copado__Status__c = 'Ready for Release';
        update createdParentRelease;
       
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        System.assertEquals('Ready for Release', assertUserStory.copado__Status__c);
        
        copado__Release__c assertChildRelease = [SELECT Id, copado__Status__c FROM copado__Release__c WHERE Name = 'DemoTestChild'];
        System.assertEquals('Ready for Release', assertChildRelease.copado__Status__c);
	}
    
    @IsTest
    static void testReleaseApprovedByQA() { 
        copado__Release__c createdParentRelease = [SELECT Id FROM copado__Release__c WHERE Name = 'DemoTestParent'];
        createdParentRelease.copado__Status__c = 'Approved by QA';
        update createdParentRelease;
       
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        System.assertEquals('Ready for Release', assertUserStory.copado__Status__c);
        
        copado__Release__c assertChildRelease = [SELECT Id, copado__Status__c FROM copado__Release__c WHERE Name = 'DemoTestChild'];
        System.assertEquals('Approved by QA', assertChildRelease.copado__Status__c);
	}
}