objects/Copado_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Lead_Owner__c</fullName>
        <label>Default Lead Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Copado Settings</label>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Next_Contact__c</fullName>
        <label>Next Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Step__c</fullName>
        <inlineHelpText>This field does not get mapped to the opportunity.</inlineHelpText>
        <label>Next Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <description>This field is used for the batch lead conversion and should be left blank.</description>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_User__c.object
<CustomObject>
    <description>This object holds the Users linked to the Salesforce Orgs.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Salesforce Users</relationshipLabel>
        <relationshipName>Salesforce_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Salesforce User</label>
    <nameField>
        <displayFormat>SU-{0000000}</displayFormat>
        <label>Salesforce User Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameter__c.object
<CustomObject>
    <description>A custom object for storing feature parameters.  A new record is created of this object for every feature parameter that is ADDED as part of an uploaded package version. This record is automatically created upon the first package install of that package version.</description>
    <fields>
        <fullName>sfFma__DataFlowDirection__c</fullName>
        <description>Determines whether data flows from the ISV to the subscriber (Feature Setting) or from the subscriber to the ISV (Usage Metric</description>
        <label>Data Flow Direction</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LMO to Subscriber</fullName>
                </value>
                <value>
                    <fullName>Subscriber to LMO</fullName>
                </value>
                <value>
                    <fullName>Provisioned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfFma__DataType__c</fullName>
        <description>Data type of the Feature Parameter.</description>
        <label>Data Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__IntroducedInPackageVersion__c</fullName>
        <description>The version of the package in which this feature parameter was first introduced</description>
        <label>Introduced in Package Version</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__Namespace_Prefix__c</fullName>
        <description>Namespace prefix of the Feature Parameter.</description>
        <label>Namespace Prefix</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__Package__c</fullName>
        <label>Package</label>
        <referenceTo>sfLma__Package__c</referenceTo>
        <relationshipLabel>Feature Parameters</relationshipLabel>
        <relationshipName>Feature_Parameters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Feature Parameter</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Feature Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>Salesforce_User__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Install_Date__c</fullName>
        <description>The Date this Package Version was initially installed by the developer. (Does not get updated as part of upgrades.)</description>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead generated from this install. This field becomes blank once the lead is converted to an account / contact in the lead conversion process</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>R00N30000001JvRAEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__License_Type__c</fullName>
        <description>This field indicates the type of license record. For example, if the license record is &quot;Read-Only&quot;, this license record cannot be modified.</description>
        <label>License Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Package_License_ID__c</fullName>
        <description>ID of package license for uninstall tracking</description>
        <label>Package License ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package</label>
        <referenceTo>sfLma__Package__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Seats__c</fullName>
        <description>number of seats covered by license</description>
        <label>Seats</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sfLma__Status__c</fullName>
        <description>This is the Status of the Package License in the Subscriber Org</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Uninstalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Used_Licenses__c</fullName>
        <label>Used Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__Package__c.object
<CustomObject>
    <description>A Package Object represents information about the package as it is defined in the developer&apos;s Salesforce Organization. A record is created or updated each time a new version of the package is uploaded to AppExchange.</description>
    <fields>
        <fullName>sfLma__Developer_Name__c</fullName>
        <label>Developer Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestLeadConvertBatch.cls
@isTest
private class TestLeadConvertBatch {

    static testMethod void testLeadConversionWithOrgAndUser() {

        Copado_Settings__c custSet = new Copado_Settings__c(
                Name = 'Default',
                Default_Lead_Owner__c = UserInfo.getUserId());
        insert custSet;

        System.assertEquals('00D20000000m7c0EAA', LeadConvertBatch.ID15to18('00D20000000m7c0'));
        
        Salesforce_Org__c org = new Salesforce_Org__c(
            Name = 'Test Org',
            OrgId__c = '00D20000000m7c0EAA');
        insert org;

        Salesforce_User__c usr = new Salesforce_User__c(
            Email__c = 'pr@copa.do',
            Salesforce_Org__c = Org.Id);
        insert usr;
        
        Lead lead = new Lead(Company='My test Account',FirstName='test', LastName='Test',LeadSource='Package Installation',Rating = 'Tier 2',NumberOfEmployees = 100, Industry = 'Bank and Finance',Next_Contact__c = System.today(), Next_Step__c = 'Next Step',Email='pr@copa.do');
        insert lead;
        sfLma__License__c license = new sfLma__License__c();
        license.sfLma__Lead__c=lead.Id;
        license.sfLma__Status__c='Active';
        license.sfLma__Subscriber_Org_ID__c='00D20000000m7c0EAA';
        license.sfLma__Used_Licenses__c = 1;
        license.sfLma__Seats__c = -1;
        license.sfLma__Install_Date__c = System.today();
        license.sfLma__License_Type__c = 'Editable';
        license.sfLma__Package_License_ID__c = 'some package id';
        
        insert license;

        sfLma__Package__c pack = new sfLma__Package__c(
                Name = 'Copado Deployer',
                sfLma__Developer_Name__c = 'Copado BasePackage'
        );
        insert pack;

        sfFma__FeatureParameter__c fpCCM = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CCM_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCCM;
        sfFma__FeatureParameter__c fpCAD = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CAD_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCAD;
        sfFma__FeatureParameter__c fpCCH = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CCH_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCCH;
        sfFma__FeatureParameter__c fpCSTL = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CST_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCSTL;
        sfFma__FeatureParameter__c fpEE = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__EE_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpEE;
        sfFma__FeatureParameter__c fpADD = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__ADD_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpADD;
        sfFma__FeatureParameter__c fpCSTM = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CST_Minutes_Packages',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCSTM;
        sfFma__FeatureParameter__c fpCBM = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CBM_Branches',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCBM;
       

        Test.startTest();
        LeadConvertBatch batchApex = new LeadConvertBatch();   
        Id batchprocessid = Database.executeBatch(batchApex,1);
        Test.stopTest(); 
        
        Lead convertedLead = [SELECT Id, FirstName, LastName, Email, IsConverted, ConvertedAccountId, ConvertedContactId FROM Lead WHERE Id =:lead.Id];
        System.assertEquals(true, convertedLead.IsConverted);
        System.assert(convertedLead.ConvertedAccountId != null);
        System.assert(convertedLead.ConvertedContactId != null);
        
        List<sfLma__License__c> results = new List<sfLma__License__c>();
        results = [SELECT Id,sfLma__Lead__c,Salesforce_Org__c, Salesforce_User__c, Salesforce_Org__r.OrgId__c FROM sfLma__License__c WHERE Id=:license.Id];
        for(sfLma__License__c r : results){
            System.assertEquals(null, r.sfLma__Lead__c);
            System.assertEquals(org.Id, r.Salesforce_Org__c);
            System.assertEquals(usr.Id, r.Salesforce_User__c);
            System.assert(r.Salesforce_Org__r.OrgId__c != null);
        }
    }

    static testMethod void testLeadConversionNoOrgNorUser() {

        Copado_Settings__c custSet = new Copado_Settings__c(
                Name = 'Default',
                Default_Lead_Owner__c = UserInfo.getUserId());
        insert custSet;
        
        System.assertEquals('00D20000000m7c0EAA', LeadConvertBatch.ID15to18('00D20000000m7c0'));
        
        Lead lead = new Lead(Company='My test Account',FirstName='test', LastName='Test',LeadSource='Package Installation',Rating = 'Tier 2',NumberOfEmployees = 100, Industry = 'Bank and Finance',Next_Contact__c = System.today(), Next_Step__c = 'Next Step',Email='pr@copa.do');
        insert lead;
        sfLma__License__c license = new sfLma__License__c();
        license.sfLma__Lead__c=lead.Id;
        license.sfLma__Status__c='Active';
        license.sfLma__Subscriber_Org_ID__c='00D20000000m7c0EAA';
        license.sfLma__Used_Licenses__c = 1;
        license.sfLma__Seats__c = -1;
        license.sfLma__Install_Date__c = System.today();
        license.sfLma__License_Type__c = 'Editable';
        license.sfLma__Package_License_ID__c = 'some package id';
    
        insert license;

        sfLma__Package__c pack = new sfLma__Package__c(
                Name = 'Copado Deployer',
                sfLma__Developer_Name__c = 'Copado BasePackage'
        );
        insert pack;

        sfFma__FeatureParameter__c fpCCM = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CCM_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCCM;
        sfFma__FeatureParameter__c fpCAD = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CAD_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCAD;
        sfFma__FeatureParameter__c fpCCH = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CCH_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCCH;
        sfFma__FeatureParameter__c fpCSTL = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CST_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCSTL;
        sfFma__FeatureParameter__c fpEE = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__EE_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpEE;
        sfFma__FeatureParameter__c fpADD = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__ADD_Licenses_Enabled',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpADD;
        sfFma__FeatureParameter__c fpCSTM = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CST_Minutes_Packages',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCSTM;
        sfFma__FeatureParameter__c fpCBM = new sfFma__FeatureParameter__c(
                sfFma__FullName__c = 'copado__CBM_Branches',
                sfFma__DataType__c = 'Integer',
                sfFma__Namespace_Prefix__c = 'copado',
                sfFma__DataFlowDirection__c = 'LMO to Subscriber',
                sfFma__IntroducedInPackageVersion__c = '10.0',
                sfFma__Package__c = pack.Id
        );
        insert fpCBM;

        Test.startTest();
        LeadConvertBatch batchApex = new LeadConvertBatch();   
        Id batchprocessid = Database.executeBatch(batchApex,1);
        Test.stopTest(); 
        
        Lead convertedLead = [SELECT Id, FirstName, LastName, Email, IsConverted, ConvertedAccountId, ConvertedContactId FROM Lead WHERE Id =:lead.Id];
        System.assertEquals(true, convertedLead.IsConverted);
        System.assert(convertedLead.ConvertedAccountId != null);
        System.assert(convertedLead.ConvertedContactId != null);
        
        List<sfLma__License__c> results = new List<sfLma__License__c>();
        results = [SELECT Id,sfLma__Lead__c,Salesforce_Org__r.OrgId__c, Salesforce_Org__c, Salesforce_User__c FROM sfLma__License__c WHERE Id=:license.Id];
        for(sfLma__License__c r : results){
            System.assertEquals(null, r.sfLma__Lead__c);
            System.assertEquals('00D20000000m7c0EAA',r.Salesforce_Org__r.OrgId__c);
            System.assert(r.Salesforce_Org__c != null);
            System.assert(r.Salesforce_User__c != null);
        }
    }
}