objects/Copado_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Admin_Password__c</fullName>
        <label>Admin_Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admin_Username__c</fullName>
        <inlineHelpText>used in the batch process to connect to the Admin org (this one)</inlineHelpText>
        <label>Admin_Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Data_Export__c</fullName>
        <label>Last Data Export</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Max_top_up_value__c</fullName>
        <label>Max top-up value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Server_URL__c</fullName>
        <label>Server_URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Copado Settings</label>
</CustomObject>

objects/kugo2p__KugamonSetting__c.object
<CustomObject>
    <description>Kugamon - Main object that controls Kugamon application behavior. Only one Kugamon Settings record is allowed. For Admin use only.</description>
    <fields>
        <fullName>kugo2p__Admin_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Administrator User, who is the designated User to receive important application notifications and error messages.</description>
        <inlineHelpText>Lookup to the Administrator User, who is the designated User to receive important application notifications and error messages.</inlineHelpText>
        <label>Administrator User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Kugamon_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>kugo2p__AllowOverrideServiceDateUpdate__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This advanced option allows an override of the automatic Date updates of the Quote and Order Service Lines. Consult with a Kugamon Administrator before making any changes.</inlineHelpText>
        <label>Allow Override Service Date Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>kugo2p__BillingMethod__c</fullName>
        <label>Billing Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Print</fullName>
                </value>
                <value>
                    <fullName>Email and Print</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__CompanyTextandTerms__c</fullName>
        <label>Company Terms &amp; Conditions</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>kugo2p__CreditTerms__c</fullName>
        <label>Credit Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Check Required</fullName>
                </value>
                <value>
                    <fullName>On Credit Hold</fullName>
                </value>
                <value>
                    <fullName>No Credit Check Required</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__DateAvailabletoPromiseBasis__c</fullName>
        <inlineHelpText>Blank value defaults to Latest of Today or Date Required

For Historical Invoice Creation, Set Value to Date Required</inlineHelpText>
        <label>Date Available to Promise Basis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Date Required</fullName>
                    <default>true</default>
                    <label>Date Required</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__DayofRevenueRecognition__c</fullName>
        <inlineHelpText>Select the day of the month your company recognize revenue.</inlineHelpText>
        <label>Day of Revenue Recognition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__DaysTillPaymentDue__c</fullName>
        <inlineHelpText>Default value for payment due date calculation; should match the Payment Terms value. Days Till Payment Due value is the default for the Additional Account Info object.</inlineHelpText>
        <label>Days Till Payment Due</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>kugo2p__DeliveryTerms__c</fullName>
        <label>Delivery Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FOB Destination</fullName>
                </value>
                <value>
                    <fullName>FOB Origin</fullName>
                    <default>true</default>
                    <label>FOB Origin</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__FirstInvoiceDateBasis__c</fullName>
        <inlineHelpText>Blank value defaults to Order Release Date or Order Date Available to Promise, if Later. If filled, Shipment Date based on Product Line Date Available to Promise.

For Historical Invoice Creation, Set Value to Date Required or Date Available to Promise</inlineHelpText>
        <label>Invoice Date Basis</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Order Date Required</fullName>
                    <default>true</default>
                    <label>Order Date Required</label>
                </value>
                <value>
                    <fullName>Order Date Available to Promise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__InvoiceTextandTerms__c</fullName>
        <inlineHelpText>Changes to text are automatically updated in Invoice text and term section in Unsent status. If the Invoice text is different, then that text will not be updated.</inlineHelpText>
        <label>Invoice Terms &amp; Conditions</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>kugo2p__OnlineConfirmationTextandTerms__c</fullName>
        <inlineHelpText>Content displayed on the Online Payment confirmation page.</inlineHelpText>
        <label>Online Order Confirmation</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>kugo2p__OnlinePaymentButton__c</fullName>
        <inlineHelpText>Indicates button and behavior that should be used on the online order page.</inlineHelpText>
        <label>Online Order Acceptance Button</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accept &amp; Approve</fullName>
                    <default>true</default>
                    <label>Accept &amp; Approve</label>
                </value>
                <value>
                    <fullName>Accept &amp; Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__PaymentMethod__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Debit/Credit Card</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Wire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__PaymentTerms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Due Upon Receipt</fullName>
                </value>
                <value>
                    <fullName>Net 7 Days</fullName>
                </value>
                <value>
                    <fullName>Net 10 Days</fullName>
                </value>
                <value>
                    <fullName>Net 30 Days</fullName>
                </value>
                <value>
                    <fullName>Net 45 Days</fullName>
                </value>
                <value>
                    <fullName>Net 60 Days</fullName>
                </value>
                <value>
                    <fullName>Net 90 Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>kugo2p__PriceBookName__c</fullName>
        <description>Default Price Book for subsequent Additional Account Info (Accounts). Please use [Choose Price Book] button to change the Price Book. This field is replaced by the Price Book lookup field.</description>
        <label>Price Book Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__RemitToCity__c</fullName>
        <label>Remit To City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__RemitToCountry__c</fullName>
        <label>Remit To Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__RemitToName__c</fullName>
        <label>Remit To Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__RemitToStateProvince__c</fullName>
        <label>Remit To State/Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__RemitToStreet__c</fullName>
        <label>Remit To Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__RemitToZipPostalCode__c</fullName>
        <label>Remit To Zip/Postal Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kugo2p__ResetQuoteOrderTermsConditions__c</fullName>
        <label>Quote/Order Terms &amp; Conditions Reset</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Update Matched Terms</fullName>
                    <default>true</default>
                    <label>Update Matched Terms</label>
                </value>
                <value>
                    <fullName>Replace All Terms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Kugamon Setting</label>
    <nameField>
        <label>Kugamon Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kugamon Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>Server_URL__c</fullName>
        <label>Server URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testMethodUtilities.cls
public class testMethodUtilities {
    public static void setupEntitlements(){
        if([SELECT Id FROM Entitlement WHERE Name ='Basic Support'].size()>0)return;
        Account bs = TestDataFactory.createAccount('My Account', 'EUR');
        insert bs;
        Id bhid = null;
        List<BusinessHours> bhs = [SELECT Id FROM BusinessHours WHERE Name ='Working hours - UTC+1' LIMIT 1];
        if(bhs.size()>0){
            bhid = bhs.get(0).Id;
        }
        Entitlement basic = new Entitlement(Name = 'Basic Support',AccountId = bs.Id, Access_Code__c=1, BusinessHoursId = bhid);
        insert basic;
        System.debug('########### basic support entitlement created: ' + basic);
    }
    public static Account createAccount(String name, String orgId){
        Account a = new Account();
        a.Name = name;
        insert a;
        return a;
    }
    public static Contact createContact(Id accountId, String firstName, String lastName, String email, String userId){
        Contact c = new Contact();
        c.AccountId = accountId;
        c.FirstName = firstName;
        c.LastName = lastName;
        c.Email = email;
        c.UserId__c = userId;
        insert c;
        return c;
    }
    public static Opportunity createOpportunity(Id accountId, String name, String StageName, String verificationKey, Double amount, String mainProblems){
        Opportunity o = new Opportunity();
        o.AccountId = accountId;
        o.CloseDate = System.today();
        o.Name = name;
        o.StageName = StageName;
        o.Amount = amount;
        o.Main_Problems__c = mainProblems;
        o.LeadSource='Advertisement';
        insert o;
        return o;
    }
    public static Boolean hasMessage(String s){
        Boolean b = false;
        for(ApexPages.Message msg : ApexPages.getMessages()){
            if(msg.getDetail().contains(s)) b = true;
        }
        return b;
    }
    public static Product2 createProduct(String name, Decimal creds, String code){
        Product2 p = new Product2();
        p.Name = name;
        p.Credits_to_be_assigned__c = creds;
        p.ProductCode = code;
        p.CurrencyIsoCode = 'EUR';
        p.IsActive = true;
        insert p;
        return p;
    }
    /*public static Pricebook2 createStandardPricebook(Id pbId){
        Pricebook2 stdPb = [select Id, isActive, isStandard from Pricebook2 where Id=:pbId limit 1];
        if (stdPb!=null && !stdPb.isActive){
            stdPb.isActive = true;
            update stdPb;
        }
        return stdPb;
    }*/
    public static Pricebook2 createCustomPricebook(String name, Boolean isActive, String curr){
        Pricebook2 pb = new Pricebook2();
        pb.Name = name;
        pb.IsActive = isActive;
        pb.CurrencyIsoCode = curr;
        insert pb;
        return pb;
    }
    public static PricebookEntry createPBE(Pricebook2 standard, Pricebook2 newPB, Product2 prod){
        PricebookEntry one = new PricebookEntry();
        one.Pricebook2Id = standard.Id;
        one.Product2Id = prod.Id;
        one.UnitPrice = 1249.0;
        one.IsActive = true;
        insert one;
        PricebookEntry ret = new PricebookEntry();
        ret.Pricebook2Id = newPB.Id;
        ret.Product2Id = prod.Id;
        ret.UnitPrice = 1250.0;
        ret.IsActive = true;
        insert ret;
        return ret;
    }
    public static Copado_Settings__c createCopadoSettings(String n, String pw, String un, Date d, Integer maxc){
        Copado_Settings__c s = new Copado_Settings__c();
        s.Name = n;
        s.Admin_Password__c = pw;
        s.Admin_Username__c = un;
        s.Last_Data_Export__c = d;
        s.Max_top_up_value__c = maxc;
        s.Server_URL__c = 'https://copado.herokuapp.com';
        insert s;
        return s;
    }
    public static kugo2p__KugamonSetting__c createKugamonSetting(String pricebookname){
        kugo2p__KugamonSetting__c testKugamonSetting = new kugo2p__KugamonSetting__c();
        testKugamonSetting.Name = 'Kugamon Configuration';
        testKugamonSetting.kugo2p__Admin_User__c = UserInfo.getUserId();
        testKugamonSetting.kugo2p__AllowOverrideServiceDateUpdate__c = true;
        testKugamonSetting.kugo2p__BillingMethod__c = 'Email';
        testKugamonSetting.kugo2p__CompanyTextandTerms__c = 'Test';
        testKugamonSetting.kugo2p__CreditTerms__c = 'No Credit Check Required';
        testKugamonSetting.kugo2p__DateAvailabletoPromiseBasis__c = 'Date Required';
        testKugamonSetting.kugo2p__DaysTillPaymentDue__c = 0;
        testKugamonSetting.kugo2p__DeliveryTerms__c = 'FOB Origin';
        testKugamonSetting.kugo2p__InvoiceTextandTerms__c = 'test';
        testKugamonSetting.kugo2p__FirstInvoiceDateBasis__c = 'Order Date Required';
        testKugamonSetting.kugo2p__DayofRevenueRecognition__c = '31';
        testKugamonSetting.kugo2p__OnlinePaymentButton__c = 'Accept & Approve';
        testKugamonSetting.kugo2p__OnlineConfirmationTextandTerms__c = 'Test';
        testKugamonSetting.kugo2p__PaymentMethod__c = 'Check';
        testKugamonSetting.kugo2p__PaymentTerms__c = 'Due Upon Receipt';
        testKugamonSetting.kugo2p__PriceBookName__c = pricebookname;
        testKugamonSetting.kugo2p__RemitToCity__c = 'MyCity';
        testKugamonSetting.kugo2p__RemitToCountry__c = 'USA';
        testKugamonSetting.kugo2p__RemitToName__c = 'Test';
        testKugamonSetting.kugo2p__RemitToStateProvince__c = 'CA';
        testKugamonSetting.kugo2p__RemitToStreet__c = '123 My Street';
        testKugamonSetting.kugo2p__RemitToZipPostalCode__c = '91405';
        testKugamonSetting.kugo2p__ResetQuoteOrderTermsConditions__c = 'Update Matched Terms';
        testKugamonSetting.kugo2p__RestrictedBannerText__c = 'Test';
        testKugamonSetting.kugo2p__SalesQuoteValidOfferInDays__c = 10;
        testKugamonSetting.kugo2p__UnitofMeasure__c = 'Each';
        testKugamonSetting.kugo2p__UnitofTerm__c = 'Year';
        testKugamonSetting.kugo2p__UpdateOpportunityAmountBasis__c = 'Net AMount';
        insert testKugamonSetting;
        return testKugamonSetting;
    }
    
    // START TESTS
    @IsTest
    static void runTestCode(){
        testHttpCalloutMock request1 = new testHttpCalloutMock(200, 'Complete', '{"status":"ok"}');
        Map<String, HttpCalloutMock> calloutMap = new Map<String, HttpCalloutMock>();
        calloutMap.put('https://testMethod.com/admin/syncFeatures?sid=someSessionId', request1);
        HttpCalloutMock multiCalloutMock = new MultiRequestMock(calloutMap);
        Test.setMock(HttpCalloutMock.class, multiCalloutMock);   
        
        Test.startTest();
        Account testAccount = createAccount('Salesforce.comTest123', 'orgId123');
        Contact testContact = createContact(testAccount.Id,'Mark','Benioff','ceo@salesforce.com', 'userId123');
        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org');
        insert org;
        Opportunity testOpportunity = createOpportunity(testAccount.Id, 'Opp Name', 'Marketing Qualification', 'testKey123',100,'Opp Main Problems');
        Id stdPricebookId = Test.getStandardPricebookId();
        Pricebook2 customPricebook = createCustomPricebook('^%New Pricebook', true, 'EUR');
        Product2 testProduct = createProduct('%$£TestProduct&^%', 10.0, '$£"Test(*)');
        PricebookEntry testEntry = createPBE(new Pricebook2(Id=Test.getStandardPricebookId()), customPricebook, testProduct);
        Copado_Settings__c cs = createCopadoSettings('testDefault', 'password', 'username', System.today(), 50);
        kugo2p__KugamonSetting__c testKugamonSetting=  createKugamonSetting(customPricebook.name);
        setupEntitlements();
        Test.stopTest();
        // MAKE ASSERTIONS
        Account[] a = [SELECT Id, Name FROM Account WHERE Name = 'Salesforce.comTest123'];
        System.assert(a.size() > 0);
        Contact[] c = [SELECT Id, FirstName, LastName, Email FROM Contact WHERE FirstName = 'Mark' AND LastName = 'Benioff' AND Email = 'ceo@salesforce.com'];
        System.assert(c.size() > 0);
        Opportunity[] o = [SELECT Id, AccountId, Name FROM Opportunity WHERE AccountId = :testAccount.Id];
        System.assert(o.size() > 0);
        Product2[] p2 = [SELECT Id, Name FROM Product2 WHERE Name =:'%$£TestProduct&^%'];
        System.assert(p2.size() > 0);
        Pricebook2[] pbs = [SELECT Id, Name FROM Pricebook2 WHERE Name =:'^%New Pricebook'];
        System.assert(pbs.size() > 0);
        PricebookEntry[] pbes = [SELECT Id, Name FROM PricebookEntry WHERE Pricebook2Id=:pbs[0].Id AND Product2Id=:p2[0].Id];
        System.assert(pbes.size() > 0);
        Copado_Settings__c[] css = [SELECT Id, Name FROM Copado_Settings__c WHERE Name =:'testDefault'];
        System.assert(css.size() > 0);
        
        
        ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'test'));
        System.assert(hasMessage('test'));
    }
}