objects/copado__Deployment_Flow__c.object
<CustomObject>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pipeline</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUserStoryDevOps360forDevelopment.cls
@IsTest
public class TestUserStoryDevOps360forDevelopment {
@testSetup static void setup() { 
        Id recordTypeIdUserStory = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('User Story').getRecordTypeId();
        copado__User_Story__c myUserStory1 = new copado__User_Story__c();
        myUserStory1.copado__User_Story_Title__c = 'UserStoryTest1';
        myUserStory1.copado__Status__c = 'Ready for Planning';
        myUserStory1.RecordTypeId = recordTypeIdUserStory;
        insert myUserStory1;
          
        copado__Deployment_Flow__c myPipeline1 = new copado__Deployment_Flow__c();
        myPipeline1.Name = 'My Pipeline1';
        insert myPipeline1;
        
        copado__Project__c myProject1 = new copado__Project__c();
        myProject1.Name = 'My Project1';
        insert myProject1;
        myUserStory1.copado__Project__c = myProject1.Id;  
        update myUserStory1;
        myUserStory1.copado__Status__c = 'Released';
        update myUserStory1;
        
        copado__User_Story__c myUserStory2 = new copado__User_Story__c();
        myUserStory2.copado__User_Story_Title__c = 'My UserStory 2';
        myUserStory2.copado__Status__c = 'Ready for Planning';
        myUserStory2.copado__Project__c = myProject1.Id;
        insert myUserStory2;
        myUserStory2.copado__Status__c = 'Released';
        update myUserStory2; 
    }
    

    @IsTest
    static void testUSisReleasedWithPipeline() {     
   
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c, copadometrics__First_Time_Promoted_to_Production__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'My UserStory 2'];
        System.assertEquals('Released', assertUserStory.copado__Status__c);
        System.assertEquals(null, assertUserStory.copadometrics__First_Time_Promoted_to_Production__c); 
    }  

    @IsTest
    static void testDevelopmentIsComplete() {     
        copado__User_Story__c UserStoryTest1 = [SELECT Id FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1'];
        UserStoryTest1.copado__Status__c = 'Development In Progress';
        update UserStoryTest1;
        UserStoryTest1.copado__Status__c = 'Ready for Release';
        Test.startTest();
        update UserStoryTest1;
        Test.stopTest();
        copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c, copadometrics__Development_Complete__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1']; 
        System.assertEquals(True, assertUserStory.copadometrics__Development_Complete__c);
   
    }
   
    @IsTest
    static void testUSisReleased() {     
        
    copado__User_Story__c assertUserStory = [SELECT Id, copado__Status__c, copadometrics__First_Time_Promoted_to_Production__c FROM copado__User_Story__c WHERE copado__User_Story_Title__c = 'UserStoryTest1']; 
        System.assertEquals('Released', assertUserStory.copado__Status__c);
        System.assertNotEquals(null, assertUserStory.copadometrics__First_Time_Promoted_to_Production__c);
    }  
}