objects/Customer_Review__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Reviews</relationshipLabel>
        <relationshipName>Customer_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Review__c</fullName>
        <label>Review</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Customer Review</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Customer Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/JBCXM__SurveyParticipant__c.object
<CustomObject>
    <description>This is used to store survey participants</description>
    <fields>
        <fullName>JBCXM__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Participants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SuP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Review__c.object
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>PER-REV-{000000}</displayFormat>
        <label>Review Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WebsiteCustomerReviewsController.cls
public class WebsiteCustomerReviewsController {
    
    public Set<String> industries {get;set;}
    public List<Customer_Review__c> reviews {get;set;}
    public String industry {get;set;}
    
    public PageReference init(){
        industry = ApexPages.currentPage().getParameters().get('industry');
		getReviews(industry);
        createIndustryList();
        return null;
    }
    public void getReviews(String i){
        reviews = new List<Customer_Review__c>();
        if(String.isNotEmpty(i) && i!='All'){
            reviews = [SELECT Id, Review__c, Contact__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Account.Name, Contact__r.Account.Industry
                   FROM Customer_Review__c where Published__c=true and Contact__r.Account.Industry=:industry order by Order__c ASC];
        }
        else{
            reviews = [SELECT Id, Review__c, Contact__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Account.Name, Contact__r.Account.Industry
                   FROM Customer_Review__c where Published__c=true order by Order__c ASC];
        }
    }
    public void createIndustryList(){
        industries = new Set<String>();
        industries.add('All');
        for(Customer_Review__c cr : [select Id, Contact__r.Account.Industry from Customer_Review__c where Published__c=true order by Contact__r.Account.Industry DESC]){
            industries.add(cr.Contact__r.Account.Industry);
        }
    }
}