objects/Demo__c.object
<CustomObject>
    <description>This object keeps all the information related to Demos.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Demos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Next_Contact__c</fullName>
        <label>Next Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Next_Step__c</fullName>
        <inlineHelpText>This field does not get mapped to the opportunity.</inlineHelpText>
        <label>Next Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/TestAutoConvertLead.cls
@isTest
private class TestAutoConvertLead {
    
    @isTest static void testConversion() {
        
        Lead l = TestDataFactory.createLead('Test', 'Customer4Life Inc.');
        l.FirstName = 'Copado';
        l.NumberOfEmployees = 90;        
        l.LeadSource = 'Advertisement';
        l.Rating = 'Tier 2';
        l.Next_Step__c = 'Next';
        l.Next_Contact__c = System.today();        
        l.Industry = 'Banking and Finance';
        
        insert l;

        Demo__c meeting = TestDataFactory.createDemo();
        meeting.Name = 'Test Demo';
        meeting.Lead__c = l.Id;
        insert meeting;

        Test.startTest();

        AutoConvertLead.AutoConvertLeadsApex(new List<Id>{meeting.Id});

        Test.stopTest();
    }   
}