objects/Interactive_Validation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interactive Validation</label>
    <nameField>
        <label>Interactive Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Achievement__c.object
<CustomObject>
    <fields>
        <fullName>ReputationPoints__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reputation Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Achievement</label>
        <referenceTo>redwing__Training_Plan_Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>Interactive_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation</label>
        <referenceTo>Interactive_Validation__c</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Dynamic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dynamic</label>
        <type>Checkbox</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <label>Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <inlineHelpText>Only Active Learning Plans will be visible to learners, Draft plans will be visible for Learning Admins</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AchievementAssignmentHandler.cls
public class AchievementAssignmentHandler {
    /** 
    Updates the Achievement Status of the user based on the Learning assignment validation status. 
    */
    public static void updateAchievementStatus(List<redwing__Achievement_Assignment__c> updatedAcvAssignments, Map<Id, redwing__Achievement_Assignment__c> oldAcvAssignments){
        Map<Id, Id> trainingPlanAchievementIdWithUser = new Map<Id, Id>();
        Map<Id, Id> trainingPlanWithUser = new Map<Id, Id>();
        Map<Id, Id> trainingPlanWithTPAchivement = new Map<Id, Id>();
        Map<Id, Id> tPlanWithUserForInvalidLA = new Map<Id, Id>();

        for (redwing__Achievement_Assignment__c badge : updatedAcvAssignments) {
            if(oldAcvAssignments.get(badge.id).redwing__Status__c != badge.redwing__Status__c && badge.redwing__Status__c == 'Acquired'){
                trainingPlanAchievementIdWithUser.put(badge.redwing__Training_Plan_Achievement__c, badge.redwing__User__c);
            }
        }

        if (!trainingPlanAchievementIdWithUser.isEmpty()) {
            for(redwing__Training_Plan_Achievement__c trainingPlanAchievement : [Select Id, redwing__Training_Plan__c From redwing__Training_Plan_Achievement__c Where Id IN :trainingPlanAchievementIdWithUser.keySet()]) {
                if (trainingPlanAchievementIdWithUser.containsKey(trainingPlanAchievement.Id)) {
                    Id achievementUserId = trainingPlanAchievementIdWithUser.get(trainingPlanAchievement.Id);
                    trainingPlanWithUser.put(achievementUserId, trainingPlanAchievement.redwing__Training_Plan__c);
                    trainingPlanWithTPAchivement.put(trainingPlanAchievement.Id, trainingPlanAchievement.redwing__Training_Plan__c);
                }
            }
        }

        if (!trainingPlanWithUser.isEmpty()) {
            for(redwing__Learning_Assignment__c module : [SELECT Id, Validation_Status__c, redwing__Learning__r.Interactive_Validation__c, redwing__Learning__r.Is_Dynamic__c,
                                                            redwing__Training_Plan__c, redwing__User__c
                                                            FROM redwing__Learning_Assignment__c
                                                            WHERE Validation_Status__c <> 'Success' AND
                                                            redwing__User__c IN :trainingPlanWithUser.keySet() AND
                                                            redwing__Training_Plan__c IN :trainingPlanWithUser.values() AND
                                                            redwing__Learning__r.Is_Dynamic__c = true AND
                                                            redwing__Learning__r.Interactive_Validation__c != null AND 
                                                            redwing__Learning__r.Interactive_Validation__r.Status__c ='Active']) {
                tPlanWithUserForInvalidLA.put(module.redwing__Training_Plan__c, module.redwing__User__c);
            }
        }

        if (!tPlanWithUserForInvalidLA.isEmpty()) {
            for (redwing__Achievement_Assignment__c badge : updatedAcvAssignments) {
                Id trainingPlanId =  trainingPlanWithTPAchivement.containsKey(badge.redwing__Training_Plan_Achievement__c) ? trainingPlanWithTPAchivement.get(badge.redwing__Training_Plan_Achievement__c) : null;
                if(trainingPlanId != null && oldAcvAssignments.get(badge.id).redwing__Status__c != badge.redwing__Status__c && badge.redwing__Status__c == 'Acquired'
                 && tPlanWithUserForInvalidLA.containsKey(trainingPlanId) && tPlanWithUserForInvalidLA.get(trainingPlanId) == badge.redwing__User__c ) {
                    badge.redwing__Status__c = 'Eligible';
                }
            }
        }
    }
    /** 
    Updates the reputation points of the user based on the achievement reputation points. 
    */
    public static void updateReputationPoints(List<redwing__Achievement_Assignment__c> updatedAcvAssignments, Map<Id, redwing__Achievement_Assignment__c> oldAcvAssignments){
        Set<Id> memberIds = new Set<Id>();
        Set<Id> achievementIds = new Set<Id>();
        Map<Id, Set<Id>> memberToAchievementMap = new Map<Id, Set<Id>>();
        for (redwing__Achievement_Assignment__c badge : updatedAcvAssignments) {
            if(oldAcvAssignments.get(badge.id).redwing__Status__c != badge.redwing__Status__c && badge.redwing__Status__c == 'Acquired'){
                memberIds.add(badge.redwing__User__c);
                Set<Id> acvList = new Set<Id>{badge.redwing__Achievement__c};
                    if(memberToAchievementMap.get(badge.redwing__User__c) != null){
                        acvList.addAll(memberToAchievementMap.get(badge.redwing__User__c));
                    }
                memberToAchievementMap.put(badge.redwing__User__c, acvList);
                achievementIds.add(badge.redwing__Achievement__c);
            }
        }
        if(!memberIds.isEmpty() && !achievementIds.isEmpty()){
            Map<Id, redwing__Achievement__c> achievementMap = new Map<Id, redwing__Achievement__c>([SELECT Id, ReputationPoints__c 
                                                                                                    FROM redwing__Achievement__c 
                                                                                                    WHERE Id IN :achievementIds AND ReputationPoints__c != null]);
            List<NetworkMember> members = [SELECT Id, MemberId, ReputationPoints 
                                           FROM NetworkMember 
                                           WHERE MemberId IN :memberIds];
            For(NetworkMember member : members){
                if(memberToAchievementMap.get(member.MemberId) != null){
                    For(Id achievementId : memberToAchievementMap.get(member.MemberId)){
                        if(achievementMap.get(achievementId) != null){
                            member.ReputationPoints = member.ReputationPoints + achievementMap.get(achievementId).ReputationPoints__c;
                        } 
                    }
                }
            }
            update members;
        }
    }

}