objects/Interactive_Validation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interactive Validation</label>
    <nameField>
        <label>Interactive Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interactive_Validation_Step__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dev1</fullName>
                </value>
                <value>
                    <fullName>Dev2</fullName>
                </value>
                <value>
                    <fullName>UAT</fullName>
                </value>
                <value>
                    <fullName>Hotfix</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExecutionDetails__c</fullName>
        <label>ExecutionDetails</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExecutionOrder__c</fullName>
        <label>ExecutionOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interactive_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation</label>
        <referenceTo>Interactive_Validation__c</referenceTo>
        <relationshipLabel>Interactive Validation Steps</relationshipLabel>
        <relationshipName>Interactive_Validation_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Validate Data</fullName>
                </value>
                <value>
                    <fullName>Validate Metadata</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interactive Validation Step</label>
    <nameField>
        <label>Interactive Validation Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validation Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interactive_Validation_Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>Interactive_Validation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation Step</label>
        <referenceTo>Interactive_Validation_Step__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Learning_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Assignment</label>
        <referenceTo>redwing__Learning_Assignment__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Validation Execution</label>
        <referenceTo>Validation_Execution__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interactive Validation Step Execution</label>
    <nameField>
        <label>Interactive Validation Step Execution Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validation Step Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>Interactive_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation</label>
        <referenceTo>Interactive_Validation__c</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Dynamic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dynamic</label>
        <type>Checkbox</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <label>Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Section_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Section Item</label>
        <referenceTo>redwing__Training_Plan_Section_Item__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>Show_Trail_Setup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Trail Setup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only published learning objects can be added to a Learning Plan</errorMessage>
            <filterItems>
                <field>redwing__Learning__c.redwing__Is_Published_Formula__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>NOTE: Only published learning objects can be associated to a Learning Plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Section Item</label>
    <nameField>
        <displayFormat>LPSI-{0000000}</displayFormat>
        <label>Learning Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Signup_Request__c.object
<CustomObject>
    <description>This object captures the Signup Requests generated from the community and creates Trialforce orgs</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Signup Request</label>
    <nameField>
        <displayFormat>SR{0000000000}</displayFormat>
        <label>Signup Request Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signup Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Validation_Execution__c.object
<CustomObject>
    <fields>
        <fullName>Interactive_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation</label>
        <referenceTo>Interactive_Validation__c</referenceTo>
        <relationshipLabel>Validation Executions</relationshipLabel>
        <relationshipName>Validation_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Learning_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Assignment</label>
        <referenceTo>redwing__Learning_Assignment__c</referenceTo>
        <relationshipLabel>Validation Executions</relationshipLabel>
        <relationshipName>Validation_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Validation Execution</label>
    <nameField>
        <displayFormat>VE-{000000}</displayFormat>
        <label>Validation Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Validation Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/tms_TrailModuleValidationController.cls
global without sharing class tms_TrailModuleValidationController {
    public enum HttpMethods {GET, POST, PUT}
    static final String COE_ORG_TYPE = 'CoE_Org';
    static final String SCRATCH_ORG_ORG_TYPE = 'Scratch_Org';
    
    // Return current user session id for Lightning to connect with CometD
    @AuraEnabled
    public static String getSessionId() {
        return UserInfo.getSessionId();
    }

    @AuraEnabled
    global static String hasIMValidationConfigStep(String moduleId) {
        List<redwing__Learning_Assignment__c> modules = [select Id, Validation_Status__c, redwing__Learning__r.Interactive_Validation__c, redwing__Learning__r.Is_Dynamic__c,
                                                            redwing__Training_Plan_Section_Item__c, redwing__Training_Plan_Section_Item__r.Show_Trail_Setup__c
                                                            from redwing__Learning_Assignment__c
                                                    where Id=:moduleId and 
                                                    redwing__Learning__r.Interactive_Validation__c != null and 
                                                    redwing__Learning__r.Interactive_Validation__r.Status__c ='Active'];
        return (modules.size()>0 && modules[0].redwing__Learning__r.Is_Dynamic__c && modules[0].redwing__Learning__r.Interactive_Validation__c != null )? ((modules[0].Validation_Status__c != null) ?  modules[0].Validation_Status__c : 'Pending') : null;
    }
    
    public static List<Interactive_Validation_Step__c> getIVConfigurationStep(String learningAssignmentId){
        List<redwing__Learning_Assignment__c> modules = [select Id, redwing__Learning__r.Interactive_Validation__c 
                                                        from redwing__Learning_Assignment__c where Id=:learningAssignmentId];
                                                        
        if(modules.size()>0 && modules[0].redwing__Learning__r.Interactive_Validation__c != null){
            List<Interactive_Validation_Step__c> imVConfigSteps = [Select Id, Name, Environment__c, Type__c, ExecutionDetails__c, ExecutionOrder__c, Interactive_Validation__c 
                                                        From Interactive_Validation_Step__c 
                                                        Where Interactive_Validation__c =:modules[0].redwing__Learning__r.Interactive_Validation__c 
                                                        AND Interactive_Validation__r.Status__c = 'Active'];
            return (imVConfigSteps.isEmpty()) ? null : imVConfigSteps;
        } else {
            return null; 
        } 
    }

    @AuraEnabled
    public static String runIVOrgConfigurationStep(String playgroundId, String learningAssignmentId){
        try {
            if(playgroundId != null) {
                List<Interactive_Validation_Step_Execution__c> stepExecution = getInteractiveValidationStepExecution(playgroundId, learningAssignmentId);
                if (stepExecution != null && !stepExecution.isEmpty()) {
                    String validationExecutionId = null;
                    for (Interactive_Validation_Step_Execution__c ivse : stepExecution) {
                        if (ivse.Validation_Execution__r.Status__c == 'Failed' || ivse.Validation_Result__c != 'Success' || ivse.ExecutionStatus__c == 'Failed') {
                            validationExecutionId = ivse.Validation_Execution__c;
                            break;
                        }
                    }
                    
                    if (validationExecutionId != null) {
                        Validation_Execution__c ve = new Validation_Execution__c(Id = validationExecutionId);
                        ve.Status__c = 'In progress';
                        update ve;
                    }

                    return 'Validation Execution Restarted';
                }

                List<Interactive_Validation_Step__c> imValidConfigSteps = getIVConfigurationStep(learningAssignmentId);

                if (imValidConfigSteps == null || imValidConfigSteps.isEmpty()) {
                    return 'Interactive Validation Configure Steps not setup yet';
                }

                List<Playground__c> pgs = [select Id, Api_Key__c, Org_Credential__c, Custom_Signup_Request__r.Domain__c from Playground__c where Id=:playgroundId];
                
                String trialOrgDomain = pgs.isEmpty() ? null : pgs[0].Custom_Signup_Request__r.Domain__c;

                Map<String, Playground_Enviroment__c> playgroundEnvs = new Map<String, Playground_Enviroment__c>();
                for(Playground_Enviroment__c env : [Select Id, Name, Authorization_URL__c, InstanceUrl__c, Type__c 
                                                    From Playground_Enviroment__c 
                                                    Where Playground__c =:playgroundId]){ 
                    if (env.Type__c != SCRATCH_ORG_ORG_TYPE) {
                        env.InstanceUrl__c = 'https://'+trialOrgDomain+ (env.Type__c == COE_ORG_TYPE ? '' : '--' + env.Name).toLowerCase() + '.my.salesforce.com';
                    }
                    
                    playgroundEnvs.put(env.Name, env);
                }

                Validation_Execution__c validationExecutionToBeInsert = new Validation_Execution__c(
                    Learning_Assignment__c = learningAssignmentId,
                    Playground__c = playgroundId,
                    Interactive_Validation__c = imValidConfigSteps[0].Interactive_Validation__c
                );

                insert validationExecutionToBeInsert;

                String api_key = pgs.isEmpty() ? null : pgs[0].Api_Key__c;
                String trialOrgCredentialId = pgs.isEmpty() ? null : pgs[0].Org_Credential__c;

                List<Interactive_Validation_Step_Execution__c> IVStepExecutionToBeInsert = new List<Interactive_Validation_Step_Execution__c>();
                for (Interactive_Validation_Step__c configStep : imValidConfigSteps) {
                    String orgName = (configStep.Environment__c == 'Trial') ? 'Copado' : configStep.Environment__c;
                    if(playgroundEnvs.containsKey(orgName)){
                        String orgCredentialId = cps_Helper.getOrgCredentialIdFromAuthorizationUrl(playgroundEnvs.get(orgName).Authorization_URL__c);
                        IVStepExecutionToBeInsert.add(createIVStepExecution(configStep, validationExecutionToBeInsert.Id, orgCredentialId, api_key, playgroundEnvs.get(orgName).InstanceUrl__c, trialOrgCredentialId));
                    }
                }
                insert IVStepExecutionToBeInsert;

                Validation_Execution__c validationExecutionStart = new Validation_Execution__c(
                    Id = validationExecutionToBeInsert.Id,
                    Status__c = 'In progress'
                );
                update validationExecutionStart;
            }
            return 'Validation Steps Execution Started';
        }catch(Exception e){
            System.debug(e);
            return null;
        }
            
    }

    public static Interactive_Validation_Step_Execution__c createIVStepExecution(
        Interactive_Validation_Step__c configStep,
        String validationExecutionId,
        String orgCredentialId,
        String api_key, 
        String targetInstanceURL, 
        String trialOrgCredentialId
    ) {

        Interactive_Validation_Step_Execution__c step = new Interactive_Validation_Step_Execution__c(
            Name = configStep.Name,
            Interactive_Validation_Step__c = configStep.Id,
            Validation_Execution__c = validationExecutionId,
            OrgCredentialId__c = orgCredentialId,
            ApiKey__c = api_key,
            Target_Instance_URL__c = targetInstanceURL,
            Trial_Org_Credential_Id__c = trialOrgCredentialId
        );

        return step;
    }
    @AuraEnabled
    public static List<Interactive_Validation_Step_Execution__c> getInteractiveValidationStepExecution(String playgroundId, String learningAssignmentId){
        List<Interactive_Validation_Step_Execution__c> inProgressIVStepExecution = [Select Id, Name, Validation_Execution__c, ExecutionStatus__c, Validation_Result__c, Interactive_Validation_Step__r.ExecutionOrder__c, 
                Validation_Execution__r.Status__c
                From Interactive_Validation_Step_Execution__c 
                Where Validation_Execution__c IN 
                (Select Id From Validation_Execution__c Where Learning_Assignment__c = :learningAssignmentId AND Playground__c =:playgroundId)
                Order By Interactive_Validation_Step__r.ExecutionOrder__c ASC];

        return inProgressIVStepExecution;
    }
}