objects/Interactive_Validation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interactive Validation</label>
    <nameField>
        <label>Interactive Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Achievement</label>
        <referenceTo>redwing__Training_Plan_Achievement__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>Interactive_Validation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation</label>
        <referenceTo>Interactive_Validation__c</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Dynamic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dynamic</label>
        <type>Checkbox</type>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <label>Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <inlineHelpText>Only Active Learning Plans will be visible to learners, Draft plans will be visible for Learning Admins</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LearningAssignmentTriggerHelper.cls
public with sharing class LearningAssignmentTriggerHelper {
    /** 
    Updates the Achievement Status of the user based on the Learning assignment validation status. 
    */
    public static void updateAchievementStatus(List<redwing__Learning_Assignment__c> updatedLearningAssignments, Map<Id, redwing__Learning_Assignment__c> oldLearningAssignments){
        Set<Id> memberIds = new Set<Id>();
        Set<Id> memberIdsForAchivement = new Set<Id>();
        Map<Id, Set<Id>> learningPlanUserIds = new Map<Id, Set<Id>>();
        Map<Id, Id> learningPlanwithAchivIds = new Map<Id, Id>();
        List<redwing__Achievement_Assignment__c> achivAssignments = new List<redwing__Achievement_Assignment__c>();
        
        for (redwing__Learning_Assignment__c learningAssignment : updatedLearningAssignments) {
            if(oldLearningAssignments.get(learningAssignment.id).Validation_Status__c != learningAssignment.Validation_Status__c && learningAssignment.Validation_Status__c == 'Success'){
                memberIds.add(learningAssignment.redwing__User__c);
                if (!learningPlanUserIds.containsKey(learningAssignment.redwing__Training_Plan__c)) {
                    learningPlanUserIds.put(learningAssignment.redwing__Training_Plan__c, new Set<Id>());
                }
                learningPlanUserIds.get(learningAssignment.redwing__Training_Plan__c).add(learningAssignment.redwing__User__c);
            }
        }

        if (!learningPlanUserIds.isEmpty()) {
            for(redwing__Learning_Assignment__c module : [SELECT Id, Validation_Status__c, redwing__Learning__r.Interactive_Validation__c, redwing__Learning__r.Is_Dynamic__c,
                                                            redwing__Training_Plan__c, redwing__User__c
                                                            FROM redwing__Learning_Assignment__c
                                                            WHERE ID <> :oldLearningAssignments.keySet() AND
                                                            Validation_Status__c <> 'Success' AND
                                                            redwing__User__c IN :memberIds AND
                                                            redwing__Training_Plan__c IN :learningPlanUserIds.keySet() AND
                                                            redwing__Learning__r.Is_Dynamic__c = true AND
                                                            redwing__Learning__r.Interactive_Validation__c != null AND 
                                                            redwing__Learning__r.Interactive_Validation__r.Status__c ='Active']) {
                if(learningPlanUserIds.containsKey(module.redwing__Training_Plan__c)){
                    Set<Id> userIds = learningPlanUserIds.get(module.redwing__Training_Plan__c);
                    if (userIds.size() > 1) {
                        userIds.remove(module.redwing__User__c);
                    } else {
                        learningPlanUserIds.remove(module.redwing__Training_Plan__c);
                    }
                }
            }
        }

        if (!learningPlanUserIds.isEmpty()) {
            for (redwing__Training_Plan_Achievement__c learningPlanAchiv : [Select Id, redwing__Training_Plan__c From redwing__Training_Plan_Achievement__c Where redwing__Training_Plan__c IN :learningPlanUserIds.keySet()]) {
                learningPlanwithAchivIds.put(learningPlanAchiv.redwing__Training_Plan__c, learningPlanAchiv.Id);
            }
        }

        if (!learningPlanwithAchivIds.isEmpty()) {
            for(Id lpId : learningPlanUserIds.keySet()){
                memberIdsForAchivement.addAll(learningPlanUserIds.get(lpId));
            }
            for (redwing__Achievement_Assignment__c achivAssignment : [Select Id, redwing__Status__c 
                                                                        From redwing__Achievement_Assignment__c 
                                                                        Where redwing__Status__c = 'Eligible' AND
                                                                        redwing__Training_Plan_Achievement__c IN :learningPlanwithAchivIds.values() AND
                                                                        redwing__User__c IN :memberIdsForAchivement]) {
                achivAssignment.redwing__Status__c = 'Acquired';
                achivAssignments.add(achivAssignment);
            }

            if (!achivAssignments.isEmpty()) {
                update achivAssignments;
            }
        }
    }
}