objects/Interactive_Validation_Step__c.object
<CustomObject>
    <fields>
        <fullName>ExecutionOrder__c</fullName>
        <label>ExecutionOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interactive Validation Step</label>
    <nameField>
        <label>Interactive Validation Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validation Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Interactive_Validation_Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>ExecutionStatus__c</fullName>
        <label>Execution Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interactive_Validation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interactive Validation Step</label>
        <referenceTo>Interactive_Validation_Step__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Learning_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Assignment</label>
        <referenceTo>redwing__Learning_Assignment__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Validation Execution</label>
        <referenceTo>Validation_Execution__c</referenceTo>
        <relationshipLabel>Interactive Validation Step Executions</relationshipLabel>
        <relationshipName>Interactive_Validation_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Payload__c</fullName>
        <label>Validation Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Validation_Result__c</fullName>
        <label>Validation Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Partial Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interactive Validation Step Execution</label>
    <nameField>
        <label>Interactive Validation Step Execution Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactive Validation Step Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <label>Validation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Validation_Execution__c.object
<CustomObject>
    <fields>
        <fullName>Learning_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Assignment</label>
        <referenceTo>redwing__Learning_Assignment__c</referenceTo>
        <relationshipLabel>Validation Executions</relationshipLabel>
        <relationshipName>Validation_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Validation Execution</label>
    <nameField>
        <displayFormat>VE-{000000}</displayFormat>
        <label>Validation Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Validation Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InteractiveValidStepExeService.cls
public with sharing class InteractiveValidStepExeService {
    
    public static void resetJob(Interactive_Validation_Step_Execution__c oldSe, Interactive_Validation_Step_Execution__c se) {
        if((oldSe.ExecutionStatus__c=='Failed' || oldSe.ExecutionStatus__c=='Completed') && (se.ExecutionStatus__c=='Pending' || se.ExecutionStatus__c=='In progress')) {
            se.Validation_Payload__c = null;
        }
    }
	//Method to update Validation status on learning assignment
    public static void updateValidationonLAssignment(Interactive_Validation_Step_Execution__c oldSe, Interactive_Validation_Step_Execution__c se) {
        if(se.Validation_Execution__c == null) {return;}
        
        if(oldSe.Validation_Result__c != se.Validation_Result__c  && (se.Validation_Result__c == 'Success' || se.Validation_Result__c == 'Failed')) {
            Boolean isAllFinished = true;
            String learningAssignmentValidationStatus = 'Success';
            String learningAssignmentId = null;
            for(Interactive_Validation_Step_Execution__c seTemp : [Select Id, Name, Validation_Result__c, Interactive_Validation_Step__r.ExecutionOrder__c, Validation_Execution__r.Learning_Assignment__c 
                                            From Interactive_Validation_Step_Execution__c 
                                            Where Validation_Execution__c =:se.Validation_Execution__c
                                            Order By Interactive_Validation_Step__r.ExecutionOrder__c ASC]){
                if (learningAssignmentId == null) {
                    learningAssignmentId = seTemp.Validation_Execution__r.Learning_Assignment__c;
                }
                if (seTemp.Validation_Result__c != 'Success' && seTemp.Validation_Result__c != 'Failed') {
                    isAllFinished = false;
                    break;
                } else if (seTemp.Validation_Result__c == 'Failed') {
                    learningAssignmentValidationStatus = 'Failed';
                }
            }

            if (isAllFinished && learningAssignmentId != null) {
                redwing__Learning_Assignment__c learningAssignment = new redwing__Learning_Assignment__c(Id = learningAssignmentId, Validation_Status__c = learningAssignmentValidationStatus);

                update learningAssignment;
            }
        }
    }

    public static void checkPayload(Interactive_Validation_Step_Execution__c oldSe, Interactive_Validation_Step_Execution__c se) {
        if(se.Validation_Payload__c == null) {return;}
        try {
            String payload = EncodingUtil.urlDecode(se.Validation_Payload__c, 'UTF-8');
            se.Validation_Payload__c = payload;
        	Map<String, Object> payloadObj = cps_InteractiveModule_Utils.parsePayload(se.Validation_Payload__c);
            if (payloadObj.containsKey('hasError') && (payloadObj.get('hasError') == 'false' || payloadObj.get('hasError') == false)) {
            	se.ExecutionStatus__c = 'Completed';
                if (payloadObj.containsKey('validationResult') && payloadObj.get('validationResult') == 'Success') {
                    se.Validation_Result__c = 'Success';
                } else if (payloadObj.containsKey('validationResult') && payloadObj.get('validationResult') == 'Failed') {
                    se.Validation_Result__c = 'Failed';
                }

            } else {
            	se.ExecutionStatus__c = 'Failed';
            }
        }
        catch (Exception e) {
        }
    }
}