objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ClickDeploy_Created_Date__c</fullName>
        <label>ClickDeploy Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Enterprise_Trial_Expiry_Date__c</fullName>
        <label>ClickDeploy Enterprise Trial Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Enterprise_Trial_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ClickDeploy Enterprise Trial Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Last_Login_Date__c</fullName>
        <label>ClickDeploy Last Login Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_License_Type__c</fullName>
        <label>ClickDeploy License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClickDeploy_Salesforce_Org_Id__c</fullName>
        <label>ClickDeploy Salesforce Org Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Salesforce_Username__c</fullName>
        <label>ClickDeploy Salesforce Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Total_Deploy_Attempt__c</fullName>
        <label>ClickDeploy Total Deploy Attempt</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Total_Deploy_This_Month__c</fullName>
        <label>ClickDeploy Total Deploy This Month</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_User_Id__c</fullName>
        <externalId>true</externalId>
        <label>ClickDeploy User Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MQL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the Lead is MQL</description>
        <label>MQL</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/LeadTriggerHandlerTest.cls
@IsTest
private class LeadTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        Contact conTest = new Contact(
            FirstName = 'Test1', LastName = 'Test1', Email = 'Test1@salesforce.com',
            ClickDeploy_Enterprise_Trial_Expiry_Date__c = Date.today(),
            ClickDeploy_Enterprise_Trial_Started__c = true,
            ClickDeploy_Total_Deploy_Attempt__c = 100,
            ClickDeploy_User_Id__c = 100,
            ClickDeploy_Last_Login_Date__c = Date.today(),
            ClickDeploy_Created_Date__c = Date.today(),
            ClickDeploy_Salesforce_Org_Id__c = 'Test_Org_Id',
            ClickDeploy_Salesforce_Username__c = 'Test1@salesforce.com'
        );
        insert conTest;
    }
    @isTest
    static void testLeadCreate()
    {
        /*
        Contact conTest = new Contact(
            FirstName = 'Test2', LastName = 'Test2', Email = 'Test2@salesforce.com',
            //ClickDeploy_Enterprise_Trial_Expiry_Date__c = Date.today(),
            ClickDeploy_Enterprise_Trial_Started__c = false,
            ClickDeploy_Total_Deploy_Attempt__c = 0,
            ClickDeploy_User_Id__c = 50,
            ClickDeploy_Last_Login_Date__c = Date.today(),
            ClickDeploy_Created_Date__c = Date.today(),
            ClickDeploy_Salesforce_Org_Id__c = 'Test_Org_Id',
            ClickDeploy_Salesforce_Username__c = 'Test2@salesforce.com',
            ClickDeploy_License_Type__c = 'Free'
        );
        insert conTest;
        // lead created
        system.assertEquals(2, [SELECT Id FROM Lead].size());
        conTest.ClickDeploy_Total_Deploy_This_Month__c = 3;
        conTest.ClickDeploy_Total_Deploy_Attempt__c = 3;
        conTest.ClickDeploy_License_Type__c = 'Free';
        update conTest;
        Lead l = [SELECT Id, Status, MQL__c FROM Lead 
            WHERE 
            ClickDeploy_User_Id__c = 50];
        //system.assertEquals(true, l.MQL__c);
        */
        Lead l = new Lead(LastName='LastName', Company='Company');
        insert l;
        update l;
        LeadTriggerHelper lh = new LeadTriggerHelper();
    }
}