objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ClickDeploy_Created_Date__c</fullName>
        <label>ClickDeploy Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Enterprise_Trial_Expiry_Date__c</fullName>
        <label>ClickDeploy Enterprise Trial Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Enterprise_Trial_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ClickDeploy Enterprise Trial Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Last_Login_Date__c</fullName>
        <label>ClickDeploy Last Login Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Salesforce_Org_Id__c</fullName>
        <label>ClickDeploy Salesforce Org Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Salesforce_Username__c</fullName>
        <label>ClickDeploy Salesforce Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_Total_Deploy_Attempt__c</fullName>
        <label>ClickDeploy Total Deploy Attempt</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ClickDeploy_User_Id__c</fullName>
        <externalId>true</externalId>
        <label>ClickDeploy User Id</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/ClickDeployLeadConversionTest.cls
@isTest
private class ClickDeployLeadConversionTest {
    @TestSetup
    static void makeData(){
        Contact conTest = new Contact(
            FirstName = 'Test1', LastName = 'Test1', Email = 'Test1@salesforce.com',
            ClickDeploy_Enterprise_Trial_Expiry_Date__c = Date.today(),
            ClickDeploy_Enterprise_Trial_Started__c = true,
            ClickDeploy_Total_Deploy_Attempt__c = 100,
            ClickDeploy_User_Id__c = 100,
            ClickDeploy_Last_Login_Date__c = Date.today(),
            ClickDeploy_Created_Date__c = Date.today(),
            ClickDeploy_Salesforce_Org_Id__c = 'Test_Org_Id',
            ClickDeploy_Salesforce_Username__c = 'Test1@salesforce.com'
        );
        insert conTest;
    }
    
    @isTest
    static void testClickDeployLeadConversion()
    {
        // nr mock test 
        List<Lead> theLeads = new List<Lead>();

        Lead l = new Lead();
        l.LastName = 'dummy';
        l.Company = 'dummy';
        insert l;
        theLeads.add(l);

        ClickDeployLeadConversion.convertLead(theLeads);
    }
}