objects/Listing__c.object
<CustomObject>
    <description>The listings to be featured on the community.</description>
    <label>Listing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Listing_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentVersion_Id__c</fullName>
        <inlineHelpText>This is the ContentVersion record Id of the associate file. This field is set by LWC using the AssetService class. This field also may have package id if asset type is install</inlineHelpText>
        <label>Asset Content Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Section__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>Link</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Resource__c</fullName>
        <label>Customer Resource</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Section__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Testimonial</fullName>
                </value>
                <value>
                    <fullName>Whitepaper</fullName>
                </value>
                <value>
                    <fullName>Case Study</fullName>
                </value>
                <value>
                    <fullName>Data Sheet</fullName>
                </value>
                <value>
                    <fullName>Customization Guide</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Assets</relationshipLabel>
        <relationshipName>Listing_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tile Logo</fullName>
                </value>
                <value>
                    <fullName>Tile Image</fullName>
                </value>
                <value>
                    <fullName>Carousel</fullName>
                </value>
                <value>
                    <fullName>Demo Video</fullName>
                </value>
                <value>
                    <fullName>Customer Resource</fullName>
                </value>
                <value>
                    <fullName>Download</fullName>
                </value>
                <value>
                    <fullName>Install</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Listing Asset</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Listing Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ListingAssetService.cls
public with sharing class ListingAssetService {

    @AuraEnabled(cacheable=true)
    public static List<Listing_Asset__c> getAssetsBySection(String listingId, String section) {
        system.debug('### ListingID: '+listingId+' SECTION:'+section);
        return [select Id, Name, Caption__c, Content_Type__c, Customer_Resource__c, Listing__c, Section__c, ContentVersion_Id__c, Order__c
         from Listing_Asset__c where Listing__c=:listingId and Section__c=:section order by Order__c ASC];
    }

    @AuraEnabled
    public static Listing_Asset__c createListingAsset(Listing_Asset__c la) {
        system.debug('Listing Asset: '+la);
        if (la!=null) {
            insert la;
            return la;
        }
        else {
            return null;
        }
    }

    @AuraEnabled
    public static Listing_Asset__c updateListingAsset(Listing_Asset__c la) {
        system.debug('Listing Asset: '+la);
        Id contentVersionId = getContentVersionId(la.ContentVersion_Id__c);
        la.ContentVersion_Id__c = contentVersionId;
        update la;
        return la;
    }

    @AuraEnabled
    public static void updateListingAssets(List<Listing_Asset__c> assets) {
        if (assets==null || assets.size()==0) return;
        update assets;
    }

    @AuraEnabled
    public static Boolean deletContentDocument(Id contentVersionId) {
        system.debug('Received delete request: '+contentVersionId);
        try {
            system.debug('try: ');
            ContentVersion cv = [select Id, ContentDocumentId from ContentVersion where Id=:contentVersionId limit 1];
            system.debug('CV: '+cv);
            ContentDocument cd = new ContentDocument(Id=cv.ContentDocumentId);
            system.debug('CD: '+cd);
            delete cd;
            system.debug('...deleted. returning true.');
            return true;
        }
        catch(Exception e) {
            system.debug('Error during content document deletion: '+e.getMessage());
            return false;
        }
    }

    @AuraEnabled
    public static void deleteAssetAndFiles(Id assetId) {
        if (assetId==null) return;
        List<ContentDocument> deletions = new List<ContentDocument>();
        List<ContentDocumentLink> files = [select ContentDocumentId, LinkedEntityId from ContentDocumentLink where LinkedEntityId=:assetId and LinkedEntity.Type='Listing_Asset__c'];
        for (ContentDocumentLink file : files) {
            deletions.add(new ContentDocument(Id=file.ContentDocumentId));
        }

        Listing_Asset__c asset = new Listing_Asset__c(Id=assetId);
        delete asset;
        delete deletions;
    }

    private static Id getContentVersionId(Id contentDocumentId) {
        try {
            ContentVersion cv = [select Id from ContentVersion where ContentDocumentId=:contentDocumentId limit 1];
            return cv.Id;
        }
        catch(Exception e) {
            return null;
        }
    }
}