objects/Listing__c.object
<CustomObject>
    <description>The listings to be featured on the community.</description>
    <fields>
        <fullName>Listing_Profile__c</fullName>
        <label>Listing Profile</label>
        <referenceTo>Listing_Profile__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Listing_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Listing__c</fullName>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Assets</relationshipLabel>
        <relationshipName>Listing_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Listing Asset</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Listing Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Listing_Profile__c.object
<CustomObject>
    <description>The listing profile is used in the community to store the profile information for a listing (e.g. company info).</description>
    <label>Listing Profile</label>
    <nameField>
        <label>Listing Profile Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listing Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/listingAssetFileUtilityServiceTest.cls
@isTest
public with sharing class listingAssetFileUtilityServiceTest {
    static testMethod void testGetFiles() {
        Listing_Profile__c profile = new Listing_Profile__c(Name='Copado Labs');
        insert profile;

        Listing__c listing = new Listing__c(Name='Listing 1', Listing_Profile__c = profile.Id);
        insert listing;

        Listing_Asset__c ass1 = new Listing_Asset__c( Listing__c=listing.Id);
        insert ass1;

        ContentVersion conVer1 = new ContentVersion( Title='Name1', PathOnClient='test', VersionData=Blob.valueof('file 1') );
        ContentVersion conVer2 = new ContentVersion( Title='Name2', PathOnClient='test', VersionData=Blob.valueof('file 2') );
        List<ContentVersion> conVerList = new List<ContentVersion>();
        conVerList.add(conVer1);
        conVerList.add(conVer2); 
        insert conVerList;

        Set<Id> ids = new Set<Id>();
        for (ContentVersion cv : conVerList) {
            ids.add(cv.Id);
        }

        List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();
        for (ContentVersion cv : [SELECT ContentDocumentId FROM ContentVersion WHERE Id IN:ids]) {
            ContentDocumentLink cdl = new ContentDocumentLink( LinkedEntityId=ass1.Id, ContentDocumentId=cv.ContentDocumentId, ShareType='I' );
            cdls.add(cdl);
        }
        insert cdls;

        Test.startTest();
        List<listingAssetFileUtilityService.AssetFile> result = listingAssetFileUtilityService.getFiles(ass1.Id);
        system.assertEquals(2, result.size());
        Test.stopTest();
    }
}