objects/Listing__c.object
<CustomObject>
    <description>The listings to be featured on the community.</description>
    <fields>
        <fullName>Listing_Profile__c</fullName>
        <label>Listing Profile</label>
        <referenceTo>Listing_Profile__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Listing_Analytics__c.object
<CustomObject>
    <fields>
        <fullName>Action2__c</fullName>
        <label>Action 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_ID__c</fullName>
        <label>Document ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Analytics</relationshipLabel>
        <relationshipName>Listing_Analytics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page_Source__c</fullName>
        <label>Page Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Listing_Analytics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Listing Analytics</label>
    <nameField>
        <displayFormat>LA-{0000000000}</displayFormat>
        <label>Listing Analytics Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Analytics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Listing_Analytics_Event__e.object
<CustomObject>
    <fields>
        <fullName>Action2__c</fullName>
        <label>Action2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_ID__c</fullName>
        <label>Document ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing_ID__c</fullName>
        <label>Listing ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Source__c</fullName>
        <label>Page Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_ID__c</fullName>
        <label>User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Listing Analytics Event</label>
    <pluralLabel>Listing Analytics Events</pluralLabel>
</CustomObject>

objects/Listing_Profile__c.object
<CustomObject>
    <description>The listing profile is used in the community to store the profile information for a listing (e.g. company info).</description>
    <label>Listing Profile</label>
    <nameField>
        <label>Listing Profile Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listing Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ListingAnalyticsServiceTest.cls
/**
 * This is the test class for ListingAnalyticsService.
 * Author: Philipp Rackwitz
 * Date: 2021-01-21
 * Version 1:
 */
@isTest
public with sharing class ListingAnalyticsServiceTest {

    /**
     * This test covers the Flow also that we are publishing an event and asserting that a Listing Analytics record was created.
     * The Platform Event is created via usage of the community where the LWC "Listing Analytics Service" component sends data to this ListingAnalyticsService Apex Class.
     * The apex class then publishes the platform event that is picked up by the flow which creates the custom object record.
     */
    static testMethod void test_publishListingEvent() {
        
        User testUser = [select Id from User where IsActive=true and UserType='CspLitePortal' limit 1];
        String dateStringFromCommunity = '2020-01-19 18:18:18';
        String action = 'Page View';
        String action2 = null;
        Listing_Profile__c testProfile = createProfile('Copado, Inc.');
        Listing__c testListing = createListing('Copado Templates', testProfile.Id);
        String documentId = 'Some doc id';
        String pageSource = 'Search Results';

        Test.startTest();

        ListingAnalyticsService.publishListingEvent(dateStringFromCommunity, testUser.Id, action, action2, testListing.Id, documentId, pageSource);
        Test.getEventBus().deliver();
        
        Test.stopTest();

        //Check that the event was published.
        EventBusSubscriber[] subscribers = getSubscribers('Listing_Analytics_Event__e');
        system.assertEquals(1, subscribers.size());

        //Check that the record was created via the flow.
        String externalId = dateStringFromCommunity+'-'+testUser.Id+'-'+action;
        Listing_Analytics__c result = getRecord(externalId);
        system.assert(result!=null);
        system.assertEquals(testUser.Id, result.User__c);
        system.assertEquals(action, result.Action__c);
        system.assertEquals(action2, result.Action2__c);
        system.assertEquals(testListing.Id, result.Listing__c);
        system.assertEquals(documentId, result.Document_ID__c);
        system.assertEquals(pageSource, result.Page_Source__c);
    }

    static testMethod void validPlatforEventInputCreatingRecord() {
        
        User testUser = [select Id from User where IsActive=true and UserType='CspLitePortal' limit 1];
        String dateStringFromCommunity = '2020-01-19 18:18:19';
        String action = 'Page View';
        String action2 = null;
        Listing_Profile__c testProfile = createProfile('Copado, Inc.');
        Listing__c testListing = createListing('Copado Templates', testProfile.Id);
        String documentId = 'Some doc id';
        String pageSource = 'Search Results';

        Listing_Analytics_Event__e evt = new Listing_Analytics_Event__e();
        evt.DateTime__c = DateTime.valueOf(dateStringFromCommunity);
        evt.User_ID__c = testUser.Id;
        evt.Action__c = action;
        evt.Action2__c = action2;
        evt.Listing_ID__c = testListing.Id;
        evt.Document_ID__c = documentId;
        evt.Page_Source__c = pageSource;
        List<Listing_Analytics_Event__e> evts = new List<Listing_Analytics_Event__e>();
        evts.add(evt);

        Test.startTest();
        ListingAnalyticsService.insertAnalyticsRecord(evts);
        Test.stopTest();

        String externalId = dateStringFromCommunity+'-'+testUser.Id+'-'+action;
        Listing_Analytics__c result = getRecord(externalId);
        system.assert(result!=null);
        system.assertEquals(testUser.Id, result.User__c);
        system.assertEquals(action, result.Action__c);
        system.assertEquals(action2, result.Action2__c);
        system.assertEquals(testListing.Id, result.Listing__c);
        system.assertEquals(documentId, result.Document_ID__c);
        system.assertEquals(pageSource, result.Page_Source__c);
    }

    //Private methos for this test class.
    private static EventBusSubscriber[] getSubscribers(String topicName) {
        return [select Name, Type, Position, Retries, LastError from EventBusSubscriber where Topic=:topicName];
    }
    private static Listing_Analytics__c getRecord(String externalId) {
        return [select Id, Action__c, Action2__c, DateTime__c, Document_ID__c, External_ID__c, Listing__c, Page_Source__c, User__c 
            from Listing_Analytics__c where External_ID__c=:externalId limit 1];
    }
    private static Listing_Profile__c createProfile(String name) {
        Listing_Profile__c lp = new Listing_Profile__c(Name=name);
        insert lp;
        return lp;
    }
    private static Listing__c createListing(String name, Id profileId) {
        Listing__c l = new Listing__c(Name=name, Listing_Profile__c=profileId);
        insert l;
        return l;
    }
}