objects/ltcomm__Learning_Order__c.object
<CustomObject>
    <fields>
        <fullName>ltcomm__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ltcomm__Purchased_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchased By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ltcomm__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Held for Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Order</label>
    <nameField>
        <displayFormat>LRDR-{000000}</displayFormat>
        <label>Learning Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ltcomm__Learning_Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>ltcomm__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ltcomm__Learning_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Learning Order</label>
        <referenceTo>ltcomm__Learning_Order__c</referenceTo>
        <relationshipLabel>Learning Order Item</relationshipLabel>
        <relationshipName>Learning_Order_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ltcomm__ObjectId__c</fullName>
        <label>Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ltcomm__Purchased_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchased By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ltcomm__Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Learning Order Item</label>
    <nameField>
        <displayFormat>LRDRI-{000000}</displayFormat>
        <label>Learning Order Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Order Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ltcomm__Learning_Order_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ltcomm__Learning_Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Learning Order</label>
        <referenceTo>ltcomm__Learning_Order__c</referenceTo>
        <relationshipLabel>Learning Order Transactions</relationshipLabel>
        <relationshipName>Learning_Order_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ltcomm__Transaction_Id__c</fullName>
        <label>Transaction Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ltcomm__Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Learning Order Transaction</label>
    <nameField>
        <displayFormat>LOT-{000000}</displayFormat>
        <label>Learning Order Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Order Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ltcomm__Payment_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is the data for eCommerce setup and payment systems.</description>
    <fields>
        <fullName>ltcomm__Stripe_Secret_Key_Production__c</fullName>
        <label>Stripe Secret Key Production</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ltcomm__Stripe_Secret_Key_Sandbox__c</fullName>
        <label>Stripe Secret Key Sandbox</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ltcomm__Use_Sandbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Sandbox</label>
        <type>Checkbox</type>
    </fields>
    <label>eCommerce Settings</label>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AcademyStripePaymentUpdateTest.cls
@IsTest
private with sharing class AcademyStripePaymentUpdateTest {

    @TestSetup static void setupData() {
        redwing__Training_Plan__c learningPlan = new redwing__Training_Plan__c(Name='Test Plan');
        insert learningPlan;

        ltcomm__Payment_Settings__c paymentSetting  = new ltcomm__Payment_Settings__c();
        paymentSetting.Name = 'PaymentSettings';
        paymentSetting.ltcomm__Use_Sandbox__c = true;
        paymentSetting.ltcomm__Stripe_Secret_Key_Sandbox__c = 'sandbox-secret-key-stripe';
        paymentSetting.ltcomm__Stripe_Secret_Key_Production__c = 'production-secret-key-stripe';
        insert paymentSetting;

    }

    @IsTest static void testStripeUpdateSuccess(){

        redwing__Training_Plan__c learningPlan = [SELECT Id, Name FROM redwing__Training_Plan__c WHERE Name = 'Test Plan'];

        ltcomm__Learning_Order__c newOrder = new ltcomm__Learning_Order__c();
        newOrder.ltcomm__Amount__c = 200;
        newOrder.ltcomm__Purchased_By__c = UserInfo.getUserId();
        newOrder.ltcomm__Status__c = 'Paid';
        insert newOrder;

        ltcomm__Learning_Order_Item__c orderItem = new ltcomm__Learning_Order_Item__c();
        orderItem.ltcomm__Learning_Order__c = newOrder.Id;
        orderItem.ltcomm__ObjectId__c = learningPlan.Id;
        orderItem.ltcomm__Status__c = true;
        orderItem.ltcomm__Purchased_By__c = UserInfo.getUserId();
        insert orderItem;

        ltcomm__Learning_Order_Transaction__c orderTransaction = new ltcomm__Learning_Order_Transaction__c();
        orderTransaction.ltcomm__Learning_Order__c = newOrder.Id;
        orderTransaction.ltcomm__Transaction_Id__c = 'transaction-id';
        orderTransaction.ltcomm__Transaction_Status__c = 'Paid';
        insert orderTransaction;

        AcademyStripePaymentUpdate.updatePaymentDetails(new List<String>{newOrder.Id});
        AcademyStripePaymentUpdate.sendErrorEmailToAcademy('test meessage', orderTransaction.Id);
    }

    @IsTest static void testStripeUpdateError(){

        ltcomm__Learning_Order__c newOrder = new ltcomm__Learning_Order__c();
        newOrder.ltcomm__Amount__c = 200;
        newOrder.ltcomm__Purchased_By__c = UserInfo.getUserId();
        newOrder.ltcomm__Status__c = 'Paid';
        insert newOrder;

        ltcomm__Learning_Order_Transaction__c orderTransaction = new ltcomm__Learning_Order_Transaction__c();
        orderTransaction.ltcomm__Learning_Order__c = newOrder.Id;
        orderTransaction.ltcomm__Transaction_Id__c = 'transaction-id';
        orderTransaction.ltcomm__Transaction_Status__c = 'Paid';
        insert orderTransaction;
    }
    
}