objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                </value>
                <value>
                    <fullName>CreateCoeCredential</fullName>
                </value>
                <value>
                    <fullName>CoE_Authorization</fullName>
                </value>
                <value>
                    <fullName>GitSetup</fullName>
                </value>
                <value>
                    <fullName>ProvisionLicenses</fullName>
                </value>
                <value>
                    <fullName>CreateEnvironment</fullName>
                </value>
                <value>
                    <fullName>CreateOrgCredentials</fullName>
                </value>
                <value>
                    <fullName>AuthorizeSandbox</fullName>
                </value>
                <value>
                    <fullName>AssignPermissionSet</fullName>
                </value>
                <value>
                    <fullName>ExecutePostInstallScript</fullName>
                </value>
                <value>
                    <fullName>CreateScratchOrgEnvironment</fullName>
                </value>
                <value>
                    <fullName>EnableUser</fullName>
                </value>
                <value>
                    <fullName>GitSetupFinish</fullName>
                </value>
                <value>
                    <fullName>CreateGitSnapshot</fullName>
                </value>
                <value>
                    <fullName>CreateBranches</fullName>
                </value>
                <value>
                    <fullName>CreateBoilerplate</fullName>
                </value>
                <value>
                    <fullName>AddingFinishingTouches</fullName>
                    <label>Adding Finishing Touches</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JobId__c</fullName>
        <externalId>true</externalId>
        <label>Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/cps_C1PJobMock.cls
@isTest
public class cps_C1PJobMock implements HttpCalloutMock {
  protected Integer code;
  protected String status;
  protected String body;
  protected Map<String, String> responseHeaders;
  public cps_C1PJobMock(Integer code, String status, String body, Map<String, String> responseHeaders) {
    this.code = code;
    this.status = status;
    this.body = body;
    this.responseHeaders = responseHeaders;
  }

  public HTTPResponse respond(HTTPRequest req) {
      HttpResponse mockResponse = new HttpResponse();
      //mockResponse.setBody('Playground_Job__c:{Status__c=In progress, Action__c=GitSetup, JobId__c=430c0e95-4771-4c66-9b42-d1eb277186b5, Id=a7O1l0000008XfOEAU, CurrencyIsoCode=EUR}');
      
      for (String key : this.responseHeaders.keySet()) {
        mockResponse.setHeader(key, this.responseHeaders.get(key));
      }
      mockResponse.setBody(this.body);
      mockResponse.setStatusCode(this.code);
      mockResponse.setStatus(this.status);
      return mockResponse;
  }
}