objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Playgrounds</relationshipLabel>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchPlaygroundMoveToUser.cls
global with sharing class BatchPlaygroundMoveToUser implements Database.Batchable<sObject>{

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('Select Id, Contact__c, User__c From Playground__c Where User__c = null');
    }

    global void execute(Database.BatchableContext bc, List<Playground__c> playgrounds) {
        Set<String> contactIds = new Set<String>();
        Map<String, String> contactAndUserIdMap = new Map<String, String>();
        List<Playground__c> playgroundToBeUpdated = new List<Playground__c>();

        for (Playground__c pg : playgrounds) {
            contactIds.add(pg.Contact__c);
        }

        if (!contactIds.isEmpty()) {
            for (User u : [Select Id, ContactId From User Where ContactId IN :contactIds]) {
                contactAndUserIdMap.put(u.ContactId, u.Id);
            }

            for (Playground__c pg : playgrounds) {
                if (contactAndUserIdMap.containsKey(pg.Contact__c)) {
                    pg.User__c = contactAndUserIdMap.get(pg.Contact__c);
                    playgroundToBeUpdated.add(pg);
                }
            }

            if (!playgroundToBeUpdated.isEmpty()) {
                update playgroundToBeUpdated;
            }

        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}