objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Playground_Configuration__c</fullName>
        <inlineHelpText>Full configuration will create all records for your playground including the complete pipeline. Choose light configuration only if you have been specifically instructed to do so</inlineHelpText>
        <label>Playground Configuration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Configuration</fullName>
                    <default>true</default>
                    <label>Full Configuration</label>
                </value>
                <value>
                    <fullName>Light Configuration</fullName>
                </value>
                <value>
                    <fullName>Full Configuration - Scratch Orgs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cps_DeleteOlderPlaygroundBatch.cls
global inherited sharing class cps_DeleteOlderPlaygroundBatch implements Database.Batchable<sObject>, Schedulable {

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'Select Id, CreatedDate From Playground__c Where Playground_Configuration__c = \'Full Configuration - Scratch Orgs\' AND CreatedDate < LAST_N_DAYS:30 order by CreatedDate DESC';
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Playground__c> playgrounds){
        if (!playgrounds.isEmpty()) {
            delete playgrounds;
        }
    }
   
    global void finish(Database.BatchableContext BC){
   
    }

    global void execute(SchedulableContext SC) {
        cps_DeleteOlderPlaygroundBatch cpsDeletePG = new cps_DeleteOlderPlaygroundBatch();
        Database.executebatch(cpsDeletePG);
    }
}