objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Playground_Configuration__c</fullName>
        <inlineHelpText>Full configuration will create all records for your playground including the complete pipeline. Choose light configuration only if you have been specifically instructed to do so</inlineHelpText>
        <label>Playground Configuration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Configuration</fullName>
                    <default>true</default>
                    <label>Full Configuration</label>
                </value>
                <value>
                    <fullName>Light Configuration</fullName>
                </value>
                <value>
                    <fullName>Full Configuration - Scratch Orgs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreateTrialOrg</fullName>
                </value>
                <value>
                    <fullName>CreateCoeCredential</fullName>
                </value>
                <value>
                    <fullName>CoE_Authorization</fullName>
                </value>
                <value>
                    <fullName>GitSetup</fullName>
                </value>
                <value>
                    <fullName>ProvisionLicenses</fullName>
                </value>
                <value>
                    <fullName>CreateEnvironment</fullName>
                </value>
                <value>
                    <fullName>CreateOrgCredentials</fullName>
                </value>
                <value>
                    <fullName>AuthorizeSandbox</fullName>
                </value>
                <value>
                    <fullName>AssignPermissionSet</fullName>
                </value>
                <value>
                    <fullName>ExecutePostInstallScript</fullName>
                </value>
                <value>
                    <fullName>CreateScratchOrgEnvironment</fullName>
                </value>
                <value>
                    <fullName>EnableUser</fullName>
                </value>
                <value>
                    <fullName>GitSetupFinish</fullName>
                </value>
                <value>
                    <fullName>CreateGitSnapshot</fullName>
                </value>
                <value>
                    <fullName>CreateBranches</fullName>
                </value>
                <value>
                    <fullName>CreateBoilerplate</fullName>
                </value>
                <value>
                    <fullName>AddingFinishingTouches</fullName>
                    <label>Adding Finishing Touches</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <description>Edition used to create a new signup request. It takes preference over Template, so template will be taken into account only if Edition is empty</description>
        <inlineHelpText>Edition used to create a new signup request. It takes preference over Template, so template will be taken into account only if Edition is empty</inlineHelpText>
        <label>Edition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TSO_Template_Id__c</fullName>
        <inlineHelpText>The 15–character ID of the Trialforce template that is the basis for the trial sign-up. Salesforce must approve the template.</inlineHelpText>
        <label>TSO Template Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Id_without_Copado_Deployer__c</fullName>
        <description>The new Template Id without Copado Deployer package</description>
        <label>Template Id without Copado Deployer</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Playground Setting</label>
    <pluralLabel>Playground Settings</pluralLabel>
</CustomObject>

objects/Signup_Request__c.object
<CustomObject>
    <description>This object captures the Signup Requests generated from the community and creates Trialforce orgs</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Org_Id__c</fullName>
        <inlineHelpText>The 15–character organization ID of the trial organization created. The system provides this read-only field once the sign-up request has been processed.</inlineHelpText>
        <label>Created Org Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <inlineHelpText>The Salesforce template that is used to create the trial organization.</inlineHelpText>
        <label>Edition</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Group</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Professional TSO</fullName>
                </value>
                <value>
                    <fullName>Partner Professional</fullName>
                </value>
                <value>
                    <fullName>Service Professional</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Enterprise TSO</fullName>
                </value>
                <value>
                    <fullName>Partner Enterprise</fullName>
                </value>
                <value>
                    <fullName>Sales Enterprise</fullName>
                </value>
                <value>
                    <fullName>Developer</fullName>
                </value>
                <value>
                    <fullName>Partner Developer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Playground_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is populated by the Playground Wizard so that ProcessBuilder can update the job and UI changes can be triggered via Playground Job Events.</inlineHelpText>
        <label>Playground Job</label>
        <referenceTo>Playground_Job__c</referenceTo>
        <relationshipLabel>Signup Request</relationshipLabel>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TSO_Template_ID__c</fullName>
        <formula>TSO_Template__r.Trialforce_Template_Id__c</formula>
        <label>TSO Template ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Signup_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Signup Request</label>
    <nameField>
        <displayFormat>SR{0000000000}</displayFormat>
        <label>Signup Request Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signup Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/newTrialSignupController.cls
public without sharing class newTrialSignupController {

    @auraEnabled
    public static User getUserInfo() {
        User currentUser = [select Id, FirstName, LastName, Email, CompanyName, ContactId from User where Id=:UserInfo.getUserId() limit 1];
        return currentUser;
    }

    // Get all the playground jobs for a given playground
    @auraEnabled
    public static List<Playground_Job__c> getPlaygroundJobs(String playgroundId){
        return cps_PlaygroundWizardController.GetPlaygroundJobs(playgroundId);
    }

    @auraEnabled
    public static Signup_Request__c getSignupRequest(String recordId) {
        Signup_Request__c sr = [select Id, Status__c, Error_Code__c, Created_Org_Id__c from Signup_Request__c where Id=:recordId limit 1];
        return sr;
    }

    @auraEnabled
    public static Signup_Request__c createSignupRequest(String username, String domain, String country, String playgroundId) {
        try {
            Playground_Setting__mdt playgroundSetting = [select Id, TSO_Template_Id__c, Template_Id_without_Copado_Deployer__c, Edition__c
                                                    from Playground_Setting__mdt
                                                    where QualifiedApiName =: cps_Helper.SETTINGS_NAME limit 1];
            User currentUser = [select Id, FirstName, LastName, Email, CompanyName, ContactId, Country from User where Id=:UserInfo.getUserId() limit 1];

            Playground_Job__c job = [select Id, Playground__c, Playground__r.Playground_Configuration__c from Playground_Job__c where Playground__c=:playgroundId and Action__c='CreateTrialOrg' limit 1];

            Signup_Request__c sr = new Signup_Request__c();
            sr.First_Name__c = currentUser.FirstName;
            sr.Last_Name__c = (currentUser.LastName==null)?'Not Provided':currentUser.LastName;
            sr.Email__c = currentUser.Email;
            sr.Company__c = (currentUser.CompanyName==null)?'Not Provided':currentUser.CompanyName;
            sr.User__c = currentUser.Id;
            sr.Country__c = (country==null)?'US':country;
            sr.Domain__c = (domain==null)?'null':domain;
            sr.Username__c = username;
            sr.Signup_Source__c = 'Playground Community';
            sr.Playground_Job__c = job.Id;
            sr.Preferred_Language__c = 'en_US';
            if (playgroundSetting.Edition__c == null || playgroundSetting.Edition__c == '') {
                if (job.Playground__r.Playground_Configuration__c == 'Full Configuration - Scratch Orgs') {
                	sr.Template__c = playgroundSetting.Template_Id_without_Copado_Deployer__c;
            	} else {
                	sr.Template__c = playgroundSetting.TSO_Template_Id__c;
            	}            	
            } else {
                 sr.Edition__c = playgroundSetting.Edition__c;               
            }
            insert sr;

            Playground__c playground = new Playground__c(Id=job.Playground__c, Custom_Signup_Request__c=sr.Id);
            update playground;

            currentUser.Country = country;
            update currentUser;
            return sr;
        } catch (Exception ex) {
            system.debug(ex.getMessage());
            String beautifulError = beautifyErrorMessage(ex.getMessage());
            AuraHandledException e = new AuraHandledException(beautifulError);
            e.setMessage(beautifulError);
            system.debug(e);
            throw e;
        }
    }

    public static String beautifyErrorMessage(String err) {
        if (err==null) return '';
        if (err.contains('LIMIT_EXCEEDED')) {
            return 'The Salesforce daily limit of SignupRequests has been reached.';
        }
        if (err.contains('The username provided is not in a valid email address format.')){
            return 'The username provided is not in a valid email address format.  Please see the example provided in the help text.';
        }
        if (err.contains('INVALID_SUBDOMAIN')) {
            return 'Invalid Subdomain. Select a name that does not contain double hyphens, spaces, end in a hyphen, include restricted words (e.g. sfdc) or exceed 22 characters.';
        }
        return err;
    }
}