objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Playground_Configuration__c</fullName>
        <inlineHelpText>Full configuration will create all records for your playground including the complete pipeline. Choose light configuration only if you have been specifically instructed to do so</inlineHelpText>
        <label>Playground Configuration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full Configuration</fullName>
                    <default>true</default>
                    <label>Full Configuration</label>
                </value>
                <value>
                    <fullName>Light Configuration</fullName>
                </value>
                <value>
                    <fullName>Full Configuration - Scratch Orgs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Playground_Enviroment__c.object
<CustomObject>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Environments</relationshipLabel>
        <relationshipName>Playground_Environments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CoE_Org</fullName>
                    <label>CoE Org</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch_Org</fullName>
                    <label>Scratch Org</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Environment</label>
    <nameField>
        <label>Playground Enviroment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Environments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Job__c.object
<CustomObject>
    <description>Jobs to complete the creation of a new Playground</description>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>This field determines the order the jobs are displayed.</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Playground__c</fullName>
        <label>Playground</label>
        <referenceTo>Playground__c</referenceTo>
        <relationshipLabel>Playground Jobs</relationshipLabel>
        <relationshipName>Playground_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Sandbox Creation</fullName>
                </value>
                <value>
                    <fullName>Record Creation</fullName>
                </value>
                <value>
                    <fullName>Git</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Job</label>
    <nameField>
        <label>Playground Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playground Jobs</pluralLabel>
    <recordTypes>
        <fullName>C1P_Job</fullName>
        <active>true</active>
        <label>C1P Job</label>
    </recordTypes>
    <recordTypes>
        <fullName>Environment_Creation</fullName>
        <active>true</active>
        <label>Environment Creation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Job</fullName>
        <active>true</active>
        <label>Job</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Playground_Sandbox__mdt.object
<CustomObject>
    <description>A list of records containing the name of each Sandbox to be created and wether if it is active or not.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Wether the record is active or not.</description>
        <inlineHelpText>Wether the record is active or not.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>This field determines the order the sandboxes are displayed.</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Sandbox.</description>
        <inlineHelpText>Type of Sandbox.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEVELOPER</fullName>
                    <default>true</default>
                    <label>DEVELOPER</label>
                </value>
                <value>
                    <fullName>DEVELOPER_PRO</fullName>
                </value>
                <value>
                    <fullName>PARTIAL</fullName>
                </value>
                <value>
                    <fullName>FULL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Playground Sandbox</label>
    <pluralLabel>Playground Sandboxes</pluralLabel>
</CustomObject>

objects/Playground_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Full_Configuration_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Full Configuration Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Full_Configuration_Scratch_Org_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Full Configuration - Scratch Org Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Light_Configuration_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Light Configuration Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Playground Setting</label>
    <pluralLabel>Playground Settings</pluralLabel>
</CustomObject>

classes/cps_PlaygroundWizardStartController.cls
public without sharing class cps_PlaygroundWizardStartController {
    private static final String FULL_CONFIGURATION = 'Full Configuration';
    private static final String FULL_CONFIGURATION_ScratchOrgs = 'Full Configuration - Scratch Orgs';
    // Create a new playground and return its info to the frontend
    @AuraEnabled
    public static Playground__c createPlayground(String playgroundName, String playgroundConfiguration) {

        // Create playground
        Playground__c playground = new Playground__c ( Name = playgroundName, Playground_Configuration__c = playgroundConfiguration, User__c = UserInfo.getUserId());
        insert playground;

        // Create playground environment
        List<Playground_Enviroment__c> playgroundEnvs = new List<Playground_Enviroment__c>();
        playgroundEnvs.add(new Playground_Enviroment__c(Name = 'Copado', Playground__c = playground.Id, Type__c = 'CoE_Org'));

        Id defaultRecType = Schema.SObjectType.Playground_Job__c.getRecordTypeInfosByDeveloperName().get('Job').getRecordTypeId();
        Id c1pRecType = Schema.SObjectType.Playground_Job__c.getRecordTypeInfosByDeveloperName().get('C1P_Job').getRecordTypeId();
        Id sandboxCreationRecType = Schema.SObjectType.Playground_Job__c.getRecordTypeInfosByDeveloperName().get('Environment_Creation').getRecordTypeId();

        // Create all the playground jobs
        List<Playground_Job__c> jobsToInsert = new List<Playground_Job__c>();
        jobsToInsert.add(cps_Helper.createPlaygroundJob(1, 'Create Copado Trial Org', 'CreateTrialOrg', playground.Id, defaultRecType, null, null));
        jobsToInsert.add(cps_Helper.createPlaygroundJob(10, 'Create Copado Credential', 'CreateCoeCredential', playground.Id, c1pRecType, null, null));
        jobsToInsert.add(cps_Helper.createPlaygroundJob(20, 'Log in with Salesforce', 'CoE_Authorization', playground.Id, defaultRecType, null, null));
        jobsToInsert.add(cps_Helper.createPlaygroundJob(30, 'Github Setup', 'GitSetup', playground.Id, c1pRecType, null, null));
        jobsToInsert.add(cps_Helper.createPlaygroundJob(40, 'Running Installation Script', 'ExecutePostInstallScript', playground.Id, c1pRecType, null, null));
        jobsToInsert.add(cps_Helper.createPlaygroundJob(50, 'Provisioning Licenses', 'ProvisionLicenses', playground.Id, c1pRecType, null, null)); // Provision APO Licenses
        if(playgroundConfiguration != FULL_CONFIGURATION_ScratchOrgs){
            jobsToInsert.add(cps_Helper.createPlaygroundJob(60, 'Creating Sandbox Environments', 'CreateEnvironment', playground.Id, sandboxCreationRecType, null, null));
        }
        else if(playgroundConfiguration == FULL_CONFIGURATION_ScratchOrgs){
            jobsToInsert.add(cps_Helper.createPlaygroundJob(60, 'Creating Scratch Org Environments', 'CreateScratchOrgEnvironment', playground.Id, sandboxCreationRecType, null, null));
        }


        if(playgroundConfiguration == FULL_CONFIGURATION || playgroundConfiguration == FULL_CONFIGURATION_ScratchOrgs) {
            jobsToInsert.add(cps_Helper.createPlaygroundJob(61, 'Granting Permissions', 'AssignPermissionSet', playground.Id, c1pRecType, null, null));
            jobsToInsert.add(cps_Helper.createPlaygroundJob(70, 'Creating Org Credentials', 'CreateOrgCredentials', playground.Id, c1pRecType, null, null));
            jobsToInsert.add(cps_Helper.createPlaygroundJob(80, 'Connect to your Trial Org', 'AuthorizeSandbox', playground.Id, sandboxCreationRecType, null, 'Copado'));
            jobsToInsert.add(cps_Helper.createPlaygroundJob(140, 'Adding Finishing Touches', 'AddingFinishingTouches ', playground.Id, c1pRecType, null, null));
        }
        List<Playground_Sandbox__mdt> plSandboxes = [SELECT DeveloperName, Type__c, Order__c FROM Playground_Sandbox__mdt WHERE Active__c=true order by Order__c ASC LIMIT 10000];

        for(Playground_Sandbox__mdt plSandbox: plSandboxes){
            Integer authOrder = 80+Integer.valueOf(plSandbox.Order__c);
            if(playgroundConfiguration != FULL_CONFIGURATION_ScratchOrgs){
                playgroundEnvs.add(new Playground_Enviroment__c(Name = plSandbox.DeveloperName, Playground__c = playground.Id, Type__c = 'Sandbox'));
                if(playgroundConfiguration == FULL_CONFIGURATION) {
                    String authorizeName = 'Connect to your ' + plSandbox.DeveloperName + ' Sandbox';
                    jobsToInsert.add(cps_Helper.createPlaygroundJob(authOrder, authorizeName, 'AuthorizeSandbox', playground.Id, sandboxCreationRecType, null, plSandbox.DeveloperName));
                }
            }
            else if(playgroundConfiguration == FULL_CONFIGURATION_ScratchOrgs){
                playgroundEnvs.add(new Playground_Enviroment__c(Name = plSandbox.DeveloperName, Playground__c = playground.Id, Type__c = 'Scratch_Org'));
                String authorizeName = 'Connect to your ' + plSandbox.DeveloperName + ' ScratchOrg';
                jobsToInsert.add(cps_Helper.createPlaygroundJob(authOrder, authorizeName, 'AuthorizeSandbox', playground.Id, sandboxCreationRecType, null, plSandbox.DeveloperName));

            }

        }

        try{
            insert jobsToInsert;
            insert playgroundEnvs;
        }catch(Exception e){
            throw e;
        }

        return playground;
    }

    @AuraEnabled
    public static Boolean canCreate(){
        return cps_PlaygroundWizardController.GetAvailablePlaygrounds() > 0;
    }

    @AuraEnabled
    public static Playground_Setting__mdt fetchPlaygroundSetting(){
        Playground_Setting__mdt setting = [SELECT Full_Configuration_Enabled__c, Full_Configuration_Scratch_Org_Enabled__c,Light_Configuration_Enabled__c FROM Playground_Setting__mdt WHERE DeveloperName =: cps_Helper.SETTINGS_NAME LIMIT 1];
        return setting;
    }
}