objects/Playground__c.object
<CustomObject>
    <description>Stores data for customer&apos;s Playgrounds created from the Copado Customer Community</description>
    <fields>
        <fullName>Org_Id__c</fullName>
        <formula>LEFT(Org_Credential__r.copado__Environment__r.copado__Org_ID__c,15)</formula>
        <label>Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Playgrounds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Playground</label>
    <nameField>
        <label>Playground Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playgrounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactRelatedPlaygrounds.cls
public class ContactRelatedPlaygrounds {

    @AuraEnabled
    public static List<Playground__c> GetPlaygroundByContactId(String recordId){
        Id conOrUserId = Id.valueOf(recordId);
        Schema.sObjectType soType = conOrUserId.getSObjectType();
        
        if (String.valueOf(soType) == 'Contact') {
            List<User> user = [Select Id from User where ContactId = :conOrUserId limit 1];
            if (user.isEmpty()) {
                return new List<Playground__c>();
            }
            conOrUserId = user[0].Id;
        }
        RETURN [SELECT Id,Name,CreatedDate,Status__c,Org_Id__c FROM Playground__c WHERE User__c =:conOrUserId ];
    }
}