objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__DefaultQuantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Specifies the starting quantity of the product when added.</description>
        <inlineHelpText>Specify the starting quantity of the product when added.</inlineHelpText>
        <label>Default Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Trac</label>
        <referenceTo>redwing__Training_Track__c</referenceTo>
        <relationshipLabel>Achievement Assignments</relationshipLabel>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Section</label>
        <referenceTo>redwing__Training_Plan_Section__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Assignments</relationshipLabel>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Assignment</label>
    <nameField>
        <displayFormat>LPAS-{0000000}</displayFormat>
        <label>Learning Plan Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section</label>
    <nameField>
        <label>Learning Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan Assignment</label>
        <referenceTo>redwing__Training_Plan_Assignment__c</referenceTo>
        <relationshipLabel>Learning Plan Section Assignments</relationshipLabel>
        <relationshipName>Training_Plan_Section_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Section Assignment</label>
    <nameField>
        <displayFormat>LPSA-{0000000}</displayFormat>
        <label>Learning Plan Section Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Learning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only published learning objects can be added to a Learning Plan</errorMessage>
            <filterItems>
                <field>redwing__Learning__c.redwing__Is_Published_Formula__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>NOTE: Only published learning objects can be associated to a Learning Plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Learning__c</referenceTo>
        <relationshipLabel>Learning Plan Section Items</relationshipLabel>
        <relationshipName>Training_Plan_Section_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Section Item</label>
    <nameField>
        <displayFormat>LPSI-{0000000}</displayFormat>
        <label>Learning Plan Section Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Trac</label>
        <referenceTo>redwing__Training_Track__c</referenceTo>
        <relationshipLabel>Learning Trac Assignments</relationshipLabel>
        <relationshipName>Training_Track_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Trac Assignment</label>
    <nameField>
        <displayFormat>LTAS-{0000000}</displayFormat>
        <label>Learning Trac Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Trac Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Level__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Track__c</fullName>
        <label>Learning Trac</label>
        <referenceTo>redwing__Training_Track__c</referenceTo>
        <relationshipLabel>Learning Trac Levels</relationshipLabel>
        <relationshipName>Training_Track_Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Trac Level</label>
    <nameField>
        <label>Learning Trac Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Trac Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Level_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Learning Plans can be added to a Trac</errorMessage>
            <filterItems>
                <field>redwing__Training_Plan__c.redwing__Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>NOTE: Only active Learning Plans can be added to a Trac</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Trac Level Items</relationshipLabel>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Track_Level__c</fullName>
        <label>Learning Trac Level</label>
        <referenceTo>redwing__Training_Track_Level__c</referenceTo>
        <relationshipLabel>Learning Trac Level Items</relationshipLabel>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Trac Level Item</label>
    <nameField>
        <displayFormat>LTLI-{0000000}</displayFormat>
        <label>Learning Trac Level Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Trac Level Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CertificationExpirationBatchTest.cls
@isTest
public class CertificationExpirationBatchTest {
    
    @testSetup
    public static void setupMethod(){
        Account accountObj = TestDataFactory.createAccount('TestGuestUser','EUR');
        INSERT accountObj;
        
        //Create contact
        Contact conObj = TestDataFactory.createContact(AccountObj.Id,'testContact');
        conObj.FirstName = 'Test';
        conObj.Email = System.now().millisecond() + 'test@test.com';
        Database.insert(conObj);
        system.assertNotEquals(null,conObj.Id, 'Contact can not created.');
        
        Product2 product = TestDataFactory.createProduct('Test Product', 'Membership fees', null);
        Product.ProductCode = 'TEST001';
        Product.IsActive = TRUE;
        Product.SBQQ__DefaultQuantity__c = 1000;
        INSERT Product;
        
        redwing__Training_Track__c trainingTrack = TestDataFactory.createTrainingTrack('Test Developer',product.Id);
        INSERT trainingTrack;
        
        redwing__Training_Track_Level__c trainingTrackLevel = TestDataFactory.createTrainingTrackLevel('Test Developer',trainingTrack.Id);
        INSERT trainingTrackLevel;
        
        redwing__Training_Plan__c trainingPlan = TestDataFactory.createTrainingPlan('Test Developer');
        INSERT trainingPlan;
        
        redwing__Training_Track_Assignment__c trainingTrackAssignment = TestDataFactory.createTrainingTrackAssignment(userinfo.getUserId(),conObj.Id,trainingTrack.Id);
        INSERT trainingTrackAssignment;
        
        redwing__Training_Plan_Assignment__c trainingPlanAssignment = TestDataFactory.createTrainingPlanAssignment(userinfo.getUserId(),conObj.Id,trainingPlan.Id);
        INSERT trainingPlanAssignment;
        
        redwing__Training_Track_Level_Item__c trainingTrackLevelItem = TestDataFactory.createTrainingTrackLevelItem(trainingTrackLevel.Id,trainingPlan.Id);
        INSERT trainingTrackLevelItem;
        
        redwing__Learning__c learning = TestDataFactory.createLearning('Test Learning');
        INSERT learning;
        
        redwing__Training_Plan_Section__c trainingPlanSection = TestDataFactory.createTrainigPlanSection('Test',trainingPlan.Id);
        INSERT trainingPlanSection;
        
        redwing__Training_Plan_Section_Assignment__c trainingPlanSectionAssignment = TestDataFactory.createTrainingPlanSectionAssignment(userinfo.getUserId(),trainingPlanSection.Id,trainingPlanAssignment.Id);
        INSERT trainingPlanSectionAssignment;
        
        redwing__Training_Plan_Section_Item__c trainingPlanSectionItem = TestDataFactory.createTrainingPlanSectionItem(learning.Id,trainingPlanSection.Id);
        INSERT trainingPlanSectionItem;
        
        redwing__Learning_Assignment__c learningAssignment = TestDataFactory.createLearningAssignment(conObj.Id,userinfo.getUserId(),trainingPlan.Id,learning.Id,trainingPlanSection.Id,trainingPlanSectionAssignment.Id,trainingPlanSectionItem.Id);
        INSERT learningAssignment;
        
        Academy_Certification_Program__c certificationProgram = TestDataFactory.createCertificationProgram();
        INSERT certificationProgram;
        
        redwing__Achievement__c achievement = TestDataFactory.createAchievement('Certifications',certificationProgram.Id);
        INSERT achievement;
        
        redwing__Training_Plan_Achievement__c trainingPlanAchievement = TestDataFactory.createTriningPlanAchievement(achievement.Id,trainingPlan.Id);
        INSERT trainingPlanAchievement;
        
        redwing__Achievement_Assignment__c achievementAssignment = TestDataFactory.createAchievementAssignment(conObj.Id,trainingPlanAchievement.Id,achievement.Id);
        INSERT achievementAssignment;
        
        Academy_Certification_Student__c  certificationStudent = TestDataFactory.createCertificationStudent(conObj);
        INSERT certificationStudent;
        
        Academy_Certification__c  certificate = TestDataFactory.createCertification(certificationStudent.Id,certificationProgram.Id);
        INSERT certificate;
        
        Academy_Certification_Examination__c  exam = TestDataFactory.createCertificationExam(certificationProgram.Id,certificate.Id, certificationStudent.Id);
        INSERT exam;
        
        certificate.Certification_Examination__c = exam.Id;
        update certificate;
    }
    @isTest
    public static void testCertificationExpirationBatch(){
        Test.startTest();
        CertificationExpirationSchedule ctrl = new CertificationExpirationSchedule();      
        String cronExp = '0 30 0 ? * * *';
        system.schedule('testCertificationExpirationBatch'+system.now(), cronExp, ctrl);
        Test.stopTest();
    }
}