objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__DefaultQuantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Specifies the starting quantity of the product when added.</description>
        <inlineHelpText>Specify the starting quantity of the product when added.</inlineHelpText>
        <label>Default Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/redwing__Learning__c.object
<CustomObject>
    <fields>
        <fullName>ltcomm__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Learning Objects</relationshipLabel>
        <relationshipName>Learning_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>redwing__Languages</valueSetName>
        </valueSet>
    </fields>
    <label>Learning</label>
    <nameField>
        <label>Learning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Objects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>ltcomm__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Learning Plans</relationshipLabel>
        <relationshipName>Learning_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>redwing__Languages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <inlineHelpText>Only Active Learning Plans will be visible to learners, Draft plans will be visible for Learning Admins</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Assignments</relationshipLabel>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Assignment</label>
    <nameField>
        <displayFormat>LPAS-{0000000}</displayFormat>
        <label>Learning Plan Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Sections</relationshipLabel>
        <relationshipName>Training_Plan_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Section</label>
    <nameField>
        <label>Learning Plan Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plan Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Section_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Plan Section Assignment</label>
    <nameField>
        <displayFormat>LPSA-{0000000}</displayFormat>
        <label>Learning Plan Section Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Section Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Track__c.object
<CustomObject>
    <fields>
        <fullName>ltcomm__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Learning Tracs</relationshipLabel>
        <relationshipName>Learning_Tracs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Enable_all_external_accounts__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Enabling this checkbox will expose this Learning Trac to all external (Community/Portal) users</inlineHelpText>
        <label>Enable for all external users (Obsolete)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>redwing__Enable_all_internal_users__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Enabling this checkbox will expose this Learning Trac to all internal users</inlineHelpText>
        <label>Enable for all internal users (Obsolete)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>redwing__Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>redwing__Languages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <inlineHelpText>Learning Tracs are not available to end users until they are &quot;Active&quot;</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Learning Trac</label>
    <nameField>
        <label>Learning Trac Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Tracs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Training_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Trac</label>
        <referenceTo>redwing__Training_Track__c</referenceTo>
        <relationshipLabel>Learning Trac Assignments</relationshipLabel>
        <relationshipName>Training_Track_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Trac Assignment</label>
    <nameField>
        <displayFormat>LTAS-{0000000}</displayFormat>
        <label>Learning Trac Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Trac Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Level__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Track__c</fullName>
        <label>Learning Trac</label>
        <referenceTo>redwing__Training_Track__c</referenceTo>
        <relationshipLabel>Learning Trac Levels</relationshipLabel>
        <relationshipName>Training_Track_Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Trac Level</label>
    <nameField>
        <label>Learning Trac Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Trac Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Level_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Track_Level__c</fullName>
        <label>Learning Trac Level</label>
        <referenceTo>redwing__Training_Track_Level__c</referenceTo>
        <relationshipLabel>Learning Trac Level Items</relationshipLabel>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Trac Level Item</label>
    <nameField>
        <displayFormat>LTLI-{0000000}</displayFormat>
        <label>Learning Trac Level Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Trac Level Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/redwing__Languages.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>da</fullName>
    </customValue>
    <customValue>
        <fullName>de</fullName>
    </customValue>
    <customValue>
        <fullName>en_US</fullName>
    </customValue>
    <customValue>
        <fullName>es</fullName>
    </customValue>
    <customValue>
        <fullName>es_MX</fullName>
    </customValue>
    <customValue>
        <fullName>fi</fullName>
    </customValue>
    <customValue>
        <fullName>fr</fullName>
    </customValue>
    <customValue>
        <fullName>it</fullName>
    </customValue>
    <customValue>
        <fullName>ja</fullName>
    </customValue>
    <customValue>
        <fullName>ko</fullName>
    </customValue>
    <customValue>
        <fullName>nl_NL</fullName>
    </customValue>
    <customValue>
        <fullName>no</fullName>
    </customValue>
    <customValue>
        <fullName>pt_BR</fullName>
    </customValue>
    <customValue>
        <fullName>ru</fullName>
    </customValue>
    <customValue>
        <fullName>sv</fullName>
    </customValue>
    <customValue>
        <fullName>th</fullName>
    </customValue>
    <customValue>
        <fullName>zh_CN</fullName>
    </customValue>
    <customValue>
        <fullName>zh_TW</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ReputationPointControllerTest.cls
@isTest
public class ReputationPointControllerTest {

     @testSetup
    public static void setupMethod(){
        Contact conObj = new Contact();
        conObj.FirstName ='test';
        conObj.LastName ='contact';
        INSERT conObj;
        
        Product2 Product = new Product2();
        Product.Name = 'Test Product';
        Product.ProductCode = 'TEST001';
        Product.IsActive = TRUE;
        Product.SBQQ__DefaultQuantity__c = 1000;
        INSERT Product;
        
        redwing__Training_Track__c Training_Track = new redwing__Training_Track__c();
        Training_Track.Name = 'Test Developer';
        Training_Track.redwing__Status__c ='Active';
        Training_Track.ltcomm__Product__c = Product.Id;
        Training_Track.redwing__Enable_all_internal_users__c = TRUE;
        Training_Track.redwing__Enable_all_external_accounts__c = TRUE;
        Training_Track.redwing__Language__c ='en_US';
        INSERT Training_Track;
        
        redwing__Training_Track_Level__c Training_Track_Level = NEW redwing__Training_Track_Level__c();
        Training_Track_Level.Name = 'Test Developer';
        Training_Track_Level.redwing__Training_Track__c = Training_Track.Id;
        INSERT Training_Track_Level;
        
        redwing__Training_Plan__c Training_Plan = new redwing__Training_Plan__c();
        Training_Plan.Name = 'Test TrainingPlan';
        Training_Plan.redwing__Status__c = 'Active';
        Training_Plan.Is_Certification_Plan__c = TRUE;
        INSERT Training_Plan;
        
        redwing__Training_Track_Assignment__c Training_Track_Assignment = NEW redwing__Training_Track_Assignment__c();
        Training_Track_Assignment.redwing__User__c = UserInfo.getUserId();
        Training_Track_Assignment.redwing__Contact__c = conObj.Id;
        Training_Track_Assignment.redwing__Status__c = 'In Progress';
        Training_Track_Assignment.redwing__Training_Track__c = Training_Track.Id;
        INSERT Training_Track_Assignment;
        
        
        redwing__Training_Plan_Assignment__c Training_Plan_Assignment = NEW redwing__Training_Plan_Assignment__c();
        Training_Plan_Assignment.redwing__User__c = UserInfo.getUserId();
        Training_Plan_Assignment.redwing__Contact__c = conObj.Id;
        Training_Plan_Assignment.redwing__Training_Plan__c = Training_Plan.Id;
        Training_Plan_Assignment.redwing__Status__c = 'In Progress';
        Training_Plan_Assignment.redwing__Progress_Percentage__c =  0.00;
        INSERT Training_Plan_Assignment;
        
        redwing__Training_Track_Level_Item__c Training_Track_Level_Item = NEW redwing__Training_Track_Level_Item__c();
        Training_Track_Level_Item.redwing__Training_Track_Level__c = Training_Track_Level.Id;
        Training_Track_Level_Item.redwing__Training_Plan__c = Training_Plan.Id;
        INSERT Training_Track_Level_Item;
        
        redwing__Learning__c Learning = new redwing__Learning__c();
        Learning.Name	= 'Quiz';
        Learning.redwing__Published__c = true;
        INSERT Learning;
        
        redwing__Training_Plan_Section__c Training_Plan_Section = NEW redwing__Training_Plan_Section__c();
        Training_Plan_Section.Name = 'Test';
        Training_Plan_Section.redwing__Training_Plan__c =Training_Plan.Id;
        INSERT Training_Plan_Section;
        
        redwing__Training_Plan_Section_Assignment__c Training_Plan_Section_Assignment = NEW redwing__Training_Plan_Section_Assignment__c();
        Training_Plan_Section_Assignment.redwing__User__c = UserInfo.getUserId();
        Training_Plan_Section_Assignment.redwing__Status__c = 'In Progress';
        Training_Plan_Section_Assignment.redwing__Training_Plan_Section__c = Training_Plan_Section.Id;
        Training_Plan_Section_Assignment.redwing__Training_Plan_Assignment__c= Training_Plan_Assignment.Id;
        INSERT Training_Plan_Section_Assignment;
        
        redwing__Training_Plan_Section_Item__c Training_Plan_Section_Item = NEW redwing__Training_Plan_Section_Item__c();
        Training_Plan_Section_Item.redwing__Learning__c = Learning.Id;
        Training_Plan_Section_Item.redwing__Training_Plan_Section__c = Training_Plan_Section.Id;
        INSERT Training_Plan_Section_Item;
        
        redwing__Learning_Assignment__c Learning_Assignment = NEW redwing__Learning_Assignment__c();
        Learning_Assignment.redwing__Contact__c = conObj.Id;
        Learning_Assignment.redwing__User__c = UserInfo.getUserId();
        Learning_Assignment.redwing__Progress__c = '';
        Learning_Assignment.redwing__Progress_Percentage__c = 0.00;
        Learning_Assignment.redwing__Evaluation_Times_Taken__c = 0;
        Learning_Assignment.redwing__Evaluation_Result__c = 'N/A';	
        Learning_Assignment.redwing__Progress__c = 'In Progress';
        Learning_Assignment.redwing__Training_Plan__c = Training_Plan.Id;
        Learning_Assignment.redwing__Learning__c = Learning.Id;
        Learning_Assignment.redwing__Training_Plan_Section__c = Training_Plan_Section.Id;
        Learning_Assignment.redwing__Training_Plan_Section_Assignment__c =Training_Plan_Section_Assignment.Id;
        Learning_Assignment.redwing__Training_Plan_Section_Item__c = Training_Plan_Section_Item.Id;
        Learning_Assignment.redwing__Times_Launched__c =1;
        Learning_Assignment.redwing__Evaluation_Score__c =1; 
        INSERT Learning_Assignment;
        
        Learning_Assignment.redwing__Evaluation_Times_Taken__c = 2;
        Learning_Assignment.redwing__Evaluation_Result__c = 'Failed';
        UPDATE Learning_Assignment;
        
        redwing__Achievement__c Achievement = new redwing__Achievement__c();
        Achievement.Name = 'Test Achievement';
        Achievement.ReputationPoints__c = 1000;
        Insert Achievement;
        
        redwing__Training_Plan_Achievement__c Training_Plan_Achievement = new redwing__Training_Plan_Achievement__c();
        Training_Plan_Achievement.redwing__Training_Plan__c = Training_Plan.Id;
        Training_Plan_Achievement.redwing__Achievement__c = Achievement.Id;
        Insert Training_Plan_Achievement;
        
        
        
    }
    @isTest
    public static void test1(){
        redwing__Training_Plan__c Training_Plan = [SELECT Id  FROM redwing__Training_Plan__c  LIMIT 1];
        ReputationPointController.getReputationPointByLearningPlanId(Training_Plan.Id);
        
    }
}