objects/redwing__Achievement_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                </value>
                <value>
                    <fullName>Acquired</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Achievement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Achievement Assignment</label>
    <nameField>
        <displayFormat>AAS-{0000000}</displayFormat>
        <label>Achievement Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement Assignments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FeaturedUserController.cls
public class FeaturedUserController {
    
    @AuraEnabled
    Public Static List<User> GetFeaturedUsers(String UserId){
        List<User> Users = new list<User>();
        /*Set<Id> userIds = new Set<Id>();
List<AggregateResult> AggregateResultList = [SELECT count(Id),redwing__User__c FROM redwing__achievement_assignment__c WHERE redwing__User__r.IsPortalEnabled = TRUE AND redwing__Status__c = 'Acquired' GROUP BY redwing__User__c  HAVING count(Id) > 30];
if(AggregateResultList != null && AggregateResultList.size() > 0){ 
for(AggregateResult aggr:AggregateResultList){             
userIds.add((String)aggr.get('redwing__User__c'));
} 
if(userIds.size()>0){
Users = [SELECT Id,Name,Title,AboutMe,FullPhotoUrl FROM USER WHERE ID IN: userIds];
}
}*/
        if(UserId!=''){
            Users = [SELECT Id,Name,Title,AboutMe,FullPhotoUrl FROM USER WHERE ID =: UserId LIMIT 1];
        }
        RETURN Users;
    }
}