objects/redwing__Achievement__c.object
<CustomObject>
    <fields>
        <fullName>ReputationPoints__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reputation Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Achievement__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Achievement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Achievement</label>
        <referenceTo>redwing__Achievement__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Achievements</relationshipLabel>
        <relationshipName>Training_Plan_Achievements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Plan Achievement</label>
    <nameField>
        <displayFormat>LPA-{0000000}</displayFormat>
        <label>Learning Plan Achievement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReputationPointController.cls
public without sharing class ReputationPointController {

    @AuraEnabled
    Public static Decimal getReputationPointByLearningPlanId(String LearningPlanId){
        Id recordId = LearningPlanId;
        List<redwing__Training_Plan_Achievement__c> Training_Plan_AchievementList = new List<redwing__Training_Plan_Achievement__c>();
        if(String.valueOf(recordId.getSobjectType())== 'redwing__Training_Plan__c'){
          Training_Plan_AchievementList = [SELECT Id,redwing__Achievement__r.ReputationPoints__c FROM redwing__Training_Plan_Achievement__c WHERE redwing__Training_Plan__c = :LearningPlanId AND redwing__Achievement__c !=NUll  LIMIT 1];
            if(Training_Plan_AchievementList.size()>0){
                RETURN Training_Plan_AchievementList[0].redwing__Achievement__r.ReputationPoints__c;
            }
        }
        RETURN Null;
        
    }
        
}