objects/redwing__Learning_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Is_Certification_Plan__c</fullName>
        <formula>redwing__Training_Plan__r.Is_Certification_Plan__c</formula>
        <label>Is Certification Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>redwing__Evaluation_Result__c</fullName>
        <label>Evaluation Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>redwing__Evaluation_Score__c</fullName>
        <label>Evaluation Score</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>redwing__Evaluation_Times_Taken__c</fullName>
        <label>Evaluation Times Taken</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Assignments</relationshipLabel>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Learning_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Assignment</label>
    <nameField>
        <displayFormat>LEA-{0000000}</displayFormat>
        <label>Learning Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Is_Certification_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a certification plan or not?</description>
        <inlineHelpText>Is it a certification plan or not?</inlineHelpText>
        <label>Is Certification Plan</label>
        <type>Checkbox</type>
    </fields>
    <label>Learning Plan</label>
    <nameField>
        <label>Learning Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Plan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Plan Assignments</relationshipLabel>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Training_Plan_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Plan Assignment</label>
    <nameField>
        <displayFormat>LPAS-{0000000}</displayFormat>
        <label>Learning Plan Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Plan Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Track__c.object
<CustomObject>
    <label>Learning Trac</label>
    <nameField>
        <label>Learning Trac Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Tracs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Track__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Trac</label>
        <referenceTo>redwing__Training_Track__c</referenceTo>
        <relationshipLabel>Learning Trac Assignments</relationshipLabel>
        <relationshipName>Training_Track_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Training_Track_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Learning Trac Assignment</label>
    <nameField>
        <displayFormat>LTAS-{0000000}</displayFormat>
        <label>Learning Trac Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Trac Assignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Level__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Track__c</fullName>
        <label>Learning Trac</label>
        <referenceTo>redwing__Training_Track__c</referenceTo>
        <relationshipLabel>Learning Trac Levels</relationshipLabel>
        <relationshipName>Training_Track_Levels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Trac Level</label>
    <nameField>
        <label>Learning Trac Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Trac Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/redwing__Training_Track_Level_Item__c.object
<CustomObject>
    <fields>
        <fullName>redwing__Training_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learning Plan</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Learning Plans can be added to a Trac</errorMessage>
            <filterItems>
                <field>redwing__Training_Plan__c.redwing__Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <infoMessage>NOTE: Only active Learning Plans can be added to a Trac</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>redwing__Training_Plan__c</referenceTo>
        <relationshipLabel>Learning Trac Level Items</relationshipLabel>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>redwing__Training_Track_Level__c</fullName>
        <label>Learning Trac Level</label>
        <referenceTo>redwing__Training_Track_Level__c</referenceTo>
        <relationshipLabel>Learning Trac Level Items</relationshipLabel>
        <relationshipName>Training_Track_Level_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Learning Trac Level Item</label>
    <nameField>
        <displayFormat>LTLI-{0000000}</displayFormat>
        <label>Learning Trac Level Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learning Trac Level Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GenericCertificationReset.cls
public class GenericCertificationReset   {
    
    public GenericCertificationReset(){
        String fromDate = '';
        String toDate = '';
        String Query = '';
        if(Label.GenericCertificationResetFrom!=NULL){
            fromDate = Label.GenericCertificationResetFrom+'T00:00:01Z';
            Query = 'SELECT Id , Name,redwing__User__c,redwing__Training_Plan__c FROM redwing__Learning_Assignment__c WHERE redwing__Evaluation_Result__c =\'Failed\' AND redwing__Evaluation_Times_Taken__c >1 AND redwing__Evaluation_Score__c > 0 AND Is_Certification_Plan__c = TRUE AND  LastModifiedDate >= '+fromDate+' AND';
        }
        if(Label.GenericCertificationResetTo!=NULL){
            toDate = Label.GenericCertificationResetTo+'T23:59:00Z';
            Query += ' LastModifiedDate <= '+toDate +' AND';
        }
        Query = Query.substring(0,Query.length()-3);
        system.debug(Query);
        list<redwing__Learning_Assignment__c> Learning_AssignmentList = DATABASE.query(Query);
        System.debug(Learning_AssignmentList);
        
        /*list<redwing__Learning_Assignment__c> Learning_AssignmentList = [
            SELECT 
            Id , Name,redwing__User__c,redwing__Training_Plan__c 
            FROM redwing__Learning_Assignment__c 
            WHERE 
            redwing__Evaluation_Result__c ='Failed' AND 
            redwing__Evaluation_Times_Taken__c >1 AND  
            LastModifiedDate >=: fromDate AND 
            LastModifiedDate <=: toDate
        ];*/
        if(Learning_AssignmentList.size()>0){
            system.debug('Learning_AssignmentList>>'+Learning_AssignmentList);
            list<redwing__Training_Track_Assignment__c> Training_Track_AssignmentList = New list<redwing__Training_Track_Assignment__c>();
            list<redwing__Training_Plan_Assignment__c> Training_Plan_AssignmentList = New list<redwing__Training_Plan_Assignment__c>();
            set<String> Training_PlanIds = new set<String>();
            set<String> UserIds = new set<String>();
            list<String> Training_Track_Levelids  = new list<String>(); 
            for(redwing__Learning_Assignment__c LearningAssignment : Learning_AssignmentList){
                Training_PlanIds.add(LearningAssignment.redwing__Training_Plan__c);
                UserIds.add(LearningAssignment.redwing__User__c);
            }
            if(Training_PlanIds.size()>0){
                Training_Plan_AssignmentList = [
                    SELECT Id 
                    FROM 
                    redwing__Training_Plan_Assignment__c
                    WHERE redwing__Training_Plan__c IN:Training_PlanIds AND redwing__User__c IN:UserIds
                ]; 
                system.debug('Training_Plan_AssignmentList'+Training_Plan_AssignmentList);
                
                list<redwing__Training_Track_Level_Item__c> Training_Track_Level_ItemList = [
                    SELECT 
                    Id,redwing__Training_Track_Level__c 
                    FROM 
                    redwing__Training_Track_Level_Item__c
                    WHERE redwing__Training_Plan__c IN:Training_PlanIds
                ];
                if(Training_Track_Level_ItemList.size()>0){
                    for(redwing__Training_Track_Level_Item__c Training_Track_Level_Item : Training_Track_Level_ItemList){
                        Training_Track_Levelids.add(Training_Track_Level_Item.redwing__Training_Track_Level__c);
                    }
                    system.debug('Training_Track_Levelids:::'+Training_Track_Levelids);
                    if(Training_Track_Levelids.size()>0){
                        list<redwing__Training_Track_Level__c> Training_Track_LevelList = [
                            SELECT 
                            Id, redwing__Training_Track__c
                            FROM redwing__Training_Track_Level__c
                            WHERE Id IN: Training_Track_Levelids AND 
                            redwing__Training_Track__c !=NULL
                        ];
                        system.debug('Training_Track_LevelList'+Training_Track_LevelList);
                        if(Training_Track_LevelList.size()>0){
                            list<String> Training_TrackIds = new list<String>();
                            for(redwing__Training_Track_Level__c Training_Track_Level : Training_Track_LevelList){
                                Training_TrackIds.add(Training_Track_Level.redwing__Training_Track__c);
                            }
                            if(Training_TrackIds.size()>0){
                                list<redwing__Training_Track__c> Training_TrackList = [
                                    SELECT 
                                    Id 
                                    FROM 
                                    redwing__Training_Track__c
                                    WHERE
                                    Id IN: Training_TrackIds
                                ];
                                if(Training_TrackList.size()>0){
                                    if(Training_TrackIds.size()>0){
                                        Training_Track_AssignmentList = [
                                            SELECT 
                                            Id,redwing__Training_Track__c,redwing__User__c
                                            FROM
                                            redwing__Training_Track_Assignment__c
                                            WHERE 
                                            redwing__Training_Track__c IN:Training_TrackIds AND
                                            redwing__User__c IN:UserIds
                                        ];
                                        if(Training_Track_AssignmentList.size()>0){
                                            system.debug('Delete Training_Track_AssignmentList'+Training_Track_AssignmentList);
                                            system.debug('DELETE Training_Plan_AssignmentList'+Training_Plan_AssignmentList);
                                            system.debug('Delete Learning_AssignmentList>>'+Learning_AssignmentList);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            
            
            
            if(Training_Track_AssignmentList.size()>0){
                system.debug('Delete Training_Track_AssignmentList'+Training_Track_AssignmentList);
                DELETE Training_Track_AssignmentList;
            }
            if(Training_Plan_AssignmentList.size()>0){
                system.debug('DELETE Training_Plan_AssignmentList'+Training_Plan_AssignmentList);
                 DELETE Training_Plan_AssignmentList;
            }
            system.debug('Delete Learning_AssignmentList>>'+Learning_AssignmentList);
            system.debug('Delete Learning_AssignmentList Size >>'+Learning_AssignmentList.size());
        }
        
    }
}