objects/Release_Communication__c.object
<CustomObject>
    <description>This object tracks the release communication for the Copado App</description>
    <label>Release Communication</label>
    <nameField>
        <label>Release Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Release Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>sfLma__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the Account associated with the license after the partner converts the Lead to an account as part of Lead Conversion process</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N30000001JvRMEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the Contact associated with the license after the partner converts the Lead to a contact as part of Lead Conversion process</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N30000001JvR6EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead generated from this install. This field becomes blank once the lead is converted to an account / contact in the lead conversion process</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>R00N30000001JvRAEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Status__c</fullName>
        <description>This is the Status of the Package License in the Subscriber Org</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Uninstalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestReleaseCommunicationExtension.cls
@isTest
private class TestReleaseCommunicationExtension{
    
    static testMethod void testCodeToEnd(){
        Account testAccount = TestDataFactory.createAccount('My Account', 'EUR');
        insert testAccount;
        system.debug('@@@'+testAccount);
        Contact testContact = TestDataFactory.createContact(testAccount.Id,'Benioff');
        testContact.UserId__c = 'userId123';
        Insert testContact;

        Contact testContact2 = TestDataFactory.createContact(testAccount.Id,'Benioff2');
        testContact2.UserId__c = 'userId1234';
        Insert testContact2;
            
        Contact testContact3 = TestDataFactory.createContact(testAccount.Id,'Benioff3');
        testContact3.UserId__c = 'userId12345';
        Insert testContact3;
           
       
        Lead testLead = TestDataFactory.createLead('test','Test company');
        testLead.Email='test@copa.do.test';
        insert testLead;
        
        /*sfLma__License__c license1 = new sfLma__License__c();
        license1.sfLma__Account__c = testAccount.Id;
        license1.sfLma__Contact__c = testContact.Id;
        license1.sfLma__Status__c = 'Active';
        //insert license1;
        
        sfLma__License__c license2 = new sfLma__License__c();
        license2.sfLma__Lead__c = testLead.Id;
        license2.sfLma__Status__c = 'Active';
        //insert license2;
        
        sfLma__License__c license3 = new sfLma__License__c();
        license3.sfLma__Lead__c = testLead.Id;
        license3.sfLma__Status__c = 'Active';
        //insert license3;

        sfLma__License__c license4 = new sfLma__License__c();
        license4.sfLma__Account__c = testAccount.Id;
        license4.sfLma__Contact__c = testContact2.Id;
        license4.sfLma__Status__c = 'Active';
        //insert license4;*/

        Release_Communication__c release = new Release_Communication__c();
        release.Name = 'best release ever';
        insert release;
        
        PageReference pageRef = Page.communicateRelease;
        pageRef.getParameters().put('id',release.id);
        Test.setCurrentPage(pageRef);
        Test.startTest();
        ReleaseCommunicationExtension ext = new ReleaseCommunicationExtension(new ApexPages.StandardController(release));
        system.debug('### all email templates: '+ext.emailTemplates);
        system.debug('### 1st Email template: '+ext.emailTemplates[0]);
        ext.selectedEmailTemplateId = ext.emailTemplates[1].getValue();
        system.debug('### selectedEmailTemplateId: '+ext.selectedEmailTemplateId);
        ext.sendEmails();
        pageRef = ext.cancel();
        Test.stopTest();
        String expected = release.Id;
        system.assertEquals('/'+expected.subString(0,15), pageRef.getUrl());
        
    }       
}