objects/Release_Communication__c.object
<CustomObject>
    <description>This object tracks the release communication for the Copado App</description>
    <label>Release Communication</label>
    <nameField>
        <label>Release Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Release Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>sfLma__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the Account associated with the license after the partner converts the Lead to an account as part of Lead Conversion process</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N30000001JvRMEA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field displays the Contact associated with the license after the partner converts the Lead to a contact as part of Lead Conversion process</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N30000001JvR6EAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Install_Date__c</fullName>
        <description>The Date this Package Version was initially installed by the developer. (Does not get updated as part of upgrades.)</description>
        <label>Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>sfLma__License_Type__c</fullName>
        <description>This field indicates the type of license record. For example, if the license record is &quot;Read-Only&quot;, this license record cannot be modified.</description>
        <label>License Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Package_License_ID__c</fullName>
        <description>ID of package license for uninstall tracking</description>
        <label>Package License ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Seats__c</fullName>
        <description>number of seats covered by license</description>
        <label>Seats</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sfLma__Status__c</fullName>
        <description>This is the Status of the Package License in the Subscriber Org</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Uninstalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Used_Licenses__c</fullName>
        <label>Used Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestReleaseCommunicationBatch.cls
@isTest
public class TestReleaseCommunicationBatch {
    static testMethod void fullBatchTest(){
        List<Account> accounts = new List<Account>();
        accounts.add(new Account(Name='My test Account1', OrgId__c='00D170000009ePwEAI'));
        accounts.add(new Account(Name='My test Account2', OrgId__c='00D90000000qEvHEAU'));
        insert accounts;

        List<Contact> contacts = new List<Contact>();
        contacts.add(new Contact(FirstName='Philipp1', LastName='Rackwitz1', Email='pr1@copa.do', AccountId=accounts[0].id, UserId__c='MyTestUserId1234', Receive_Release_Communication__c=false));
        contacts.add(new Contact(FirstName='Philipp2', LastName='Rackwitz2', Email='pr2@copa.do', AccountId=accounts[1].id, UserId__c='MyTestUserId1235', Receive_Release_Communication__c=false));
        contacts.add(new Contact(FirstName='Philipp3', LastName='Rackwitz3', Email='pr3@copa.do', AccountId=accounts[0].id, UserId__c='MyTestUserId1236', Receive_Release_Communication__c=true));
        insert contacts;
        
        List<sfLma__License__c> licenses = new List<sfLma__License__c>();
        system.debug('Contact 0'+contacts[0]);
        system.debug('Contact 1'+contacts[1]);
        system.debug('Contact 2'+contacts[2]);
        
        licenses.add(new sfLma__License__c(sfLma__Account__c=accounts[0].Id, sfLma__Contact__c=contacts.get(0).Id, sfLma__Status__c='Active', sfLma__Subscriber_Org_ID__c=accounts[0].OrgId__c.subString(0,15), sfLma__Used_Licenses__c = 1, sfLma__Seats__c = -1, sfLma__Install_Date__c = system.today(), sfLma__License_Type__c = 'Editable', sfLma__Package_License_ID__c = 'some package id'));
        licenses.add(new sfLma__License__c(sfLma__Account__c=accounts[1].Id, sfLma__Contact__c=contacts.get(1).Id, sfLma__Status__c='Active', sfLma__Subscriber_Org_ID__c=accounts[1].OrgId__c.subString(0,15), sfLma__Used_Licenses__c = 1, sfLma__Seats__c = -1, sfLma__Install_Date__c = system.today(), sfLma__License_Type__c = 'Editable', sfLma__Package_License_ID__c = 'some package id'));
        insert licenses;

        Release_Communication__c r = new Release_Communication__c(name ='test rc');
        insert r;
        
        Test.startTest();
        ReleaseCommunicationBatch batchApex = new ReleaseCommunicationBatch([select Id from EmailTemplate where IsActive=true limit 1].Id, r.id);   
        Database.executeBatch(batchApex);
        Test.stopTest(); 
        system.assertEquals(3, [select count() from contact where Last_Release_Communication_Sent__c=:r.id]);
        
    }
}