objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Salesforce Org Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameterInteger__c.object
<CustomObject>
    <description>Custom object that is part of FMA for storing Feature Parameter Overrides for integers

A new record is created of this object for every feature parameter that is ADDED as part of a package install in an org. This record is automatically created upon every package install.

The Feature Parameter object serves as an index.</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Value will be set to 0 when expired</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Checked__c</fullName>
        <formula>IF(TODAY()+7 =  Expiration_Date__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Is checked true when expiration date is expire before 7 days.</inlineHelpText>
        <label>Is Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <formula>sfFma__License__r.Salesforce_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__License__c</fullName>
        <label>License</label>
        <referenceTo>sfLma__License__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Feature Parameter Integer</label>
    <nameField>
        <displayFormat>FPI-{0000}</displayFormat>
        <label>Feature Parameter Integer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameter Integers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Expiration_Date__c</fullName>
        <description>A formula field which displays the Expiration Date or “Does not expire&quot; based on the value in the Expiration field.</description>
        <formula>if(  sfLma__Expiration__c &lt;&gt; date(1970,1,1),text( sfLma__Expiration__c ),&quot;Does not expire&quot;)</formula>
        <label>Expiration Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Org_Edition__c</fullName>
        <description>The type of org for this subscriber.</description>
        <formula>sfLma__Org_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Org Edition</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleEmailAlertForSalesforceOrg.cls
global class ScheduleEmailAlertForSalesforceOrg implements Schedulable{
    global void execute(SchedulableContext SC) {
        string Url = System.URL.getSalesforceBaseUrl().toExternalForm();
        List<String> idList = new List<String>();
        List<String> mailToAddresses = new List<String>(); 
        Map<Id,Salesforce_Org__c> SFDCMap = new MAp<Id,Salesforce_Org__c>();
        Group gp = [SELECT (SELECT UserOrGroupId FROM GroupMembers) FROM Group WHERE Name = 'Deal Desk & Renewal'];
        for (GroupMember gm : gp.GroupMembers) {
            idList.add(gm.UserOrGroupId);
        }
        List<User> userList = [SELECT Email FROM User WHERE Id IN :idList];
        for(User u : userList) {
            mailToAddresses.add(u.email);
        }
        for(sfFma__FeatureParameterInteger__c  fpiObj : [SELECT Id,sfFma__FullName__c,sfFma__License__r.Name,Is_Checked__c,
                                                         sfFma__License__r.sfLma__Org_Edition__c,sfFma__License__r.Salesforce_Org__c,
                                                         Expiration_Date__c,sfFma__License__r.Salesforce_Org__r.Name,sfFma__License__r.Salesforce_Org__r.Id,sfFma__License__r.Salesforce_Org__r.Account_Status__c FROM sfFma__FeatureParameterInteger__c 
                                                         Where Is_Checked__c=True AND sfFma__License__r.Salesforce_Org__r.Org_Type__c='Production' ]){
                                                                System.debug('@@@@Send Email');
                                                                 Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                                                                 mail.setToAddresses(mailToAddresses);
                                                                 mail.setSubject('After 7 Days Salesforce Org Services Expiring');
                                                                 String body = 'Hi,'+ +'<br/>';
                                                                 body += 'Here is the Salesforce Org Details'+ +'<br/>';
                                                                 body += 'Salesforce Org Name :- '+fpiObj.sfFma__License__r.Salesforce_Org__r.Name+ '<br/>';
                                                                 body += 'Salesforce Org Status :- '+fpiObj.sfFma__License__r.Salesforce_Org__r.Account_Status__c+ '<br/>';
                                                                 body += 'License Name :- '+fpiObj.sfFma__License__r.Name+ '<br/>';
                                                                 body += 'Org Edition :- '+fpiObj.sfFma__License__r.sfLma__Org_Edition__c+ '<br/>';
                                                                 body += 'Feature Parameter Full Name :- '+fpiObj.sfFma__FullName__c+ '<br/>';
                                                                 body += 'Expiration Date :- '+fpiObj.Expiration_Date__c+ '<br/>';
                                                                 body += 'Record Link :-'+Url+'/'+fpiObj.sfFma__License__r.Salesforce_Org__r.Id+ '<br/>';
                                                                 body += 'Thanks';
                                                                 mail.setHtmlBody(body);
                                                                 Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                                                             
                                                         }
        for(sfLma__License__c liceObj :[Select id,sfLma__Expiration_Date__c,sfLma__Org_Edition__c,Salesforce_Org__r.Id,Name,Salesforce_Org__r.Account_Status__c,Salesforce_Org__r.Org_Type__c,Salesforce_Org__r.name from sfLma__License__c
                                        where sfLma__Expiration_Date__c !='Does not expire' AND Salesforce_Org__r.Org_Type__c='Production']){
                                            Date startDate = Date.today();
                                            Date endDate = date.valueOf(liceObj.sfLma__Expiration_Date__c);
                                            Integer noOfDays = startDate.daysBetween( endDate );
                                            
                                            system.debug( 'Output is ' + noOfDays );
                                            if(noOfDays == 7){
                                                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                                                mail.setToAddresses(mailToAddresses);
                                                mail.setSubject('After 7 Days Salesforce Org Services Expiring');
                                                String body = 'Hi,'+ +'<br/>';
                                                body += 'Here is the Salesforce Org Details'+ +'<br/>';
                                                body += 'Salesforce Org Name :- '+liceObj.Salesforce_Org__r.Name+ '<br/>';
                                                body += 'Salesforce Org Status :- '+liceObj.Salesforce_Org__r.Account_Status__c+ '<br/>';
                                                body += 'License Name :- '+liceObj.Name+ '<br/>';
                                                body += 'Org Edition :- '+liceObj.sfLma__Org_Edition__c+ '<br/>';
                                                body += 'Expiration Date :- '+liceObj.sfLma__Expiration_Date__c+ '<br/>';
                                                body += 'Record Link :-'+Url+'/'+liceObj.Salesforce_Org__r.Id+ '<br/>';
                                                body += 'Thanks';
                                                mail.setHtmlBody(body);
                                                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                                            }
                                        }
    }
}