objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org_Edition__c</fullName>
        <label>Org Edition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Developer Edition</fullName>
                </value>
                <value>
                    <fullName>Enterprise Edition</fullName>
                </value>
                <value>
                    <fullName>Unlimited Edition</fullName>
                </value>
                <value>
                    <fullName>Base Edition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameter__c.object
<CustomObject>
    <description>A custom object for storing feature parameters.  A new record is created of this object for every feature parameter that is ADDED as part of an uploaded package version. This record is automatically created upon the first package install of that package version.</description>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Feature Parameter</label>
    <nameField>
        <displayFormat>FP-{0000}</displayFormat>
        <label>Feature Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfFma__FeatureParameterInteger__c.object
<CustomObject>
    <description>Custom object that is part of FMA for storing Feature Parameter Overrides for integers

A new record is created of this object for every feature parameter that is ADDED as part of a package install in an org. This record is automatically created upon every package install.

The Feature Parameter object serves as an index.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <formula>sfFma__License__r.Salesforce_Org__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Salesforce Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__FeatureParameter__c</fullName>
        <description>The parent Feature Parameter object.</description>
        <label>Feature Parameter</label>
        <referenceTo>sfFma__FeatureParameter__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sfFma__FullName__c</fullName>
        <description>Name of the Feature Parameter</description>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfFma__License__c</fullName>
        <label>License</label>
        <referenceTo>sfLma__License__c</referenceTo>
        <relationshipLabel>Feature Parameter Integers</relationshipLabel>
        <relationshipName>Feature_Parameter_Integers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>sfFma__Value__c</fullName>
        <label>Feature Parameter Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature Parameter Integer</label>
    <nameField>
        <displayFormat>FPI-{0000}</displayFormat>
        <label>Feature Parameter Integer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Parameter Integers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Org_Edition__c</fullName>
        <description>The type of org for this subscriber.</description>
        <formula>sfLma__Org_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Org Edition</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestLicenseTrigger.cls
@isTest
private class TestLicenseTrigger {

    static testMethod void testFeatureParameterIntegers() {

        Salesforce_Org__c org = new Salesforce_Org__c(Name='Test Org', OrgId__c='00D20000000m7c0EAA');
        insert org;

		sfLma__License__c license = TestLicenseHelper.createTestLicense(null);

        TestLicenseHelper.createPackageAndFeatures();

        Test.startTest();

        license.Salesforce_Org__c = org.Id;
        update license;

        Map<String, Id> fpMap = new Map<String, Id>();
        for (sfFma__FeatureParameter__c p : [select Id, sfFma__FullName__c from sfFma__FeatureParameter__c]) {
            fpMap.put(p.sfFma__FullName__c, p.Id);
        }
        
        for (sfFma__FeatureParameterInteger__c fpi : [SELECT sfFma__License__c, sfFma__FeatureParameter__c, sfFma__FullName__c,sfFma__Value__c FROM sfFma__FeatureParameterInteger__c]) {
            System.assertEquals(license.Id, fpi.sfFma__License__c, 'Assertian failed for '+fpi.sfFma__FullName__c);
            System.assertEquals(fpMap.get(fpi.sfFma__FullName__c), fpi.sfFma__FeatureParameter__c, 'Assertian failed for '+fpi.sfFma__FullName__c);
            System.assertEquals(0, fpi.sfFma__Value__c, 'Assertian failed for '+fpi.sfFma__FullName__c);
        }
        
		Test.stopTest();
        
        List<Salesforce_Org__c> orgL = [SELECT Id, Org_Edition__c, Name FROM Salesforce_Org__c WHERE Id = :org.Id];
        System.assertEquals(1, orgL.size());
        System.assertEquals(license.sfLma__Org_Edition__c, orgL[0].Org_Edition__c);
        System.assertEquals(orgL[0].Name, 'Test Org');
    }
}