objects/Salesforce_Org__c.object
<CustomObject>
    <description>This object will hold the current Salesforce Org accounts.</description>
    <fields>
        <fullName>Copado_Server__c</fullName>
        <label>Copado Server</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US-East</fullName>
                </value>
                <value>
                    <fullName>EU-West</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credits__c</fullName>
        <inlineHelpText>This value comes from Heroku backend with the number available Credits to consume.</inlineHelpText>
        <label>Credits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrgId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>OrgId</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Selenium_Minutes__c</fullName>
        <inlineHelpText>This value comes from Heroku backend with the number available Selenium Minutes to consume.</inlineHelpText>
        <label>Selenium Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Salesforce Org</label>
    <nameField>
        <label>Salesforce Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Salesforce_User__c.object
<CustomObject>
    <description>This object holds the Users linked to the Salesforce Orgs.</description>
    <fields>
        <fullName>Salesforce_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Salesforce Org</label>
        <referenceTo>Salesforce_Org__c</referenceTo>
        <relationshipLabel>Salesforce Users</relationshipLabel>
        <relationshipName>Salesforce_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Salesforce User</label>
    <nameField>
        <displayFormat>SU-{0000000}</displayFormat>
        <label>Salesforce User Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/assignFreeCreditsExtension.cls
public class assignFreeCreditsExtension {
    public ApexPages.StandardController stdController {get; set;}
    public Salesforce_Org__c org {get;set;}
    public boolean renderRefreshButton {get;set;}

    public assignFreeCreditsExtension(ApexPages.StandardController stdController) {
        org = (Salesforce_Org__c)stdController.getRecord();
        org = [SELECT Id, Name, OrgId__c, Selenium_Minutes__c, Credits__c, Copado_Server__c FROM Salesforce_Org__c WHERE Id = :org.Id LIMIT 1];
        renderRefreshButton = false;
    }
    public pageReference assignCredits(){
        if(org.Credits__c == null || org.Credits__c == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'You must enter a credit amount to proceed.'));
            return null;
        }

        List<Salesforce_User__c> su = new List<Salesforce_User__c>();
        su = [select id, Salesforce_Org__c from Salesforce_User__c where Salesforce_Org__c=:org.id];
        if(su.size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Salesforce_Org__c has no users.'));
            return null;
        }

        admin_utilities.addTransaction(org.Id, 'addCredits', org.Credits__c);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Credits assigned successfully.'));
        renderRefreshButton = true;
        return null;
    }
    public pageReference assignMinutes(){
        if(org.Selenium_Minutes__c == null || org.Selenium_Minutes__c == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'You must enter Minutes to proceed.'));
            return null;
        }

        List<Salesforce_User__c> us = new List<Salesforce_User__c>();
        us = [select id, Salesforce_Org__c from Salesforce_User__c where Salesforce_Org__c=:org.id];
        if(us.size() == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Salesforce_Org__c has no users.'));
            return null;
        }

        admin_utilities.addTransaction(org.Id, 'addMinutes', org.Selenium_Minutes__c);
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Minutes assigned successfully.'));
        renderRefreshButton = true;
        return null;
    }

    public class AssignWrapper {
        public Decimal credits {get;set;}
        public Decimal minutes {get;set;}
    }
}