objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__FirstSegmentTermEndDate__c</fullName>
        <description>Used with multi-segment Products to prorate first segment.</description>
        <inlineHelpText>For multi-segment Products, enter the end date in order to prorate first segment.</inlineHelpText>
        <label>First Segment Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__AllowAssetRefund__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the underlying asset may have its quantity refunded. Only relevant for Amendments.</description>
        <inlineHelpText>Indicates whether the asset represented by this line may be refunded.</inlineHelpText>
        <label>Allow Asset Refunds</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
        <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
        <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net unit price for the product quoted by this line item.</description>
        <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
        <label>Net Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProrateMultiplier__c</fullName>
        <description>Calculated ratio used to compute Prorated Price.</description>
        <inlineHelpText>Calculated ratio used to compute Prorated Price.</inlineHelpText>
        <label>Prorate Multiplier</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProratedListPrice__c</fullName>
        <description>Prorated list unit price.</description>
        <inlineHelpText>Prorated list unit price.</inlineHelpText>
        <label>Prorated List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__SegmentIndex__c</fullName>
        <description>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</description>
        <inlineHelpText>For multi-segmented Products, Index representing this Quote Line&apos;s position in the segment table.</inlineHelpText>
        <label>Segment Index</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__SubscribedQuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscribedAssetHelp</customHelpPage>
    <description>Links a particular asset to the subscription that covers it.</description>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the quote for the quoteLines.</description>
        <inlineHelpText>Identifies the quote for the quoteLines.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote</relationshipLabel>
        <relationshipName>Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscribed Quote Line</label>
    <nameField>
        <displayFormat>SQL-{00000000}</displayFormat>
        <label>Subscribed Quote Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribed Quote Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleProductinQuoteLines.cls
//This scheduler class will map Renewal QuoteLines with Product and run in every 10 minutes.
global class ScheduleProductinQuoteLines implements Schedulable {
   
    global void execute(SchedulableContext sc) {       
       
        // process each batch of records default size is 200
        Map<string,SBQQ__QuoteLine__c> renewQuoteLineIdAndQuoteLine = new Map<string,SBQQ__QuoteLine__c>();
        List<SBQQ__QuoteLine__c> updateQuoteLineList = new List<SBQQ__QuoteLine__c>();
        
        List<SBQQ__QuoteLine__c> qtLineList = [SELECT Id, SBQQ__AllowAssetRefund__c,SBQQ__Quote__c,OriginalQuoteLineId2__c, SBQQ__StartDate__c, SBQQ__EndDate__c, SBQQ__ListPrice__c, SBQQ__ProrateMultiplier__c, SBQQ__NetPrice__c, SBQQ__ProratedListPrice__c FROM SBQQ__QuoteLine__c where SBQQ__Product__c = null AND  OriginalQuoteLineId2__c != null];
        IF(Test.isRunningTest()){
            qtLineList = [SELECT Id, SBQQ__AllowAssetRefund__c,SBQQ__Quote__c,OriginalQuoteLineId2__c, SBQQ__ListPrice__c FROM SBQQ__QuoteLine__c where OriginalQuoteLineId2__c != null];
        }
        for(SBQQ__QuoteLine__c quoteLine : qtLineList) {            
            renewQuoteLineIdAndQuoteLine.put(quoteLine.OriginalQuoteLineId2__c,quoteLine);              
        }   
       
        if(!renewQuoteLineIdAndQuoteLine.isEmpty()) {
            for(SBQQ__QuoteLine__c originalQuoteLine : [Select Id, SBQQ__ProrateMultiplier__c,SBQQ__Product__c, SBQQ__Quote__r.SBQQ__FirstSegmentTermEndDate__c,SBQQ__SegmentIndex__c, SBQQ__ListPrice__c from SBQQ__QuoteLine__c where Id IN:renewQuoteLineIdAndQuoteLine.keySet()]) {
                renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__Product__c = originalQuoteLine.SBQQ__Product__c; 
                renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ProrateMultiplier__c = 12;
                
                renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__AllowAssetRefund__c = true;
                if(renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ProrateMultiplier__c != null && renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ListPrice__c != null) {
                    renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__NetPrice__c = (renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ListPrice__c)*(renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ProrateMultiplier__c);
                    renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ProratedListPrice__c = (renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ListPrice__c)*(renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id).SBQQ__ProrateMultiplier__c);
                }
                updateQuoteLineList.add(renewQuoteLineIdAndQuoteLine.get(originalQuoteLine.Id));
            }
        }

        if(!updateQuoteLineList.isEmpty()) {               
            try {           
                update updateQuoteLineList;
            
            } catch(Exception e) {
                System.debug(e);
            }    
        }         
    }  
}