objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleUpdateRenewalQuoteField.cls
//This scheduler class will uncheck the 'Is Not Clone Quote' field on Renewal Quote.
global class ScheduleUpdateRenewalQuoteField implements Schedulable {
   
    global void execute(SchedulableContext sc) {     
        
        List<SBQQ__Quote__c> updateQuoteList = new List<SBQQ__Quote__c>(); 
       
        // process each batch of records default size is 200
        List<SBQQ__Quote__c> quoteList = [SELECT Id from SBQQ__Quote__c where SBQQ__Type__c='Renewal' AND SBQQ__Opportunity2__c != null AND Is_Not_Clone_Quote__c = true];      
        
        for(SBQQ__Quote__c quote : quoteList) {            
            quote.Is_Not_Clone_Quote__c = false;  
            updateQuoteList.add(quote);             
        }     
        
        if(!updateQuoteList.isEmpty()) {               
            try {           
                update updateQuoteList ;
            
            } catch(Exception e) {
                System.debug(e);
            }    
        }         
    }  
}