objects/Service_Tokens__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used for Service Token to confirm authenticity of inbound webService requests.</description>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Service Tokens</label>
</CustomObject>

objects/sfLma__License__c.object
<CustomObject>
    <description>An object that replicates information from the license object in the subscriber&apos;s Salesforce organization. Records are created each time a subscriber successfully installs a package.</description>
    <fields>
        <fullName>sfLma__Package_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Package Version</label>
        <referenceTo>sfLma__Package_Version__c</referenceTo>
        <relationshipName>R00N30000001JvQxEAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sfLma__Subscriber_Org_ID__c</fullName>
        <description>This is the ID of the Subscriber organization</description>
        <label>Subscriber Org ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sfLma__Version_Number__c</fullName>
        <label>Version Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/sfLma__Package_Version__c.object
<CustomObject>
    <description>This object represents a specific version of a package uploaded by the developer to the AppExchange. Licenses relate to this object, since a user has a specific version installed in their Salesforce organization.</description>
    <fields>
        <fullName>sfLma__Version_Number__c</fullName>
        <label>Version Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Package Version</label>
    <nameField>
        <label>Package Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Package Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CopadoLicenseService.cls
@RestResource(urlMapping='/CopadoLicenseService/*')
global without sharing class CopadoLicenseService {
    @HttpGet
    global static String getLicenseByOrgId() {
        LicenseHelper.webServiceResult wsr = new LicenseHelper.webServiceResult();
		sfLma__License__c license = new sfLma__License__c();
        
        RestRequest req = RestContext.request;
        String orgId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        system.debug('@@@ '+orgId);
        try {
            license = [SELECT Id, Name, sfLma__Package_Version__r.sfLma__Version_Number__c, sfLma__Subscriber_Org_ID__c FROM sfLma__License__c where sfLma__Subscriber_Org_ID__c = :orgId limit 1];
            //system.debug('License found: '+license);
            //wsr.isSuccess = true;
            //wsr.status = 200;
            //wsr.statusMessage = 'Success';
            //wsr.body = String.valueOf(license);
            return license.sfLma__Package_Version__r.sfLma__Version_Number__c;
        }
        catch (Exception e) {
            //wsr.isSuccess = false;
            //wsr.status = 500;
            //wsr.statusMessage = 'Could not find license with orgId ("'+orgId+'"): '+e.getMessage();
            return null;//JSON.serialize(wsr);
        }
    }
	@HttpPost
    global static String enterMethods(){
        LicenseHelper.webServiceResult wsr = new LicenseHelper.webServiceResult();
        RestRequest req = RestContext.request;
        Map<String, String> reqHeaders = req.headers;
        Service_Tokens__c serviceToken = Service_Tokens__c.getValues('AcademyCommunityIntegration');
        if(!reqHeaders.containsKey('apiKey') || reqHeaders.get('apiKey')!= serviceToken.Token__c) {
            wsr.isSuccess = false;
            wsr.status = 401;
            wsr.statusMessage = 'UNAUTHORIZED: You must specify a valid "apiKey"';
            return JSON.serialize(wsr);
        }
        RestResponse res = Restcontext.response;
        String orgId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        String uriString = String.valueOf(req.requestURI);
        
        sfLma__License__c license = new sfLma__License__c();
        try {
            license = [select Id, sfLma__Subscriber_Org_ID__c FROM sfLma__License__c where sfLma__Subscriber_Org_ID__c = :orgId limit 1];
            system.debug('License found: '+license);
        }
        catch (Exception e) {
            wsr.isSuccess = false;
            wsr.status = 500;
            wsr.statusMessage = 'Could not find license with orgId ("'+orgId+'"): '+e.getMessage();
            return JSON.serialize(wsr);
        }
        
        if(uriString.containsIgnoreCase('convertlead')) {
            system.debug('convertLead');
            wsr = LicenseHelper.convertLeadToLicense(license.Id);
        }
        else if(uriString.containsIgnoreCase('provisionlicenses')) {
            system.debug('provisionLicenses');
            if(req.requestBody == null) {
                wsr.isSuccess = false;
                wsr.status = 500;
                wsr.statusMessage = 'When doing a POST, the body cannot be left empty.';
                return JSON.serialize(wsr);
            }
            wsr = LicenseHelper.provisionCopadoLicenses(license.Id, req.requestBody.toString());
        }
        else if(uriString.containsIgnoreCase('updatelicense')) {
            system.debug('updateLicense');
            if(req.requestBody == null) {
                wsr.isSuccess = false;
                wsr.status = 500;
                wsr.statusMessage = 'When doing a POST, the body cannot be left empty.';
                return JSON.serialize(wsr);
            }
            wsr = LicenseHelper.updateLicense(license.Id, req.requestBody.toString());
        }
        else {
            wsr.isSuccess = false;
            wsr.status = 500;
            wsr.statusMessage = 'The URL was parsed but the "provisionLicenses", "convertLead", "updateLicense" strings were not found. URL received:'+req.requestURI;
        }
        return JSON.serialize(wsr);
	}
}