objects/Step_Execution__c.object
<CustomObject>
    <fields>
        <fullName>Payload__c</fullName>
        <label>Payload</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step Execution</label>
    <nameField>
        <label>Step Execution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Step Executions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StepExecutionService.cls
public with sharing class StepExecutionService {
    
    public static void resetJob(Step_Execution__c oldSe, Step_Execution__c se) {
        if((oldSe.Status__c=='Failed' || oldSe.Status__c=='Completed') && (se.Status__c=='Pending' || se.Status__c=='In progress')) {
            se.Payload__c = null;
        }
    }

    public static void checkPayload(Step_Execution__c oldSe, Step_Execution__c se) {
        if(se.Payload__c == null) {return;}
        try {
            String payload = EncodingUtil.urlDecode(se.Payload__c, 'UTF-8');
            se.Payload__c = payload;
        	Map<String, Object> payloadObj = cps_InteractiveModule_Utils.parsePayload(se.Payload__c);
            if (payloadObj.containsKey('hasError') && (payloadObj.get('hasError') == 'false' || payloadObj.get('hasError') == false)) {
            	se.Status__c = 'Completed';
            } else {
            	se.Status__c = 'Failed';
            }
        }
        catch (Exception e) {
        }
    }
}