objects/Use_Case__c.object
<CustomObject>
    <fields>
        <fullName>Automated_Date__c</fullName>
        <label>Automated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Definition</fullName>
                    <default>true</default>
                    <label>In Definition</label>
                </value>
                <value>
                    <fullName>Defined</fullName>
                </value>
                <value>
                    <fullName>Test In Progress</fullName>
                </value>
                <value>
                    <fullName>Manually Tested</fullName>
                </value>
                <value>
                    <fullName>Automatically Tested</fullName>
                </value>
                <value>
                    <fullName>Partially Automated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Use Case</label>
    <nameField>
        <label>Use Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Use Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUseCaseObject.cls
@IsTest
private class TestUseCaseObject {
    @IsTest
    static void testValidationDate() {
        Use_Case__c myUseCase = new Use_Case__c();
        myUseCase.Name = 'New Use Case';
        myUseCase.Status__c = 'In Definition';
        insert myUseCase;

        myUseCase.Status__c = 'Automatically Tested';
        update myUseCase;

        Use_Case__c assertUseCase = [SELECT Id, Automated_Date__c FROM Use_Case__c WHERE Id = :myUseCase.Id];
        
        System.assertEquals(System.today(), assertUseCase.Automated_Date__c);

    }
}